### ISSUE TITLE
Nallar has stopped working on TickThreading for now.

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#1001]
For those who haven't seen:

"Going to stop working on TT for now. Just not fun any more, and that's basically the only reason I was able to invest so much time in it previously.

Sorry."
http://forum.feed-the-beast.com/threads/tickthreading-concurrent-entity-tile-entity-ticks-and-other-optimisations.6498/page-37#post-394223

Luckily, the latest builds seem stable enough. Nallar has been working on this for nearly 8 months straight, so needless to say he's earned a vacation.

**Comment by HaoSs07** [comment]
well that su*ks :) bun understandable , TT was an ambitious project, and for him alone to do so much work, was expecting to end at some point.

**Comment by Drehmini** [comment]
:O Nallar, I will miss you. Hope everything goes well!

**Comment by alicheek** [comment]
Is there not some one that can look after this project while nallar has a break from it because I think its such a shame as something as great as this has to be held back.

**Comment by cjm721** [comment]
I am starting back at school in a few days with java as my first years focus. If I can I will try and see what I can do to help.
