### ISSUE TITLE
Energy Systems Error

### ISSUE THREAD

**Issue by vavraCZe** [MinimallyCorrect/TickThreading#1018]
Is it problem between gregech and UE or problem with TT? What can I do?

http://hastebin.com/majewovigu.avrasm

**Comment by GUIpsp** [comment]
TT Isn't mantained anymore.

**Comment by vavraCZe** [comment]
Too bad! :/

**Comment by MrVoltz** [comment]
Why it isn't mantianed? Can someone continue to work on it?

**Comment by GUIpsp** [comment]
@MrVoltz  nallar got burnt out, and no one has the skill/interest to maintain it.

**Comment by vavraCZe** [comment]
O_O Nallar is back? :D
