### ISSUE TITLE
Server crash with Packet14BlockDig

### ISSUE THREAD

**Issue by MrVoltz** [MinimallyCorrect/TickThreading#1019]
Hello, I have issue with TickThreading.
Here is crash log: https://gist.github.com/MrVoltz/7454458

Njolbrim (author of Skript) replied:

> Either CraftBukkit or TickThreading appear to think that Packet14BlockDig can be handled asynchronously, but Bukkit defines the BlockBreakEvent as being called on the main server thread, thus Skript does no synchronisation of its own, which now results in Skript interfering with itself, eventually blocking the main server thread.
> 
> Please report this issue to TickThreading as well, and if it's not their doing you should report this to CraftBukkit.

**Comment by LunNova** [comment]
Workaround is to remove lines 80->82 from https://github.com/nallar/TickThreading/blob/master/resources/patches.xml inside the TT jar.

Won't be adding a patch for this as not maintaining 1.5/1.4 branches.
