### ISSUE TITLE
Disappearing Entities Issue - All Recent Builds (Pretty Big Issue)

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#102]
Reporting this on behalf of a user on FTB Forums:
http://forum.feed-the-beast.com/threads/tickthreading-concurrent-entity-tile-entity-ticks-and-other-optimisations.6498/page-10#post-112386

I also am experiencing the same thing, I thought it was just me so I didn't bother to report it.

**Comment by ghost** [comment]
+1

Entities not saving or loading on a server restart. Almost everything is gone, including buildcraft frame entities and stevecarts <- that's the easiest way to test, make a random module cart, place it (in GM mode), restart server, log back in, gone.

I have 4 quarrys in one chunk (convering a area of ~10*10 chunks) and from a server restart only one quarry has the black/yellow line (frame entity), and therefor is the only that can operate.

**Comment by Puremin0rez** [comment]
Yep, can confirm your results. Didn't know it effected ALL entities!!!

Rolling to a backup from 2 days ago :(

**Comment by LunNova** [comment]
321dc87f6ecea01d should fix it.

**Comment by LunNova** [comment]
And it seems that the fix caused all vanished entities to reappear. Closing this, as it's confirmed working.
