### ISSUE TITLE
TT and FTB Unleashed 1.1.7

### ISSUE THREAD

**Issue by ghost** [MinimallyCorrect/TickThreading#1022]
The upgrade to the latest version of AE (rv 13-c) is causing massive console spam:
Exception ticking TileEntity c appeng.me.tile.TileController @1118022318 in overworld/0 at x, y, z: 14830, 43, -12674 (snip)
Caused by: java.lang.NullPointerException

Complete error log: http://www.sourcemaker.us/paste/?paste=22

Used TT build 186 for MC 1.5.x

Do you have any advise?

**Comment by dariusc93** [comment]
TickThreading for 1.5.2 is no longer supported.

Related too issue #1020
