### ISSUE TITLE
Welcome Back !!

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#1023]
What Version you plan on working on as i been running a 1.6.4 Server recently that needs some serious loving..

I have been doing some thinking and would it make sense to do a TickThreading-Core then a TickThreading-Mods versoin that way if you just want to patch CORE functions of the server you can ? 

Main thing that comes to mine is chunk loading / generation etc all the core functions?

Just a thought and don't know how feasible that is.

**Comment by floh22** [comment]
oh god thank you Nallar! The God of anti lag has returned! Cant wait to see how stable 1.6.4 versions are :)

**Comment by Miaourt** [comment]
Yaaaay !
