### ISSUE TITLE
Can't seem to patch TT properly. (Mac OS X Mavericks)

### ISSUE THREAD

**Issue by Twiggholmes** [MinimallyCorrect/TickThreading#1027]
01:42:10 [INFO] Started TT metrics reporting. This can be disabled in PluginMetrics.cfg
01:42:10 [WARNING] Patching required for /Users/admin/Desktop/Minecraft/mcpc-plus.jar because it is out of date.
Expected -891168041, got null
01:42:10 [WARNING] Patching required for /Users/admin/Desktop/Minecraft/mods/CodeChickenCore 0.9.0.6.jar because it is out of date.
Expected 559538970, got null
01:42:10 [WARNING] Patching required for /Users/admin/Desktop/Minecraft/mods/industrialcraft-2_2.0.295-experimental.jar because it is out of date.
Expected -1025687664, got null
01:42:10 [WARNING] Patching required for /Users/admin/Desktop/Minecraft/mods/forestry-A-2.3.0.6.jar because it is out of date.
Expected 333211317, got null
01:42:10 [WARNING] Patching required for /Users/admin/Desktop/Minecraft/mods/TickThreading-1.6.4.27.jar because it is out of date.
Expected 713057946, got null
01:42:10 [WARNING] Patching required for /Users/admin/Desktop/Minecraft/mods/Thaumcraft4.0.3a.zip because it is out of date.
Expected 1419726034, got null
01:42:10 [WARNING] Patching required for /Users/admin/Desktop/Minecraft/mods/WR-CBE 1.4.0.6.jar because it is out of date.
Expected 1744776869, got null
01:42:10 [WARNING] Patching required for /Users/admin/Desktop/Minecraft/mods/buildcraft-A-1.6.2-4.1.0.jar because it is out of date.
Expected -121686838, got null
01:42:10 [SEVERE] TickThreading is disabled, because your server has not been patched or the patches are out of date
To patch your server, simply run the PATCHME.bat/sh file in your server directory

Also, make a full backup of your server if you haven't already!

Files checked for patches: mcpc-plus.jar,coremods,mods,plugins

> 2013-12-03 01:42:10 [INFO] [TickThreading] Running TickThreading v1.6.4.27 for MC1.6.4 - 1.7.0_45-b18
> 2013-12-03 01:42:12 [SEVERE] [TickThreading] An error occurred while patching, can't continue
> java.lang.NoClassDefFoundError: org/objectweb/asm/commons/Remapper
>     at java.lang.ClassLoader.defineClass1(Native Method)
>     at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
>     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>     at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
>     at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
>     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
>     at nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:52)
>     at nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:27)
> Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.commons.Remapper
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
>     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
>     ... 14 more
> 01:42:12 [INFO] Stopping server
> 01:42:12 [INFO] Saving worlds
> logout

**Comment by ghost** [comment]
First, your using outdated mods.

Second, Tick Threading is not ready for 1.6.4. Nallar said he would let the community know when it was ready.

**Comment by LunNova** [comment]
I've updated the main forum post to mention that it's not updated fully yet, ![](http://i.imgur.com/SnsSfX8.png)

**Comment by Twiggholmes** [comment]
Thank you
I will update my mods and wait for the signal  :)
may I have a link to the main forum please?
