### ISSUE TITLE
Patcher Not Working

### ISSUE THREAD

**Issue by floh22** [MinimallyCorrect/TickThreading#1029]
Patcher file seems to be correct. the server jar is called server.jar and tickthreading is called: TickThreading. mods folder does exist and Tickthreading is in it:

error when trying to patch:
http://pastebin.com/Nk1aucP3
am i patching it correctly? has something changed?

**Comment by LunNova** [comment]
1.6 update isn't done.

There won't be a patcher any more, will patch at runtime. Possibly will need to start the server with a different start line, depending on some Forge stuff, but nothing like the old system.

**Comment by LunNova** [comment]
See #1030. Also note that the link to the builds on the forum thread should say "broken" for the 1.6.4 builds, unless I forgot to put that there.

**Comment by floh22** [comment]
well im happy to help you test. just tell me when you have a version which might run ^^

also, you might wanna write "broken" in the dl section here as well: https://github.com/nallar/TickThreading
