### ISSUE TITLE
Items falling through world - Build #729

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#103]
If you throw an item on the ground and then place a block on top of it, the item will begin to "try" to push itself out but fails to do so and start glitching itself block by block downwards. I had to mine 50+ block downwards to save a cooked porkchop :P

**Comment by Puremin0rez** [comment]
Make sure you leave the block on top of the item for a good 10+ seconds, you'll see it appear to "push" itself from the block but then teleport back in after some time and start flipping the hell out

**Comment by Puremin0rez** [comment]
It also do it if an item falls on a non full block, such as a stair etc. It'll "bounce" for a few seconds before doing the same glitchy behavior and fall downwards infinity

**Comment by LunNova** [comment]
Oops, messed up the item patch. :(

d4b8efb635838693cf5e4d3 should fix it.

**Comment by Puremin0rez** [comment]
It's fixed :)
