### ISSUE TITLE
Runtime patching

### ISSUE THREAD

**Issue by LunNova** [MinimallyCorrect/TickThreading#1030]
Swap to patching at runtime for 1.6.4 to make TT easier to use + easier to update for new minecraft versions.

**Comment by GUIpsp** [comment]
Using tweaker maybe?

**Comment by LunNova** [comment]
Probably, not sure.

Are tweakers guaranteed to run after FML does runtime deobfuscation now or is it like coremods in 1.5?

**Comment by LunNova** [comment]
To expand on that, the alternative would be to start the server through the TT jar instead of the forge jar, and it would do classloading stuff there to make sure the ordering is correct. Not sure if that's necessary though, may work fine by default or just need some reflection which is much easier.

**Comment by GUIpsp** [comment]
AFAIK, you can specify when your tweaker gets applied, I'd ask @cpw to be sure.

**Comment by alicheek** [comment]
how would you go about installing TT 1.6.4  is it the same way where you would put it into your mods folder and just start the server up?

**Comment by ruifung** [comment]
It's not ready yet.
