### ISSUE TITLE
build.xml failing: Traced to fml.py's get_headers(url)

### ISSUE THREAD

**Issue by Jamezz** [MinimallyCorrect/TickThreading#1032]
_snip_  
 [exec] Fixing MCP Workspace
     [exec] Press any key to continue . . .   File "C:\Users\Jamezz\git\TickThreadingNallar\build\forge\fml\fml.py", line 173, in get_headers
     [exec]     response = urllib2.urlopen(HeadRequest(url))
     [exec]   File "urllib2.pyc", line 126, in urlopen
     [exec]   File "urllib2.pyc", line 406, in open
     [exec]   File "urllib2.pyc", line 519, in http_response
     [exec]   File "urllib2.pyc", line 444, in error
     [exec]   File "urllib2.pyc", line 378, in _call_chain
     [exec]   File "urllib2.pyc", line 527, in http_error_default
     [exec] urllib2.HTTPError: HTTP Error 403: Forbidden
     [exec] urllib2.HTTPError: HTTP Error 403: Forbidden
download-libs:
prepatch:
    [javac] Compiling 2 source files to C:\Users\Jamezz\git\TickThreadingNallar\build\classes

BUILD FAILED
C:\Users\Jamezz\git\TickThreadingNallar\build.xml:137: C:\Users\Jamezz\git\TickThreadingNallar\build\forge\mcp\lib does not exist.
Total time: 28 seconds

Looks like Mojang isn't playing nice and letting us download libraries. This was discussed at http://www.minecraftforge.net/forum/index.php/topic,11001.0.html 

Does something need to be fixed or is this classified as an intermittent issue?

**Comment by Jamezz** [comment]
My attempts at band-aid fixes didn't help. It sounds like Forge is only supporting gradle as a build system from now on as well.

**Comment by LunNova** [comment]
I'll add something to build.XML to patch FML.py with the patch from that
thread tomorrow.
