### ISSUE TITLE
ME systems cause player logout

### ISSUE THREAD

**Issue by Munckis** [MinimallyCorrect/TickThreading#1035]
This is on 1.5.2 FTB Unleashed, so if you aren't working on things this old now just close this thread and I won't cry about it :)

Anyways, after server being on for a few minutes i get this in console:

17.12 15:46:25 [Server] INFO Caused by: java.lang.NullPointerException
17.12 15:46:25 [Server] INFO at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
17.12 15:46:25 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
17.12 15:46:25 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
17.12 15:46:25 [Server] INFO at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
17.12 15:46:25 [Server] INFO at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:90)
17.12 15:46:25 [Server] INFO at appeng.common.base.AppEngTile.func_70316_g(AppEngTile.java:557)
17.12 15:46:25 [Server] INFO java.lang.RuntimeException: java.lang.NullPointerException
17.12 15:46:25 [Server] SEVERE Exception ticking TileEntity c appeng.me.tile.TileController @625550001 in Overworld/0 at x, y, z: -4342, 64, -2168
17.12 15:46:25 [Server] SEVERE MC might crash now...
17.12 15:46:25 [Server] SEVERE java.lang.NullPointerException
17.12 15:46:25 [Server] SEVERE Exception When Ticking appeng.me.tile.TileController at -4342, 64, -2168
17.12 15:46:23 [Server] INFO Caused by: java.lang.NullPointerException
17.12 15:46:23 [Server] INFO at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
17.12 15:46:23 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
17.12 15:46:23 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
17.12 15:46:23 [Server] INFO at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
17.12 15:46:23 [Server] INFO at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:90)
17.12 15:46:23 [Server] INFO at appeng.common.base.AppEngTile.func_70316_g(AppEngTile.java:557)
17.12 15:46:23 [Server] INFO java.lang.RuntimeException: java.lang.NullPointerException

Anyone who tries to use any ME controller that gets this error will get instantly logged out with a "Internal Server Error" message.

Like I said on FTB unleashed 1.1.7, MCPC+ and Tickthreading 1.5.2 build 186

**Comment by NachtRaben** [comment]
In 152 with TT ME controllers were notorious for becoming bugged, if an admin breaks it and replaces it it should stop that from happening, thats how i fixed the issue. (issue become more common in worlds other then overworld)

**Comment by dariusc93** [comment]
1.5.2 is not supported anymore.

**Comment by Munckis** [comment]
Awesome thanks for the heads up, replacing the block has helped thus far. You have quite an amazing plugin here and thanks for keeping it going.

**Comment by dariusc93** [comment]
I would recommend updating to 1.6.4 when possible.
