### ISSUE TITLE
Starting Up

### ISSUE THREAD

**Issue by gunnar19991** [MinimallyCorrect/TickThreading#1036]
I see that you made TT a server wrapper but when I put the forge files in side the TT jar then start up it will get to the end of starting up and tell me to remove TT from the mods folder and it is not on their is this a bug with TT at the moment?

**Comment by LunNova** [comment]
I haven't finished updating it so that will happen.

However, that's not how you're supposed to use it. Just put the TT jar in the same folder as the forge jar and start from the TT jar, no need to add any files.

Documentation is incomplete and will be updated once it actually works.
