### ISSUE TITLE
[1.5.2 TT] any chance of removing Applied energestics patch so it works on Unleashed 1.1.7?

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#1037]
Hey there nallar was wondering if maybe you could put up a build of your 1.5.2 TT with out the AE patching in it, tried it with it in and it totally screwed up with about 32MB of logs in about 3mins :P

**Comment by LunNova** [comment]
That's not how patching works, the server gets patched to make everything threaded and the other patches fix what threading everything breaks.

You can try removing the AE patches yourself if you want, remove the <AppliedEnergistics> part in patches.xml in the TT jar.

It will probably just break everything even more though.
