### ISSUE TITLE
Logging/Display numbers of time kicked due to "hack"

### ISSUE THREAD

**Issue by Sp0nge** [MinimallyCorrect/TickThreading#104]
Write/read a value +1 pr time on trigger readable ingame and/or txtfile?

**Comment by Torins** [comment]
If ya gonna write something to hdd, I'd suggest a whole log -> time, location, name and reason (assuming multiple reasons avaliable)

**Comment by LunNova** [comment]
I'll be able to implement this for any checks TT does, but the vanilla warnings are just redirecting when the server logs to console.

**Comment by LunNova** [comment]
Not implementing this, as TT will not be doing any of its own cheat detection.
