### ISSUE TITLE
TickThreading Not Starting

### ISSUE THREAD

**Issue by Katelyn-SN** [MinimallyCorrect/TickThreading#1046]
I know right at this moment tickthreading for 1.6.4 is still in development so to help aid the development process i noticed these issues

Tickthreading launches as a wrapper but server stops because tickthreading still thinks its in the mods folder

**Comment by floh22** [comment]
also, whats the status of TT? Is it dead or just slow at the moment. a little heads up would be nice :)

**Comment by LunNova** [comment]
Just rather slow. Very slow.
