### ISSUE TITLE
Add support without forge

### ISSUE THREAD

**Issue by john01dav** [MinimallyCorrect/TickThreading#1047]
Hello, I am attempting to setup a mini-game server (using vanilla, with spigot) and I would like to avoid using bungeecoord at all costs (because it just takes too much money to pay for a bunch of servers to be networked). What I would like is a replacement jar for craftbukkit (and spigot) that is simply used instead and has all of the functions of tickthreading and all of the functions of bukkit (plugins).

**Comment by GUIpsp** [comment]
This sounds unlikely to happen, forge will add support for vanilla clients soon anyways.

**Comment by LunNova** [comment]
Invalid/won't fix for the reason @GUIpsp mentioned - no point putting the effort in when forge already will soon.
