### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by MineMine** [MinimallyCorrect/TickThreading#1048]
or WIP (for version of 1.6.4)

I know that nallar is good man and he have been worked hard

everyday I've been checked github and FTB thread for three weeks (exactly same time,It is in my schedule!)

This project is really important to me and anyone who runs modded minecraft server

**Comment by LunNova** [comment]
Sort of.

It's a case of extreme laziness. No excuses, I'm a bad dev.

**Comment by MineMine** [comment]
I still waiting for you, Even if the progress is standstill in development stage

p.s you are not bad dev :D

**Comment by CoryManson** [comment]
There a huge bounty on this nallar :)

Your stuck in PlanetSide, aren't you?

**Comment by witchway915** [comment]
But Nallar! FTB Subreddit Server Needs you!!!!!!! <3 we're starting the server back up soonish

**Comment by MineMine** [comment]
CHEER UP!!

**Comment by witchway915** [comment]
Nallar, you are not a bad dev, you're an awesome dev. please come back to us :)

**Comment by LunNova** [comment]
@Cozza38 

mhm. ![Hours played in planetside per month](http://i.imgur.com/DIAiJ5g.png). oops.

**Comment by Slind14** [comment]
@nallar looks like you would have the time for it but other things first atm. :) (no motivation/interest)
we are on ~10 tps during peak time with 4 servers about 40-50 players on each.

**Comment by floh22** [comment]
Nallar. make it when you feel like it :) cant wait for the finished product thats for sure :)

**Comment by dariusc93** [comment]
Shame on you nallar. You are not a bad dev. Just take your time. People can wait for TT. There are ways to boost the performance on the server you know :)

**Comment by LunNova** [comment]
Guess this can be closed now? :D
