### ISSUE TITLE
No PATCHME.sh

### ISSUE THREAD

**Issue by lordlemon** [MinimallyCorrect/TickThreading#1049]
Hi, I am using feed the best monster with mcpc+ for 1.6.4, and when I put TT in the mods folder all goes well, and the server closes as it should, but no PATCHME.sh or .bat shows up in the server root folder, however there is a tickthreading logs folder. This mod worked perfectly on my feed the beast unleashed server, I do not understand what the problem is.
Thanks for your time and thanks for the great mod!

**Comment by dariusc93** [comment]
Please read commits. This build isnt usable yet
