### ISSUE TITLE
Switch to Gradle?

### ISSUE THREAD

**Issue by dariusc93** [MinimallyCorrect/TickThreading#1052]
I notice in one of your recent commits that it stated a port to gradle, but I see no gradle  script. If you would like me too, I can setup everything for you (or get someone who loves gradle too.) It is not hard but the only issues I currently see at the moment is about  the prepatcher, as well as some of your dependency (I was porting tickprofiler to gradle long ago when i caught on.)

**Comment by LunNova** [comment]
I'm currently on holiday with intermittent internet access. The only issue
currently with switching to gradle is what you noted with the prepatcher.
If you can PR with prepatching working that'd be excellent, otherwise I'll
get it done when back some time after Monday 21st.

**Comment by LunNova** [comment]
Closed via 96fa30c4c651c881f645706ee7c700db4d735477.
