### ISSUE TITLE
Error Causing Lag

### ISSUE THREAD

**Issue by ghost** [MinimallyCorrect/TickThreading#1055]
Hello, 

I'm having errors in the console and small crashes just seconds, somewhere around 1-2 seconds locks the server and back to normal then the console the following error appears:

29.04 00:11:52 [Server] INFO at net.minecraft.network.TcpReaderThread.run(ReplaceTcpReaderThread.java:22)
29.04 00:11:52 [Server] INFO at net.minecraft.network.TcpConnection.readNetworkPacket(TcpConnection.java:74)
29.04 00:11:52 [Server] INFO at net.minecraft.network.TcpConnection.func_74447_i(TcpConnection.java:300)
29.04 00:11:52 [Server] INFO at net.minecraft.network.packet.Packet.func_73272_a(Packet.java:165)
29.04 00:11:52 [Server] INFO java.io.IOException: Bad packet id 35
29.04 00:11:52 [Server] SEVERE Failed to handle packet from unknown
29.04 00:11:47 [Server] INFO at net.minecraft.network.TcpReaderThread.run(ReplaceTcpReaderThread.java:22)
29.04 00:11:47 [Server] INFO at net.minecraft.network.TcpConnection.readNetworkPacket(TcpConnection.java:74)
29.04 00:11:47 [Server] INFO at net.minecraft.network.TcpConnection.func_74447_i(TcpConnection.java:300)
29.04 00:11:47 [Server] INFO at net.minecraft.network.packet.Packet.func_73272_a(Packet.java:165)
29.04 00:11:47 [Server] INFO java.io.IOException: Bad packet id 35
29.04 00:11:47 [Server] SEVERE Failed to handle packet from unknown

28.04 21:51:26 [Server] INFO Received a tiny packet for network id 52 that is not recognised here
28.04 21:51:26 [Server] INFO Player Ninjinski set home location [casa]
28.04 21:51:23 [Server] INFO 1
28.04 21:51:23 [Server] INFO 1
28.04 21:51:23 [Server] INFO /179.223.169.169:64965 lost connection
28.04 21:51:23 [Server] INFO /177.156.37.7:51842 lost connection
28.04 21:51:23 [Server] INFO /186.247.156.201:52820 lost connection
28.04 21:51:20 [Server] INFO at net.minecraft.network.TcpReaderThread.run(ReplaceTcpReaderThread.java:22)
28.04 21:51:20 [Server] INFO at net.minecraft.network.TcpConnection.readNetworkPacket(TcpConnection.java:74)
28.04 21:51:20 [Server] INFO at net.minecraft.network.TcpConnection.func_74447_i(TcpConnection.java:300)
28.04 21:51:20 [Server] INFO at net.minecraft.network.packet.Packet.func_73272_a(Packet.java:165)
28.04 21:51:20 [Server] INFO java.io.IOException: Bad packet id 35
28.04 21:51:20 [Server] SEVERE Failed to handle packet from unknown
28.04 21:51:17 [Server] INFO at net.minecraft.network.TcpReaderThread.run(ReplaceTcpReaderThread.java:22)
28.04 21:51:17 [Server] INFO at net.minecraft.network.TcpConnection.readNetworkPacket(TcpConnection.java:74)
28.04 21:51:17 [Server] INFO at net.minecraft.network.TcpConnection.func_74447_i(TcpConnection.java:300)
28.04 21:51:17 [Server] INFO at net.minecraft.network.packet.Packet.func_73272_a(Packet.java:165)
28.04 21:51:17 [Server] INFO java.io.IOException: Bad packet id 35
28.04 21:51:17 [Server] SEVERE Failed to handle packet from unknown

**Comment by Dark-Arcana** [comment]
What version/build are you using?

**Comment by LunNova** [comment]
Is this an issue with 1.5.2 TickThreading? That's no longer being supported, sorry.

It looks like you might have posted this issue in the wrong place - I don't see anything tickthreading-related in your error log, and if you're on 1.6 minecraft it'd be impossible to get this error with TT as there are no 1.6 TT releases.

**Comment by ghost** [comment]
I need a version of TickThreading to 1.5.2 without bugs, I own the largest Brazilian and need this mod modpack server it helped me a lot, I am able to donate a large sum for it.
