### ISSUE TITLE
Start again! :D

### ISSUE THREAD

**Issue by MineMine** [MinimallyCorrect/TickThreading#1056]
I've listened that nallar is starting again to improve modded minecraft world! 

I hope i can use first 1.6.4 release as soon as possible :D

**Comment by Dark-Arcana** [comment]
You can follow along in irc on Esper in #TickThreading. Nallar is making some progress, but it could be weeks before anything is completed. If you would like to help test beta builds, we can get you signed up when the time comes. Or if you would like to support in other ways, you can donate to Nallar! Thanks for the support.

**Comment by Daniel86268** [comment]
I am a huge fan of TickThreading and I would love to help beta builds of TickThreading. Just let me know if and when you need help. I have a Server myself with a bunch of mods and I have experiences with the normal Forge Minecraft server as well as MCPC+. :)

**Comment by HaoSs07** [comment]
Same here. I used TT and reported bugs back when it was on 1.4.7. If beta testers are needed. sign me up.
