### ISSUE TITLE
Let us know when you want bug/crash reports.

### ISSUE THREAD

**Issue by ghost** [MinimallyCorrect/TickThreading#1059]
Technically the build server is working and TickThreading can be installed but I don't know if its the right time yet to be reporting stuff.

**Comment by Dark-Arcana** [comment]
There is some preliminary testing being done to find breaking points and patch it well enough to work in a more stable setting. Right now, that's being taken care of. It will most likely crash for you if you try it and/or corrupt any worlds you have. When it is available for more widespread testing, some kind announcement will be made.

**Comment by ghost** [comment]
Looks like its time to begin the bug hunt.
