### ISSUE TITLE
732: Iron doors

### ISSUE THREAD

**Issue by Sp0nge** [MinimallyCorrect/TickThreading#106]
Wont show as open/closed but they still works. Sounds for the doors are played, they just wont update clientside to the correct state.

**Comment by Puremin0rez** [comment]
Can't reproduce

Beware that there is apparently an issue with Block Updates in the build of Forge that MC v8 uses.

I'm on Optifine Ultra C2 and I'm not getting the issue.

**Comment by LunNova** [comment]
This is probably related to the forge changes to PlayerInstance.

**Comment by LunNova** [comment]
Fixed. :)
