### ISSUE TITLE
Punching animals causes them to fly away.

### ISSUE THREAD

**Issue by ghost** [MinimallyCorrect/TickThreading#1061]
They fly much further than just the normal knockback. After a few very short amount of time they teleport back to the starting position. Its not just a visual glitch, when I punch the space they used to be, no additional damage is dealt.

Tested using build 101 with Forge 965 as server jar, no mods, no MCPC+.

**Comment by LunNova** [comment]
Do items dropped in flowing water flow properly?

Do passive mobs walk around at all?

**Comment by ghost** [comment]
Items flowing through water works correctly,

Passive mobs are not moving at all. I tested cows and sheep.

Aggressive mobs have the same behavior. While in survival I spawned a creeper and even when I punch it it refuses to move or explode.

Edit: Both passive and aggressive mobs refuse to be moved by water, they fling themselves like when I punch them and then teleport back to the initial point of water entry.
