### ISSUE TITLE
Controls while riding horses are messed up.

### ISSUE THREAD

**Issue by ghost** [MinimallyCorrect/TickThreading#1062]
Horses have a clumsy control system to begin with but I can easily tell something is wrong, the controls appear to be almost mirrored at times. For example, pressing forwards causes the horse to go back. There are no errors in console on either my client or the server.

Tested using TickThreading build 105, Forge 965 as server jar, no mods.

**Comment by LunNova** [comment]
A possible workaround is setting concurrentMovementUpdates = false in TT's
config.

**Comment by ghost** [comment]
An interesting note:

The bug appears to be direction dependent. For example:

While facing West the controls work as expected. Facing East the controls are perfectly mirrored. Facing South they are turned 90 degrees and the same but in the opposite direction for the North.

Also, turning concurrentMovemnetUpdates off is proven to fix this issue.
