### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by BrMateus** [MinimallyCorrect/TickThreading#1072]
Hello,

My server has something wrong, look at these screenshots and see.

http://i.imgur.com/82lnryn.png
http://i.imgur.com/i4Ezck4.png

**Comment by LunNova** [comment]
TT for 1.5.2 is no longer supported, however I can give you some advice.

Run `/profile e`, `/ticks`, `/profile p` and `/profile a` to see what's slow on your server.

You can reply with the results here and I'll take a quick look.

**Comment by BrMateus** [comment]
The UltimateSolarPanels is causing lag, what can I do?

**Comment by LunNova** [comment]
Screenshot what those commands show.

**Comment by BrMateus** [comment]
http://i.imgur.com/Yj8MHn4.png
http://i.imgur.com/B5pHyWg.png
http://i.imgur.com/HdEtC5W.png
http://i.imgur.com/PtN22sr.png

**Comment by LunNova** [comment]
Your best bet is to ban the use of those solar panels which are taking all your tick time. I guess that's not an option as it'll annoy many of your players?

TickThreading for 1.5 was never finished, and does not work well.

**Comment by BrMateus** [comment]
Block the solar panels and not an option and my server and a modpack version 1.5.2 to 1.6.4 migration unfeasible, you have any suggestions?
