### ISSUE TITLE
TT124 Issues (NPE) with AE, MFR and LogiPipes

### ISSUE THREAD

**Issue by nylser** [MinimallyCorrect/TickThreading#1073]
I'm getting the following logspam, while testing the newest TickThreading build 124 for 1.6 right now: https://mineguild.net/status/tickthreading.1.log
It seems to be mostly AE and LogisticsPipes.

**Comment by Vycraftujto** [comment]
- 1 
  same isue AE is actuali one big multi block where ticking is made by TileController it screeme on every profiler cause this block is actuali whole ME system. 

Same isue was on 1.5 it is on latest wersion of ME
Im guess fix will not be soon so can we have at least silece of this block in log?
