### ISSUE TITLE
HEE Incompatibility.

### ISSUE THREAD

**Issue by Dark-Arcana** [MinimallyCorrect/TickThreading#1074]
Server Log: https://gist.github.com/Dark-Arcana/21e1ef65185c28e5ea93

Forge Log: https://gist.github.com/Dark-Arcana/fff0f7dbc6847eb8b1ab

No crash associated with this issue. Player logs in, can't move, screen shakes like you're stuck inside a block. Error prints out constantly. I attempted to use world edit to remove blocks in case I was stuck inside something. I couldn't break anything by hand.

TT 126
MCPC+ 251

**Comment by Dark-Arcana** [comment]
Removed HEE for testing. Still can't move. But that above is an obvious issue that will need to be looked at XD.

**Comment by LunNova** [comment]
This change should fix the HEE error, however you may need to copy your HEE save data from the working server - the saved infestation data on your TT test server will have been corrupted.

It'll be a file called "infestation.nbt" in the world directory.

**Comment by Dark-Arcana** [comment]
Alright awesome. Thanks Nallar. I'll test again later.
