### ISSUE TITLE
Launch error. java.lang.SecurityException

### ISSUE THREAD

**Issue by ghost** [MinimallyCorrect/TickThreading#1076]
TickThreading build 137. Forge 965. No mods.

JVM Arguments: java -Xms1G -Xmx1G -jar TickThreading.jar --serverJar=minecraftforge.jar

It doesn't get far enough to even create logs and this is a freshly downloaded version of Forge and TickThreading.

java.lang.SecurityException: class "cpw.mods.fml.relauncher.FMLLogFormatter"'s signer information does not match signer information of other classes in the same package.

If you need I can run this setup on my Ubuntu laptop and that should let me copy the console unlike Windows.

**Comment by LunNova** [comment]
It turns out this error only happens when not using MCPC+, and I was running my test server with MCPC+ so didn't catch it.
