### ISSUE TITLE
Player cannot take damage | McMyAdmin Crash

### ISSUE THREAD

**Issue by Katelyn-SN** [MinimallyCorrect/TickThreading#1078]
Player cannot take damage no matter what the cause from falling out of the world to drinking poison potions nothing can affect you except the /kill command

![2014-05-06_23 30 00](https://cloud.githubusercontent.com/assets/2229748/2898880/d713cb30-d5a9-11e3-831b-728bada6a458.png)

**Comment by Dark-Arcana** [comment]
In your screenshot, you have 17/20 health. You must have taken some damage somehow.

Also, as stated in IRC, test in forge (without mcpc+) to rule out any other interactions that could be causing this issue. Test in both cases before posting an issue.

**Comment by LunNova** [comment]
Confirmed as happening only when using MCPC+.

**Comment by Katelyn-SN** [comment]
Also the reason for me specifying the test environment and you do take
damage its like a one hit thing just after the server starts then it never
happens again

**Comment by LunNova** [comment]
It's actually one hit after connecting - relog repeatedly while standing in lava and you do eventually die.
