### ISSUE TITLE
Exception while updating block neighbors - [Log Spam - No Crash]

### ISSUE THREAD

**Issue by Dark-Arcana** [MinimallyCorrect/TickThreading#1080]
Using my modpack, worldedit, essentials, and async world edit:

Spawned sacred rubber tree. Then used world edit command //overlay to spawn fire on top of the tree to set the whole thing on fire. I accidentally spawned torches instead haha. So I removed the torches and then spawned the fire. This is what printed out, about 100k lines:

https://gist.github.com/Dark-Arcana/3ffbbf3eeaf3aee3c859

**Comment by LunNova** [comment]
Can you try that without TT please? Doing something as silly as that might be the cause of the crash, not a TT bug! :P

I'll try to fix it anyway, although it does look like a vanilla bug.

**Comment by ghost** [comment]
This is one of those cases where no sane person would do this even with the massive performance boost from TickThreading. The clientside lag alone makes me cringe.

**Comment by Dark-Arcana** [comment]
Who said I was sane?! Although, it didn't cause a crash and everything was perfectly fine. I've done stuff like this just messing around in vanilla/bukkit/forge in a "just want to watch the world burn" kind of way. I wanted to see what would happen with TT. And obviously it printed out a lot of errors. Like I said, I've done this in every other environment in the past without any errors. I wouldn't have done a stress test without knowledge of the outcome in non TT environments.

**Comment by LunNova** [comment]
Can you try this again on latest? dbff2fe12a42c64 should fix it.

**Comment by LunNova** [comment]
Presuming fixed, no response after 5 days.
