### ISSUE TITLE
Profiling/Server status GUI

### ISSUE THREAD

**Issue by LunNova** [MinimallyCorrect/TickThreading#1081]
Something similar to what Opis can do.

**Comment by Dark-Arcana** [comment]
Great idea. Are you going to build this on top of TickProfiler? Will it be a client/server mod? And considering all of the other things you're already working on, will you need any help with it? I don't write Java (I know Python, PHP, JS, etc), but I could take my knowledge and try to take a crack at it.

I know Opis implements Java Swing to create a separate window. From what I've been told, Swing isn't the easiest thing to work with. Could look into different libraries/apis for a gui implementation. It's up to you.

**Comment by Vycraftujto** [comment]
superb if you can do this cause oppis was allways easier to find things
