### ISSUE TITLE
Client crash from ticking entity

### ISSUE THREAD

**Issue by Vycraftujto** [MinimallyCorrect/TickThreading#1083]
server working perfect better then perferct freaking MIRACKLE!!!!

but klients are crashed by ticking entites hapening players whit biggest factories

Crash log
https://gist.github.com/Vycraftujto/647294831a0018568f35

**Comment by LunNova** [comment]
It looks like this FMP issue: https://github.com/Chicken-Bones/ForgeMultipart/issues/139

Did it not happen at all before adding TT? Are you using MCPC?

**Comment by Vycraftujto** [comment]
nop whit out TT it is all ok.. and yes MCPC latest

btw client disconect on opening AE inventory good whit out TT disconect whit TT
