### ISSUE TITLE
Crash with latest mekanism build 6.0.4.42

### ISSUE THREAD

**Issue by XileForce** [MinimallyCorrect/TickThreading#1090]
Server crashes during startup with This:

Also I only tested this In MCPC+ sorry :(

Crash Report: http://pastebin.com/qY1VEeFq
ServerLog: http://pastebin.com/eK6GW9XH
TickPatcher Log: http://pastebin.com/M2VHL9Fb

**Comment by Katelyn-SN** [comment]
I would try with a fresh world and see if it occurs if your not on one already

Also TT is not usable at this moment it works and patches but it is extremely unstable and should not be used for any production servers as major bugs and/or destructive bugs are present.

**Comment by XileForce** [comment]
Yes this is a fresh world. And I'm using this on a test server of course :). I'm not that crazy....yet. Just figured I would help test stuff for nallar.

**Comment by Katelyn-SN** [comment]
Alright then you will have to wait for nallar to look over it as i am not anyone to tell you how to fix such as i have never even used that mod before.

**Comment by XileForce** [comment]
Well it only happens with TT so I assume its something related to that. I'm sure nallar will be able to tell what's up.
