### ISSUE TITLE
Thermal Expansion Energy conduits sometimes not working

### ISSUE THREAD

**Issue by Daniel86268** [MinimallyCorrect/TickThreading#1092]
On a large server some other players and I are encountering, that suddenly Thermal Expansion energy conduits stop working. They just stop transfering energy. Breaking and replacing the machines or the energy conduits doesn't fix it. If I put the machines next to each other (energy producer and consumer) the energy transfer is fine.
I have no errorlog, but this happened the first time after installing TickThreading, so I assume it's caused by TickThreading.
We are using Thermal Expansion 3.0.0.2.

**Comment by ghost** [comment]
You should update to TE 3.0.0.6. I've already heard and experienced this issue without the TickThreading mod.

**Comment by Katelyn-SN** [comment]
The error is present on the most recent version of TE so we will have to have nallar look into it i have this occuring on my server as well but breaking and placing the conduits right next to the power source seems to fix the issue temporarily

**Comment by LunNova** [comment]
Please confirm if this is still an issue on latest. The new tick region locking should prevent this from happening.

**Comment by Katelyn-SN** [comment]
And you would be correct a 2 hour period no reported disconnects or issues with conduits or with TE in general. Even alot of the console spam on b-team with tropicraft seems to be gone with this build im not sure if its caused by the bug not being present anymore or the cause not in the world anymore just time will tell.

**Comment by Daniel86268** [comment]
We've tested it for a couple of hours now, we haven't encountered any problems so far. I think it's fixed. Great work :D.
