### ISSUE TITLE
Error causing lag

### ISSUE THREAD

**Issue by BrMateus** [MinimallyCorrect/TickThreading#1093]
09.05 19:29:19 [Server] INFO at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:941)
09.05 19:29:19 [Server] INFO at net.minecraft.world.World.func_72866_a(World.java:391)
09.05 19:29:19 [Server] INFO at rebelkeithy.mods.atum.artifacts.arrow.EntityAtumFishHook.func_70071_h_(EntityAtumFishHook.java:210)
09.05 19:29:19 [Server] INFO java.lang.NullPointerException
09.05 19:29:19 [Server] SEVERE Exception ticking entity EntityAtumFishHook['entity.Atum.EntityAtumFishHook.name'/258623, l='DIM7', x=1042.24, y=31.90, z=1833.79] in rX: 65, rZ: 114, hashCode: 7471169/Twilight Forest/7:
09.05 19:29:19 [Server] INFO at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
09.05 19:29:19 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
09.05 19:29:19 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
09.05 19:29:19 [Server] INFO at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
09.05 19:29:19 [Server] INFO at nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:61)
09.05 19:29:19 [Server] INFO at net.minecraft.world.World.func_72870_g(World.java:2481)
09.05 19:29:19 [Server] INFO at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:941)
09.05 19:29:19 [Server] INFO at net.minecraft.world.World.func_72866_a(World.java:391)
09.05 19:29:19 [Server] INFO at rebelkeithy.mods.atum.artifacts.arrow.EntityAtumFishHook.func_70071_h_(EntityAtumFishHook.java:210)
09.05 19:29:19 [Server] INFO java.lang.NullPointerException
09.05 19:29:19 [Server] SEVERE Exception ticking entity EntityAtumFishHook['entity.Atum.EntityAtumFishHook.name'/258623, l='DIM7', x=1042.24, y=31.90, z=1833.79] in rX: 65, rZ: 114, hashCode: 7471169/Twilight Forest/7:
09.05 19:29:19 [Server] INFO at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
09.05 19:29:19 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
09.05 19:29:19 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
09.05 19:29:19 [Server] INFO at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
09.05 19:29:19 [Server] INFO at nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:61)
09.05 19:29:19 [Server] INFO at net.minecraft.world.World.func_72870_g(World.java:2481)
09.05 19:29:19 [Server] INFO at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:941)
09.05 19:29:19 [Server] INFO at net.minecraft.world.World.func_72866_a(World.java:391)
09.05 19:29:19 [Server] INFO at rebelkeithy.mods.atum.artifacts.arrow.EntityAtumFishHook.func_70071_h_(EntityAtumFishHook.java:210)
09.05 19:29:19 [Server] INFO java.lang.NullPointerException
09.05 19:29:19 [Server] SEVERE Exception ticking entity EntityAtumFishHook['entity.Atum.EntityAtumFishHook.name'/258623, l='DIM7', x=1042.24, y=31.90, z=1833.79] in rX: 65, rZ: 114, hashCode: 7471169/Twilight Forest/7:
09.05 19:29:19 [Multicraft] Skipped 114 lines due to rate limit (30/s)
09.05 19:29:19 [Server] INFO at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:941)
09.05 19:29:19 [Server] INFO at net.minecraft.world.World.func_72866_a(World.java:391)
09.05 19:29:19 [Server] INFO at rebelkeithy.mods.atum.artifacts.arrow.EntityAtumFishHook.func_70071_h_(EntityAtumFishHook.java:210)
09.05 19:29:19 [Server] INFO java.lang.NullPointerException
09.05 19:29:19 [Server] SEVERE Exception ticking entity EntityAtumFishHook['entity.Atum.EntityAtumFishHook.name'/258623, l='DIM7', x=1042.24, y=31.90, z=1833.79] in rX: 65, rZ: 114, hashCode: 7471169/Twilight Forest/7:
09.05 19:29:18 [Server] INFO at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
09.05 19:29:18 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
09.05 19:29:18 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
09.05 19:29:18 [Server] INFO at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
09.05 19:29:18 [Server] INFO at nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:61)
09.05 19:29:18 [Server] INFO at net.minecraft.world.World.func_72870_g(World.java:2481)
09.05 19:29:18 [Server] INFO at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:941)
09.05 19:29:18 [Server] INFO at net.minecraft.world.World.func_72866_a(World.java:391)
09.05 19:29:18 [Server] INFO at rebelkeithy.mods.atum.artifacts.arrow.EntityAtumFishHook.func_70071_h_(EntityAtumFishHook.java:210)
09.05 19:29:18 [Server] INFO java.lang.NullPointerException
09.05 19:29:18 [Server] SEVERE Exception ticking entity EntityAtumFishHook['entity.Atum.EntityAtumFishHook.name'/258623, l='DIM7', x=1042.24, y=31.90, z=1833.79] in rX: 65, rZ: 114, hashCode: 7471169/Twilight Forest/7:
09.05 19:29:18 [Server] INFO at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
09.05 19:29:18 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
09.05 19:29:18 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
09.05 19:29:18 [Server] INFO at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
09.05 19:29:18 [Server] INFO at nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:61)
09.05 19:29:18 [Server] INFO at net.minecraft.world.World.func_72870_g(World.java:2481)
09.05 19:29:18 [Server] INFO at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:941)
09.05 19:29:18 [Server] INFO at net.minecraft.world.World.func_72866_a(World.java:391)
09.05 19:29:18 [Server] INFO at rebelkeithy.mods.atum.artifacts.arrow.EntityAtumFishHook.func_70071_h_(EntityAtumFishHook.java:210)
09.05 19:29:18 [Server] INFO java.lang.NullPointerException
09.05 19:29:18 [Server] SEVERE Exception ticking entity EntityAtumFishHook['entity.Atum.EntityAtumFishHook.name'/258623, l='DIM7', x=1042.24, y=31.90, z=1833.79] in rX: 65, rZ: 114, hashCode: 7471169/Twilight Forest/7:
09.05 19:29:18 [Multicraft] Skipped 146 lines due to rate limit (30/s)
09.05 19:29:17 [Server] INFO at rebelkeithy.mods.atum.artifacts.arrow.EntityAtumFishHook.func_70071_h_(EntityAtumFishHook.java:210)
09.05 19:29:17 [Server] INFO java.lang.NullPointerException
09.05 19:29:17 [Server] SEVERE Exception ticking entity EntityAtumFishHook['entity.Atum.EntityAtumFishHook.name'/258623, l='DIM7', x=1042.24, y=31.90, z=1833.79] in rX: 65, rZ: 114, hashCode: 7471169/Twilight Forest/7:
09.05 19:29:17 [Server] INFO at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
09.05 19:29:17 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
09.05 19:29:17 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
09.05 19:29:17 [Server] INFO at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
09.05 19:29:17 [Server] INFO at nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:61)
09.05 19:29:17 [Server] INFO at net.minecraft.world.World.func_72870_g(World.java:2481)
09.05 19:29:17 [Server] INFO at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:941)
09.05 19:29:17 [Server] INFO at net.minecraft.world.World.func_72866_a(World.java:391)
09.05 19:29:17 [Server] INFO at rebelkeithy.mods.atum.artifacts.arrow.EntityAtumFishHook.func_70071_h_(EntityAtumFishHook.java:210)
09.05 19:29:17 [Server] INFO java.lang.NullPointerException
09.05 19:29:17 [Server] SEVERE Exception ticking entity EntityAtumFishHook['entity.Atum.EntityAtumFishHook.name'/258623, l='DIM7', x=1042.24, y=31.90, z=1833.79] in rX: 65, rZ: 114, hashCode: 7471169/Twilight Forest/7:
09.05 19:29:17 [Server] INFO at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
09.05 19:29:17 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
09.05 19:29:17 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
09.05 19:29:17 [Server] INFO at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
09.05 19:29:17 [Server] INFO at nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:61)
09.05 19:29:17 [Server] INFO at net.minecraft.world.World.func_72870_g(World.java:2481)
09.05 19:29:17 [Server] INFO at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:941)
09.05 19:29:17 [Server] INFO at net.minecraft.world.World.func_72866_a(World.java:391)
09.05 19:29:17 [Server] INFO at rebelkeithy.mods.atum.artifacts.arrow.EntityAtumFishHook.func_70071_h_(EntityAtumFishHook.java:210)
09.05 19:29:17 [Server] INFO java.lang.NullPointerException
09.05 19:29:17 [Server] SEVERE Exception ticking entity EntityAtumFishHook['entity.Atum.EntityAtumFishHook.name'/258623, l='DIM7', x=1042.24, y=31.90, z=1833.79] in rX: 65, rZ: 114, hashCode: 7471169/Twilight Forest/7:
09.05 19:29:17 [Server] INFO Received a tiny packet for network id 52 that is not recognised here
09.05 19:29:17 [Multicraft] Skipped 105 lines due to rate limit (30/s)
09.05 19:29:16 [Server] INFO at rebelkeithy.mods.atum.artifacts.arrow.EntityAtumFishHook.func_70071_h_(EntityAtumFishHook.java:210)
09.05 19:29:16 [Server] INFO java.lang.NullPointerException
09.05 19:29:16 [Server] SEVERE Exception ticking entity EntityAtumFishHook['entity.Atum.EntityAtumFishHook.name'/258623, l='DIM7', x=1042.24, y=31.90, z=1833.79] in rX: 65, rZ: 114, hashCode: 7471169/Twilight Forest/7:
09.05 19:29:16 [Server] INFO at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
09.05 19:29:16 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
09.05 19:29:16 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
09.05 19:29:16 [Server] INFO at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
09.05 19:29:16 [Server] INFO at nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:61)
09.05 19:29:16 [Server] INFO at net.minecraft.world.World.func_72870_g(World.java:2481)
09.05 19:29:16 [Server] INFO at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:941)
09.05 19:29:16 [Server] INFO at net.minecraft.world.World.func_72866_a(World.java:391)
09.05 19:29:16 [Server] INFO at rebelkeithy.mods.atum.artifacts.arrow.EntityAtumFishHook.func_70071_h_(EntityAtumFishHook.java:210)
09.05 19:29:16 [Server] INFO java.lang.NullPointerException
09.05 19:29:16 [Server] SEVERE Exception ticking entity EntityAtumFishHook['entity.Atum.EntityAtumFishHook.name'/258623, l='DIM7', x=1042.24, y=31.90, z=1833.79] in rX: 65, rZ: 114, hashCode: 7471169/Twilight Forest/7:
09.05 19:29:16 [Server] INFO at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
09.05 19:29:16 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
09.05 19:29:16 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
09.05 19:29:16 [Server] INFO at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
09.05 19:29:16 [Server] INFO at nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:61)
09.05 19:29:16 [Server] INFO at net.minecraft.world.World.func_72870_g(World.java:2481)
09.05 19:29:16 [Server] INFO at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:941)
09.05 19:29:16 [Server] INFO at net.minecraft.world.World.func_72866_a(World.java:391)
09.05 19:29:16 [Server] INFO at rebelkeithy.mods.atum.artifacts.arrow.EntityAtumFishHook.func_70071_h_(EntityAtumFishHook.java:210)
09.05 19:29:16 [Server] INFO java.lang.NullPointerException
09.05 19:29:16 [Server] SEVERE Exception ticking entity EntityAtumFishHook['entity.Atum.EntityAtumFishHook.name'/258623, l='DIM7', x=1042.24, y=31.90, z=1833.79] in rX: 65, rZ: 114, hashCode: 7471169/Twilight Forest/7:
09.05 19:29:16 [Server] INFO TobiGamer25 used the wrong password
09.05 19:29:16 [Multicraft] Skipped 56 lines due to rate limit (30/s)
09.05 19:29:15 [Server] INFO at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:941)
09.05 19:29:15 [Server] INFO at net.minecraft.world.World.func_72866_a(World.java:391)
09.05 19:29:15 [Server] INFO at rebelkeithy.mods.atum.artifacts.arrow.EntityAtumFishHook.func_70071_h_(EntityAtumFishHook.java:210)
09.05 19:29:15 [Server] INFO java.lang.NullPointerException
09.05 19:29:15 [Server] SEVERE Exception ticking entity EntityAtumFishHook['entity.Atum.EntityAtumFishHook.name'/258623, l='DIM7', x=1042.24, y=31.90, z=1833.79] in rX: 65, rZ: 114, hashCode: 7471169/Twilight Forest/7:
09.05 19:29:14 [Server] INFO at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
09.05 19:29:14 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
09.05 19:29:14 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
09.05 19:29:14 [Server] INFO at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
09.05 19:29:14 [Server] INFO at nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:61)

**Comment by LunNova** [comment]
1.5 is not supported. TT for 1.5 was not finished. Do not use TT for 1.5.
