### ISSUE TITLE
Extra Utilities Transfer pipes not working

### ISSUE THREAD

**Issue by Zeroxius** [MinimallyCorrect/TickThreading#1100]
TickThreading-1.6.4.178
FTBServer-1.6.4-965 (No MCPC+) Monster pack (With some extra mods)
extrautils-1.0.3a

Extra Utilities transfer nodes don't pass items or liquid down transfer pipes. No errors show up in log, and this does not happen when TT is not installed.

Edit: Problem does not resolve even if pipes are broken and replaced. It appears the transfer node doesn't search for an inventory through the pipes as if the pipes weren't there.

**Comment by Katelyn-SN** [comment]
Things like this should be fixed in the latest 184 build :)

Please test those and report back.

**Comment by Zeroxius** [comment]
Now transfer nodes/pipes are working perfectly on build 190. :D Thank you!
