### ISSUE TITLE
java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by vanZeben** [MinimallyCorrect/TickThreading#1101]
Setting the auto-save interval to 0 in the config, in order to disable it as I have other saving methods employed returns said error http://pastebin.com/raw.php?i=FZAimARc

https://github.com/vanZeben/TickThreading/commit/4b22f14f19dd2205d9dd7b2c0439e199bf44bb0e is a fix for this

**Comment by Katelyn-SN** [comment]
You should make a pull request

**Comment by LunNova** [comment]
You missed another use on L297! :P

I'll add support for this, but why do you want to use something else for saving? TT's partial saving is designed to have very low impact compared to normal saving, and I've also fixed some cases where chunk.isModified was set by mods for no reason.
