### ISSUE TITLE
version 1.6.4 with thermal expansion fluids.

### ISSUE THREAD

**Issue by beaverextreme** [MinimallyCorrect/TickThreading#1108]
There appears to be an issue with Thermal expansion and fluids in this version. Below is the log with the first 3 errors, as it spammed the log with the same thing until I closed it. 

https://gist.github.com/beaverextreme/e16d25c918e8c73e1969

**Comment by LunNova** [comment]
Duplicate of #1102.

**Comment by LunNova** [comment]
Should be fixed with 1e2bdde43405db2fa.
