### ISSUE TITLE
Minefactory Reloaded Conveyor belts

### ISSUE THREAD

**Issue by jznomoney** [MinimallyCorrect/TickThreading#1114]
I am having issues with mfr conveyor belts not functioning properly with tickthreading being used on 1.6.4.  I am also loading it through mcpc+ as well.  The belts only seem to move in one direction when I rotate them.  The look like they are faced properly but when I go on them I only go one direction.

**Comment by Katelyn-SN** [comment]
Please test against vanilla forge and mcpc+ so we can know if it occurs on both also post your tickthreading logs.

**Comment by jznomoney** [comment]
I can't get it to load vanilla weird.
