### ISSUE TITLE
EnderIO spam logfile with ConcurrentModificationException

### ISSUE THREAD

**Issue by WeslieDE** [MinimallyCorrect/TickThreading#1133]
05-19 10:31:15 [WARNING] [EnderIO] NetworkPowerManager: Exception thrown when updating power network java.util.ConcurrentModificationException

**Comment by LunNova** [comment]
Good job, EnderIO mod dev. Good job. Let's just catch exceptions and not print the stack trace or rethrow them. How helpful.

Just to find the error message I need to make a patch. :/
