### ISSUE TITLE
Strange issues when people teleport?

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#114]
I've been getting these all day today whenever someone dies (which teleports them) or whenever someone teleports via mystcraftbook or does /home

http://pastebin.com/sS491EXu

**Comment by LunNova** [comment]
Looks like the position update is being processed at the same time as the respawning.

**Comment by Puremin0rez** [comment]
Only appears to happen when a teleport is between dimensions, which is pretty noticeable in a mystcraft based server.
