### ISSUE TITLE
deadlock server crash?

### ISSUE THREAD

**Issue by witchway915** [MinimallyCorrect/TickThreading#1148]
The Log File
https://gist.github.com/witchway915/e83d6298f31837ce9e95

The patcher file
https://gist.github.com/witchway915/e83d6298f31837ce9e95

Using TPPI v 0.3.0
MCPC+
Aside from Adding TT, I updated Opis, and Mytown

**Comment by LunNova** [comment]
I'm pretty sure Opis' packet profiler is non-threadsafe and broken, without TT.

Fixing it anyway, but can't see how it doesn't crash without TT.
