### ISSUE TITLE
Paypal

### ISSUE THREAD

**Issue by Sp0nge** [MinimallyCorrect/TickThreading#115]
Add you paypal-link somewhere

**Comment by Puremin0rez** [comment]
I disagree with the label put on this ticket! This is a very important issue and must be resolved!

**Comment by Puremin0rez** [comment]
@nallar 

Does this mean yes?

**Comment by GUIpsp** [comment]
@Puremin0rez Still tagged as wontfix

**Comment by LunNova** [comment]
And, of course, github's markdown doesn't allow the `bitcoin:` protocol.
