### ISSUE TITLE
World loading speed around the player

### ISSUE THREAD

**Issue by Daniel86268** [MinimallyCorrect/TickThreading#1155]
First of all: This isn't an error.
When spawning to a non-chunkloaded place, or teleporting to this place the player is usually standing in a single chunk for a few seconds. The chunks nearby aren't loading for quite some time. Then the chunks are loading from one direction to the other, which is taking quite some time.
I've encountered it on 1.4.7 versions of TickThreading too. 
I've tested it on a xeon e3-1230v2 server with 4 gig ram. Also I was the only player online. CPU load usually around 0.1% to 3%, memory load at 900mb/3G. So It wasn't caused by the serverhardware.
I think it would be awesome, if the chunks near the player are loading first, and later the chunks further away.
Thanks in advance :)

**Comment by devryb** [comment]
Actually noticed this happen and the chunks would simply not load for me until the server was restarted.
One thing that did happen though shortly before it started was a full map backup.  So maybe that caused the issue.  This however wasn't an issue without TT

Here's a nice example:
http://i.imgur.com/d7o722o.jpg

**Comment by Daniel86268** [comment]
I am not using map backups of any kind, so it can't be related to that. Also In your screenshot there are some chunks loaded. I was experiencing that I was standing in the only chunk around that was loaded. There was no other chunk loaded. After a few seconds though the world loaded guite fine. 
I am pretty sure, this relates to the World loading order: Normally the world starts to load directly around the player, then further away. With Tickthreading the world loads from one side of the render distance to the other.
With this loading order the whole world loading for one player might be faster, I don't know if this is the case, but it seems slower because the chunks nearby the player are beeing loaded later on.

**Comment by devryb** [comment]
I also seen the one chunk thing at that time as well.  That screenshot was from relogging a couple times.  But ya if it loaded for you eventually then this is unrelated as it simply wouldn't load for anyone on the server until it was restarted.
