### ISSUE TITLE
Server has deadlocked (7 times) Async Chunkloading Error

### ISSUE THREAD

**Issue by Zilacon** [MinimallyCorrect/TickThreading#1161]
http://pastie.org/9207453

Now this happens with Async Chunkloading enabled OR disabled on the mcpc.yml config file, i have tested it with both.

**Comment by LunNova** [comment]
See line 175 of your paste, the deadlock is in no way related to async chunkloading. 

It is because the idisguise plugin is stupidly update checking on the main thread and with no timeout set so it waits forever trying to check for an update with a server it can't connect to for some reason.

**Comment by Zilacon** [comment]
Alright thanks for clearing that up, ill go talk to him then.
