### ISSUE TITLE
WorldGuard dont work anymore

### ISSUE THREAD

**Issue by WeslieDE** [MinimallyCorrect/TickThreading#1162]
WorldGuard dont stop user to place blocks in protectet areas.
Without TT its work.
I have test it with the Monster modpack

Step 1 - Download Monster Modpack and add mcpc
Step 2 - Add WorldGuard and WorldEdit
Step 3 - Start server, all work
Step 4 - Add TT
Step 5 - Everyone can place blocks but dont destroy in protectet areas.

**Comment by WeslieDE** [comment]
i have made a littel plugin to test it.

https://github.com/PePaPu/DontBuildInWorldNull

on a bukkit server its work. On a mcpc+ too. 
Only with TT the BlockPlaceEvent dont work.

**Comment by LunNova** [comment]
Did this work correctly on older TT builds? If so, do you know the last build it worked with?

**Comment by WeslieDE** [comment]
jup, in the past its have work.

the last time who im sure that it work was before B209

**Comment by devryb** [comment]
Can also confirm this with build 219.

**Comment by vanZeben** [comment]
Somewhere between 207 and 209 (inclusive on both) broke this, 206 and earlier work fine

**Comment by LunNova** [comment]
That fix is completely untested, I need to sleep now. Sorry.

**Comment by vanZeben** [comment]
That fix results in an immediate crash when breaking a block: http://pastebin.com/GKX6W5hd

**Comment by Katelyn-SN** [comment]
Yep for me as well i reverted to build 119
