### ISSUE TITLE
Server Deadlock build #219 - Meteorcraft?

### ISSUE THREAD

**Issue by ProsperCraft** [MinimallyCorrect/TickThreading#1165]
A player was in this mystcraft world and it deadlocked the server, see attached log.
The console didn't show anything at all, it just quit responding.

http://www.mediafire.com/download/xets43aacm8nd9j/DIM_MYST3.BROKEN.zip

See log at-
http://paste.md-5.net/puqatoguvo.hs

**Comment by Katelyn-SN** [comment]
Please edit this and post the log to pastebin.com

**Comment by LunNova** [comment]
Not a TT bug, will fix anyway. Nasty world gen code there which has a propensity for infinite loops.

**Comment by ProsperCraft** [comment]
You are so awesome!
