### ISSUE TITLE
Exception ticking block net.minecraft.block.BlockGrass

### ISSUE THREAD

**Issue by Zilacon** [MinimallyCorrect/TickThreading#1187]
Not sure if you wanted a seperate error report for this or not so here it is.

05-26 19:12:53 [SEVERE] [TickThreading] Exception ticking block net.minecraft.block.BlockGrass@4d9bc9bb at x20y664z60 in Sanctuary/3
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_6_R3.CraftWorld.getBlockAt(CraftWorld.java:82)
    at net.minecraft.block.BlockGrass.func_71847_b(BlockGrass.java:56)
    at net.minecraft.world.WorldServer.run(WorldServer.java:605)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by devryb** [comment]
Got something similar

27.05 18:44:32 [Server] INFO at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
27.05 18:44:32 [Server] INFO at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
27.05 18:44:32 [Server] INFO at net.minecraft.world.WorldServer.run(WorldServer.java:605)
27.05 18:44:32 [Server] INFO at net.minecraft.block.BlockGrass.func_71847_b(BlockGrass.java:77)
27.05 18:44:32 [Server] INFO at net.minecraft.world.World.func_72798_a(World.java:188)
27.05 18:44:32 [Server] INFO at net.minecraft.world.World.func_72964_e(World.java:212)
27.05 18:44:32 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ThreadedChunkProvider.java:449)
27.05 18:44:32 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.getChunkAtInternal(ThreadedChunkProvider.java:550)
27.05 18:44:32 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_73239_e(ThreadedChunkProvider.java:745)
27.05 18:44:32 [Server] INFO at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75815_a(ThreadedChunkLoader.java:156)
27.05 18:44:32 [Server] INFO at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75822_a(ThreadedChunkLoader.java:188)
27.05 18:44:32 [Server] INFO at net.minecraftforge.event.EventBus.post(EventBus.java:108)
27.05 18:44:32 [Server] INFO at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
27.05 18:44:32 [Server] INFO at net.minecraftforge.event.ASMEventHandler_330_WorldExtensionEventHandler_onChunkDataLoad_Load.invoke(.dynamic)
27.05 18:44:32 [Server] INFO at codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkDataLoad(WorldExtensionManager.java:38)
27.05 18:44:32 [Server] INFO at codechicken.lib.world.WorldExtension.loadChunkData(WorldExtension.java:57)
27.05 18:44:32 [Server] INFO java.lang.NullPointerException
27.05 18:44:32 [Server] SEVERE A mod failed to handle a ChunkDataEvent.Load event for 4,1
