### ISSUE TITLE
Possible enhancement with mystcraft

### ISSUE THREAD

**Issue by Katelyn-SN** [MinimallyCorrect/TickThreading#1188]
Im wondering if TT could add this as a feature a patch to mystcraft that would allow you to change where mystcraft dimensions are saved on the disk. For me and many others that run public servers with mystcraft this would be quite essential as it would allow us to move mystcraft dimensions off our SSDs and to our 1-2TB HDDs

Not really a performance enhancement but something that would benefit server owners quite a bit

**Comment by Katelyn-SN** [comment]
This isn't a bug.. Its a enhancement that should be made...

**Comment by LunNova** [comment]
I was skimming the titles when setting the labels, didn't notice as "enhancement" was misspelled (phone autocorrected?) to "enchantment". Fixed it now.
