### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#119]
It seems like the newer builds are very ram hungry, I'm not sure if my server has just gotton to that point or if TT is being unhappy.

Can't confirm its TT either way, so thought I'd leave this here for investigation.

**Comment by Puremin0rez** [comment]
I should note I haven't tried the "world cleaning" build yet - gonna go do that now

**Comment by LunNova** [comment]
I'm also trying to investigate a heap dump, leaving my PC on all night
analysing it. Apparently it takes a long time to calculate the retained
sizes of 50 million objects.

**Comment by LunNova** [comment]
and fixed! :D
