### ISSUE TITLE
IllegalStateException with teleporting - Build #816

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#120]
Still happening for me:
http://pastebin.com/rcErGZT0

**Comment by LunNova** [comment]
Still broken after 2a02f64?

**Comment by Puremin0rez** [comment]
@nallar 
It's still happening, however it no longer kicks me :)

**Comment by Puremin0rez** [comment]
Sorry - You did indeed fix Mystcraft causing this problem - so thanks alot for that!

However, now Fihgus command teleport commands are broken and causing these issues every single time
http://pastebin.com/A70sUynL

**Comment by Puremin0rez** [comment]
Still happening:
http://pastebin.com/N8QVQT15

**Comment by LunNova** [comment]
Using latest fihgu's, couldn't get this to happen while testing a fix for #117.

**Comment by Puremin0rez** [comment]
@nallar 

It's only happening (and still happening) on certain dimensions for me

Dimension 4 and 8 appear to give this error everytime I do a /spawn, while others do not.

Same pastebin as before, nothing changed in error:
http://pastebin.com/N8QVQT15

**Comment by Puremin0rez** [comment]
Teleporting is fixed now, but I still get this error which causes me to get thrown into the void on some dimensions.

Dimension 4 and Dimension 8 give me this error when using /spawn to leave them. Zero idea why.

**Comment by LunNova** [comment]
Can you try with 3e02f6ad32ad814c1d?

**Comment by Puremin0rez** [comment]
@nallar 

You fixed it! But... now there's more strange behavior.

It loads all the chunks fine and no error in console, but i can't break any blocks or anything until I relog.

/ticks e shows 0 players - so that's not good.

We're getting further!

**Comment by LunNova** [comment]
Still happening after the fix we discussed early in the morning two days ago on IRC?

**Comment by tprussak** [comment]
I'm running mystcraft and fighu's on my server, and I don't get any errors switching worlds on build 913.

**Comment by SShadowS** [comment]
I dont have world switching errors anymore. Build 918.
