### ISSUE TITLE
MASSIVE Network & World usage when exploring world.

### ISSUE THREAD

**Issue by Zilacon** [MinimallyCorrect/TickThreading#1207]
Me and 2 others were exploring the server going separate directions, after about 5 mins of exploring this is what i saw when doing /tps

http://prntscr.com/3oicew

Almost 300% load on the world we were exploring for just 200 chunks!
And 140% Network Load...

Any idea what could be causing this?

**Comment by Littleniamh** [comment]
Are you running a modpack with Alternative Terrain Generation mod.

I see similar problems within my server when that's running as it generates much larger areas than the normal Terrain Generation.

**Comment by Zilacon** [comment]
The only thing that would be generating terrain is Biomes O Plenty and Better Dungeons

Here is my pack: http://www.technicpack.net/modpack/details/apocalyptic-gaming-tech-rpg.363244
