### ISSUE TITLE
[Suggestion] Focus on essential mods that are included in most modpacks

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickThreading#1209]
Hey,

I would like to propose to focus on mods like thermal expansion that are included in all well played modpacks like:
- Monster
- B-Team
- Agrarian Skies
- Horizons
- ....

.. and are essential to the game-play and important to players.

This would allow us to use tickthreading earlier and profit by delivering less lag to the players.

**Comment by ghost** [comment]
Couple issues:

Deciding which mods are essential.

"profit by delivering less lag to the players." - If you mean money when you say profiting that is highly distasteful. If you just want Tick Threading so you can cram more players onto a money grabbing server then in my opinion you can go twiddle your thumbs while your server bursts into flames. Apologies if this is not what you mean.

What about issues with "non-essential" mods? What if Logistics Pipes is deemed "non-essential", should issues for that mod be ignored until Tick Threading runs flawlessly with "essential" mods?

**Comment by Slind14** [comment]
Sorry, in my culture "profit" is not only money related. This wouldn't change anything for us delivering more slots or anything, but it would improve the tps which is a "profit" mainly for the players and save us time dealing with the complaints and telling that there isn't much we can do. Next to this, it might also allow us to merge servers back together instead of having multiple ones.

I'm not saying that only these mods should be supported, what I suggest is to make a list of mods that are within most of the modpacks and used/loved by most players. This would allow everyone to use tickthreading earlier and let the players enjoy their loved modpacks on medium servers with improved performance thanks to nallar.

**Comment by Slind14** [comment]
Edit: Just a small example, Agrarian Skies is mainly based on Thermal Expension, there are a lot of servers out but they all are exploding as it hyped that much. If TE would be usable with TT servers could already use it.
