### ISSUE TITLE
Tickthreading bug with Thermal Expansion 3.0.0.7

### ISSUE THREAD

**Issue by UXELDUXEL** [MinimallyCorrect/TickThreading#1211]
Hi i am currently building a server with Tickthreading v1.6.4.230 and i am having some issues with thermal Expansion 3.0.0.7.

All pipes of Thermal Expansion are disconnecting from eachother(at chunk borders) when the chunk reloads(eg server restart and chunk reload) and sometimes they just completely bug out.
I think its because of forge multipart not working with tickthreading but i am not sure abbout that. Sometimes those pipes just do weird stuff for exemple turning an Endertank into an enderchest just while staying next to it. This didnt happen while we dont had tickthreading

**Comment by UXELDUXEL** [comment]
really ... hmm but the pipes were working fine without tickthreading
I dont think its caused by thermal expansion i just made a world copy to my testserver without tickthreading and its working fine there

Anyways maybe it just derps out more often with tickthreading i keep restarting my testserver the entire night every 10 minutes tomorrow i am gonna tell you if it has derped out ... (I dont want to fix that mod with javaassist myself god damit)

so it didnt derp out without tickthreading even tho i made 100 restarts

**Comment by UXELDUXEL** [comment]
Alright this one got fixed by updateing forge multipart to the version 250
i think the version 244 i was using just wasnt compatible to tickthreadings seems fine if something goes wrong again i will report

**Comment by UXELDUXEL** [comment]
to early still pipes disconnecting ... on server restart damn

**Comment by Katelyn-SN** [comment]
Already a known issue please close this duplicate.
