### ISSUE TITLE
Issue with thermal expansion [Modpack CrackPack] Version: THERMALEXPANSION-3.0.0.7

### ISSUE THREAD

**Issue by Zerys2424** [MinimallyCorrect/TickThreading#1214]
Fluid ducts no longer work correctly and do not transport fluids.

All power conduits from the mod no longer transmit power and sometimes do not connect properly. 

Does not seem to throw an error in console / log

Tick threading version: 230 current latest  for me.

**Comment by Katelyn-SN** [comment]
Already a known issue please close this duplicate.

**Comment by Katelyn-SN** [comment]
Please look at #1235 for a possible fix
