### ISSUE TITLE
Agrarian Skies Server Deadlock

### ISSUE THREAD

**Issue by witchway915** [MinimallyCorrect/TickThreading#1219]
https://gist.github.com/witchway915/9233ac17e58ad7e6dc87

using Agrarian Skies  v2.1.6

MCPC+ mcpc-plus-1.6.4-R2.1-forge965-B272

TT 230

If you need anything else let me know

**Comment by Zilacon** [comment]
@witchway915 I dont suppose you still got B272 for MCPC? Ive been looking everywhere and cannot find it because of the DMCA.
