### ISSUE TITLE
NullPointerException on /tps - Build #820

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#122]
http://pastebin.com/mD83mCQd

**Comment by Puremin0rez** [comment]
Probably related to this:
https://github.com/nallar/TickThreading/issues/121

**Comment by LunNova** [comment]
Possibly. Fixed via 78f2e85e27d9. If it still shows a world as "NaN" tick time, it's being loaded/unloaded incorrectly.

If you're using BukkitForge, that might be causing it. Recent builds seem to do some odd stuff with worlds.
