### ISSUE TITLE
Patching 821 "error"

### ISSUE THREAD

**Issue by Sp0nge** [MinimallyCorrect/TickThreading#123]
02-04 16:28:13 [FINE] [TickThreading] Patching methods [transferPlayerToDimension(Lnet/minecraft/entity/player/EntityPlayerMP;ILnet/minecraft/world/Teleporte
02-04 16:28:13 [WARNING] [TickThreading] Failed to find exact match for (Lnet/minecraft/entity/player/EntityPlayerMP;ILnet/minecraft/world/Teleporter;)V, try
02-04 16:28:13 [FINE] [TickThreading] Patching gm with synchronize(field:$1.f,deobf:net.minecraft.server.management.ServerConfigurationManager/respawnPlayer)

**Comment by LunNova** [comment]
Just a warning, I'll clean it up later.
