### ISSUE TITLE
Twilight Forest Chunk Generation

### ISSUE THREAD

**Issue by ghost** [MinimallyCorrect/TickThreading#1230]
Request an investigation into the serve lag that's produced while using MCPC+ and TickThreading. It's terrible, the client freezes upward towards a minute or more.

Using:
TickThreading-1.6.4.233.jar

mcpc-plus-1.6.4-R2.1-forge965-B272.jar
twilightforest-1.20.2.jar

Thank you.

**Comment by kMaiSmith** [comment]
Is this while generating in the Twilight Forest dimension or over all?

**Comment by Zilacon** [comment]
This is not an issue with TT as i have experienced and fixed it myself.

The problem with TwilightForest is it spawns these trees called Canopy Trees that go high into the sky with a crap ton of leaves making the forest seem "dark and spooky".

In 1.5.2 there was no option to disable this but thank god it was added to 1.6.4. Go into your config and scroll all the way to the bottom and set the canopy tree size from 1.7 to 0 this will remove the darkness from the forest but overall will greatly improve performance.

Also minimaps and twilight forest do not get along well, if you got a minimap and you still experience lag after getting rid of canopy trees, that's your next lag source.

**Comment by ghost** [comment]
@Zilacon 

Thank you very much! I had to add the performance section, it wasn't found inside the config. It's working great now.

**Comment by Zilacon** [comment]
No problem! Glad i could help :)
