### ISSUE TITLE
Unable to start 1.6.4 ftbserver w/ mcmyadmin

### ISSUE THREAD

**Issue by Russell-IO** [MinimallyCorrect/TickThreading#1242]
we are unable to set the --serverJar=xyz.jar when using McMyAdmin, is it possible to parameterise this value instead of requiring it as a command line argument ?

**Comment by Katelyn-SN** [comment]
Modify the generated ttlaunch.properties files in the root of the server if your intended on using this on a public server do not its way to unstable

**Comment by Russell-IO** [comment]
@tf101-wizard Thank you, no it's a private server

**Comment by Russell-IO** [comment]
I've documented these steps & raised a PR
