### ISSUE TITLE
Applied Energistics - Missing I.D.s

### ISSUE THREAD

**Issue by lemeur68** [MinimallyCorrect/TickThreading#1243]
Im playing on a custom mod pack with out TT whenever I make Applied Energistics items then save and exit then reneter my world their I.D.s change and dissapre. PLEASE HELP I LOSE ALL MY STUFF IN THE COMPUTER.

MODS IM USING:
[1.6.4]BetterFurnacesV3.4.dev
[1.6.4]Ultimate Tools Universal by Sahdow169[1.11.0.0]
[Forge]MrCrayfishConstructionModv1.0.5 (1.6.4)
1.6.4 DamageIndicatorsv2.9.2.3
AetherCraft-1.2.9.71 (1)
AnimationAPI v1.1.2 mc1.6.4
appeng-rv14-finale3-mc16x
backpack-1.26.29-1.6.x
buildcraft-A-1.6.4-4.2.2
CodeChickenCore 0.9.0.7
COFHCORE-2.0.0.5
Dungeon Mobs v3.0.2
Extra-Utilities-Mod-1.6.4
Familiars_API_1.6.4a
Familiars_DefaultMobPack_1.6.4a
Familiars_ExtendedFamPack_1.6.4a
Familiars_HerobrineFamPack_1.6.4a
Galacticraft-1.6.4-2.0.13.1063
Galacticraft-Planets-1.6.4-2.0.13.1063
Hawkeye Mod v2.1.3 Forge
idfix-1.6.4-1.1.0
idfixminus-1.6.4-1.0.0
InventoryTweaks-MC1.6.2-1.56-b77 (1)
ironchest-universal-1.6.4-5.4.1.702
LuckyBlock_v4.2.1_1.6.4
MicdoodleCore-1.6.4-2.0.13.1063
MinersDeluxe-v2.2.4
More Swords Mod 2.5.5. For 1.6.2
MorePlayerModels_1.6.2-1.6.4
Mutant_Creatures_v1.4.4_mc1.6.4
NotEnoughItems 1.6.1.8
Starminer164-0_9_5
Superheroes Unlimited Mod V2.3.3 (1)
SVIM_v1.5.1_1.6.4
Sync2.1.1
TelePads 1.6.4 v5
THERMALEXPANSION-3.0.0.5
VeinMiner.0.12.2_MC1.6

**Comment by Katelyn-SN** [comment]
This is not a error caused by TickThreading as such no support will be provided.

**Comment by lemeur68** [comment]
Why though?

**Comment by Katelyn-SN** [comment]
Because these are the issue section for TickThreading if your not running TickThreading then we have no reason to support you with and error not caused by this software

@nallar Request to close issue

**Comment by lemeur68** [comment]
Okay thank you for telling me.
