### ISSUE TITLE
TickThreading with Chickenbones Translocators on Multiplayer

### ISSUE THREAD

**Issue by LLunatic** [MinimallyCorrect/TickThreading#1247]
Have a very heavily modded server losely based around the FTB monster pack that we installed tick threading onto to help with some of the CPU issues we were having. Shortly after we tried playing around with the translocators mod and found that it worked just fine, till you left the area or the chunk unloaded. Upon the chunk unloading the translocators blocks just disappear completely. No log on the console, nothing i can find in the tick threading logs.

Wondering if Tickthreading may be the cause of this i have removed it from my server for the time being and the translocator blocks work just fine now and dont disappear. 

I really would like to continue to be able to use tick threading as it definitely helps with the CPU and seems to make the server run much smoother. Any suggestions?

**Comment by Katelyn-SN** [comment]
TickThreading is highly unstable and should not be used on any server other
than for development and testing.

**Comment by dariusc93** [comment]
Like @tf101-wizard  stated that TT is unstable. If you use TT you do accept the risk of corruption, etc., and should make backups before (and even during) use of TT. To they disappear as in completely from the map, or it doesnt render when you come back? If so, go back to the chunk and try /tick r

**Comment by LLunatic** [comment]
I regularly take backups. I have had a few other issues with Tick Threading as well that i have not yet reported. But since i removed it from my server i have not had any of these issues. Im aware that its unstable and still in testing.

Yes they seem to disappear completely. Translocators is supposed to move items from one inventory to another. There are not still items moving from inventory to another when they disappear. So im assuming its not a rendering issue.

**Comment by Katelyn-SN** [comment]
I see this issue present as well no errors or anything it just gone no chunk resets or anything.

**Comment by LLunatic** [comment]
Any news on getting this issue resolved?

**Comment by dariusc93** [comment]
At the moment, TT is currently inactive. I have no time to go and debug it myself mainly since I do not support 1.6.4 no more. I would suggest removing TT from the server. If you have performance issues, run warmroast, opis, or some type of jvm profiler to determine the cause of the performance decrease.
