### ISSUE TITLE
Low Profile 1.7.10 Update?

### ISSUE THREAD

**Issue by Zilacon** [MinimallyCorrect/TickThreading#1249]
I was wondering if you could toss most of the complicated stuff out the window like mod patching and simply make a update for 1.7.10 that does server based things like the following:
- Crash Localization (Only crash the clients/players in the chunks around where the crash started, this is on 1.5.2/1.6.4 and it makes sure the servers uptime is always high.)
- Deadlock Detection (This has literally saved me from insanity, which is why ive been a huge fan of your work. Maintaining 8+ servers and dealing with deadlocks or crashes is a life killer. This automated my network so i could actually focus on my computer business. Just having this on 1.7.10 would be wonderful not to constantly worry about my servers deadlocking while im away.)
- Region & Chunk Management (Region sizes, chunk unloading, etc)
- World Unloading (Already in nTweaks a simple copy/paste i hope?)
- Tile Entity Unloading (Unload tile entities in worlds or chunks not in use.)
- TickThreading's Tick Profiler (TT's TP is better than TP because you can do /ticks in a world and get an instant output of the EXACT coordinates of whos messing up your server. TP gives you a very vague range by just giving you the region coordinates.)
- nTweaks (Just throwing this in would cover a lot of TT already like the AI, Mobs, World Unloading, ETC and seems to work after your latest fix perfectly fine.)
- TE Tick Control? (1.7.10 KCauldron has a huge tile entity list of tick timings you can edit it would be great if it was simplified. Like Machines: 2 / Pipes: 2 / Cables: 1 / ETC. Basically allow group control of the tick timings instead of individually changing them. My modpack is 230 mods strong and the TE file is over 12,000 lines long.)

As for the multi-threading that would be an awesome addition for the SERVER but i do not want to see you get burned out again trying to patch every single mod. Just getting the server part of TT going would make me extremely happy.

Also a plus side of not patching mods, the restarts wont take 15 minutes lol. Although your mod cache on the 1.5.2 version seemed to fix this but it was removed in 1.6.4.

But if you dont want to do it i understand, i figured id just ask. I have been using TickThreading since 1.4.7.

**Comment by LunNova** [comment]
I don't really want to do a 1.7.10 release. The modded MC world is starting to move on to 1.8.9, and by the time it's actually done there will be few people who need it.

If this does get done, it'll be done after the 1.8.9 release by downgrading the 1.8.9 release to 1.7.10-and turning off threading, depending on how much of a pain that is. 1.7.10 <> 1.8.9 is a pretty big jump :(

**Comment by Zilacon** [comment]
Alright, as it stands right now only 4 or 5 of the mods in my pack have updated to 1.8 in the last year. So i really do not see a full 1.8 modpack coming anytime soon which is why i thought id ask.

Plus there is NO server solution for 1.8. KCauldron is the only modded server software on the internet and he has no intentions of updating to 1.8 because as he states "Its 10x worse than 1.7". So since there is no server software out there for it i really dont see there being a large demand for 1.8 mods or modpacks.

**Comment by LunNova** [comment]
The lack of a server with bukkit API support for 1.8.[0/8/9] is a big problem there.

The most promising candidate is [Pore, the bukkit <> Sponge bridge](https://forums.spongepowered.org/t/pore-a-bukkit-sponge-bridge/1663/75). Sponge has entered beta now, and I hope this combination will reach a usable state soon.

Now that Forge has fixed/added workarounds for many of the problems with the blockstates/model loading, we're [starting to see mod updates](https://bot.notenoughmods.com/1.8.9.html). 
FTB have [locked updates for 1.7.10 packs](http://forum.feed-the-beast.com/threads/ftb-news-dec-28th-2015.137368/).

It will probably be multiple months before TT is in a working state. The first 1.4.7 version took about 6 months to reach stability.

**Comment by tenten8401** [comment]
i cri everytiem

**Comment by LunNova** [comment]
Definitely not going for 1.7.10. As expected, I've been too busy lately and there's no way I'll have time to backport for 1.7.10.
