### ISSUE TITLE
Using Mixins

### ISSUE THREAD

**Issue by gabizou** [MinimallyCorrect/TickThreading#1251]
So I've noticed that there's something called [Mixin](https://github.com/nallar/Mixin) and while it's great and all to do this, I would like to note that there's already another [Mixin library](https://github.com/SpongePowered/Mixin) which at SpongePowered, we've developed for a little over a year now, and suffice to say that the power wielded with it is pretty substantial. Examples can be found in [SpongeCommon](https://github.com/SpongePowered/SpongeCommon/tree/master/src/main/java/org/spongepowered/common/mixin) and [SpongeForge](https://github.com/SpongePowered/SpongeForge/tree/master/src/main/java/org/spongepowered/mod/mixin).

Note that I'm not dissuading you from developing your own mixin library, just, if it helps to speed up development to use an existing well tested library that does almost everything possible to remain mod compatible as possible while still wielding the power of injections and additions to Minecraft's code at runtime.

**Comment by LunNova** [comment]
Thanks for your interest. I had a discussion with @Mumfrey recently on IRC and can post a transcript if you want. Small excerpt regarding the naming

>  <nallar> Sorry Mum_frey, I'll say mix_in for now. stole your project's name as it's an existing programming term, and made more sense than "PrePatcher". I can rename it to "TerribleHackyCodeInjectorThingamabob" if you want

This was meant as a joke, but if you do have more sensible ideas for an alternate name I'm happy to swap it over.

Unfortunately, SpongePowered/Mixin doesn't really match my needs - and I'm not sure it's intended to?

Things I needed (or do not necessarily need but strongly prefer to the implementation in SpongePowered/Mixin):
- Applying mixins to both .java source files and .classes
- Allowing the addition of fields and methods to the target classes in the development environment, so I can access these without casting to interfaces (impossible with fields) with `@Add` (previously `@Declare` in older TT versions which used PrePatcher).
- Allowing access to private/protected methods/fields/inner classes without needing to add stubs
- Ability to completely replace an existing class (for example: [1.5.2 ThreadedChunkProvider](https://github.com/nallar/TickThreading/blob/1.5.2/src/common/nallar/patched/storage/ThreadedChunkProvider.java)

If adding this sort of behavior to SpongePowered/Mixin without interfering withe existing usecases is possible, I could swap to it but that sounds like a significant engineering effort for minimal benefit. I may also have misunderstood, and some of this behavior is already possible in SpongePowered/Mixin.
