### ISSUE TITLE
java.lang.Error: Inconsistent transformation results.

### ISSUE THREAD

**Issue by ProsperCraft** [MinimallyCorrect/TickThreading#1252]
On forge-1.8.9-11.15.1.1764-universal
with spongeforge-1.8.9-1763-4.1.0-BETA-1212
Tickthreading-core doesn't seem to load - there is no config file created.

Possibly relevant portion of the log file-
http://pastebin.com/4WQ6pSFR

Entire log- https://www.dropbox.com/s/bawkkzmtrnhyt3e/fml-server-latest.log?dl=1

**Comment by LunNova** [comment]
ModPatcher issues with Sponge transformers have been resolved in ModPatcher/0ed2e55a05bb4a36588 and other commits on the same day.
