### ISSUE TITLE
Does this still work on 1.8.9?

### ISSUE THREAD

**Issue by madtomic** [MinimallyCorrect/TickThreading#1253]
Great project btw!

**Comment by madtomic** [comment]
What I mean is for spigot 1.8.9 servers.

**Comment by Katelyn-SN** [comment]
No, it will not work on Spigot server's it's designed around forge it's not a plugin.

**Comment by LunNova** [comment]
I'm currently not targetting Spigot/MCPC/Cauldron/etc type things.

For 1.8.9 I wasn't aware that there even was a release of that sort of thing?

**Comment by ShlongDongSilver** [comment]
sponge i believe has a 1.8, thats probably the only forge plugin handler. https://github.com/SpongePowered

**Comment by LunNova** [comment]
Sponge will be supported. It currently causes some issues with patching, but they will be fixed.
