### ISSUE TITLE
Is 1.7.10 still an option?

### ISSUE THREAD

**Issue by tenten8401** [MinimallyCorrect/TickThreading#1255]
A lot of the modded servers are still running on 1.7.10 and it would be absolutely wonderful if you could give this a backport to 1.7.10 as that version completely missed out.

Glad your back by the way!

**Comment by LunNova** [comment]
See discussion under #1249 and #1248

**Comment by tenten8401** [comment]
That's just sad. Can't wait until my favorite mods go to 1.8.9

-Isaac
On 7/2/2016 9:19:10 PM, Ross Allan notifications@github.com wrote:
See discussion under #1249 [https://github.com/nallar/TickThreading/issues/1249] and #1248 [https://github.com/nallar/TickThreading/issues/1248]

**Comment by tenten8401** [comment]
May I just point this out.
1.2k mods vs 47.
http://modlist.mcf.li/version/1.7.10
http://modlist.mcf.li/version/1.8.9

**Comment by ghost** [comment]
Number of mods for a specific version of Minecraft should never be the determining factor for which version of the Forge API you build a new piece of software for. All in all, stick to the past for to long and you're bound to be in a situation where nothing progresses at all.
