### ISSUE TITLE
It will support SpongeForge?

### ISSUE THREAD

**Issue by MineMine** [MinimallyCorrect/TickThreading#1256]
I'm very exciting that you restart the Tickthreading project :D

**Comment by LunNova** [comment]
Yes, I aim to support sponge.

There are already a few ~lovely~ horrible workarounds in ModPatcher to ensure I can patch after sponge's mixins are applied.

https://github.com/nallar/ModPatcher/blob/1.10.2/src/main/java/me/nallar/modpatcher/LaunchClassLoaderUtil.java

**Comment by MineMine** [comment]
I glad that you say so :D
