### ISSUE TITLE
1.7.10?

### ISSUE THREAD

**Issue by BlayzerQ** [MinimallyCorrect/TickThreading#1257]
Why not version for 1.7.10?

**Comment by LunNova** [comment]
See #1255, #1249, #1248

**Comment by BlayzerQ** [comment]
1.7.10 is actual for big minecraft modded networks.
Is it possible to port the mod on 1.7.10 for a fee?

**Comment by ghost** [comment]
He already tried that, he got burned out to the point where it wasn't worth it. All in all, if you really want TickThreading that badly for MC 1.7.10, learn how to code and attempt to do it yourself.
