### ISSUE TITLE
861: Enet not working again

### ISSUE THREAD

**Issue by Sp0nge** [MinimallyCorrect/TickThreading#126]
Updated to this build from 853 and the stable enet stopped for some players just after the update.

**Comment by LunNova** [comment]
This might just have been the ENet failing to work correctly on restart bug, not the random disconnecting bug which seems fixed.

Possibly an issue with events - IC2 uses them for adding/removing from enet.

**Comment by LunNova** [comment]
Fixed via 563f723ebcbe2
