### ISSUE TITLE
A couple clarifications

### ISSUE THREAD

**Issue by benjamin-kirkbride** [MinimallyCorrect/TickThreading#1260]
I am putting this as an issue because it is currently not clear in any documentation that I have seen.

Does using this and TickProfiler redundant?

What is the current state of the 1.10.2 release?

The /ticks command doesn't work.

I'm currently testing this out on a 1.10.2 server, and it is working great! I was getting over 160ms/t and am now getting <10

**Comment by LunNova** [comment]
> Does using this and TickProfiler redundant?

For 1.5.2 and 1.4.7, yes. TickProfiler was included in TickThreading.

> What is the current state of the 1.10.2 release?

Very incomplete. Have implemented some very basic optimisations which aren't related to threading as a way of testing out the new patching system.

> I'm currently testing this out on a 1.10.2 server, and it is working great! I was getting over 160ms/t and am now getting <10

I don't understand anything.
