### ISSUE TITLE
1.10.2 server not start with TT

### ISSUE THREAD

**Issue by marekvac** [MinimallyCorrect/TickThreading#1267]
Hey, I have put TickThreading-core on my 1.10.2 server. And after server done generating world. Start spaming this. https://pastebin.com/UdtcPBEt And server will not start.

**Comment by LunNova** [comment]
TickThreading is not yet ready for minecraft 1.10.2.

![image](https://user-images.githubusercontent.com/782440/44281506-f1f0b400-a24f-11e8-8ab1-3b63c8078e29.png)
