### ISSUE TITLE
Wither Skeleton SoulShard Spawners become Skeleton Spawners

### ISSUE THREAD

**Issue by coderjcronin** [MinimallyCorrect/TickThreading#127]
After running and patching TickThreading, all tier Wither Skeleton spawners (created via SoulShards plugin) become regular skeleton spawners. Removing TickThreading and restoring the original mod files turns them back into Wither spawners.

**Comment by LunNova** [comment]
I disabled the spawned skeletons' extra code, it was rather slow. I guess it was responsible for doing this.

I'll try to replace it soon.

edit: and I'm bad, that wasn't the issue with spawned skeletons. Reverted that change.
