### ISSUE TITLE
#886 BuildCraft Conductive pipes wont transfer energy anymore.

### ISSUE THREAD

**Issue by SShadowS** [MinimallyCorrect/TickThreading#129]
Electric engine -> Wooden Con -> Golden Con -> Golden Con -> Golden Con -> Machine

All power builds up in first Golden Con til it explodes.

**Comment by LunNova** [comment]
Is this still broken in latest?

**Comment by SShadowS** [comment]
I can't check it at the moment as I have only access to the console from here, but uploaded the new version and now Overworld is at 133% load (/tps).
And that were not the case before.
You are welcome to get access to the server if that helps you regarding debugging and the logs you need.

**Comment by SShadowS** [comment]
Disregard the lag issue, it settled by itself somehow. But Confuctive pipes are still not working.
The offer to give you access to the server still stands.

UPDATE Lag issue:
It had 5500 Entities load constantly until first person logged in, then it fell to about 76 entities.

**Comment by LunNova** [comment]
I've disabled all forms of mob spawning in latest if 0 players are online, which should fix that.

Can you link a screenshot of the faulty setup, and gist/pastebin your TickThreadingLogs/tickthreading.log? Thanks.

**Comment by SShadowS** [comment]
Full log:
https://gist.github.com/SShadowS/4761238

Picture of setup:
http://peecee.dk/uploads/022013/2013-02-12_09.53.36.png

**Comment by amcgrath18** [comment]
Yeah Im have the same problem.

**Comment by LunNova** [comment]
Still broken?

**Comment by alicheek** [comment]
id say its fixed never had any of my players complain
