### ISSUE TITLE
Xycraft and Thaumcraft random client side crashes

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#13]
Again, mildly similar to Carpenter crashing issue

Ever since we've Installed TickThreading on our main server, people have been crashing client-side with the following 2 crash reports - I've had them send me there entire folder of crash reports and it's happening quite frequently and they all seem to have the same error.

We removed TickThreading for an entire day, and the issues did not happen.

I understand client crashs can be a bitch to fix, so hopefully you find something out.

Here is the XyCraft crash that is happening - again, it's hard to reproduce this - it just happens randomly when teleporting or walking around or logging in.
http://pastebin.com/sM05wL5d

And here is the ThaumCraft client crash that is happening - again, can't really reproduce this - it just happens.
http://pastebin.com/gSFsswqQ

**Comment by LunNova** [comment]
TT seems to be making a forge issue worse - in the build included with mindcrack, forge is at a build with faulty chunk compression. This causes chunks to load incorrectly sometimes, which can cause rendering crashes.

The issue only happens with multiple players in an area, and I believe that TT is making it worse by increasing the chance of two players loading the same chunks at the same time.

It may be fixed if you either update before patching, or if already patched update forge in TickThreadingBackups/mindcrack.jar to forge 489 then patch.

Haven't proven this, doing some testing just now.

**Comment by LunNova** [comment]
Forge was already up to date, but the issue I reported with the fields not being volatile has not been fixed - I've added this to the patcher. It fixes an issue with garbage chunk data, but maybe not the issue causing this. There may also be others.

**Comment by Puremin0rez** [comment]
Should I go ahead and update Forge on the server to the latest available build? I'm assuming it'll still be compatible with the clients

**Comment by LunNova** [comment]
No, turns out forge was already up to date - I got the version wrong.

The issue should be fixed in the latest build though :)

**Comment by Puremin0rez** [comment]
Okay I'll be sure to try it out - thanks for being awesome! One of my favorite devs.

**Comment by Puremin0rez** [comment]
So far so good... haven't had any users report client crashes today.

**Comment by LunNova** [comment]
Closing this, since these exceptions seem to be fixed.
