### ISSUE TITLE
Mystcraft Accelerated Symbols do not work

### ISSUE THREAD

**Issue by tprussak** [MinimallyCorrect/TickThreading#132]
The accelerated symbol from Mystcraft does not work, as it normally functions by raising the tickrate of that age, however, TT changes something and causes it not to work.
Mystcraft v0.9.5.00
TickThreading v913
Forge v515

**Comment by LunNova** [comment]
I won't be fixing this. Mystcraft implements this in a way which causes reduced performance, so there's not much point in supporting it with this mod. If you really need it I can try, but it seems like a lot of bother for something which will just make performance worse.
