### ISSUE TITLE
Opening Carpenter

### ISSUE THREAD

**Issue by Sp0nge** [MinimallyCorrect/TickThreading#14]
Generated 07.01.13 20:15

-- Head --
Stacktrace:
    at forestry.factory.gui.GuiFermenter.drawGuiContainerBackgroundLayer(GuiFermenter.java:29)
    at forestry.core.gui.GuiForestry.a(GuiForestry.java:231)

-- Screen render details --
Details:
    Screen name: forestry.factory.gui.GuiFermenter
    Mouse location: Scaled: (320, 240). Absolute: (640, 481)
    Screen size: Scaled: (640, 481). Absolute: (1280, 962). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [ays['Sp0nge'/986, l='MpServer', x=330,57, y=65,62, z=312,62]]
    Chunk stats: MultiplayerChunkCache: 225
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (96,64,256), Chunk: (at 0,4,0 in 6,16; contains blocks 96,0,256 to 111,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 14267494 game time, 1024961 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false

Stacktrace:
    at ayp.a(WorldClient.java:440)
    at net.minecraft.client.Minecraft.b(Minecraft.java:2401)
    at net.minecraft.client.Minecraft.run(Minecraft.java:787)
    at java.lang.Thread.run(Unknown Source)

java.lang.ClassCastException: forestry.factory.gadgets.MachineCarpenter cannot be cast to forestry.factory.gadgets.MachineFermenter
    at forestry.factory.gui.GuiFermenter.drawGuiContainerBackgroundLayer(GuiFermenter.java:29)
    at forestry.core.gui.GuiForestry.a(GuiForestry.java:231)
    at ban.b(EntityRenderer.java:1004)
    at net.minecraft.client.Minecraft.J(Minecraft.java:882)
    at net.minecraft.client.Minecraft.run(Minecraft.java:771)
    at java.lang.Thread.run(Unknown Source)
--- END ERROR REPORT 2014bbc4 ----------

Some parts are taken out, like what entities are around, systemspecs etc. If those are needed, let me know

**Comment by LunNova** [comment]
Looks like the patcher must have messed up, as I've tested the fix as working locally. Please add your patcher.log.

**Comment by Sp0nge** [comment]
Patcher:

01-07 20:24:33 [WARNING] [TickThreading] in is in multiple jars: /home/minecraft/testingonly/minecrack.jar, /home/minecraft/testingonly/mods/StevesCarts2.0.0.a41.zip
01-07 20:24:33 [INFO] [TickThreading] Replaced a
01-07 20:24:33 [INFO] [TickThreading] Replacing (Llq;Laoe;)Ljava/util/List; with (Llq;Laoe;)Ljava/util/List;
01-07 20:24:33 [INFO] [TickThreading] Replaced b
01-07 20:24:33 [INFO] [TickThreading] Replacing (Llq;Laoe;)Ljava/util/List; with (Llq;Laoe;)Ljava/util/List;
01-07 20:24:33 [INFO] [TickThreading] Replaced a
01-07 20:24:33 [INFO] [TickThreading] Replacing (Ljava/lang/Class;)I with (Ljava/lang/Class;)I
01-07 20:24:33 [INFO] [TickThreading] Replaced h
01-07 20:24:33 [INFO] [TickThreading] Replacing ()V with ()V
01-07 20:24:33 [WARNING] [TickThreading] yc is in multiple jars: /home/minecraft/testingonly/minecrack.jar, /home/minecraft/testingonly/mods/StevesCarts2.0.0.a41.zip
01-07 20:24:33 [WARNING] [TickThreading] zz is in multiple jars: /home/minecraft/testingonly/minecrack.jar, /home/minecraft/testingonly/mods/StevesCarts2.0.0.a41.zip
01-07 20:24:33 [INFO] [TickThreading] Replacing (Laoe;)Z with (Laoe;)Z
01-07 20:24:33 [INFO] [TickThreading] Replacing kc with me.nallar.tickthreading.patched.LongHashMap
01-07 20:24:33 [WARNING] [TickThreading] iq is in multiple jars: /home/minecraft/testingonly/minecrack.jar, /home/minecraft/testingonly/mods/StevesCarts2.0.0.a41.zip
01-07 20:24:33 [WARNING] [TickThreading] lq is in multiple jars: /home/minecraft/testingonly/minecrack.jar, /home/minecraft/testingonly/mods/StevesCarts2.0.0.a41.zip
01-07 20:24:34 [WARNING] [TickThreading] cpw.mods.fml.common.FMLModContainer is in multiple jars: /home/minecraft/testingonly/minecrack.jar, /home/minecraft/testingonly/mods/StevesCarts2.0.0.a41.zip
01-07 20:24:34 [INFO] [TickThreading] Not patching com.mumfrey.liteloader.core.HookProfiler, not found.
01-07 20:24:34 [INFO] [TickThreading] blockUpdates -> javassist.is.faulty.ThreadLocals.redPowerBlockUpdateSet
01-07 20:24:34 [INFO] [TickThreading] powerSearchTest -> javassist.is.faulty.ThreadLocals.redPowerPowerSearchTest
01-07 20:24:34 [INFO] [TickThreading] powerSearch -> javassist.is.faulty.ThreadLocals.redPowerPowerSearch
01-07 20:24:34 [INFO] [TickThreading] Removed signing info from ModularForceFieldSystemV2.2.8.2.14.zip
01-07 20:24:34 [INFO] [TickThreading] Removed signing info from extrabees-1.4.9.6-prerelease.zip
01-07 20:24:35 [INFO] [TickThreading] Removed signing info from StevesCarts2.0.0.a41.zip
01-07 20:24:35 [INFO] [TickThreading] Patched 1 classes in Factorization-0.7.10.jar, patchHash: -304770502
01-07 20:24:35 [INFO] [TickThreading] Patched 1 classes in industrialcraft-2_1.112.170-lf.jar, patchHash: 1968997397
01-07 20:24:35 [INFO] [TickThreading] Added 1 classes required by patches.
01-07 20:24:36 [INFO] [TickThreading] Patched 2 classes in buildcraft-A-3.3.0.jar, patchHash: -968048817
01-07 20:24:36 [INFO] [TickThreading] Removed signing info from AdvancedMachines_4.7a.zip
01-07 20:24:36 [INFO] [TickThreading] Removed signing info from RedPowerMechanical-2.0pr6.zip
01-07 20:24:37 [INFO] [TickThreading] Removed signing info from Traincraft-3.1.13_010.jar
01-07 20:24:37 [INFO] [TickThreading] Removed signing info from RedPowerCompat-2.0pr6.zip
01-07 20:24:37 [INFO] [TickThreading] Removed signing info from OmniTools-2.2.5.zip
01-07 20:24:37 [INFO] [TickThreading] Removed signing info from Railcraft_1.4.6-6.12.2.0.zip
01-07 20:24:38 [INFO] [TickThreading] Patched 11 classes in minecrack.jar, patchHash: -1779151149
01-07 20:24:38 [INFO] [TickThreading] Added 2 classes required by patches.
01-07 20:24:38 [INFO] [TickThreading] Patched 1 classes in RedPowerCore-2.0pr6.zip, patchHash: 1370962707
01-07 20:24:39 [INFO] [TickThreading] Removed signing info from ComputerCraft1.481.zip
01-07 20:24:39 [INFO] [TickThreading] Removed signing info from forestry-A-1.6.4.1.jar
01-07 20:24:40 [INFO] [TickThreading] Patched 2 classes in ThermalExpansion-2.1.6.zip, patchHash: 1488500180
01-07 20:24:40 [INFO] [TickThreading] Removed signing info from xycraft-universal-1.4.6-0.9.44.zip
01-07 20:24:40 [INFO] [TickThreading] Removed signing info from RedPowerDigital-2.0pr6.zip
01-07 20:24:41 [INFO] [TickThreading] Removed signing info from Traincraft-3.1.13_010.jar
01-07 20:24:41 [INFO] [TickThreading] Removed signing info from ComputerCraft1.48pr3.zip
01-07 20:24:41 [INFO] [TickThreading] Done. Press enter to exit.

**Comment by LunNova** [comment]
We discussed via IRC + voice, got it fixed. :)
