### ISSUE TITLE
#943 Console spam ic2/Buildcraft addContinuousTickCallback

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#143]
http://pastebin.com/p3S2pCBg

**Comment by LunNova** [comment]
[Known IC2 bug with foam and cables](http://bt.industrial-craft.net/view.php?id=240)

**Comment by HaoSs07** [comment]
strange.  i use foam and cables for more then 2 weeks now. but never got this spam in console.
