### ISSUE TITLE
TT build #944 [TickThreading] Exception in main tick loop // codechicken

### ISSUE THREAD

**Issue by The-sMi** [MinimallyCorrect/TickThreading#148]
its a problem with codechicken, the server works but the log file get every sec a entry with this error.

http://pastebin.com/ap0nCNLL

**Comment by cronixia** [comment]
Getting the same thing, I get this error multiple times a second.

http://pastebin.com/mWCemaSh

Followed with this error a few minutes later, spammed every second.

02-17 02:27:49 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
