### ISSUE TITLE
log with errors.  multiple mods ? 

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#150]
http://pastebin.com/ZNbipP5u

**Comment by HaoSs07** [comment]
server crashed  3 times today with the same error 
http://pastebin.com/mRVbHW8x ( crash report from crash-report directory )

**Comment by LunNova** [comment]
This should be fixed in latest. If that doesn't fix it, turn off world unloading in TT's config.

**Comment by HaoSs07** [comment]
ok. try last build now.

**Comment by HaoSs07** [comment]
for now all its good. will monitor the server. you can close it
