### ISSUE TITLE
Crash with FTB Mindcrack 1.4.7 & TT 947

### ISSUE THREAD

**Issue by Quest79** [MinimallyCorrect/TickThreading#151]
Fresh install, right after running PATCHME
https://gist.github.com/anonymous/4968221

**Comment by LunNova** [comment]
However, TT is not currently useable on clients, there's not much point in trying.

**Comment by Quest79** [comment]
Wouldn't it help in FTB SSP? My tile entities are at 30% overall. Thanks for the quick response!

**Comment by LunNova** [comment]
That's probably the rendering time, which TT won't help with.

It would help in single player if you've managed to build enough stuff on your own to make the internal server lag, but you probably haven't.
