### ISSUE TITLE
Crash report. computer craft ?

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#153]
http://pastebin.com/Pq6aRtmZ

also this happend... 02-17 02:26:07 [SEVERE] [TickThreading] Froze while attempting to stop - halting server. 

i was monitoring the server just when the error happen. does the stop really works ? gamecp reboots the server if it does not detect it online. but don't think the stop from TT works.

**Comment by LunNova** [comment]
This is a computercraft deadlock bug with some peripherals, and fixed in the latest computercraft version.

With exitOnDeadlock enabled in the config the stop should always work, but it can take a while if the deadlock also causes saving the world to freeze.

**Comment by LunNova** [comment]
Also, see #39
