### ISSUE TITLE
Map Chunk "Borders"

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#16]
Not sure if TT is causing it - but I haven't noticed it until I messed around with the newest builds - possibly related to the errors in my other issue report?

http://i.imgur.com/5p8IP.jpg

**Comment by Puremin0rez** [comment]
Now that I'm looking over it, I'm pretty sure this is NOT caused by TT - but I'm leaving this ticket here incase you stumble upon anything. Better to report more then less!

I'm guessing MindCrack v7 updated some terrain stuff

**Comment by LunNova** [comment]
That seems to be the case, won't have time to test with v7 for about 8 hours so I'll leave this open just in case it is a problem.

**Comment by LunNova** [comment]
Looks like the extrabiomesxl update changed worldgen.
