### ISSUE TITLE
Exception in main tick loop

### ISSUE THREAD

**Issue by scenegull** [MinimallyCorrect/TickThreading#164]
Not sure how this works, my first time. I like the plugin, but this error showed up after a few hours of play. It's running on a FTB server, latest as of date. I will paste a section of the log here. If it should go someplace else, I'm sorry. The end of the log just repeats ad infinitum. It doesn't appear to be affecting the server, just floods the console.

Ok, I'm not entirely useless, figured out how to use a github link.

https://gist.github.com/scenegull/4990714

**Comment by LunNova** [comment]
This is fixed in the latest build, however it may be broken in other ways.

**Comment by LunNova** [comment]
Closing, forgot to close this earlier. Oops.
