### ISSUE TITLE
Server crash right after patching to 969 from 958.

### ISSUE THREAD

**Issue by SShadowS** [MinimallyCorrect/TickThreading#165]
It won't even start

https://gist.github.com/SShadowS/4990779

**Comment by LunNova** [comment]
That's an odd error, were there any other errors in the console? I don't
see how patching could make the modinfo file fail to parse...

**Comment by SShadowS** [comment]
Might have been, but had to revert back quickly to 958. Have had the error
on all builds above that number. Will copy the files to another VM to
reproduce the error.
Den 20/02/2013 00.06 skrev "Ross Allan" notifications@github.com:

> That's an odd error, were there any other errors in the console? I don't
> see how patching could make the modinfo file fail to parse...

**Comment by SShadowS** [comment]
I have now researched it a bit and it seems to be ForgeBackup that breaks it. But it is strange that if I use 958 then ForgeBackup dont break.

**Comment by LunNova** [comment]
I have forgebackup installed while on latest, and it doesn't crash on startup. Might have accidentally fixed it? :)

**Comment by xfloh22** [comment]
tryed latest build and also have forgebackup installed, il see if uninstalling changes anything, exact same version update is causing it to break

**Comment by LunNova** [comment]
It's an forgebackup bug, just that TT build happens to make it happen. :p

[Made a report with monoxide, should be fixed in the next forgebackup version.](http://www.minecraftforge.net/forum/index.php/topic,4606.msg32630.html#msg32630)
