### ISSUE TITLE
Exception in server tick loop - java.lang.StackOverflowError

### ISSUE THREAD

**Issue by geoffcorey** [MinimallyCorrect/TickThreading#166]
Patcher.log

https://gist.github.com/geoffcorey/4991074

Crash Report

https://gist.github.com/geoffcorey/4991059

Running MindCrack 8.1.0 + Logistics Pipes  with the following JVM params on dedicated 8-core 16GB machine

 -XX:UseSSE=4 -XX:+UseCMSCompactAtFullCollection -XX:ParallelGCThreads=6 -XX:+UseConcMarkSweepGC -XX:+DisableExplicitGC -XX:+CMSIncrementalMode -XX:+CMSIncrementalPacing -XX:+UseCompressedOops -XX:+AggressiveOpts

**Comment by LunNova** [comment]
Try build 958.

**Comment by geoffcorey** [comment]
Get this about every 20 - 30 seconds but the server is not crashing or lagging.

02-19 18:45:48 [SEVERE] [TickThreading] TickThreading v1.0.0.958 for MC1.4.7 is installed on this server!
If anything breaks, check if it is still broken without TickThreading
We don't want to annoy mod devs with issue reports caused by TickThreading.
Seriously, please don't.
If it's only broken with TickThreading, report it at http://github.com/nallar/TickThreading
02-19 18:45:51 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c logisticspipes.proxy.cc.LogisticsTileGenericPipe_CC logisticspipes.proxy.cc.LogisticsTileGenericPipe_CC@3835d7fd x,y,z: 12, 67, 658 at x,y,z:12,67,658
Tick region: rX: 0, rZ: 41, hashCode: 2686976:
java.lang.NullPointerException
        at logisticspipes.routing.PathFinder.getConnectedRoutingPipes(PathFinder.java:104)
        at logisticspipes.routing.PathFinder.getConnectedRoutingPipes(PathFinder.java:50)
        at logisticspipes.routing.ServerRouter.recheckAdjacent(ServerRouter.java:292)
        at logisticspipes.routing.ServerRouter.checkAdjacentUpdate(ServerRouter.java:657)
        at logisticspipes.routing.ServerRouter$floodCheckAdjacent.isInteresting(ServerRouter.java:644)
        at logisticspipes.routing.ServerRouter.act(ServerRouter.java:592)
        at logisticspipes.routing.ServerRouter.act(ServerRouter.java:604)
        at logisticspipes.routing.ServerRouter.act(ServerRouter.java:604)
        at logisticspipes.routing.ServerRouter.act(ServerRouter.java:604)
        at logisticspipes.routing.ServerRouter.updateAdjacentAndLsa(ServerRouter.java:708)
        at logisticspipes.routing.ServerRouter.update(ServerRouter.java:723)
        at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:283)
        at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
        at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:89)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:150)
02-19 18:45:51 [SEVERE] [TickThreading] Exception during tile entity tick

**Comment by geoffcorey** [comment]
Quick followup.  Other then that exception show up in the logs the 8 cores on the machine have a nice distribution and the game is very responsive with 8 ppl logged on playing.

**Comment by geoffcorey** [comment]
Sorry the exception above is every few minutes in the tickthreading.log.   The error showing up in console every 20-30 seconds is:

SEVERE Exception during entity tick at rX: 7, rZ: 31, hashCode: 2031623:
19.02 19:00:30 [Server] INFO java.lang.NullPointerException
19.02 19:00:30 [Server] INFO Tick region: rX: 97, rZ: 38, hashCode: 2490465:
19.02 19:00:30 [Server] INFO ticking: c buildcraft.transport.TileGenericPipe buildcraft.transport.TileGenericPipe@153e193b x,y,z: 1566, 23, 611 at x,y,z:1566,23,611

**Comment by geoffcorey** [comment]
Followup.  Eventually the world got corrupt with chunk errors in the nether.  We had to revert to a backup and roll back to 8.0.1 of MindCrack.

**Comment by geoffcorey** [comment]
So generated a completely new world using the latest build of Tick Threading 

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2/22/13 9:27 PM
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 0
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:487)
    at fy.run(SourceFile:849)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.4.7
    Operating System: Linux (amd64) version 3.5.0-23-generic
    Java Version: 1.7.0_15, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 390288512 bytes (372 MB) / 632881152 bytes (603 MB) up to 954466304 bytes (910 MB)
    JVM Flags: 2 total; -Xms512M -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
    FML: MCP v7.26a FML v4.7.32.553 Minecraft Forge 6.6.1.524 61 mods loaded, 61 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FEPreLoader [Forge Essentials|PreLoader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeEssentials [Forge Essentials](ForgeEssentials-core-1.4.7-1.1.1.251.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore [CoFH Core](CoFHCore.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core [BuildCraft](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ComputerCraft [ComputerCraft](computercraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CCTurtle [ComputerCraft Turtles](computercraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion [Thermal Expansion](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OmniTools [OmniTools](omnitools.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2 [IndustrialCraft 2](IC2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest [The Twilight Forest](TwilightForest.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders [BC Builders](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy [BC Energy](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory [BC Factory](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport [BC Transport](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon [BC Silicon](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization [Factorization](factorization.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtrabiomesXL [ExtrabiomesXL](extrabiomes.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry [Forestry for Minecraft](forestry.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Railcraft [Railcraft](railcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerCore [RedPower](redpowercore.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerBase [RP Base](redpowercore.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerMachine [RP Machine](redpowermechanical.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerCompat [RP Compat](redpowercompat.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerWiring [RP Wiring](redpowerdigital.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerLogic [RP Logic](redpowerdigital.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerLighting [RP Lighting](redpowerdigital.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerWorld [RP World](redpowermechanical.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedPowerControl [RP Control](redpowermechanical.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion|Factory [Factory](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion|Energy [Energy](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion|Transport [Transport](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    XyCraft [XyCraft](xycraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GregTech_Addon [GregTech-Addon](GregTech.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2NuclearControl [Nuclear Control](IC2NuclearControl.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest [Iron Chest](IronChest.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft [Thaumcraft](Thaumcraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LogisticsPipes|Main [Logistics Pipes](LogisticsPipes-MC1.4.7-0.7.0.90.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PortalGun [Portal Gun](PortalGun.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    StevesCarts [Steve's Carts](StevesCarts.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TickThreading [TickThreading](TickThreading-1.4.7-1.0.0.979.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AdvancedMachines [IC2 Advanced Machines Addon](advancedmachines.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AdvancedSolarPanel [Advanced Solar Panels](advancedsolarpanel.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ChickenChunks [ChickenChunks](chickenchunks.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderStorage [EnderStorage](enderstorage.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BinnieCore [Binnie Core](extrabees.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraBees [Extra Bees](extrabees.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GraviSuite [Gravitation Suite](gravisuite.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MiscPeripherals [MiscPeripherals](miscperipherals.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ModularForceFieldSystem [Modular ForceField System V2](modularforcefieldsystem.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ObsidiPlates [Obsidian Pressure Plates](obsidiplates.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TC [Traincraft](traincraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    drceph.petrogen [Petroleum Generator](petrogen.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SoulShards [SoulShards](soulshards.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WR-CBE|Core [WR-CBE Core](wirelessredstonecore.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WR-CBE|Addons [WR-CBE Addons](wirelessredstoneaddons.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WR-CBE|RedPower [WR-CBE RedPower](wirelessredstoneredpower.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Player Count: 0 / 20; []
    Is Modded: Definitely; Server brand changed to 'forge,fml'
    Type: Dedicated Server (map_server.txt)

**Comment by LunNova** [comment]
Doesn't look like the patcher actually patched the server jar - tickthreading isn't in the server brand. Can you paste the patcher log?

**Comment by geoffcorey** [comment]
https://gist.github.com/geoffcorey/5020363

**Comment by LunNova** [comment]
That's odd, looks like it patched successfully.

Can you try latest, and give a full console log, patcher log and a copy of the server jar if it still doesn't work? I've changed patching since you last tried.

**Comment by geoffcorey** [comment]
I will give it a shot.   Might be Sunday morning when players are offline.

**Comment by geoffcorey** [comment]
Patched it tonight.  

http://pastebin.com/rJnu78xB

**Comment by geoffcorey** [comment]
So the odd thing happening now is a lot of <player> moved wrongly messages.   I added in XX:-OmitStackTraceInFastThrow to the java start script and will restart later this morning to hopefully get better error messages.   Here is what the current TickThreading log looks like https://gist.github.com/geoffcorey/5024139

Another odd behavior is Forge seems to drop permissions when I go to the nether.  Log out and log in and the permissions come back.   Talked to them on IRC and they suggested to use latest betabuild 286.   I put the vanilla jars back in the directory and even before I applied TickThreading patch the server would not start so I dropped back to the 251 build.    May just replace Forge altogether with something else.

**Comment by LunNova** [comment]
Turn off 'antiCheatNotify' in the config if you don't want the moved wrongly messages - that's a vanilla warning message, TT allows admins to see it instead of it just being shown in console as it can be helpful for finding cheaters. Unfortunately, it also can be quite unhelpful, as there are some collision bugs which cause it to be displayed even if people aren't cheating.

By 'lost permissions' do you mean that people couldn't interact with anything?

**Comment by LunNova** [comment]
If that was the issue, fixed via e553d71e683.

**Comment by geoffcorey** [comment]
Removed forge and installed 1001 and repatched against clean mods.  Some errors in the logs but nether block breaking issue is resolved.  Server so far responsive and other then the initial startup errors listed below the log file is quiet.   I will update the ticket later after users rejoin and normal play resumes.

TickThreading.log http://pastebin.com/UNVBP7vd
Patch.log http://pastebin.com/57tNLj8L

**Comment by geoffcorey** [comment]
So odd defect.   When 2 players go through a portal, one player will be invisible to the other until the invisible player logs out and logs back in.   No errors in the log.

**Comment by geoffcorey** [comment]
Quick update.  No errors in logs other then initial posted earlier after several hours of normal gameplay.  Load is balanced across CPUs very nicely.  No memory leaks.

**Comment by geoffcorey** [comment]
Only other issue found is sleep will result in random times rather then dawn.  Sometimes it you wake up and it is earlier in the night!?!?    Anyway I am not sure this is a TickThreading issue.   

Unless you want to keep the issue open for the initial stack traces after patching, feel free to close this issue.

**Comment by LunNova** [comment]
The time should be set correctly after a77a80521368.

**Comment by geoffcorey** [comment]
have not upgraded yet but will do that this weekend.  The other item that is odd is the timers would stop or get stuck.  Not sure if that is a result of TT or something else.   No info in the logs showing any errors.

**Comment by LunNova** [comment]
When you next update, if a timer gets stuck can you run `/dump <x y z of the timer>` and pastebin the results?

**Comment by geoffcorey** [comment]
Upgraded and when one of the players disconnected we got about 800K of this in the logs until I restarted the server

http://pastebin.com/D6qitTmp

Patcher log is http://pastebin.com/6q6jBFqi

Also had 1 timer stop.  When I tried to do the dump on the timer I get

No Block at Overworld/0 x,y,z15,209,69
World time: 15898891
No tile entity at Overworld/0 x,y,z15,209,69

**Comment by geoffcorey** [comment]
The player in question was going from The End to the Overworld when he got disconnected.  Odd thing is 2 of the machines he built and all of his stuff he was wearing disappeared

**Comment by LunNova** [comment]
"No Block at Overworld/0 x,y,z15,209,69" means what it says - if that command gives that incorrectly, then something's completely broken. All it's doing is world.getBlockId, and if that doesn't work most of minecraft involving blocks would break.

Are you sure you got the coordinates right? :s (209 does seem like quite a high y coordinate :p)

Do you still have access to what the first error in the logs was from when that happened? All those exceptions tell us is that world.playerEntities is null, not why, and another exception was probably thrown earlier when it broke.

**Comment by geoffcorey** [comment]
ah, I got y,z mixed.   next time it sticks I'll reissue the command

**Comment by geoffcorey** [comment]
Stuck timer dump
http://pastebin.com/aEYrb2vN

**Comment by geoffcorey** [comment]
Updated to build 1178.   Everything is running smooth and seeing nothing in the logs all morning.   Unreported issue of trees not growing under a chunkloader (tree farm) unless a player was logged appears to be also was corrected.    I am going to close this issue out.   Will reopen if issue reappears.
