### ISSUE TITLE
Incompability with dynmap

### ISSUE THREAD

**Issue by vsilvar** [MinimallyCorrect/TickThreading#168]
Is response to the problem of:
[SEVERE] [dynmap] Error while checking world times:
java.lang.NullPointerException

And your suggesting of contacting the mod author, this response was given:
https://github.com/webbukkit/dynmap/issues/1158

Is there any option to keep both dynmap and cleanWorlds enabled?

**Comment by LunNova** [comment]
@mikeprimm

Nevermind, I see what's wrong - dynmap is handling the world unload in
another thread, after it has been cleaned? I'll make it wait a few ticks.

**Comment by mikeprimm** [comment]
Nah, that was actually handling for the fact that I've seen these event issued by things other than the server thread (which is horribly wrong, but not something I can fix directly).  What it did is took the stuff that I need to have run on the server thread and dispatches that to run after the event.  I'm making the change to make sure that we consider the world unloaded before the event returns, independent of which thread calls the event.

**Comment by mikeprimm** [comment]
OK - I don't have TT setup to test specifically, but the latest Dynmap dev build for Forge should avoid this issue.

**Comment by LunNova** [comment]
Thanks :)
