### ISSUE TITLE
Another Random Clientside Crash

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#17]
http://pastebin.com/zL6yQan2

3 of my users had that today, I figured it was just Minecraft itself but since someone over in the TickThreading thread on FTB forums posted it aswell - I figured it might be an issue.

http://forum.feed-the-beast.com/threads/tickthreading-concurrent-entity-tile-entity-ticks-and-other-optimisations.6498/page-2#post-81010

**Comment by LunNova** [comment]
Thanks, I'll look into it.

**Comment by LunNova** [comment]
This indicates a client bug which isn't TT's fault, as far as I can see.

Some mod is removing entities incorrectly while ticking them in the client. Are people using mystcraft/TF portals when this happens? That may be related.

**Comment by Puremin0rez** [comment]
I don't have Mystcraft installed and I haven't gotten this crash for quite a few days now, so I'm assuming its a unpredictable crash unrelated to TT
