### ISSUE TITLE
Completely failed to save a chunk! error back 

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#170]
http://pastebin.com/kArT20F1

only happens from time to time.

**Comment by LunNova** [comment]
Java has unhelpfully decided not to give a stack trace. :/

Add -XX:-OmitStackTraceInFastThrow to your java parameters, then when it happens again paste the log.

**Comment by HaoSs07** [comment]
after running the server all night the 1gb TT log was to big to open :)) so ... need to try again

**Comment by HaoSs07** [comment]
http://pastebin.com/uf8KZgSP

scroll down past the known pipe error :P

**Comment by LunNova** [comment]
One of your world's .mcr files is corrupted.

**Comment by HaoSs07** [comment]
mcr or mca ? i can reset the nether/end/twilight. but if its overworld... probably there is no way to see what region is corrupted??

**Comment by LunNova** [comment]
Don't have time tonight, will make it log the region tomorrow.

**Comment by HaoSs07** [comment]
no problem, i have time :) thx for help
