### ISSUE TITLE
Custompack with TT

### ISSUE THREAD

**Issue by Sp0nge** [MinimallyCorrect/TickThreading#171]
https://gist.github.com/Sp0nge/09b04c5932effec6927a

We were running threaded worldgeneration at the time (mytown updated for testing) i think, that ill stilll need to get checked.

**Comment by LunNova** [comment]
You can't actually do threaded generation, minecraft's world gen isn't threadsafe. You'll get very buggy terrain.

The server thread froze waiting for the generation lock, which it never acquired as there were 8 other MyTown threads trying to generate at the same time.
