### ISSUE TITLE
Applied energetic with TT build 963

### ISSUE THREAD

**Issue by Sp0nge** [MinimallyCorrect/TickThreading#172]
This is prob the start of the series "mod not covered with FTB" :)

https://gist.github.com/Sp0nge/3da8e4976b7a6241a9d7

**Comment by HaoSs07** [comment]
what does that mean ?

**Comment by xaviorm** [comment]
This issue is in the current stable build as well. From what we could tell last night it looks like it may be wires trying to connect to blocks that will not receive the connection. At least it looked like all the locations we had in the logs were stone bricks.
