### ISSUE TITLE
TT #1001 and newer bukkitforge

### ISSUE THREAD

**Issue by xfloh22** [MinimallyCorrect/TickThreading#175]
The newest builds breaks bukkit forge. It doesnt show any TT related errors but when i remove TT bukkit forge works perfectly. if i find any errors, i will post them

**Comment by WebMaka** [comment]
FWIW, I run BukkitForge for Essentials/GroupManager, Lockette, and the WorldEdit/Border/Guard combo. TT#1006 and BukkitForge #252 do work with each other. Or at least they do enough that Essentials is throwing the MOTD up on my server, and GroupManager permissions appear to be working.

Now if I could just find a solution to that bane of Minecraft server operators everywhere: endofstream disconnects...

**Comment by xfloh22** [comment]
just found an error when i started the server up:

http://pastebin.com/fcL1D1rr

this happens for every plugin i have on the server

**Comment by LunNova** [comment]
Are you also on the newest bukkitforge?

**Comment by xfloh22** [comment]
build #252, which is the newest i see on its jenkins

edit: just to be sure i took a completely clean version of mindcrack v8.1.1. and installed only bukkitforge and TT and the error still happened when i installed just one plugin. and i also get this error when stopping the server with the 2 installed: 

http://pastebin.com/Ypp23Eti

**Comment by LunNova** [comment]
438dc9364c7f should also fix this.
