### ISSUE TITLE
Patching server.

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#177]
running from root:
sh PATCHME.sh
Error: Could not find or load main class me.nallar.tickthreading.patcher.PatchMain

. I patched the server on my pc. then uploadit with FTP . when i start the server. it says that there is no patch,or the patch is old. and run the patchme.sh/cmd.

Any idea ?

**Comment by LunNova** [comment]
Did you remember every folder/file which needs copied? (server jar, mods, coremods, patchedMods)

I've changed the PATCHME.sh/cmd files in latest, so they should work even if they were created on a different computer.

**Comment by HaoSs07** [comment]
used 1015 to patch. and copied all files/folder except server.proprieties . On my pc the patch works. after i upload it to ftp. they don't. and i get the first error if i try to repatch . will try the latest

**Comment by LunNova** [comment]
Can you try latest? The patcher has had a few more changes with how it handles files. If that still doesn't fix it, please upload a copy of your server folder(except don't upload the worlds) so I can try to find what exactly is broken.

**Comment by HaoSs07** [comment]
i see if i have time today . if not. will try next week.probably Tuesday. will come with feedback

**Comment by HaoSs07** [comment]
patched on pc. uploaded to linux server. patch not there :) tryed last version. with direwolf and ultimate modpack

**Comment by HaoSs07** [comment]
also. i had a patched version. removed chicken chunks do to an error.
uploaded a day later patched chicken chunks (made on my pc. with same TT version ). TT does not see the server patched. had do repatch :)
