### ISSUE TITLE
Exception during tile entity tick ticking: c thermalexpansion.transport.tileentity.TileTeleportEnergy thermalexpansion.transport.tileentity.TileTeleportEnergy

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#186]
Running a Direwolf20 FTB server using TickThreading build 1082 and MCPC+ build 233.
The server runs fine for about 5 minutes then crashes with this (From tickthreading.log)
http://pastebin.com/7QtdEZNH

**Comment by LunNova** [comment]
Crashed due to an issue with chickenchunks which is now fixed.
