### ISSUE TITLE
Teleporting issues :\

### ISSUE THREAD

**Issue by Bucky420** [MinimallyCorrect/TickThreading#187]
when you tp with essentials and some other plugins with mcpc+  http://ci.md-5.net/job/MCPC-Plus/

you get stuck in the ground and or become invisable no clue how this happens but a quick fix would be nice.

**Comment by clienthax** [comment]
No such issues on my server with this, please insure you are using the latest build of mcpc

**Comment by LunNova** [comment]
Closing, as there have been no further reports of this and it was likely due to an older MCPC+ version.
