### ISSUE TITLE
Newest FTB build errors

### ISSUE THREAD

**Issue by xfloh22** [MinimallyCorrect/TickThreading#189]
When i start an updated ftb server like mindcrack 8.2 normally, everything is fine, but when i add TT this error shows: 

http://pastebin.com/E47MYk7t

**Comment by LunNova** [comment]
That's actually a bug with latest TT, it won't work with any version of FTB. Try an older build.

**Comment by xfloh22** [comment]
k thanks, though it workds with my mindcrack :O

**Comment by clienthax** [comment]
fixed yet nallar?

**Comment by LunNova** [comment]
Seems to work, hasn't had much testing.

**Comment by clienthax** [comment]
yep works now
