### ISSUE TITLE
Feature: Change Vanilla Auto-Save Interval?

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#19]
Does this have anything to do with Threading? Not really.

Would it be awesome to change the save interval? Yes!

TickThreading seems to be about improving performance and this slight ability to change the save interval would be amazing.

If you don't want to add it to TickThreading, do you think you could make a simple mod that would be able to do such a thing? or know a mod that would be able to do this?

By default Minecraft saves every 90 seconds (might even be 90 ticks, I don't remember) - Bukkit changed this because of the pauses that would happen every 90 seconds, making it configurable via the config file for Bukkit. They made it disabled by default because plugins can do such a thing - but I don't know of any for Forge, so that's not an option right now.

For reference, this is the line of code that determines that from Bukkit's side of things - presumably similar outside of Bukkit
https://github.com/EcoCityCraft/Spigot/blob/41c83dc7a90942506aaf1c871c162fb48ed64548/src/main/java/net/minecraft/server/MinecraftServer.java#L482

**Comment by LunNova** [comment]
I'll make it configurable in TT.
