### ISSUE TITLE
Players cant drop items

### ISSUE THREAD

**Issue by clienthax** [MinimallyCorrect/TickThreading#192]
Players cant drop items anymore, if droped as admin item just disapears
if a oplayer drops it it kicks them for hacking as theyve droped too fast

**Comment by LunNova** [comment]
Fixed being kicked, items still won't drop if there's only a single item in the stack, not sure why. I don't have time to fix it now, it's almost 2AM.

**Comment by clienthax** [comment]
Thanks, get to bed :P

**Comment by LunNova** [comment]
So I don't forget by tomorrow: the issue isn't that items aren't being dropped, it's that they're being picked up immediately.
