### ISSUE TITLE
patchme.sh run

### ISSUE THREAD

**Issue by ghost** [MinimallyCorrect/TickThreading#198]
Last login: Mon Mar 11 21:09:58 on ttys001
Csorba-Mac-mini:~ csorbabalazs$ cd /Users/csorbabalazs/Desktop/Ultimate_Server 
Csorba-Mac-mini:Ultimate_Server csorbabalazs$ sh PATCHME.sh
03-11 21:19:10 [INFO] [TickThreading] Running TickThreading v1.0.0.1109 for MC1.4.7
03-11 21:19:10 [SEVERE] [TickThreading] Can't patch - no backup for BukkitForge-1.4.7-255.jar exists, and a patched copy is already in the mods directory.
You will need to replace this file with a new unpatched copy.
03-11 21:19:10 [SEVERE] [TickThreading] An error occurred while patching, can't continue
java.lang.Error: Missing backup for patched file
    at me.nallar.tickthreading.patcher.ClassRegistry.restoreBackups(ClassRegistry.java:221)
    at me.nallar.tickthreading.patcher.PatchManager.loadBackups(PatchManager.java:74)
    at me.nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:98)
    at me.nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:32)
03-11 21:19:10 [INFO] [TickThreading] Done. Press enter to exit.

**Comment by LunNova** [comment]
> `03-11 21:19:10 [SEVERE] [TickThreading] Can't patch - no backup for BukkitForge-1.4.7-255.jar exists, and a patched copy is already in the mods directory.
> You will need to replace this file with a new unpatched copy.`

Did you do what it told you to do?

**Comment by ghost** [comment]
i use 1019 update but when I run patchme.sh  this message

**Comment by LunNova** [comment]
Erm, read the message I quoted. :p

You need to download bukkitforge again. You probably deleted/moved the TickThreadingBackups folder. Don't do that.

**Comment by ghost** [comment]
sorry :) it's work :)
