### ISSUE TITLE
Server deadlock , chunk related ( codechicken again ? )

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#200]
http://pastebin.com/v04cJmye

**Comment by clienthax** [comment]
can you see if it happens with the chicken patch here?
https://github.com/MazeXD/PatchEngine/wiki/Patches

their gc is stupid anyway, causes void areas on the map

**Comment by HaoSs07** [comment]
will try it now. thx. 
strange patch, but managed to install it and add patches

also last night server crashed with minimal error:

03-12 02:41:23 [INFO] [Minecraft] mooose lost connection: disconnected: Connection reset
03-12 02:41:23 [INFO] [STDOUT] Unloading Player: mooose
03-12 02:41:41 [SEVERE] [ForgeModLoader] A mod failed to handle a ChunkDataEvent.Load event
03-12 02:45:16 [SEVERE] [ForgeModLoader] A mod failed to handle a ChunkDataEvent.Load event
03-12 02:46:01 [SEVERE] [ForgeModLoader] A mod failed to handle a ChunkDataEvent.Load event
03-12 02:46:04 [SEVERE] [ForgeModLoader] A mod failed to handle a ChunkDataEvent.Load event
03-12 02:49:32 [SEVERE] [ForgeModLoader] A mod failed to handle a ChunkDataEvent.Load event
03-12 02:52:06 [SEVERE] [ForgeModLoader] A mod failed to handle a ChunkDataEvent.Load event
03-12 02:52:18 [SEVERE] [ForgeModLoader] A mod failed to handle a ChunkDataEvent.Load event

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Deadlock Detector"

**Comment by HaoSs07** [comment]
and... not working

http://pastebin.com/buk1YjWM (forge log )

http://pastebin.com/Kn7nS1pN

**Comment by LunNova** [comment]
This is an issue with a chickenbones mod, as you suggested. I'll look into it.

edit: Actually, it's in xycraft, which for some reason has a copy of codechickencore under a different package in it. :s

**Comment by xfloh22** [comment]
just a question, but doesnt xycraft cause lag when the crystals get generated? and does tt fix this?

**Comment by HaoSs07** [comment]
i reverted to a stable build i was using before.1082. no deadlock here.

LE//i have no lag from crystals. but i also filled the world using FE world border before releasing the server

**Comment by LunNova** [comment]
Should be fixed with 56c761ad3db4d2a228f2ab8c4684.

xycraft crystals only cause client/"FPS" lag, so TT won't make any difference.
