### ISSUE TITLE
#1110 Deadlock on launch (NOT USING MCPC+)

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#201]
Logs too long for github still, here's a pastebin link once again. Mods being used: FTB Direwolf20, ForgeEssentials, Chunkprotection, BackMeUp http://pastebin.com/wB4RCYin

Not sure if it's a recent change, but no builds since 1082 have worked for me. They all crash instantly as soon as the first person joins, or after about 1-2 minutes with nobody on.

**Comment by LunNova** [comment]
I did push a fix yesterday in 95821b568315daaa31c, but for some reason the build service never built it :s.

Should be fixed in 1111.
