### ISSUE TITLE
TT #1120 thermal expansion error

### ISSUE THREAD

**Issue by xfloh22** [MinimallyCorrect/TickThreading#207]
this error shows when people enter certain areas and they crash.

http://pastebin.com/hJTG6GAP

**Comment by LunNova** [comment]
I believe that means you have a corrupt chunk somewhere :(

Unfortunately, Forge doesn't log the location when that happens. I'll try to add that.

edit: Nevermind, I already added that! :) If this continues to be a problem with latest TT, use worldedit on MCPC+ or MCEdit dev/beta version if on vanilla, and remove that block.
