### ISSUE TITLE
IC2 wires stop working randomly (Build 290)

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#21]
I wake up to my log file being over 1gb!

Wires randomly stopped working sometime during the night and all that is spammed in console to infinity is the following

2013-01-09 19:21:28 [WARNING] [IC2] EnergyNet.emitEnergyFrom: ic2.core.block.wir
ing.TileEntityElectricMFSU@bc095ba is not added to the enet
2013-01-09 19:21:28 [WARNING] [IC2] EnergyNet.emitEnergyFrom: ic2.core.block.wir
ing.TileEntityElectricMFSU@488ab94 is not added to the enet
2013-01-09 19:21:28 [WARNING] [IC2] EnergyNet.emitEnergyFrom: ic2.core.block.gen
erator.tileentity.TileEntityGenerator@853a263 is not added to the enet
2013-01-09 19:21:28 [WARNING] [IC2] EnergyNet.emitEnergyFrom: ic2.core.block.gen
erator.tileentity.TileEntitySolarGenerator@3c002280 is not added to the enet
2013-01-09 19:21:28 [WARNING] [IC2] EnergyNet.emitEnergyFrom: ic2.core.block.gen
erator.tileentity.TileEntityGeoGenerator@77a2c850 is not added to the enet
2013-01-09 19:21:28 [WARNING] [IC2] EnergyNet.emitEnergyFrom: ic2.core.block.wir
ing.TileEntityTransformerLV@352e7709 is not added to the enet
2013-01-09 19:21:28 [WARNING] [IC2] EnergyNet.emitEnergyFrom: ic2.core.block.wir
ing.TileEntityTransformerLV@352e7709 is not added to the enet
2013-01-09 19:21:28 [WARNING] [IC2] EnergyNet.emitEnergyFrom: ic2.core.block.wir
ing.TileEntityTransformerLV@352e7709 is not added to the enet
2013-01-09 19:21:28 [WARNING] [IC2] EnergyNet.emitEnergyFrom: ic2.core.block.wir
ing.TileEntityTransformerLV@352e7709 is not added to the enet
2013-01-09 19:21:28 [WARNING] [IC2] EnergyNet.emitEnergyFrom: ic2.core.block.gen
erator.tileentity.TileEntityGeoGenerator@250719ab is not added to the enet
2013-01-09 19:21:28 [WARNING] [IC2] EnergyNet.emitEnergyFrom: ic2.core.block.wir
ing.TileEntityElectricMFSU@324f7315 is not added to the enet

and probably even more - it's possible there was a TT error thrown, but I couldn't find it anywhere.

Edit: Here is the only thing I found in the TT log - not sure if related
01-09 14:57:12 [SEVERE] [TickThreading] Inconsistent state, a tile entity is in the wrong TickRegion
 entity: class anr at x,y,z:438,41,321
 Has hashcode: 1310747
 Region: rX: 27, rZ: 27, hashCode: 1769499

**Comment by LunNova** [comment]
Ouch, will need to add a log size limit. Any exceptions in
tickthreading.log?

**Comment by Puremin0rez** [comment]
@nallar 

This is the only thing I found in the TT.log file

01-09 14:57:12 [SEVERE] [TickThreading] Inconsistent state, a tile entity is in the wrong TickRegion
entity: class anr at x,y,z:438,41,321
Has hashcode: 1310747
Region: rX: 27, rZ: 27, hashCode: 1769499

No idea if its relevant, but there is nothing else besides that - and I can't open up the log file to check because it's too big lol

**Comment by LunNova** [comment]
Disregard that last question, failed at reading.

**Comment by Puremin0rez** [comment]
It's possible this is related to this:
http://forum.feed-the-beast.com/threads/mindcrack-modpack-v7-warning-ic2-api-error-ic2-core-block-machine.7081/

but some of the users are reporting power works fine etc - which in my case, it's not. It'll just happen and kill all ic2 power on the server from ticking.

**Comment by Puremin0rez** [comment]
Still unsure if this issue is related to TT - I think TT might just be amplying the effect of the bug - so hopefully the new ic2 fixes it.

**Comment by Puremin0rez** [comment]
I am now testing my modified IC2 (current ftb ic2 with new energynet classes thrown in) + TT

Time to see the results over a course of time..

**Comment by Puremin0rez** [comment]
Well then! That most definitely did not help.

8GB Log file and exact same problem as before :(

I'm thinking this is a TT problem now, I haven't seen anyone else talk about this specific issue im receiving.

**Comment by Puremin0rez** [comment]
@nallar 
Here's more of that spam crap i've been seeing:
http://pastebin.com/wXutdttU

This wouldn't be that bad of an issue if it didn't spam the log file - could you possibly patch that debug out of ic2? (not sure if possible)

**Comment by LunNova** [comment]
Which build is this occurring in? Can't reproduce power not working.

I'll look into reducing logging.

**Comment by Puremin0rez** [comment]
@nallar 

It's build 290

I've tried stock IC2, IC2 modified with new enegerynet classes and nothing works.

It's extremely hard to replicate because it happens when it feels like it, the server was up for 17 hours but didn't happen until the last 2 hours of that. In this case however, wires did NOT stop working - however, the spam was being written at least every half a second and dropped the performance of both of my servers.

It's hard to say if its TT or not, but I haven't heard anyone mention anything like this on FTB so I'm not sure why I'm the only one getting it.

If only the spamming of debug text (from IC2) was fixed - i would be happy enough. The fact that I almost ran out of harddrive space today makes me even more unwary then a little power failure bug.

**Comment by LunNova** [comment]
I'll take a closer look at the ENet code.

**Comment by Puremin0rez** [comment]
It just happened again in the first hour - Gonna try rolling without TT

**Comment by LunNova** [comment]
It's definitely a TT issue, just I can't reproduce it :(

**Comment by Puremin0rez** [comment]
@nallar 

This may be related to the region based ticking of TT

I had 2 users today tell me there power stopped working in there house at this time, yet the power in other places around the map was functioning at this time. Eventually, they all slowly started to "die".

You've simulated real life power outages via TT - congratulations!!! hahaha

As said, if the debug spam from IC2 could be disabled - it would make this issue must more livable. Running out of Disk Space from a log is definitely NOT COOL.

**Comment by Puremin0rez** [comment]
@nallar 

I'm now rolling with Build 377 so we'll see if this issue still happens on it...

I still would like to see the ic2 debug messages nerfered, however.

**Comment by LunNova** [comment]
It might finally be fixed as of build 414.

**Comment by Puremin0rez** [comment]
Appears to be solved :)
