### ISSUE TITLE
Interrupt during async packet handling causes error in blocking MySQL calls

### ISSUE THREAD

**Issue by wolfe02** [MinimallyCorrect/TickThreading#213]
http://forum.feed-the-beast.com/threads/tickthreading-concurrent-entity-tile-entity-ticks-and-other-optimisations.6498/page-21

We moved to the latest version of Tick threading, using Forge Essentials and Precious Stones. This has started happening with block breaking.

**Comment by LunNova** [comment]
Replied in the forums with a temporary fix, will fix this properly soon.
