### ISSUE TITLE
#1147 Odd behavior when no players on server/Odd memory usage

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#220]
With #1147, when no players are online, it takes about 5-10 minutes to unload dimensions. In addition, the ticks on the overworld skyrockets to around 150ms-200ms, cpu usage keeps going up all the way to 100% (older TT builds allowed CPU usage to drop to almost nothing if the server was empty), and memory climbs to fill 8gb/8gb.

The moment a player joins, though, it goes back to normal, very fast world unloads, memory usage drops to a reasonable amount (usually 1gb-2gb for 5 players), and CPU usage drops to normal levels. (It works awesomely).

Edit: I've noticed after having my server up for an extended period of time with after everyone else leaves and if just 1 person on, memory usage seems to stay at the higher load levels (~3gb-4gb) and not drop back down to the lower levels normal to only 1 person on the server.

**Comment by aquagene** [comment]
Yep, this bug seems to be completely fixed in #1153. Been running my server for about 5 hours now, not a single issue related to memory usage nor any problems when the server is empty. Awesome build so far.

**Comment by aquagene** [comment]
I've reopened this as it seems I was wrong. While the server gui does not display the memory going up, the actual java process eventually does use all 8 gigs I have allocated to it, and then stays at 8 gigs. Server does not crash, though, and keeps running smoothly, so I'm not 100% sure if this is a bug or not.

**Comment by LunNova** [comment]
Don't set -Xmx so high unless you actually expect to use the memory - the JVM may not be using all of the memory, but it will still hold onto it.

Also, make sure you're looking at the memory usage correctly - if on Linux, you want to look at RES + SHM. VIRT usage isn't really relevant.
