### ISSUE TITLE
Null for /profile e and /ticks

### ISSUE THREAD

**Issue by tubaboy26** [MinimallyCorrect/TickThreading#228]
Whenever we use the /profile e or a or the /ticks commands, it returns empty. This is since an update to the latest version.
![/profile](https://puu.sh/2mGXh)
![/ticks](https://puu.sh/2mH4A)
Also worth mentioning is that the overall TPS is very low while the individual TPS of each world remains a perfect 20. It is also using up a lot more memory with tick threading to run slower (???).

**Comment by LunNova** [comment]
Full console log? Looks like TT failed to initialise, or another mod replaced its replacements of the entity lists.

**Comment by LunNova** [comment]
I've also added more debugging in latest, so if you can get the full report from it that would be more helpful.
