### ISSUE TITLE
help

### ISSUE THREAD

**Issue by wolfe02** [MinimallyCorrect/TickThreading#234]
http://pastebin.com/eRm0TrMN ok this is a what i am geting when i put a block down and that i get kick from the server we are useing 1187 of TT.

**Comment by LunNova** [comment]
This is due to a bukkitforge bug, see [here](http://forum.feed-the-beast.com/threads/tickthreading-concurrent-entity-tile-entity-ticks-and-other-optimisations.6498/page-22#post-189851) for a workaround.
