### ISSUE TITLE
nether & Twilight world loading problem

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#236]
Hey there the server i run has mcpc+ and i running ftb ultimate , ive installed the tickthreading on the server and everythin seems to work great but then i realised my other worlds arent loaded when i uesed /gc any ideas how i can solve this issue

Thanks

**Comment by alicheek** [comment]
found a work around , seems when world unloading is enabled thee worlds are functioning for a bit then close down. when trying to enter into a portal though it wont re-initiate so i just set it to false and now it seems to be working perfectly.

**Comment by LunNova** [comment]
MCPC+ doesn't properly support world unloading yet, just use the workaround you've already discovered.

**Comment by LunNova** [comment]
https://github.com/MinecraftPortCentral/MCPC-Plus/pull/742
