### ISSUE TITLE
#1206 Not saving chunk

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#240]
3-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 19,5, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 20,5, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 25,5, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 26,4, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 113,21, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 14,5, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 25,4, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 14,4, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 24,3, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 120,26, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 124,26, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 115,27, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 127,24, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 127,23, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 128,17, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 26,3, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 13,3, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 16,2, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 26,2, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 25,2, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 128,15, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 128,18, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 128,19, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 129,15, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 13,4, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 129,14, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 129,16, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 129,17, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 129,18, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 129,20, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 129,21, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 129,23, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 129,24, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 129,25, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 129,19, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 130,19, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 130,16, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 130,15, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 243,259, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 129,26, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 130,17, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 130,18, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 130,20, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 130,21, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 130,22, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 130,24, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 130,26, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 130,25, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 131,19, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 131,15, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 131,16, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 131,17, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 131,20, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 131,21, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 131,22, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 131,25, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 131,26, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 131,18, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 121,27, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 129,27, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 130,27, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 131,27, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 124,28, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 120,28, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 129,28, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 130,28, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 131,28, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 13,2, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 15,2, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 12,2, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 19,1, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 118,27, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 18,1, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 126,11, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 127,11, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 122,11, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 127,10, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 126,10, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 122,10, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 122,9, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 126,9, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 121,8, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 124,8, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 118,8, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 122,8, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 125,8, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 121,7, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 11,1, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 112,11, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 12,1, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 12,0, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 11,0, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 12,-3, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 12,-2, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 12,-1, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 13,-3, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 13,-2, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 14,-2, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 20,-1, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 24,-1, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 26,1, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 27,2, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 28,1, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 28,2, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at -1,6, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 0,6, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 3,-3, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 3,-1, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 3,0, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 3,1, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 3,5, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 4,-5, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 4,1, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 4,6, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 5,-2, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 5,-1, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 5,1, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 5,3, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 6,-2, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 6,-1, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 7,-1, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 8,-5, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 8,-3, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 29,2, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 29,3, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 16,-4, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 8,7, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 175,-8, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 176,-14, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 176,-8, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 177,-14, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 180,-13, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 179,-15, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 179,-13, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 179,-7, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 180,-14, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 180,-10, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 183,-19, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 185,-18, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 183,-14, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 185,-9, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 186,-15, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 186,-14, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 186,-7, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 175,-6, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 10,0, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 37,-223, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 31,-227, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 31,-228, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 31,-225, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 31,-226, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 31,-223, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 31,-222, not in correct location in chunks map.
03-26 20:13:51 [WARNING] [TickThreading] Not saving chunk at 31,-224, not in correct location in chunks map.

this is only a part of the warning. basically the entire map is not save... tips ?

**Comment by LunNova** [comment]
Already fixed in 1212.
