### ISSUE TITLE
Crash on Startup with ForgeEssentials

### ISSUE THREAD

**Issue by Stechi** [MinimallyCorrect/TickThreading#247]
Like the title say,
I wanted to use TickThreading and ForgeEssentials together,
because of the Tick-Threadin of Tick-Threading and functions like Backup, Permissions, Chat-Functions... from ForgeEssentials.

I know ForgeEssentials has its own TickHandler-Thingy,
but i tried and I failed.

But it would be coll to use both Mods.

Logs:
http://pastebin.com/E8WUkkNJ
http://pastebin.com/Mu3DAW2J
http://pastebin.com/wrYzTDmX

Greetings
 Stechi

**Comment by LunNova** [comment]
Looks like you didn't run the patcher, and just disabled patching in TT's config.

If you have ran the patcher, you either have a coremod which conflicts (possibly FE), or you installed a jar mod after patching. If using TT, jar mods should always be installed before installing TT.

**Comment by HaoSs07** [comment]
i have latest fe and latest tt and works good

**Comment by Stechi** [comment]
@nallar I did run the patcher and installed TT last.

@HaoSs07 Which versions the stable or the beta?

Thx for reply
Stechi

**Comment by HaoSs07** [comment]
beta

**Comment by Stechi** [comment]
Ok just for confirmation. I installed the server complete without TT and started. 
All is working fine.

---

I stop the server add TT to the mod-folder
and start the server, he starts up, say something about TT not knowing if he should patch,
and crash.
http://pastebin.com/LrCjXGcR
http://pastebin.com/k9gXrDv2
http://pastebin.com/CJwz9ykC

---

I make the PATCHME.sh runable and run it,
it sucessfully patches some mods, the CodeChickenCore.jar and the minecraft_server.jar
I have now the TT_backup-folder and the patchedMods-folder

---

I run the server and it crashes with the errors in the logs from my initialpost

# 

Version Infos:
ForgeEssentials-core-1.4.7-1.2.0.254
TickThreading-1.4.7-1.0.0.1216

#

**Comment by LunNova** [comment]
If you're using both a forge jar and server jar, instead of a single jar,
that might cause this. Not sure, hard to read logs on a phone. If there is
some other bug you've found, won't be able to fix it til I'm back from
being on holiday in two weeks.

**Comment by Stechi** [comment]
Ahh yeah that was it.
You should change this at your install-instructions.
But i have a new error, but has nothing to do with ForgeEssentials.
I make a new issue.^^

Thx
Stechi
