### ISSUE TITLE
MCPC-Plus With ticktreading breaks the_end

### ISSUE THREAD

**Issue by Siedge** [MinimallyCorrect/TickThreading#248]
I use tickthreading with MCPC-Plus and whenever i install tickthreading it breaks the end if u try to tp to it u get Null and if u try to use portal portal doesn't work and i know its tick threading because if i install tick threading it works fine.

**Comment by LunNova** [comment]
Turn off world unloading.

**Comment by Siedge** [comment]
still get the same issue

**Comment by Geijoh** [comment]
This appears to fix the issue for me

**Comment by Siedge** [comment]
well actually sorry error isn't null its Error: Hole in Floor
