### ISSUE TITLE
Bedrock Bug

### ISSUE THREAD

**Issue by ray73864** [MinimallyCorrect/TickThreading#249]
So we had a major issue on our server, i had to remove TT for now, but basically, with TT installed, if you place something on the bedrock (a simple torch will do), the bedrock below it disappears, vanishes without a trace, no amount of restarting the server, etc... will bring that bedrock back.

Removed TT and the bug disappeared completely.

This is in the FTB Ultimate pack.

![2013-03-28_05 47 58](https://f.cloud.github.com/assets/1343103/312033/d0f9102a-976b-11e2-846e-ccec12a166b1.png)

**Comment by HaoSs07** [comment]
can confirm it, for me this only happens with the new flatbedrock mod

**Comment by ray73864** [comment]
Yeah, as said, the bug only popped up when i had TT installed, so it is likely an incompat between TT and FlatBedrock mod.

**Comment by xfloh22** [comment]
running ultimate pack as well an no problems of this sort...

**Comment by dadealus** [comment]
happens to me as well. seems to be any interaction with the bedrock
