### ISSUE TITLE
Bug on Server-Startup with Factorization Dimensional Slices

### ISSUE THREAD

**Issue by Stechi** [MinimallyCorrect/TickThreading#250]
# 

Version info:
TickThreading-1.4.7-1.0.0.1226, TickThreading-1.4.7-1.0.0.1216
Factorization-0.7.21
# 

I have done everything on the install-instructions.
but after I running the PATCHME.sh and starting the Server again  I get:

http://pastebin.com/463mD3yg
http://pastebin.com/WamHXEuR
http://pastebin.com/f3eKdqcg

---

After I change the Factorization-config:

dimensionslices {
    # work in progress; may be unstable
    B:enableDimensionSlices=false
}

to:

dimensionslices {
    # work in progress; may be unstable
    B:enableDimensionSlices=true
}

I get this:

http://pastebin.com/QrP3PCGi
http://pastebin.com/ZSGy1knJ
http://pastebin.com/vL5Jrc0W

I tried it with the version I had (1216) and then with the newest (1226),
but both give the same error and then i tested the stable,
but it also throws an error,
but I will make an extra issue,
because it seem not related to foactorization.

Greetings
Stechi

**Comment by Lathanael** [comment]
I can confirm this error:
https://gist.github.com/Lathanael/89bff3210bd5d0e1d92c
Used TickThreading-1.4.7-1.0.0.1234  and Factorization-0.7.21

Note:
I tried it with enabled and disabled slices. Crashes with both settings.
