### ISSUE TITLE
Server Startup - Exception getting block [stable build]

### ISSUE THREAD

**Issue by Stechi** [MinimallyCorrect/TickThreading#251]
Again me.^^

As usual i have done everything in the install-instructions.

After run the server for the first time with TT
I get this if I try to join:

http://pastebin.com/8ta5RWt7
http://pastebin.com/3KsSupwH
http://pastebin.com/eCqdcYn5

---

and after I run the PATCHME.sh I get:

http://pastebin.com/UBee4imm
http://pastebin.com/0ypCiFqq
http://pastebin.com/vDFJLqZz

Thx for your time
Stechi

**Comment by HaoSs07** [comment]
i sugest you get the latest beta

**Comment by Stechi** [comment]
If your looking for the other issues I posted, then you would see, the latest beta just throws another error.^^

Greetings
Stechi

**Comment by HaoSs07** [comment]
from what i can tell you have a missing world 
Cannot Hotload Dim: Could not get provider type for dimension 2, does not exist

do a fresh modpack install

**Comment by Stechi** [comment]
yeah it works,
but has some bugs with ticking if you overload it.^^
--> new issue

Thx
Stechi
