### ISSUE TITLE
TwoWayReentrantReadWriteLock

### ISSUE THREAD

**Issue by Jakja2** [MinimallyCorrect/TickThreading#252]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 3/29/13 3:32 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: me/nallar/tickthreading/util/concurrent/TwoWayReentrantReadWriteLock
    at ou.<init>(SourceFile:27)
    at yc.<init>(World.java:321)
    at in.<init>(WorldServer.java:103)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:266)
    at ho.c(DedicatedServer.java:180)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
    at fy.run(SourceFile:849)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.4.7
    Operating System: Windows 8 (x86) version 6.2
    Java Version: 1.7.0_15, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 36729544 bytes (35 MB) / 94208000 bytes (89 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 1 total; -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.26a FML v4.7.35.556 Minecraft Forge 6.6.2.534 72 mods loaded, 72 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    PowerCrystalsCore [PowerCrystals Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    mod_bspkrsCore [bspkrsCore]([1.4.7]bspkrsCorev1.01.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    TreeCapitator [TreeCapitator]([1.4.6]TreeCapitator.Forge.1.4.6.r07.Uni.CoreMod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Core [BuildCraft](buildcraft-A-3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Factory [BC Factory](buildcraft-A-3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Transport [BC Transport](buildcraft-A-3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Silicon [BC Silicon](buildcraft-A-3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    APUnofficial [Additional Pipes](AdditionalPipes2.1.3u42-BC3.4.2-MC1.4.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CoFHCore [CoFH Core](CoFHCore-1.4.7.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ComputerCraft [ComputerCraft](ComputerCraft1.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CCTurtle [ComputerCraft Turtles](ComputerCraft1.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion [Thermal Expansion](ThermalExpansion-2.2.2.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    OmniTools [OmniTools](OmniTools-3.0.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    IC2 [IndustrialCraft 2](industrialcraft-2_1.115.231-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ImmibisCore [Immibis Core](immibis-core-52.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AdvancedRepulsionSystems [Advanced Repulsion Systems](adv-repulsion-systems-52.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AdvancedMachines [IC2 Advanced Machines Addon](AdvancedMachines_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AdvancedPowerManagement [Advanced Power Management](AdvancedPowerManagement-1.1.55-IC2_1.112.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AppliedEnergistics [Applied Energistics](appeng-rv9-f.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Builders [BC Builders](buildcraft-A-3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Energy [BC Energy](buildcraft-A-3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ChickenChunks [ChickenChunks](ChickenChunks 1.3.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CompactSolars [Compact Solar Arrays](compactsolars-universal-1.4.7-4.0.3.29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    DimensionalAnchors [Dimensional Anchors](dimensional-anchor-52.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    DimensionalDoors [Dimensional Doors](DimensionalDoors-1.4.6R1.2.1RC1-12.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    EE3 [Equivalent Exchange 3](ee3-universal-pre1f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    EnderStorage [EnderStorage](EnderStorage 1.4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    factorization [Factorization](Factorization-0.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FlatBedrock [FlatBedrock](FlatBedrock_1.0.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    IC2NuclearControl [Nuclear Control](IC2NuclearControl-1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    IronChest [Iron Chest](ironchest-universal-1.4.7-5.1.0.260.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion|Factory [Factory](ThermalExpansion-2.2.2.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion|Energy [Energy](ThermalExpansion-2.2.2.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion|Transport [Transport](ThermalExpansion-2.2.2.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    LogisticsPipes|Main [Logistics Pipes](LogisticsPipes-MC1.4.7-0.7.0.90.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MFReloaded [Minefactory Reloaded](MineFactoryReloaded-2.3.2-287.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MFReloaded|CompatExtraBiomes [MFR Compat: ExtraBiomes](MineFactoryReloaded-2.3.2-287.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MFReloaded|CompatForestry [MFR Compat: Forestry](MineFactoryReloaded-2.3.2-287.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MFReloaded|CompatIC2 [MFR Compat: IC2](MineFactoryReloaded-2.3.2-287.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MFReloaded|CompatPams [MFR Compat: Pam's Mods](MineFactoryReloaded-2.3.2-287.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerCore [RedPower](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerBase [RP Base](RedPowerCore-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerWorld [RP World](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MFReloaded|CompatRP2 [MFR Compat: RP2](MineFactoryReloaded-2.3.2-287.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MFReloaded|CompatSoulShards [MFR Compat: Soul Shards](MineFactoryReloaded-2.3.2-287.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MFReloaded|CompatSufficientBiomes [MFR Compat: Sufficient Biomes](MineFactoryReloaded-2.3.2-287.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MFReloaded|CompatThaumcraft [MFR Compat: Thaumcraft](MineFactoryReloaded-2.3.2-287.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MFReloaded|CompatTwilightForest [MFR Compat: TwilightForest](MineFactoryReloaded-2.3.2-287.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MFReloaded|CompatVanilla [MFR Compat: Vanilla](MineFactoryReloaded-2.3.2-287.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MFReloaded|CompatXyCraft [MFR Compat: XyCraft](MineFactoryReloaded-2.3.2-287.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    mmmPowersuits [MachineMuse's Modular Powersuits](ModularPowersuits-0.3.2-199.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Mystcraft [Mystcraft](mystcraft-uni-1.4.7-0.10.1.00.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    NetherOres [Nether Ores](NetherOres-2.0.6-32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    OCS [OpenCCSensors](OpenCCSensors-0.1.4b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    PowerConverters [Power Converters](PowerConverters-2.2.2-29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerMachine [RP Machine](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerCompat [RP Compat](RedPowerCompat-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerWiring [RP Wiring](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerLogic [RP Logic](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerLighting [RP Lighting](RedPowerDigital-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerControl [RP Control](RedPowerMechanical-2.0pr6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    StevesCarts [Steve's Carts](StevesCarts2.0.0.a61.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Tubestuff [Tubestuff](tubestuff-52.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    weaponmod [Balkon's WeaponMod](Weaponmod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    WR-CBE|Core [WR-CBE Core](WR-CBE Core 1.3.2.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    WR-CBE|Addons [WR-CBE Addons](WR-CBE Addons 1.3.2.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    WR-CBE|RedPower [WR-CBE RedPower](WR-CBE RedPower 1.3.2.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Profiler Position: N/A (disabled)
    Player Count: 0 / 20; []
    Is Modded: Definitely; Server brand changed to 'forge,fml'
    Type: Dedicated Server (map_server.txt)

**Comment by Jakja2** [comment]
.

**Comment by LunNova** [comment]
Patching failed for some reason. For now, keeping minecraft forge as a separate jar might not work, try not doing that if you are.
