### ISSUE TITLE
Modded leaves decay even if attached to logs.

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#253]
I'm running MCPC+ 1.4.7 (Legacy build 7) and TickThreading build 1226. I looked around and it seems to be the same issue as #66 - Modded leaves, specifically autumn forests from ExtraBiomesXL, will decay even if attached to a naturally generated tree. Vanilla leaves work normally.

Any other info you need can be provided, but there aren't any errors that log to the console.

**Comment by aquagene** [comment]
Got this as well with the newest builds past #1220.

**Comment by dadealus** [comment]
I believe this is happening for us as well. 99% sure 1% could be a player with a non log-able item.

**Comment by joey19982** [comment]
This appears to be fixed as of the latest build, but my server has only been up for a few minutes. I'll close it after a little while if it doesn't happen again.
