### ISSUE TITLE
Player kicked when placing blocks in specific chunk.

### ISSUE THREAD

**Issue by AlexRichman** [MinimallyCorrect/TickThreading#255]
I have created an issue on the BukkitForge page detailing the problem, you can see it here:
https://github.com/keepcalm/BukkitForge/issues/599

As I mentioned in the post, I'm not sure whether the issue is with BukkitForge or TickThreading, so I've posted it here too.

Thanks for your help,
- Alex

**Comment by LunNova** [comment]
It's a bukkitforge bug, I have already created a bukkitforge issue for it.
As a workaround, enable generateChunkOnProvideRequest.

**Comment by AlexRichman** [comment]
Ah, thanks very much for your help.
- Alex
