### ISSUE TITLE
Does ChunkCache work with MCPC+?

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#256]
Well, it sure has been awhile since I've played with FTB! Nice to see you again Nallar xD

Managed to get TickThreading and MCPC+ working almost flawlessly together (had to change some TT configs) and I was wondering if the chunk cache feature worked with MCPC+?

**Comment by LunNova** [comment]
Not yet. I'll add that to the ever-growing list of things to fix when I'm
back from being on holiday. :P

**Comment by Puremin0rez** [comment]
@nallar 

Okay :) Thanks for getting TT working so well with MCPC+!

When I last tinkered with FTB a few months ago it didn't work at all xD

**Comment by Puremin0rez** [comment]
@nallar 

Figured i'd ask - are all the core components working with TT + MCPC?

Such as the different threads, etc. I'd think some things would conflict like the GC in TT and MCPC etc but I guess not!

**Comment by Puremin0rez** [comment]
and likewise, does the benefits of MCPC also stick around with TT? (Multithreaded chunk loading inherited from bukkit, etc)

I also reckon TTs /tps command is more reliable since it potentially patches over tick loop?

So many questions! So out of the loop xD

**Comment by Loonacy** [comment]
The issue tracker probably isn't the place to be asking these questions.  I think you'd be better off on the forum:
http://forum.feed-the-beast.com/threads/tickthreading-concurrent-entity-tile-entity-ticks-and-other-optimisations.6498/
