### ISSUE TITLE
Industrial Information Pannels(All recent TT Versions)

### ISSUE THREAD

**Issue by xfloh22** [MinimallyCorrect/TickThreading#259]
it seems like industrial information pannels dont connect or even work alone with TT installed. I have tryed it with the last 50 Versions but no luck. no error reports in the console

**Comment by HaoSs07** [comment]
yes,  can confirm there is a problem with pannels

**Comment by xfloh22** [comment]
might this be related to #337?

**Comment by HaoSs07** [comment]
mine vas related to block updates, if i force the update placing/braking a block next to the info panel it worked, but did not test this on latest builds

**Comment by LunNova** [comment]
Is this still broken in latest?

**Comment by HaoSs07** [comment]
will ask my admins to test
