### ISSUE TITLE
persistent deadlock

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#260]
http://pastebin.com/Lt9hqcgd

had to shut down the server, deadlock won`t stop

**Comment by xfloh22** [comment]
actually, i had this without TT and when i added TT that bug didnt show anymore. so strange. it seems like forge chicken chunks does some wierd things with the tick manager, that might be it as well.

**Comment by HaoSs07** [comment]
thx for the tip. i can test that in 1 second

**Comment by LunNova** [comment]
It looks like a BC filler is getting in to a loop.

**Comment by HaoSs07** [comment]
Yah;is not from CC
hmm... how to find the filler ? any tips ?

also nallar. any tips for debugging; i hate to came here every deadlock; but it seems i can understand it, where exactly does it tell you the problem ?

**Comment by HaoSs07** [comment]
@nallar did a rollback and banned filler, but deadlock still happens from time to time

**Comment by HaoSs07** [comment]
http://pastebin.com/G27yRZHN

still happening ...

**Comment by LunNova** [comment]
That's a different deadlock, involving a combination of two mods doing silly things. :/
