### ISSUE TITLE
Redpower BlockBreaker log spam.

### ISSUE THREAD

**Issue by AlexRichman** [MinimallyCorrect/TickThreading#261]
Getting a ton of these messages: https://gist.github.com/AlexRichman/5294779 spammed whenever a block breaker does it's thing.

Doesn't seem to impact server performance, but it sure is annoying.

**Comment by LunNova** [comment]
That's a BukkitForge bug and would crash the server if TT was not
installed. Unless it definitely only occurs with TT, report it to BF and
close this.

**Comment by AlexRichman** [comment]
Heh, I'm noticing a recurring theme here. Perhaps I'll try to remove BukkitForge and replace it with mods that weren't written by a penguin via the process of slapping it's fins repeatedly on the keyboard.

Thanks,
- Alex
