### ISSUE TITLE
Crash on startup - TickThreading-1.4.7-1.0.0.942

### ISSUE THREAD

**Issue by Nithlus** [MinimallyCorrect/TickThreading#262]
Server crashes on startup after adding TickThreading-1.4.7-1.0.0.942 & running the Patchme

http://pastebin.com/dqRMDby4

Don't think i did anything wrong so would like someone to take a look if they can

**Comment by LunNova** [comment]
The 'stable-ish' build is not MCPC+ compatible. Try latest.
