### ISSUE TITLE
bugged world save ? Disappearing items 

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#263]
With the latest TT builds, player have reported disappearing items from chests,
Example: put 2 stacks of ender pearls in chest, come back 10 minutes later and the pearls are gone

this does not happen if TT is not installed, Did a 2 days test, nothing missing, Put TT again, first report after 2 hours

I have a timed 10 minutes autosave using command block

**Comment by LunNova** [comment]
Fixed, see #264.

**Comment by HaoSs07** [comment]
fore some reason players still report losing items in chest after a fast chunk reload, using fe home teleport from a chunk to another
