### ISSUE TITLE
Build #1226 - Chunk-GC possibly eating Chunk Loader chunks?

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#265]
I do not have hard evidence to prove this, but I think Chunk-GC might be eating Chunk Loader chunks (World Anchor in particular)

Every 600 ticks I see quite a surge of CPU and IO from my performance monitor - I spent a good hour trying to debug what could be causing this when I realized it could definitely be Chunk-GC doing this. These spikes happened even when no players were online, providing even further of a hint to me it could be the chunk loaders.

I set the Chunk-GC to some crazy number that will make it take weeks to issue (since i don't think you can disable it in TT) and now the spikes are gone.

My (not scientific) theory is that Chunk-GC is possibly eating the chunk loader chunks and then the chunk loader instantly spawns them back, causing for a noticeable spike just to happen again a minute later.

Just thought I'd share my 2 cents - I read over the TT Chunk GC code and to me it looks like its simply checking if EntityPlayerMP is within range, keep loaded and if they are not in range, unload... but I could definitely be reading that wrong.

**Comment by LunNova** [comment]
It also doesn't unload any chunks with chunkloader tickets. Try diabling
loadChunkOnProvideRequest.

**Comment by Puremin0rez** [comment]
@nallar 

What exactly will that do?

I had to enable the generateChunkOnProvideRequest because worlds such as the nether etc would not load properly on MCPC+ with it disabled - so I'm wondering what disabling loadChunkOnProvideRequest might do.

**Comment by LunNova** [comment]
Probably your issue isn't that chunk loaded chunks are being unloaded, it's
more likely that chunks which are being loaded by bad mod/minecraft code
are being loaded again. If loadChunkOnProvideRequest is off, only load
chunk and getChunkAt(x, z, true, ...) in ChunkProviderServer will actually
load chunks, instead of for example, redpower checking for nearby
inventories on a chunk boundary.

**Comment by LunNova** [comment]
Although if it's buggy and you need generate..., then you can't turn off
load.

**Comment by Puremin0rez** [comment]
@nallar 

Hmm, okay then, i'll toy with things later. I presume chunk loaders would still function with that off?

Hope to see you back at home soon :)

**Comment by Puremin0rez** [comment]
@nallar 
Yeah disabling the loadChunkOnProvideRequest made chunk loaders appear to not work and once again worlds did not function properly under MCPC+

Looks like I'll just leave GC off for now

**Comment by LunNova** [comment]
Is this any better now, as chunk caching works?

Should probably be a separate issue for load/generateChunkOnProvideRequest being necessary for world loading.

**Comment by Puremin0rez** [comment]
@nallar Appears to be, but I still see a noticeable spike whenever Chunk GC runs (maybe unavoidable?)

I've set my chunk-gc to every 5 minutes so it's not as bad now - plus i got the caching set to 8000

I'll go make that ticket now :)

**Comment by LunNova** [comment]
Can you confirm that this isn't actually caused by #277?

**Comment by Puremin0rez** [comment]
@nallar 

Will try the new save builds and get back to you with info :)

**Comment by Puremin0rez** [comment]
Spike are almost non existent now - knocking 'em out @nallar !
