### ISSUE TITLE
Updating from 942 to 1227 fatal error server unable to start after patching

### ISSUE THREAD

**Issue by ghost** [MinimallyCorrect/TickThreading#266]
Startup Error: http://pastebin.com/dNWwcsYg
Patch log: http://pastebin.com/jXW6vBeB

**Comment by LunNova** [comment]
There have been some changes in patching that require a clean install
before trying newer builds, somewhere between 970 and 1020 iirc.

**Comment by ghost** [comment]
Okay thanks, I recommend putting that in the OP. :)
