### ISSUE TITLE
[ForgeModLoader] Failed to load chunk/ Chunks are resetting to different states

### ISSUE THREAD

**Issue by Zerys2424** [MinimallyCorrect/TickThreading#269]
12:42:55
 ForgeModLoader:
User max1112_nl connecting with mods [MFReloaded|CompatSufficientBiomes, BiblioCraft, RedPowerWiring, TwilightForest, OmniTools, BuildCraft|Transport, ChargePads, RedPowerCompat, WR-CBE|Core, MFReloaded|CompatIC2, RedPowerLogic, ObsidiPlates, ThermalExpansion|Energy, DamageIndicatorsMod, Thaumcraft, drceph.petrogen, WR-CBE|RedPower, Forestry, EnderStorage, XyCraftWorld, GraviGun, AdvancedMachines, BinnieCore, MFReloaded|CompatPams, mmmPowersuits, IronChest, MFReloaded|CompatRP2, BuildCraft|Energy, Railcraft, GregTech_Addon, ImmibisCore, EE3, MiscPeripherals, PortalGun, ModularForceFieldSystem, factorization, RedPowerLighting, AppliedEnergistics, RedPowerBase, MFReloaded|CompatExtraBiomes, MFReloaded, MFReloaded|CompatXycraft, XyCraft, ThermalExpansion, NetherOres, BuildCraft|Silicon, ThermalExpansion|Transport, GraviSuite, XyCraftMachines, IC2NuclearControl, BuildCraft|Core, ThermalExpansion|Factory, MFReloaded|CompatForestry, IC2, ExtraBees, StevesCarts, ExtrabiomesXL, Mystcraft, ComputerCraft, WR-CBE|Addons, AdvancedSolarPanel, BuildCraft|Factory, RedPowerMachine, XReliquary, SoulShards, RedPowerCore, MFReloaded|CompatThaumcraft, CCTurtle, Tubestuff, RedPowerControl, MFReloaded|CompatTwilightForest, MFReloaded|CompatSoulShards, BuildCraft|Builders, RedPowerWorld, PowerConverters]
12:42:55
 Minecraft:
max1112_nl[/62.163.32.169:51124] logged in with entity id 181 at (2578.201532806591, 33.0, -489.60683987498345)
12:42:55
 CONSOLE:
[SEVERE] [ForgeModLoader] Failed to load chunk
12:42:55
 CONSOLE:
NBT data
12:42:55
 CONSOLE:
java.util.zip.ZipException: incorrect data check
12:42:55
 STDOUT:
Loading Player: max1112_nl
12:42:55
 STDOUT:
Sending serverside check to: max1112_nl
12:42:57
 GraviGun:
[1.4.7v2] Recieved client info from max1112_nl
12:42:57
 PortalGun:
[1.4.7v5] Recieved client info from max1112_nl

**Comment by Zerys2424** [comment]
also this 

13:52:46
 Minecraft:
thew1ldc4rd[/91.85.46.250:40111] logged in with entity id 378216 at (251.5, 36.5, -484.5)
13:52:52
 Minecraft:
max1112_nl hit the ground too hard
13:53:36
 CONSOLE:
TIMED_WAITING
13:53:36
 CONSOLE:
Connection #71 read thread
13:53:36
 CONSOLE:
PID: 602 | Alive: true | State: BLOCKED | Daemon: false | Priority:5
13:53:36
 CONSOLE:
BLOCKED on java.util.LinkedList@3d4311f4 owned by "Server thread" Id=13
13:53:36
 CONSOLE:
blocked on java.util.LinkedList@3d4311f4
13:53:36
 CONSOLE:
Connection #71 write thread
13:53:36
 CONSOLE:
PID: 603 | Alive: true | State: TIMED_WAITING | Daemon: false | Priority:5
13:53:36
 CONSOLE:
TIMED_WAITING
13:53:36
 CONSOLE:
PID: 143 | Alive: true | State: TIMED_WAITING | Daemon: false | Priority:5
13:53:36
 CONSOLE:
TIMED_WAITING on org.luaj.vm2.LuaThread$State@1a05de9
13:53:37
 CONSOLE:
waiting on org.luaj.vm2.LuaThread$State@1a05de9
13:53:37
 CONSOLE:
PID: 144 | Alive: true | State: TIMED_WAITING | Daemon: false | Priority:5
13:53:37
 CONSOLE:
TIMED_WAITING on org.luaj.vm2.LuaThread$State@6e3bf6f2
13:53:37
 CONSOLE:
waiting on org.luaj.vm2.LuaThread$State@6e3bf6f2
13:53:37
 CONSOLE:
PID: 335 | Alive: true | State: TIMED_WAITING | Daemon: false | Priority:5
13:53:37
 CONSOLE:
TIMED_WAITING on org.luaj.vm2.LuaThread$State@79324bb3
13:53:37
 CONSOLE:
waiting on org.luaj.vm2.LuaThread$State@79324bb3
13:53:37
 CONSOLE:
PID: 336 | Alive: true | State: TIMED_WAITING | Daemon: false | Priority:5
13:53:37
 CONSOLE:
TIMED_WAITING on org.luaj.vm2.LuaThread$State@512f2df
13:53:37
 CONSOLE:
waiting on org.luaj.vm2.LuaThread$State@512f2df
13:53:37
 CONSOLE:
PID: 337 | Alive: true | State: TIMED_WAITING | Daemon: false | Priority:5
13:53:37
 CONSOLE:
TIMED_WAITING on org.luaj.vm2.LuaThread$State@8f2064f
13:53:37
 CONSOLE:
waiting on org.luaj.vm2.LuaThread$State@8f2064f
13:53:37
 CONSOLE:
PID: 146 | Alive: true | State: TIMED_WAITING | Daemon: false | Priority:5
13:53:37
 CONSOLE:
TIMED_WAITING on org.luaj.vm2.LuaThread$State@787d0fe9
13:53:37
 CONSOLE:
waiting on org.luaj.vm2.LuaThread$State@787d0fe9
13:53:37
 CONSOLE:
PID: 595 | Alive: true | State: TIMED_WAITING | Daemon: false | Priority:5
13:53:37
 CONSOLE:
TIMED_WAITING on org.luaj.vm2.LuaThread$State@2ff60ee8
13:53:37
 CONSOLE:
waiting on org.luaj.vm2.LuaThread$State@2ff60ee8
13:53:37
 CONSOLE:
PID: 596 | Alive: true | State: TIMED_WAITING | Daemon: false | Priority:5
13:53:37
 CONSOLE:
TIMED_WAITING on org.luaj.vm2.LuaThread$State@62439fbb
13:53:37
 CONSOLE:
waiting on org.luaj.vm2.LuaThread$State@62439fbb
13:53:37
 CONSOLE:
PID: 597 | Alive: true | State: TIMED_WAITING | Daemon: false | Priority:5
13:53:37
 CONSOLE:
TIMED_WAITING on org.luaj.vm2.LuaThread$State@1718a751
13:53:37
 CONSOLE:
waiting on org.luaj.vm2.LuaThread$State@1718a751
13:53:37
 CONSOLE:
Deadlock Detector
13:53:37
 CONSOLE:
PID: 76 | Alive: true | State: RUNNABLE | Daemon: false | Priority:5
13:53:37
 CONSOLE:
RUNNABLE
13:53:37
 CONSOLE:
PID: 15 | Alive: true | State: RUNNABLE | Daemon: false | Priority:5
13:53:37
 CONSOLE:
RUNNABLE
13:53:37
 CONSOLE:
File IO Thread
13:53:37
 CONSOLE:
PID: 145 | Alive: true | State: TIMED_WAITING | Daemon: false | Priority:1
13:53:37
 CONSOLE:
TIMED_WAITING
13:53:37
 CONSOLE:
PID: 3 | Alive: true | State: WAITING | Daemon: true | Priority:8
13:53:37
 CONSOLE:
WAITING on java.lang.ref.ReferenceQueue$Lock@70eeef91
13:53:37
 CONSOLE:
waiting on java.lang.ref.ReferenceQueue$Lock@70eeef91
13:53:37
 CONSOLE:
Immibis Core background task
13:53:37
 CONSOLE:
PID: 17 | Alive: true | State: TIMED_WAITING | Daemon: true | Priority:5
13:53:37
 CONSOLE:
TIMED_WAITING on java.util.TaskQueue@554742ec
13:53:37
 CONSOLE:
waiting on java.util.TaskQueue@554742ec
13:53:37
 CONSOLE:
Listen thread
13:53:37
 CONSOLE:
PID: 30 | Alive: true | State: BLOCKED | Daemon: false | Priority:5
13:53:37
 CONSOLE:
BLOCKED on java.util.Collections$SynchronizedRandomAccessList@29bf1af2 owned by "Server thread" Id=13
13:53:37
 CONSOLE:
blocked on java.util.Collections$SynchronizedRandomAccessList@29bf1af2
13:53:37
 CONSOLE:
PID: 128 | Alive: true | State: WAITING | Daemon: false | Priority:5
13:53:37
 CONSOLE:
WAITING on java.util.TaskQueue@44ccf3ea
13:53:37
 CONSOLE:
waiting on java.util.TaskQueue@44ccf3ea
13:53:37
 CONSOLE:
Reference Handler
13:53:37
 CONSOLE:
PID: 2 | Alive: true | State: WAITING | Daemon: true | Priority:10
13:53:37
 CONSOLE:
WAITING on java.lang.ref.Reference$Lock@42dd681d
13:53:37
 CONSOLE:
waiting on java.lang.ref.Reference$Lock@42dd681d
13:53:37
 CONSOLE:
Server thread
13:53:37
 CONSOLE:
PID: 13 | Alive: true | State: RUNNABLE | Daemon: false | Priority:5
13:53:37
 CONSOLE:
RUNNABLE
13:53:38
 CONSOLE:
World Tick - 6
13:53:38
 CONSOLE:
PID: 136 | Alive: true | State: BLOCKED | Daemon: true | Priority:5
13:53:38
 CONSOLE:
BLOCKED on java.util.concurrent.LinkedBlockingQueue@300cd7de owned by "World Tick - 1" Id=131
13:53:38
 CONSOLE:
blocked on java.util.concurrent.LinkedBlockingQueue@300cd7de
13:53:38
 CONSOLE:
World Tick - 7
13:53:38
 CONSOLE:
PID: 137 | Alive: true | State: BLOCKED | Daemon: true | Priority:5
13:53:38
 CONSOLE:
BLOCKED on java.util.concurrent.LinkedBlockingQueue@300cd7de owned by "World Tick - 1" Id=131
13:53:38
 CONSOLE:
blocked on java.util.concurrent.LinkedBlockingQueue@300cd7de
13:53:38
 CONSOLE:
World Tick - 8
13:53:38
 CONSOLE:
PID: 138 | Alive: true | State: BLOCKED | Daemon: true | Priority:5
13:53:38
 CONSOLE:
BLOCKED on java.util.concurrent.LinkedBlockingQueue@300cd7de owned by "World Tick - 1" Id=131
13:53:38
 CONSOLE:
blocked on java.util.concurrent.LinkedBlockingQueue@300cd7de
13:53:38
 STDOUT:
Unloading Player: bendicksonthe3rd
13:53:38
 STDERR:
Exception in thread "Thread-251" java.util.ConcurrentModificationException
13:53:38
 STDERR:
at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
13:53:38
 STDERR:
at java.util.ArrayList$Itr.next(Unknown Source)
13:53:38
 STDERR:
at me.nallar.tickthreading.minecraft.DeadLockDetector$4.run(DeadLockDetector.java:145)
13:53:38
 TickThreading:
Attempting to save
13:53:38
 Minecraft:
Saving chunks for level 'world'/Overworld
13:53:38
 Minecraft:
Saving chunks for level 'world'/Nether
13:53:38
 Minecraft:
Saving chunks for level 'world'/The End
13:53:38
 Minecraft:
Saving chunks for level 'world'/Twilight Forest
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:38
 CONSOLE:
[WARNING] [ForgeModLoader] Exception attempting to save a chunk
13:53:40
 TickThreading:
Saved, now attempting to stop the server and disconnect players cleanly
13:53:40
 Minecraft:
Stopping server
13:53:40
 Minecraft:
Saving players
13:53:40
 STDOUT:
Unloading Player: dibbley75
13:53:40
 STDOUT:
Unloading Player: steampunkmage
13:53:40
 STDOUT:
Unloading Player: max1112_nl

**Comment by LunNova** [comment]
Fixed, see #294.
