### ISSUE TITLE
Exception ticking world Twilight Forest/7 java.lang.NullPointerException

### ISSUE THREAD

**Issue by geoffcorey** [MinimallyCorrect/TickThreading#271]
[Ultimate 1.0.1]  + TickThreading-1.4.7-1.0.0.1227.jar  no other addons or mods.

patch.log
https://gist.github.com/geoffcorey/5334291

tickthreading.log
https://gist.github.com/geoffcorey/c143dfb46d960dad0af9

No crash reports

**Comment by LunNova** [comment]
Does this happen with world unloading disabled?

**Comment by xfloh22** [comment]
exactly the same issue as #179 not sure why this is happening.

**Comment by geoffcorey** [comment]
it appears that when world unloading is disabled that error goes away.  Also seems to slow down a bunch of memory leaks (likely the mods).    

Another odd item that seems to be happening is I pull a jetpack out of the mfe.  Go to an age and then comeback and there is another jetpack in the mfe.   Also I left a jetpack in the mfe after pulling out an electric wrench and jumped into an age.  When I came back the jetpack turned into another electric wrench.

**Comment by LunNova** [comment]
Sounds like #264, update and it should be fixed.

**Comment by geoffcorey** [comment]
Well that error didn't go away with disabling world unloading.  Spoke too soon.

11.04 23:29:55 [Server] INFO at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
11.04 23:29:55 [Server] INFO at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
11.04 23:29:55 [Server] INFO at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:544)
11.04 23:29:55 [Server] INFO at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:447)
11.04 23:29:55 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:283)
11.04 23:29:55 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
11.04 23:29:55 [Server] INFO at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
11.04 23:29:55 [Server] INFO at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd(ChunkLoaderEventHandler.java)
11.04 23:29:55 [Server] INFO at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd_sync0(ChunkLoaderEventHandler.java:39)
11.04 23:29:55 [Server] INFO at codechicken.chunkloader.ChunkLoaderManager.tickEnd(ChunkLoaderManager.java:855)
11.04 23:29:55 [Server] INFO at codechicken.chunkloader.ChunkLoaderManager.tickDownUnloads(ChunkLoaderManager.java:893)
11.04 23:29:55 [Server] INFO at codechicken.chunkloader.ChunkLoaderManager$ChunkLoaderOrganiser.tickDownUnloads(ChunkLoaderManager.java:394)
11.04 23:29:55 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:932)
11.04 23:29:55 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:934)
11.04 23:29:55 [Server] INFO at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
11.04 23:29:55 [Server] INFO java.util.ConcurrentModificationException
11.04 23:29:55 [Server] SEVERE Exception ticking world Twilight Forest/7

**Comment by geoffcorey** [comment]
Here is another stack trace from this morning.  This one was for the the Nether.

12.04 08:42:43 [Server] INFO at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
12.04 08:42:43 [Server] INFO at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
12.04 08:42:43 [Server] INFO at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:544)
12.04 08:42:43 [Server] INFO at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:447)
12.04 08:42:43 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:283)
12.04 08:42:43 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
12.04 08:42:43 [Server] INFO at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
12.04 08:42:43 [Server] INFO at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd(ChunkLoaderEventHandler.java)
12.04 08:42:43 [Server] INFO at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd_sync0(ChunkLoaderEventHandler.java:39)
12.04 08:42:43 [Server] INFO at codechicken.chunkloader.ChunkLoaderManager.tickEnd(ChunkLoaderManager.java:855)
12.04 08:42:43 [Server] INFO at codechicken.chunkloader.ChunkLoaderManager.tickDownUnloads(ChunkLoaderManager.java:893)
12.04 08:42:43 [Server] INFO at codechicken.chunkloader.ChunkLoaderManager$ChunkLoaderOrganiser.tickDownUnloads(ChunkLoaderManager.java:394)
12.04 08:42:43 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:932)
12.04 08:42:43 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:934)
12.04 08:42:43 [Server] INFO at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
12.04 08:42:43 [Server] INFO java.util.ConcurrentModificationException
12.04 08:42:43 [Server] SEVERE Exception ticking world Nether/-1
12.04 08:42:29 [Server] INFO at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
12.04 08:42:29 [Server] INFO at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
12.04 08:42:29 [Server] INFO at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:544)
12.04 08:42:29 [Server] INFO at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:447)
12.04 08:42:29 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:283)
12.04 08:42:29 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
12.04 08:42:29 [Server] INFO at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
12.04 08:42:29 [Server] INFO at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd(ChunkLoaderEventHandler.java)
12.04 08:42:29 [Server] INFO at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd_sync0(ChunkLoaderEventHandler.java:39)
12.04 08:42:29 [Server] INFO at codechicken.chunkloader.ChunkLoaderManager.tickEnd(ChunkLoaderManager.java:855)
12.04 08:42:29 [Server] INFO at codechicken.chunkloader.ChunkLoaderManager.tickDownUnloads(ChunkLoaderManager.java:893)
12.04 08:42:29 [Server] INFO at codechicken.chunkloader.ChunkLoaderManager$ChunkLoaderOrganiser.tickDownUnloads(ChunkLoaderManager.java:394)
12.04 08:42:29 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:932)
12.04 08:42:29 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:934)
12.04 08:42:29 [Server] INFO at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
12.04 08:42:29 [Server] INFO java.util.ConcurrentModificationException
12.04 08:42:29 [Server] SEVERE Exception ticking world Nether/-1
12.04 08:36:25 [Server] INFO at me.nallar.tickthreading.minecraft.Th

**Comment by geoffcorey** [comment]
Upgraded to http://nallar.me/buildservice/job/TickThreading/lastSuccessfulBuild/artifact/target/TickThreading-1.4.7-1.0.0.1276.jar

Just tested the duplicate bug.   Basically pull something out of an iron chest.  Go to an age.  Come back and the item is still in the chest and your personal inventory

**Comment by geoffcorey** [comment]
The opposite also happens where you place an item in the iron chest.  Go to an age. Come back and the item is gone.

**Comment by geoffcorey** [comment]
And this is still in the logs

04-13 07:47:00 [SEVERE] [TickThreading] Exception ticking world Nether/-1
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
    at java.util.HashMap$EntryIterator.next(HashMap.java:934)
    at java.util.HashMap$EntryIterator.next(HashMap.java:932)
    at codechicken.chunkloader.ChunkLoaderManager$ChunkLoaderOrganiser.tickDownUnloads(ChunkLoaderManager.java:394)
    at codechicken.chunkloader.ChunkLoaderManager.tickDownUnloads(ChunkLoaderManager.java:893)
    at codechicken.chunkloader.ChunkLoaderManager.tickEnd(ChunkLoaderManager.java:855)
    at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd_sync0(ChunkLoaderEventHandler.java:39)
    at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd(ChunkLoaderEventHandler.java)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:283)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:466)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:563)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by geoffcorey** [comment]
Yeah I had to remove TickThreading this morning.  The disappearing item problem seem to be worst then before.

**Comment by xfloh22** [comment]
is it just me or this is an error only when chickenchunks is installed? codechicken is in the error and when i removed it i stopped getting it...

**Comment by LunNova** [comment]
The not saving issue was probably #294 which is now also fixed.
