### ISSUE TITLE
Build #1236 - load/generateChunkOnProvideRequest must be enabled for worlds to properly load under MCPC+

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#272]
If load/generateChunkOnProvideRequest are set to false, worlds (such as the nether) will not load and leave the player sitting in a nether portal that does not teleport them.

Soon as both options are turned on, worlds work like normal.

I also believe world unloading needs to be set to false or the same issue will occur again after the servers been online for a little while.

This is probably only an issue with MCPC+

**Comment by Puremin0rez** [comment]
@nallar 

So question - Would you recommend I shut both options off? Keep them on? Still not 100% sure of purpose

**Comment by LunNova** [comment]
Both off is better, but it may break some chunk loaders.

**Comment by Puremin0rez** [comment]
@nallar 

Gotcha, i'll try out the fix in a little bit :)

**Comment by alicheek** [comment]
@nallar 

weird when i put them both to false if you teleported so some areas the chunk would not even load

**Comment by Puremin0rez** [comment]
@nallar 

Same issues as the person above me, teleporting would often throw the person into a limbo state where nothing loaded (Reminds me of my Mystcraft issues months back... nooooo)

**Comment by LunNova** [comment]
https://github.com/MinecraftPortCentral/MCPC-Plus/pull/742

**Comment by Puremin0rez** [comment]
@nallar 

Grabbed the new MCPC+ and the newest TT, shut both options off and kept world unloading enabled and everything appears to be working well!

**Comment by LunNova** [comment]
Nice :)
