### ISSUE TITLE
Build #1239 Issue mass amounts of chunks an entities loaded.

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#273]
Hey there im usung mcpc+ 1.4.7 L9 for FTB Ultimate. so when i dont have tick threading ont he server , the values when i type /gc for chunks loaded and entities are at like numbers at 2500 chunks and 1400 entities when about 50 people are on now with tickthreading added it has gone up to 5000 chunks and 3400 entities with 20 people on it , im not sure why its happening, also the tps is dropping to about 17tps with only the 20 people on

EDIT:

Just to add There was no errors coming up in the TT logs and ive tried most settings in the config of TT  like setting the chunk caching from 2000 to 100 (made no difference to number of chunks that were loaded up) Now i dont know if the mod needs to work with a specific mod like chickenchunks because i have removed that from the mod.

**Comment by LunNova** [comment]
Try turning off "loadChunkOnProvideRequest" in TT's config.

**Comment by alicheek** [comment]
Ill give that a try with the new build when I did that the last time of you teleported to an area the world wouldn't load , think you fixed that issue though

**Comment by alicheek** [comment]
Ok with build #1274 the chunks loading and unloading seems to be working good, but right now the entities are still double what they should be, im using clearlagg to limit the amount of entities on the map but it seems that with TT installed it either cant communicate through the mod, my limit is set at 1000 entities and right now with about 25 people on but there is 3000 entities right now lol appart from that good job seems to be working like a charm.

**Comment by alicheek** [comment]
Oh other comment ive noticed that creepers now bypass essentials permission to stop creepers from destroying blocks

**Comment by alicheek** [comment]
Oh found also another error where if you set unloading world at true when you go into the twilight portal you get disconnected from the server
