### ISSUE TITLE
Build #1239 - Server randomly turns Peaceful?

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#275]
No idea why but after leaving the server on for almost 15 hours, the server appears to have suddenly become "peaceful" and no hostiles will spawn.

Using a monster egg to spawn them will show them spawn for a slight second then go away, which is what happens on peaceful mode.

Restarting the server without touching ANYTHING fixed the problem but I'm worried it'll happen again.

I've verified the difficulty was NOT changed because I set it to hard once again but they still failed to spawn until I issued a reboot.

This might be MCPC+ or TT - hard to tell with some of these issues to be honest

**Comment by LunNova** [comment]
If it happens again, report what `/ticks e` shows.

**Comment by Puremin0rez** [comment]
@nallar 

Just happened again, this is what /ticks e shows
http://i.imgur.com/IPmddlw.png

**Comment by LunNova** [comment]
Is it broken in all dimensions?

**Comment by Puremin0rez** [comment]
@nallar 

Yes, although now i have even more strange behavior to report...

I found an area on the server that hostiles can spawn fine in, but once i go a few chunks over, it breaks again.

It appears hostiles are disabled in most chunks on the server, but not all. Passives work fine in all.

**Comment by LunNova** [comment]
What mods/plugins do you have installed? TT probably broke some mod/plugin which controls spawns.

**Comment by Puremin0rez** [comment]
@nallar 

I only use a permissions plugin and worldedit and commandbook - just basic administration tools, no mob limiters or anything

but... I did just find the issue!

If you have creative mode, it is impossible for mobs to spawn anywhere in your area -> as soon as I switch to survival mode, all hostiles spawn properly again.

Are creative mode players excluded from hostile spawning? That's something i have never ever witnessed before and I don't think that's vanilla behavior.

**Comment by LunNova** [comment]
Can you confirm that that doesn't happen without TT?

**Comment by alicheek** [comment]
@nallar 
This might explain one of the other problems i get, i have a player detector connected to an auto juke box, so its set to play music when any one goes in its vicinity, which normally works fine some on will come in to the area it will play the music. But with TT installed it goes a bit erratic so when some one stays around the vicinity it will keep restarting almost like the player entity keeps reappearing and disappearing.

**Comment by Puremin0rez** [comment]
@nallar 

Appears to be a TT issue - Just tried it on "vanilla" forge and MCPC+ and it didn't happen but when I added TT to the mix it started happening.

I'd say it was a plugin conflict with TT but I don't have any plugin that could possibly cause this.

**Comment by Puremin0rez** [comment]
Also, it appears to get even weirder.

I spawned tons and tons of zombies in survival mode then switched to creative and it instantly killed all of them.

For some reason Creative Mode is acting like a "hostile purger" - this is so strange.

**Comment by alicheek** [comment]
@Puremin0rez 
yes thats my issue also i get a huge build up of entities on my map, also a huge build up of chunks loaded (that may be a different issue though)

**Comment by Puremin0rez** [comment]
To be honest I don't really care if Creative mode isn't letting hostiles spawn (and even killing them apparently), I just didn't realize I was in creative when this issue was happening so I was worried it was something worse.

It's still a silly issue though and should be looked at :P

**Comment by LunNova** [comment]
Get latest, go into survival, spawn mobs around you, run /ticks e, change to creative, run /ticks e, give the console log.

**Comment by LunNova** [comment]
Also, can't replicate. :s ![](http://i.imgur.com/9Tw7PPU.jpg)

**Comment by Puremin0rez** [comment]
Appears to be somehow related to NEI - Removed it, issue stopped happening. A feature I suppose?

Regardless, this is a uber miniscule issue and possibly even a feature. closing.
