### ISSUE TITLE
[mcpc] Auto-save feature when set to a low interval lags hard

### ISSUE THREAD

**Issue by dadealus** [MinimallyCorrect/TickThreading#277]
can almost time it with a stop watch. but basically when the Save-all tick thing triggers all commands, chest interactions, machine interactions .... basically everything except block breaking comes to a hault even TT's /tps. once it recovers TT's tps report shows everything running at 20 ticks except for overall which is at like 0.3 TPS

**Comment by LunNova** [comment]
Are you sure this is auto save? Seems more likely that it would be chunk GC. (See #265)

**Comment by dadealus** [comment]
I found the following 
with saveInterval at default Increasing chunkGCInterval to some high number caused the duration of the lag spike to increase

With saveInterval set to 72000 chunkGCInterval can be set to anything (even 600) and the lag spike does not occur until about an hour passes.
