### ISSUE TITLE
Tickthreading broke dynmap

### ISSUE THREAD

**Issue by swarmski** [MinimallyCorrect/TickThreading#278]
Duplicate issue over at the Dynmap issue tracker (not sure what mod is at fault)
https://github.com/webbukkit/dynmap/issues/1232

Just installed the latest TickThread mod which seems to not work with Dynmap?

Tiles wiped and black map
Fullrender completes without rendering anything
[INFO] Full render starting on world 'world'...
[INFO] Full render of map 'flat' of 'world" completed - 0 tiles rendered (0.00 msec/map-tile, NaN msec per render)
[INFO] Full render of map 'surface' of 'world' completed - 0 tiles rendered (0.00 msec/map-tile, NaN msec per render)
[INFO] Full render of map 'cave' of 'world' completed - 0 tiles rendered (0.00 msec/map-tile, NaN msec per render)
[INFO] Full render of 'world' finished.

Troubleshooting steps
Delete dynmap folder and run serverstart again (to recreate dynmap folder) - Still doesnt work

Using TickThreading-1.4.7-1.0.0.1243

**Comment by LunNova** [comment]
Are you using forge dynmap or bukkit dynmap?

**Comment by swarmski** [comment]
Using the following

Minecraft v1.4.7 with Forge v6.6.x, MCPC+ v1.4.7: DynmapForge v1.6 
FTB Launcher running Mindcrack

**Comment by LunNova** [comment]
Try Bukkit dynmap - it should work, as you're using MCPC+.

**Comment by LunNova** [comment]
Also, make sure world unloading is off in TT's config. It breaks with MCPC+

**Comment by swarmski** [comment]
Apologies if silly question.  The bukkit Dynmap says i need to;
Extract dynmap-*-bin.zip in your plugins directory.

I dont have a plugins directory?  Currently i use "Minecraft v1.4.7 with Forge v6.6.x, MCPC+ v1.4.7:" and all i do is place the mod into the "mods" folder and it extracts automatically and setsup on server start.

Dynmap is working as such that players are slowing discovering the world and it renders.  However an attempt to do a full render to rediscover what was already rendered results in that same quick finish problem as in first post?

**Comment by clienthax** [comment]
make a plugins folder in the same folder as your mods folder

**Comment by swarmski** [comment]
Hi Clienthax

I created the Plugins folder in the Mods folder, however upon server start dynmap does not load.

Any ideas?

**Comment by clienthax** [comment]
make a plugins folder in the SAME folder as your mods folder

**Comment by LunNova** [comment]
(the server directory, the folder which the mods folder is in, the direfctory containing your server jar, etc. :P)

**Comment by swarmski** [comment]
Okay understand thanks.

Just FYI 1.5 dynmap is working fine

**Comment by chun69gus** [comment]
I am having the same problem with latest Dynmap and TT. 

@swarmski, whewn you say 1.5 dynmap is working fine, was that the bukkit or forge version?

**Comment by chun69gus** [comment]
Tried 1.5 and get errors.
Also tried the 1.7 alpha 2 and it does the same as 1.6
