### ISSUE TITLE
[MCPC] Infinite water source isnt sync'd with chunk ticks

### ISSUE THREAD

**Issue by dadealus** [MinimallyCorrect/TickThreading#279]
Basically it seems that whatever processes the regeneration of water isn't in sync with the tick rate of the chunk its located in.

Why is this bad?

water pumps setup in infinite pools run dry almost instantly because the pool doesn't regenerate in any sort of fashionable time.

**Comment by Puremin0rez** [comment]
Maybe due to "aggregate-chunkticks" on MCPC+ ?

Seeing the same sort of thing, tuned that setting back to 1 (vanilla) to see if that fixes anything.

**Comment by LunNova** [comment]
Sure this isn't an MCPC+ issue? There've been some issues related to water flow in MCPC+.

**Comment by dadealus** [comment]
Sorry I confirmed this was still happening with out TT but forgot to close this ticket closing it now
