### ISSUE TITLE
[MCPC] Picking up armor causes current armor to delete

### ISSUE THREAD

**Issue by dadealus** [MinimallyCorrect/TickThreading#281]
for the 12 hours we had TT running I saw this happening as well as many players reporting the problem.

The issue.

your wearing diamond armor and you see a noob in leather.

you run over and kill them

their items drop on the ground and you pick them up.

the moment you run over their leather armor your diamond armor get deleted and you are now wearing leather armor.

**Comment by Puremin0rez** [comment]
I can confirm this +1
