### ISSUE TITLE
Build #1246-possible chunk loading and reloading issue

### ISSUE THREAD

**Issue by Kusinagie** [MinimallyCorrect/TickThreading#283]
Hey Nallar

So i set this up in a mystcraft lava age. 
![2013-04-12_04 25 11](https://f.cloud.github.com/assets/4134724/371920/5372bbd8-a34b-11e2-8a4a-ea3bee7ba8d0.png)
![2013-04-12_04 25 34](https://f.cloud.github.com/assets/4134724/371921/5603da94-a34b-11e2-9c5e-1809959a3bff.png)
(the random bit of golden pipe to the left of the chunkloader marks the center of the chunk)

As you can see the load of this is upwards of 200%
I originally set this up with build 1226 and going full-bore tps was still 20 with very low load (18% or so)  and this went through 15 or so layers with no problems.

But with 1246 it clears a layer then only one pump lowers and continues the others stay idle. That is until i break the chunk loader and leave the age. then they all continue, otherwise the others sit idle. Also i think those chunks are not unloading after i leave with no chunkloader there because the load of that age stays up in the 200's

Here is the ForgeModLoader-server-0 file:https://gist.github.com/Kusinagie/5370624
this shows alot of spam about reloading and unloading chunks
...and myself spaming the tps command : p 

If i can get you anymore info to help let me know

**Comment by LunNova** [comment]
Run /profile e while in that world, screenshot/copy results.

**Comment by Kusinagie** [comment]
Here you go Nallar
with build 1246
![2013-04-12_22 42 23](https://f.cloud.github.com/assets/4134724/376001/3deee202-a3e4-11e2-9582-be4497d5b06d.png)
After updating to 1274
![2013-04-12_22 33 07](https://f.cloud.github.com/assets/4134724/376002/599b1ad4-a3e4-11e2-84a0-5187d9996baf.png)

I did notice with build 1274 the load seemed to only be hitting 150-160% instead of in the 200's.
If i can get you anything else let me know.

**Comment by Kusinagie** [comment]
correction it randomly hit in the 200's  after i had restarted the server when i got home. so i guess no difference between the builds. not sure if that helps any?

**Comment by LunNova** [comment]
Doesn't look like a TT issue, looks like the pumps are bugged out - see how factory.TilePump is taking 99.477% of the tick time, and each pump is taking 20ms.

Use jvisualvm and get a profiling snapshot so I can see exactly what's going on.

**Comment by Kusinagie** [comment]
okay i got visualvm installed but im not sure how to use it :p 
I figured out how to view the server and i see the profiling tab but there are options there so what should i do from there?

**Comment by LunNova** [comment]
Use the sampling tab, start it sampling for a few minutes, stop it, click the snapshot button, save the snapshot and post it here.

**Comment by Kusinagie** [comment]
Okay I'm doing cpu now. I will give it a few minutes. You want me to do memory as well?

**Comment by LunNova** [comment]
Just CPU sampling is fine.

**Comment by Kusinagie** [comment]
Okay i think i did this right.
https://www.dropbox.com/s/904jxxx8kr9tvpv/1365940605057.nps
Let me know what else i can do for ya.

**Comment by LunNova** [comment]
Looks like buildcraft pumps can't handle infinite lava like this correctly.

**Comment by LunNova** [comment]
Did you get this sorted?

**Comment by LunNova** [comment]
BC performance issue, see https://github.com/BuildCraft/BuildCraft/issues/861

Pumps are going to be redesigned in future, I might backport the changes to 1.4.7 + 1.5.
