### ISSUE TITLE
Build #1272 - Chunk & Entities failures

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#286]
Spamming nonstop:
http://pastebin.com/mJEGuqTZ

Images:
http://i.imgur.com/j8GoS1K.jpg
http://i.imgur.com/roZ3PPa.jpg

Seems to be "stripes" of world that doesn't tick

**Comment by Puremin0rez** [comment]
@nallar 

Maybe reloaded to loadChunkOnProvideRequest? Something else?

**Comment by LunNova** [comment]
That's the debugging which runs with /ticks e I added for you to try to find what was killing mobs when you were in creative.

**Comment by LunNova** [comment]
Although the world loading in stripes may be loadChunkOnPRovideRequest related.

**Comment by Puremin0rez** [comment]
@nallar 

Ah, yeah that started showing up when i did /ticks e - makes sense

What about the chunk failures and the absolute stopping of entities? They get "fixed" when lighting a fire or something on it / next to it

**Comment by LunNova** [comment]
Try latest, might be fixed. If not, will have to wait for tomorrow, need to sleep.

**Comment by Puremin0rez** [comment]
Seems to be fixed, but i'll leave this here another day or so because "fixed" issues like to show up after I say they're fixed :)
