### ISSUE TITLE
[TT #1274] [1.4.7 mcpc+ L11] Bees mod client crash

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#288]
since i isntalled TT my players and i are now expericencing a new crash, at firsti thought it had something todo with them being on the edge of a chunk but turns out is just every one of their items are not working , when ever you right click to interact with it your client just freezes and crashes.

client crash log 

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 13/04/13 07:40
Description: Exception in world tick

java.lang.ArrayIndexOutOfBoundsException: 0
    at forestry.core.gui.LiquidTankSlot.<init>(LiquidTankSlot.java:30)
    at forestry.factory.gui.GuiFermenter.<init>(GuiFermenter.java:14)
    at forestry.factory.GuiHandlerFactory.getClientGuiElement(GuiHandlerFactory.java:49)
    at forestry.core.GuiHandler.getClientGuiElement(GuiHandler.java:25)
    at cpw.mods.fml.common.network.NetworkRegistry.openLocalGui(NetworkRegistry.java:316)
    at cpw.mods.fml.common.network.FMLNetworkHandler.openGui(FMLNetworkHandler.java:339)
    at qx.openGui(EntityPlayer.java:2304)
    at cpw.mods.fml.common.network.OpenGuiPacket.execute(OpenGuiPacket.java:55)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handleFMLPacket(FMLNetworkHandler.java:102)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:67)
    at ayh.a(NetClientHandler.java:1483)
    at di.a(SourceFile:59)
    at com.mumfrey.liteloader.core.HookPluginChannels.a(HookPluginChannels.java:99)
    at cg.b(TcpConnection.java:458)
    at ayh.d(NetClientHandler.java:240)
    at ayp.b(WorldClient.java:92)
    at net.minecraft.client.Minecraft.l(Minecraft.java:1874)
    at net.minecraft.client.Minecraft.J(Minecraft.java:848)
    at net.minecraft.client.Minecraft.run(Minecraft.java:773)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at forestry.core.gui.LiquidTankSlot.<init>(LiquidTankSlot.java:30)
    at forestry.factory.gui.GuiFermenter.<init>(GuiFermenter.java:14)
    at forestry.factory.GuiHandlerFactory.getClientGuiElement(GuiHandlerFactory.java:49)
    at forestry.core.GuiHandler.getClientGuiElement(GuiHandler.java:25)
    at cpw.mods.fml.common.network.NetworkRegistry.openLocalGui(NetworkRegistry.java:316)
    at cpw.mods.fml.common.network.FMLNetworkHandler.openGui(FMLNetworkHandler.java:339)
    at qx.openGui(EntityPlayer.java:2304)
    at cpw.mods.fml.common.network.OpenGuiPacket.execute(OpenGuiPacket.java:55)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handleFMLPacket(FMLNetworkHandler.java:102)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:67)
    at ayh.a(NetClientHandler.java:1483)
    at di.a(SourceFile:59)
    at com.mumfrey.liteloader.core.HookPluginChannels.a(HookPluginChannels.java:99)
    at cg.b(TcpConnection.java:458)
    at ayh.d(NetClientHandler.java:240)

-- Affected level --
Details:
    Level name: MpServer
    All players: 2 total; [ays['alicheek'/5683, l='MpServer', x=-1015.75, y=57.62, z=-1250.47], VoxelPlayerEntityOtherPlayerMP['xXColdmanXx'/1401, l='MpServer', x=-1011.25, y=72.50, z=-1276.94]]
    Chunk stats: MultiplayerChunkCache: 81
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-27,110,-318), Chunk: (at 5,6,2 in -2,-20; contains blocks -32,0,-320 to -17,255,-305), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Level time: 37383849 game time, 37691700 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 8 total; [VoxelPlayerEntityOtherPlayerMP['xXColdmanXx'/1401, l='MpServer', x=-1011.91, y=72.50, z=-1276.34], VoxelPlayerEntityOtherPlayerMP['Ladiesman2014'/2478, l='MpServer', x=-1026.66, y=73.02, z=-1275.66], ays['alicheek'/5683, l='MpServer', x=-1015.75, y=57.62, z=-1250.47], qr['Zombie'/5056, l='MpServer', x=-972.53, y=89.00, z=-1297.53], mc['entity.ItemFrame.name'/5055, l='MpServer', x=-1012.50, y=66.50, z=-1289.94], VoxelPlayerEntityOtherPlayerMP['xXColdmanXx'/1401, l='MpServer', x=-1011.25, y=72.50, z=-1276.94], qr['Zombie'/4311, l='MpServer', x=-968.33, y=88.00, z=-1279.87], VoxelPlayerEntityOtherPlayerMP['xXColdmanXx'/1401, l='MpServer', x=-1011.25, y=72.50, z=-1276.94]]
    Retry entities: 0 total; []
Stacktrace:
    at ayp.a(WorldClient.java:439)
    at net.minecraft.client.Minecraft.l(Minecraft.java:1887)
    at net.minecraft.client.Minecraft.J(Minecraft.java:848)
    at net.minecraft.client.Minecraft.run(Minecraft.java:773)
    at java.lang.Thread.run(Unknown Source)

-- Affected level --
Details:
    Level name: MpServer
    All players: 2 total; [ays['alicheek'/5683, l='MpServer', x=-1015.75, y=57.62, z=-1250.47], VoxelPlayerEntityOtherPlayerMP['xXColdmanXx'/1401, l='MpServer', x=-1011.25, y=72.50, z=-1276.94]]
    Chunk stats: MultiplayerChunkCache: 81
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-27,110,-318), Chunk: (at 5,6,2 in -2,-20; contains blocks -32,0,-320 to -17,255,-305), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Level time: 37383849 game time, 37691700 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 8 total; [VoxelPlayerEntityOtherPlayerMP['xXColdmanXx'/1401, l='MpServer', x=-1011.91, y=72.50, z=-1276.34], VoxelPlayerEntityOtherPlayerMP['Ladiesman2014'/2478, l='MpServer', x=-1026.66, y=73.02, z=-1275.66], ays['alicheek'/5683, l='MpServer', x=-1015.75, y=57.62, z=-1250.47], qr['Zombie'/5056, l='MpServer', x=-972.53, y=89.00, z=-1297.53], mc['entity.ItemFrame.name'/5055, l='MpServer', x=-1012.50, y=66.50, z=-1289.94], VoxelPlayerEntityOtherPlayerMP['xXColdmanXx'/1401, l='MpServer', x=-1011.25, y=72.50, z=-1276.94], qr['Zombie'/4311, l='MpServer', x=-968.33, y=88.00, z=-1279.87], VoxelPlayerEntityOtherPlayerMP['xXColdmanXx'/1401, l='MpServer', x=-1011.25, y=72.50, z=-1276.94]]
    Retry entities: 0 total; []

-- System Details --
Details:
    Minecraft Version: 1.4.7
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_17, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 155245304 bytes (148 MB) / 441061376 bytes (420 MB) up to 4225236992 bytes (4029 MB)
    Mod Pack: CWW256 forgot to change this.
    LiteLoader Mods: 5 loaded mod(s)
          - VoxelPacket version 2.0.2
          - VoxelPlayer version 0.9.6
          - Integrated Sound Packs version 1.1.1
          - VoxelMenu version 1.4.7_05
          - VoxelMap version 1.0.0
    JVM Flags: 7 total; -Xms256M -Xmx4096M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:+AggressiveOpts -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=128m
    AABB Pool Size: 2952 (165312 bytes; 0 MB) allocated, 50 (2800 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
    FML: 
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MiscPeripheralsASM [MiscPeripherals ASM](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    PowerCrystalsCore [PowerCrystals Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ComputerCraft [ComputerCraft](computercraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CCTurtle [ComputerCraft Turtles](computercraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Core [BuildCraft](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Builders [BC Builders](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Energy [BC Energy](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Factory [BC Factory](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Transport [BC Transport](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Silicon [BC Silicon](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    factorization [Factorization](factorization.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ExtrabiomesXL [ExtrabiomesXL](extrabiomes.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forestry [Forestry for Minecraft](forestry.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHCore [CoFH Core](CoFHCore.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThermalExpansion [Thermal Expansion](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OmniTools [OmniTools](omnitools.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    IC2 [IndustrialCraft 2](IC2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Railcraft [Railcraft](railcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RedPowerCore [RedPower](redpowercore.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RedPowerBase [RP Base](redpowercore.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RedPowerMachine [RP Machine](redpowermechanical.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RedPowerCompat [RP Compat](redpowercompat.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RedPowerWiring [RP Wiring](redpowerdigital.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RedPowerLogic [RP Logic](redpowerdigital.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RedPowerLighting [RP Lighting](redpowerdigital.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RedPowerWorld [RP World](redpowermechanical.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RedPowerControl [RP Control](redpowermechanical.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThermalExpansion|Factory [Factory](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThermalExpansion|Energy [Energy](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThermalExpansion|Transport [Transport](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ImmibisCore [Immibis Core](immibiscore.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Tubestuff [Tubestuff](tubestuff.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TwilightForest [The Twilight Forest](TwilightForest.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    XyCraft [§3XyCraft](xycraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GregTech_Addon [GregTech-Addon](GregTech.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MiscPeripherals [MiscPeripherals](MiscPeripherals.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AdvancedMachines [IC2 Advanced Machines Addon](advancedmachines.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AdvancedSolarPanel [Advanced Solar Panels](advancedsolarpanel.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AppliedEnergistics [Applied Energistics](AppliedEnergistics.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BiblioCraft [BiblioCraft](BiblioCraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ChargePads [Charge Pads](ChargePads.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ChickenChunks [ChickenChunks](ChickenChunks.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    EE3 [Equivalent Exchange 3](ee3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    EnderStorage [EnderStorage](EnderStorage.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BinnieCore [Binnie Core](extrabees.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ExtraBees [Extra Bees](extrabees.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FlatBedrock [FlatBedrock](FlatBedrock.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeIRC [ForgeIRC](forgeirc.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GraviGun [GraviGun](GraviGun.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GraviSuite [Gravitation Suite](gravisuite.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    IC2NuclearControl [Nuclear Control](IC2NuclearControl.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_InvTweaks [Inventory Tweaks](InvTweaks.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    IronChest [Iron Chest](IronChest.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MFReloaded [Minefactory Reloaded](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MFReloaded|CompatExtraBiomes [MFR Compat: ExtraBiomes](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MFReloaded|CompatForestry [MFR Compat: Forestry](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MFReloaded|CompatIC2 [MFR Compat: IC2](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MFReloaded|CompatPams [MFR Compat: Pam's Mods](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MFReloaded|CompatRP2 [MFR Compat: RP2](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    SoulShards [SoulShards](soulshards.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MFReloaded|CompatSoulShards [MFR Compat: Soul Shards](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MFReloaded|CompatSufficientBiomes [MFR Compat: Sufficient Biomes](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Thaumcraft [Thaumcraft](Thaumcraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MFReloaded|CompatThaumcraft [MFR Compat: Thaumcraft](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MFReloaded|CompatTwilightForest [MFR Compat: TwilightForest](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    XyCraftWorld [§2XyCraft World](xycraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MFReloaded|CompatXycraft [MFR Compat: Xycraft](MineFactoryReloaded.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ModularForceFieldSystem [Modular ForceField System V2](modularforcefieldsystem.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mmmPowersuits [MachineMuse's Modular Powersuits](ModularPowersuits.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Mystcraft [Mystcraft](mystcraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIPlugins [NEI Plugins](neiplugins.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NetherOres [Nether Ores](NetherOres.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ObsidiPlates [Obsidian Pressure Plates](obsidiplates.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    drceph.petrogen [Petroleum Generator](petrogen.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    PortalGun [Portal Gun](PortalGun.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    PowerConverters [Power Converters](PowerConverters.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    SecretRoomsMod [The SecretRoomsMod](secretroomsmod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    StevesCarts [Steve's Carts](StevesCarts.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThaumicBees [ThaumicBees](ThaumicBees.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    WR-CBE|Core [WR-CBE Core](wirelessredstonecore.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    WR-CBE|Addons [WR-CBE Addons](wirelessredstoneaddons.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    WR-CBE|RedPower [WR-CBE RedPower](wirelessredstoneredpower.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    XReliquary [Xeno's Reliquary](XReliquary.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    XyCraftMachines [§9XyCraft Machines](xycraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEI-Mystcraft-Plugin [NEI Mystcraft Plugin](neipluginMyst.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    LWJGL: 2.4.2
    OpenGL: GeForce GT 555M/PCIe/SSE2 GL version 4.3.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'forge,fml'
    Type: Client (map_client.txt)
    Texture Pack: Default
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 1587 (88872 bytes; 0 MB) allocated, 35 (1960 bytes; 0 MB) used

**Comment by alicheek** [comment]
@nallar 

Turns out its just forestry in general for some reason evey one crashed when they right click on of the machines

**Comment by Puremin0rez** [comment]
@nallar 

Same issue, something changed in TT recently that's causing this

**Comment by LunNova** [comment]
If you have the time, could you pinpoint exactly which build causes this? Finding what causes client issues is a huge pain :(

**Comment by Puremin0rez** [comment]
@nallar 

Honestly don't have the time to pinpoint exact build but i am fairly certain it started on THIS commit or sometime close afterwards.

https://github.com/nallar/TickThreading/commit/26e33578b5ab1c36ab8e705da278bf91a31fbdb6

**Comment by LunNova** [comment]
I thought this was fixed, apparently it isn't, just received http://pastebin.com/eKPJvmU5

Might be related to #446

**Comment by alicheek** [comment]
yea happening with me with build 1539 wasn't doing it for a while though so don't know what's changed

**Comment by LunNova** [comment]
Fixed with #446's fix.
