### ISSUE TITLE
[TT #1446] [1.4.7 mcpc+ L19] Redpower wires intermittently provide power

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#289]
Hey there of  a problem with the player detector, instead of just giving a constant redstone signal when a player is in the vicinity it its going on and off like its a AC current instead of DC
it wasnt doing this before i installed TT, causes some issues say if you want to connect it up to a auto juke box because it just keeps spazzing out and repeating the start of the song

Good work though still seems to be working well appart from minor things like that.

**Comment by LunNova** [comment]
Which mod is the player detector from?

**Comment by LunNova** [comment]
Possible fix, but it may be irrelevant depending on which player detector you're using. That should fix it if there was an issue with Immibis' player detector.

**Comment by alicheek** [comment]
it was the greg tech player detector

**Comment by alicheek** [comment]
The greg tech one is still doing the same thing

**Comment by LunNova** [comment]
Is this still happening after https://github.com/nallar/TickThreading/commit/1bd5c18e096c16b96f09a93b51ddd5a725c64efb?

**Comment by alicheek** [comment]
@nallar 

Still does it but no where near as quickly so song will play for about 10 seconds then it will restart the song, this is just with me bein there staying next to it with no one else , should be doing the whole song unless i have gone and some other player comes in its area it would restart.

**Comment by alicheek** [comment]
@nallar 

Strange it seems to be actually the redpower wire  that is causing the issue, when i use redstone to connect it up it doesnt randomly restart now , might be something wrong with the way the redpower signals are being read.

**Comment by LunNova** [comment]
Is this actually fixed or do you just not care about the issue? I do still want to find why redpower wire is being unreliable. You could edit this and change the titile/description to properly describe the issue with wires.

**Comment by alicheek** [comment]
oh sorry! guessed it was fixed since haven't had any player issues ill test it right now just to let u know

**Comment by alicheek** [comment]
@nallar  

Its fixed :)

**Comment by alicheek** [comment]
@nallar 
ohhh noo its not was working there for about 30 secs and now its looping at the start

soz about that was too quick on my feet there

**Comment by alicheek** [comment]
its very weird its very inconsistent , for instance its basically gone through the whole song here now?

**Comment by LunNova** [comment]
Can you screenshot the setup which this happens with? I can replicate this, but it only happens if the wire is having block updates from something else next to it, or for example has a timer also connected to it set to run quickly.

**Comment by alicheek** [comment]
That's the set up there 
![2013-04-28_01 19 34](https://f.cloud.github.com/assets/3965516/435075/7998264a-af99-11e2-88ba-3d847efbc501.png)
