### ISSUE TITLE
TT 1283 (&1274): Chunk resetting after using Portal

### ISSUE THREAD

**Issue by MrScopi** [MinimallyCorrect/TickThreading#294]
I've got a small world where I am running between a quarry and an ore processing room using Portals.  The portals are not in the chunks of either of the two destinations.

The ore processing room has Redpower blutricity machines, basic IC2 machines, and a barrel.  What I do is this:
- Set ores to macerate and drop off cobble in the barrel
- Run to portal
- Grab more cobble from quarry
- Run through portal
- Drop off cobble in barrel

When I reach the last step, I have been noticing that occasionally the number will be reset to what it was before Step 1, and my ores will be out of the macerator and back in the chest.

In 1274 I received 60-sec interval messages that the quarry chunks were being unloaded before the queue was prepared.  In 1283 the logs are silent.

I've tested three combinations of portal travel:
1. Use portals on both ends
2. Walk to quarry, portal back
3. Portal to quarry, walk back

I am only able to reproduce this error using methods 1 and 3, leading me to believe it is unloading chunks without saving them when I portal AWAY.  I think this is corroborated when I only see the portal destination (clear portal instead of obfuscated) when I walk away from the portal.

Let me know what further information is needed to troubleshoot this issue.  I feel like it is unloading chunks without saving them first, then recalling the older chunk during reload.

Finally, thanks for this mod!  It has made a big difference in my tiny server's performance.

**Comment by LunNova** [comment]
Does this still happen in 1284?

**Comment by MrScopi** [comment]
Yes it does.  It also appeared to skip around.

Using barrel amt as one test, I started at 54 stacks, filled it.  Portaled, came back, at 54.  Added five for 59, portaled.  Came back to 64.

Machines (macerator and blulectric furnace) seem to follow the same trend, rolling back in concert with barrel.

**Comment by LunNova** [comment]
Okay, managed to reproduce this bug locally, should have it fixed soon.

**Comment by HaoSs07** [comment]
nallar what is a normal save interval for that high number of chunks i have ?

**Comment by LunNova** [comment]
Probably between 400 and 1000. Fixing your save interval will not fix this issue.

**Comment by HaoSs07** [comment]
ok; I will wait for you to work your magic :D :+1:

**Comment by LunNova** [comment]
@MrScopi Nice observation! It is fluctuating, because what happens is the chunk loads the way it was saved the time before it last saved. Not sure why yet :P

**Comment by MrScopi** [comment]
FYI that fixed it, and man is it spammy.  The rastering quarry movement isn't helping one bit. :)

Thank you!

**Comment by LunNova** [comment]
bed1da2fc52085
