### ISSUE TITLE
[TT #1286] [1.4.7 mcpc+ L11]  When area unloads UI with Forestry items dont work

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#298]
Dont have any error logs for it  but weird thing is if you place the forestry items freshly down they will work if you interact with them, but if you right click after letting them unload then come back to them they do not respond when you right click them.

**Comment by Puremin0rez** [comment]
I can vouch for this issue, although it doesn't happen all the time for me.

**Comment by LunNova** [comment]
Does it still happen after 50658faa8f4bf19a? What is loadChunkOnProvideRequest set to?

**Comment by LunNova** [comment]
Another possible cause fixed in b4eee944ed9e11bc3d.

**Comment by alicheek** [comment]
It was set to false , ill try the new build now

**Comment by alicheek** [comment]
@nallar 

Its weird i went to one place and they worked, then i went back to the place when a player first got crashed and i right clicked those ones and i crashed , so i removed them and replaced them and then they worked now i dont know how long they will work for so ill let you know with some further testing

**Comment by Puremin0rez** [comment]
@nallar 

Using #1291 and issue still appears to happen

**Comment by Puremin0rez** [comment]
Scratch that, it only happened once and it was fine afterwards. Strange issue >_>

**Comment by LunNova** [comment]
Not happened on any newly replaced items since that fix?

**Comment by Puremin0rez** [comment]
@nallar 

Nope, I haven't had it happen here since the fix.

**Comment by alicheek** [comment]
Yea seems to be fine now
