### ISSUE TITLE
Quarry stop running after server reboot

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#299]
As the save chunk bug seems to be finally resolved, I have a older bug with quarry , they stop working after reboot, they need to be broke and placed again,
 usually after reboot they check the frame integrity ; rebuild if necessary ,and mine again. but now they don't, also the black and yellow frame appears and stay there even if the exterior frame is intact.

**Comment by Puremin0rez** [comment]
I can also vouch for this issue - it appears to be new and sprouted from the new chunk save fixes

**Comment by Nohau** [comment]
Just a suggestion if your running mcpc+ i found adding the user [[BuildCraft]] to the ops fixed that problem .

**Comment by LunNova** [comment]
Run /dump <x, y, z> on the stuck quarry and paste the results, if @Nohau's fix doesn't help.

**Comment by HaoSs07** [comment]
i dont use mcpc

![2013-04-14_02 50 47](https://f.cloud.github.com/assets/3189195/377284/859086ae-a495-11e2-82c3-10d9658f3401.png)
![2013-04-14_02 51 11](https://f.cloud.github.com/assets/3189195/377285/894a5928-a495-11e2-8373-b56c98cbc609.png)
![2013-04-14_02 51 14](https://f.cloud.github.com/assets/3189195/377286/908f7ee8-a495-11e2-91c8-69842a74e310.png)

**Comment by kenneaal** [comment]
This also happens under MCPC+ without TickThreading and with [BuildCraft] in ops.txt.

**Comment by alicheek** [comment]
It only happens if i have TT installed

**Comment by HaoSs07** [comment]
from player reports, if the quarry is connected to a tessaract it will stop, if its connected to engines  directly will continue to work after restart, can someone test this ?

**Comment by Nohau** [comment]
Running FTB Ultimate using TT# 1306 in a MystCraft world on server restart using energy  tessarcts and ender chest works fine for me but this was first install of 1306 if we do a restart i will update this if outcome is different.

**Comment by Nohau** [comment]
Using TT # 1312 with this type of setup energy tessaract directly on the quarry then a pipe to the ender chest still no issue serveral restarts since. Utilizing FTB Ultimate

**Comment by Nohau** [comment]
Scratch that first restart of 1312 we now see this problem

**Comment by Nohau** [comment]
Build 1315 fixed my issue.and purposely restarted server after upgrade to verify.

**Comment by HaoSs07** [comment]
i still have it, tessaract with conduits linked to 2 quarry’s , they stop after reboot

**Comment by Nohau** [comment]
Only thing I can think of that I might have done different was i reinstalled all of FTB Ultimate mods in this case then reran the patch against the server and mods. 

But did this on 1312 and on the upgrade to 1315 .

**Comment by HaoSs07** [comment]
so... fore some reason my quarry's work now after restart :)
