### ISSUE TITLE
Close, issue fixed in newer builds

### ISSUE THREAD

**Issue by gustav9797** [MinimallyCorrect/TickThreading#30]
Current configuration(enabling chunkticking or worldticking crashes it):

```
# Whether chunk ticks should be threaded
B:enableChunkTickThreading=false

# Whether entity ticks should be threaded
B:enableEntityTickThreading=true

# Whether tile entity ticks should be threaded
B:enableTileEntityTickThreading=true

# Whether world ticks should be threaded
B:enableWorldTickThreading=false
```

I've checked through server.log and tickthreading logs, no errors.
Maybe this has something to do with disabling ticking?

**Comment by LunNova** [comment]
Disabling chunk tick threading should just revert it to normal behaviour, I must have broken something else :(

Will look into it.
