### ISSUE TITLE
Deadlock after 10 minutes, server load 1000% +

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#301]
https://gist.github.com/HaoSs07/5382472

Also i still get Save queue overloaded in Overworld/0 consider decreasing saveInterval., and the save is set for 260, do i need to go any lower ?

**Comment by HaoSs07** [comment]
P.S. ur last 3 jenkins build have faild

**Comment by LunNova** [comment]
Can you get the error again on latest?

**Comment by HaoSs07** [comment]
https://gist.github.com/HaoSs07/5382740 happen under 1 minute after start

**Comment by LunNova** [comment]
Latest again?

**Comment by HaoSs07** [comment]
testing, u sure have a lot of work nallar, i hope one day you can get it super stable and enjoy a week with no issues

**Comment by HaoSs07** [comment]
seems something else broke / https://gist.github.com/HaoSs07/5382796 , stopped just after start, made 500 kb log in seconds

**Comment by LunNova** [comment]
Now?

**Comment by HaoSs07** [comment]
already on it, it started, will test 1 hour, if it deadlocks again i will come with replay, if not i will close the issue; thx for the help.

**Comment by alicheek** [comment]
even in that last build it was working fine for me dont know why your having an issue :S

**Comment by HaoSs07** [comment]
with that big number of mods its a lot of possibility for something to go wrong for me and not for others, i also don't have a lot of issues posted by other :)

**Comment by alicheek** [comment]
Ah fair does man :) im using FTB Ultimate

**Comment by HaoSs07** [comment]
@nallar 

its starts from 8 % load; and goes up to 3000 % then this happen https://gist.github.com/HaoSs07/5382986

**Comment by alicheek** [comment]
Using Mcpc+ L13 by any chance?

**Comment by HaoSs07** [comment]
nop; vanilla

**Comment by alicheek** [comment]
ever thought about using mcpc much more efficient  and can use bukkit plugins http://ci.md-5.net/job/MCPC-Plus-Legacy/

**Comment by xfloh22** [comment]
this error is so old, ive been having this for over a month now and have even posted it here... i really hate chickenchunks and xycrap, the 2 mods that allways cause errors

**Comment by HaoSs07** [comment]
no, not really, my settup is hardly compatible with MCPC ,and don't want any bukkit plugins 

xfloh did you manage to fix it ? i get it just after 10 minutes of server on.

**Comment by alicheek** [comment]
How is it not compatible? Thats the whole point of mcpc is to merge bukkit and forge again and it works great also has systems to optimise load my server runs well with 60 people on it and im still only a VPS

**Comment by xfloh22** [comment]
i have never really found a way to fix it since every time i try to remove chickenchunks my server doesnt even start up. sometimes i get lucky and it runs 30minutes but after that it just goes to hell.

**Comment by HaoSs07** [comment]
chickenchunk i can remove, core is the problem.

**Comment by alicheek** [comment]
Core doesnt seem to give me an issue have you changed anything in its config?

**Comment by HaoSs07** [comment]
problem if removed :p not in game; is not a mod by itself

**Comment by xfloh22** [comment]
really? every time i try the console gives me this error even without TT:

http://pastebin.com/gM0dCfT8

**Comment by LunNova** [comment]
@HaoSs07 Looks like this is the issue with spammy TickNextTickList updates again. Testing a possible fix + some debugging stuff, will push soon if it works.

**Comment by LunNova** [comment]
@xfloh22 Rename/delete the world's forcedchunks.dat

**Comment by xfloh22** [comment]
ur amazing nallar :D thanks

**Comment by xfloh22** [comment]
still get this error: http://pastebin.com/fVQAi7Rf

oh ok, will try Haos' fix now

**Comment by HaoSs07** [comment]
yah, remove chickenchunk from mods and patched mods, delete the forcedchunks, reboot, you will probably get a error, reboot again, and it sould work

**Comment by LunNova** [comment]
@HaoSs07 Can you try latest again? Probably a spammy log, hopefully no crashing. Report the log spam if there is any.

**Comment by HaoSs07** [comment]
sure thing; on it

**Comment by xfloh22** [comment]
it keeps creating a new forcedchucks.dat even when chickenchunks is removed

**Comment by HaoSs07** [comment]
hmm; you removed from mods and patched mods too right ? try a tt repatch after,

**Comment by LunNova** [comment]
It should create a new one. If that error still happens, check you didn't leave an old forcedchunks.dat in another world.

**Comment by xfloh22** [comment]
well i ran a script over it and i had the file 10 times... not sure where but they are gone now :p

worked :D you guys are awesome!

**Comment by HaoSs07** [comment]
in every folder called dim_Number is one, that includes world,twilighy,end,mystcraft ages, etc

so far so good nallar, no errors, will test a little more,

**Comment by HaoSs07** [comment]
seems to be ok, hers some of the spammy log https://gist.github.com/HaoSs07/5383537

**Comment by HaoSs07** [comment]
as a side note, this fix seems to brake applied energetics storage, im losing disk data often

**Comment by xfloh22** [comment]
can config extremely spammy log. one of those errors every tick.

nvm, seems to only happen when i generate new chunks...

**Comment by HaoSs07** [comment]
the spammy was added by nallar for some debug , im sure will be removed in the next build

**Comment by xfloh22** [comment]
ik, just saying i got it as well :)

**Comment by LunNova** [comment]
Can you run `/ticks b` after updating to latest? Related to what caused this issue.

**Comment by HaoSs07** [comment]
will do

**Comment by HaoSs07** [comment]
sory, i was tired last time and posted another command; here is the ticks b

04-18 12:31:29 [INFO] [TickThreading]
116 pending block updates
Block | Count
1119tile.rc.block.worldlogic | 60
1434tile.world.blocks.aesthetic.sulfurTorch | 29
66tile.water | 15
71tile.gravel | 9
68tile.lava | 3

i will let you close this when you think is done

**Comment by LunNova** [comment]
116 pending updates is far better than before, you had over 5000. Seems fixed.
