### ISSUE TITLE
Build #1291-kicked  from server and can't rejoin 

### ISSUE THREAD

**Issue by Kusinagie** [MinimallyCorrect/TickThreading#302]
I was setting up to do that profile snapshot for you. breaking the chunkloader, leaving the dimension till it unloads then returning seems to be the trick in getting all the pumps to drop down till they hit lava, then the load jumps up in that 200 area. then placing the chunkloader again i was kicked from the server and couldn't join till i restarted the server.
Here's the server log: https://gist.github.com/Kusinagie/5382536

**Comment by LunNova** [comment]
World loading/unloading issue which was fixed in the recent world unload/load redesign.
