### ISSUE TITLE
TT 1301 (and 1283): getChunkAt returns chunks during/before population

### ISSUE THREAD

**Issue by MrScopi** [MinimallyCorrect/TickThreading#303]
I'm currently generating and exploring Mystcraft ages and noticed a repeating problem.  While exploring for Libraries, I'll usually find what appears to be a partial library.  Trying to move to where the Library should be (i.e. through the walls) results in getting "stuck" and kicked backwards.  Disconnecting and reconnecting will show the full library, usually where I was getting stuck.

I have seen this issue with trees, Libraries, Thaumcraft hills, and obelisks.  Basically anything that isn't strictly terrain.

I don't know if this is a problem explicitly with TT+Mystcraft, or TT+new chunks.  But my guess would be that Mystcraft might be playing with structure placement in a way different from normal world generation.

Attached are pictures from an age where I collided with a Thaumcraft hill, before and after.
![2013-04-14_16 06 51](https://f.cloud.github.com/assets/4146337/378585/bd6fb4aa-a549-11e2-8c92-537ef5f2ddc2.png)
![2013-04-14_16 07 05](https://f.cloud.github.com/assets/4146337/378586/bd7bc952-a549-11e2-87d3-988e4d6c57e4.png)

Again, logging off/on will fix the issue, so it's not a permanent problem.  And after reloading, these chunks will not have errors again -- it's only on the first pass generation.

Thanks again.

**Comment by Puremin0rez** [comment]
@nallar @MrScopi 

I can't believe I never reported this.

I am having this problem in the Overworld too.

I'm using MCPC+ with TT 1291 but the problem has been happening since I got back into FTB.

Chunks when generating are "stripped" and relogging will fix the issue until new chunks are once again generated.

**Comment by ghost** [comment]
I've also experienced this issue on nearly every world I touch, seen it on multiple servers. Could be flying or walking, exploring is extremely difficult as you often run into invisible trees and stuff. If server TPS is aiming for 20, /tps will show 20 tps, if it's aiming for 15, it'll show 15 tps. These screenshots are from a 20 tps server.

It can take up to 10mins for the map to literally rearrange itself in front of you to how it's suppose to be (before and almost after):
![2013-04-15_09 36 06](https://f.cloud.github.com/assets/4166113/383967/1685ea36-a631-11e2-9036-8e5ce58458a0.png)
![2013-04-15_09 36 56](https://f.cloud.github.com/assets/4166113/383968/1b2ac5b6-a631-11e2-90d0-e6f8a4f90dd8.png)
Relogging does fix this, however I often notice some of the blocks that were hovering such as leaf blocks will no longer be present and saplings/apples will litter the area.

I've tried to remove mods such as ChickenChunks to see if there was some form of conflict etc to no effect;
MCPC+ Legacy (14)
Tickthreading 1308 - Guava 12.0.1
FTB - Mindcrack 8.2.0

**Comment by alicheek** [comment]
This is a Xycraft problem as soon as i removed it i had no world loading issues

**Comment by MrScopi** [comment]
I'm running a version of ftb lite that does not include xycraft, so for me
that probably isn't a problem. But the mods I've added, like mystcraft,
came from the ftb ultimate server files.

**Comment by ghost** [comment]
@alicheek 
I had tried removing Xycraft before, this again, didn't change a thing.

**Comment by alicheek** [comment]
hmm i also do have mystcraft removed maybe that has something to do with it , might be something to do with myscraft not working with TT then sorry guys thought it was xycraft that was the issue :)

**Comment by MrScopi** [comment]
No problem this is troubleshooting.

**Comment by ghost** [comment]
Just a note: FTB - Mindcrack doesn't have Mystcraft bundled with it.

**Comment by MrScopi** [comment]
I'm running FTB Lite with the following added from Ultimate:
BiblioCraft
EnderStorage
ExtraBees
ExtraBiomes
Factorization
Mystcraft
ThaumicBees
TwilightForest

**Comment by Puremin0rez** [comment]
This appears to stem directly from TT

I ran a 100% vanilla forge server and did not have the issues in terrain gen, then added TT and the stripping issues began.

Hope @nallar can figure it out :)

**Comment by LunNova** [comment]
And now we know what was causing saplings to drop when they shouldn't. Thanks for the observation @Draylynn.

Chunks were being returned by getChunkAt during population in some cases, leading to this.

**Comment by Puremin0rez** [comment]
@nallar 

Just thought I'd let you know that it's still happening for me

**Comment by LunNova** [comment]
If you run `/ticks r 2` while in a broken chunk, is it fixed?

**Comment by ghost** [comment]
Can't seem to get the map up at all now. User error or?
`/ticks r 2` - Refreshed 4 chunks - character was still floating with 4 floating chickens.

`04-18 21:40:39 [SEVERE] [ForgeModLoader] Exception loading chunk asynchronously.
java.lang.NoSuchMethodError: zx.clone_()Lzx;
    at zz.refreshExtendedBlockStorage(Chunk.java:226)
    at im.a(ThreadedChunkProvider.java:621)
    at zz.a(Chunk.java:1303)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:506)
    at im.getChunkAt(ThreadedChunkProvider.java:400)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:739)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
04-18 21:40:39 [SEVERE] [TickThreading] Exception ticking world Overworld/0`

`[WARNING] [TickThreading] Null chunk at [75, 104] when trying to send chunks to iq['Draylynn'/12, l='world', x=1316.50, y=90.74, z=1689.50](Draylynn at 1316.5,90.73799998760221,1689.5)`

MCPC+ Legacy  Build: 15 
Mindcrack 8.0.2
TickThreading #1347

**Comment by LunNova** [comment]
Oops, try 1348.

**Comment by LunNova** [comment]
Urgh, mcp changes the return type too for some reason, try 1354.

**Comment by ghost** [comment]
Overworld is a lot better, still some weird chunk loading - before and client relog:
![2013-04-18_22 57 44](https://f.cloud.github.com/assets/4166113/399493/d696090c-a873-11e2-91a3-8848822980d3.png)
![2013-04-18_22 58 01](https://f.cloud.github.com/assets/4166113/399494/d832716a-a873-11e2-8e8a-d05befbe307d.png)
Instead of entire sections of map rearranging, it appears to be the odd structure (tree's for example), 'materializing'. It's explorable!

Alternate dimensions such as Twilight are still stripped;
![2013-04-18_23 00 31](https://f.cloud.github.com/assets/4166113/399507/3c4f0f6e-a874-11e2-9bec-543fe6b4d06d.png)
However Twilight Forest was throwing an exception;
`04-18 23:00:16 [SEVERE] [TickThreading] Exception ticking world Twilight Forest/7
java.lang.NullPointerException
    at codechicken.xycraftcopy.core.world.WorldExtensionManager.preTick(WorldExtensionManager.java:242)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager.access$400(WorldExtensionManager.java:25)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionServerTickHandler.tickStart(WorldExtensionManager.java:157)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:59)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:296)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:432)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:547)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)`

After removing Xycraft/ChickenChunks the results are similar to the overworld.
`/ticks r 2` Refreshed 4 chunks, everytime, no visible changes.
