### ISSUE TITLE
TT#1306 GregTech - IDSU keeps reseting 

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#304]
I noticed since installing the mod our IDSU's (Interdimensional Energy Storage Unit) keep randomly going back to 0 eu and not holding it's charge as well it appears it also resets to 0 on server restart. 

![2013-04-14_16 48 47](https://f.cloud.github.com/assets/4019875/378620/3c16d006-a54d-11e2-9a54-184b8b061b2b.png)
![2013-04-14_16 48 58](https://f.cloud.github.com/assets/4019875/378621/3db05b94-a54d-11e2-821c-9e8e9ef3c1ea.png)

**Comment by Nohau** [comment]
Like to add that this is not new it was doing it on 1278 as well but just now started to get to the point to verify it was doing this and not me going crazy :)

**Comment by Nohau** [comment]
Also to note we have multiple IDSU's all linked to the same person and we are using chunkloaders to keep them loaded just in case that was the issue and still we get the problem.

**Comment by SuddenTurmoil** [comment]
Just chiming in to say that this is happening on my server as well. Players report that it seems like the IDSU has a pseudo cap at 2M EU at which point the IDSU will reset to 0. It may not have anything to do with the actual amount of EU and probability just dictates it very rarely makes it past 2M EU. Also, two of my players have witnessed it reset while they had its GUI open so it specifically getting unloaded shouldn't be the issue.

**Comment by Nohau** [comment]
i seen it goto 30-40 mil and reset right in front of me as well.
