### ISSUE TITLE
Empty XyCraft tanks on reload, java.lang.NullPointerException   at codechicken.chunkloader.TileChunkLoaderBase.g(TileChunkLoaderBase.java:147)

### ISSUE THREAD

**Issue by geoffcorey** [MinimallyCorrect/TickThreading#305]
Loaded up 1308 and all the xycraft tanks became empty.  Also get a whole lot of these errors in the TickThreading logs.

04-14 22:02:04 [SEVERE] [TickThreading] TickThreading v1.0.0.1308 for MC1.4.7 on 1.4.7 tickthreading,forge,fml is installed on this server!
If anything breaks, check if it is still broken without TickThreading
We don't want to annoy mod devs with issue reports caused by TickThreading.
Seriously, please don't.
If it's only broken with TickThreading, report it at http://github.com/nallar/TickThreading
04-14 22:06:29 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c codechicken.chunkloader.TileChunkLoader codechicken.chunkloader.TileChunkLoader@5171ea7e x,y,z: 660, 79, -637 at x,y,z:660,79,-637
Tick region: rX: 41, rZ: -39, hashCode: -2555863:
java.lang.NullPointerException
  at codechicken.chunkloader.TileChunkLoaderBase.g(TileChunkLoaderBase.java:147)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

Mods listing + TickThreading.log + patcher.log at

https://gist.github.com/geoffcorey/9366855a21d4cdfa123d

**Comment by geoffcorey** [comment]
Follow up on this xycraft bug.   If I use a linking book to go to another world and then come back my xycraft tank is empty.  When i rehook up the liquidduct (no longer attached after I leave for another world) it becomes a xycraft tank again but the contents are lost

**Comment by geoffcorey** [comment]
14.04 22:27:12 [Server] INFO Sending serverside check to: dtherrien
14.04 22:27:12 [Server] INFO [dtherrien: De-opped dtherrien]
14.04 22:23:47 [Server] INFO Loading chunk 309237645254: 71,-58 while saving is in progress.
14.04 22:22:40 [Server] INFO ... 8 more
14.04 22:22:40 [Server] INFO at aev.a(SourceFile:33)
14.04 22:22:40 [Server] INFO at afc.b(SourceFile:66)
14.04 22:22:40 [Server] INFO at afd.<init>(SourceFile:93)
14.04 22:22:40 [Server] INFO at afq.a(SourceFile:516)
14.04 22:22:40 [Server] INFO at afs.a(ComponentVillage.java:37)
14.04 22:22:40 [Server] INFO at afe.a(StructureVillagePieces.java:249)
14.04 22:22:40 [Server] INFO at afe.d(StructureVillagePieces.java:193)
14.04 22:22:40 [Server] INFO at zd.a(WorldChunkManager.java:217)
14.04 22:22:40 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
14.04 22:22:40 [Server] INFO at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
14.04 22:22:40 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
14.04 22:22:40 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
14.04 22:22:40 [Server] INFO at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:715)
14.04 22:22:40 [Server] INFO at im.getChunkAt(ThreadedChunkProvider.java:328)
14.04 22:22:40 [Server] INFO at im.getChunkAt(ThreadedChunkProvider.java:464)
14.04 22:22:40 [Server] INFO at abb.e(ChunkProviderGenerate.java:667)
14.04 22:22:40 [Server] INFO at aaz.a(SourceFile:29)
14.04 22:22:40 [Server] INFO at aev.a(SourceFile:60)
14.04 22:22:40 [Server] INFO t: Exception preparing structure feature
14.04 22:22:40 [Server] SEVERE Exception loading chunk asynchronously.

**Comment by geoffcorey** [comment]
Followup testing on this.   When I logged off and logged back in the tank was no longer a tank until I hooked it back up to liquiducts and it lost all the contents.  I checked with lasers from the chunk loader and it was missing the corner of the xycraft tank.   I increased the range on the chunk loader and logged off and logged back it and remained a tank with contents still there.

I'm guess that partial unloading of the tank in a different chunk cause the error.

**Comment by geoffcorey** [comment]
One good news on the update?  My mining age is no longer unstable! :-)

**Comment by geoffcorey** [comment]
Checking Xycraft issue log now that I found it I see it has numerous issues. Including https://bitbucket.org/Soaryn/xycraft/issue/231/xycraft-tank-deletes-liquid-level

**Comment by GTB3NW** [comment]
Having same issue as described, when TT is installed the xycraft tanks seem to delete liquid levels. B1343
