### ISSUE TITLE
Build #1308 - SecretRooms mod crash

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#307]
Started happening recently

http://pastebin.com/gpVWchX3

Happens immediately after server start - requires a few reboots until it doesn't come up and kill the server.

**Comment by LunNova** [comment]
This is a known SecretRooms mod issue, it normally just causes a chunk reset. I'll change it so any tile entities which fail to validate on chunk load are deleted, instead of crashing the server.
