### ISSUE TITLE
Build #1308 - Xycraft problems in Twilight Forest

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#313]
http://pastebin.com/f6mJXX8W

**Comment by LunNova** [comment]
Does this stop happening if world unloading is disabled?

**Comment by Puremin0rez** [comment]
@nallar 

I'm not sure - Haven't gotten the error again since.

**Comment by LunNova** [comment]
I've added a lot of code for ensuring world load/unload events are fired correctly and that world lists are kept in sync, and for logging if this fails. This should now be fixed.
