### ISSUE TITLE
Build #1332 - Memory Leak?

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#321]
I installed one of the recent versions and notice my ram just keeps going up and up and up and never going down, eventually it will die off with heap size failure.

Don't really have any more information then that...

**Comment by LunNova** [comment]
Won't be able to investigate this until tomorrow, sorry :(

**Comment by Puremin0rez** [comment]
@nallar 

Okay, I'm rolling back to #1315 (yesterdays build) which I'm pretty sure did not have the issue. I think something changed with chunks today that caused things to go wrong.

Problem is, i got a linked blocking error on that that's fixed on the new one - so I think I'm going to crash either way :(

**Comment by LunNova** [comment]
If you can find the exact build number or commit in the next 6.5 hours I
can probably fix it in the morning before I leave for school.

**Comment by Puremin0rez** [comment]
@nallar 

Additional Information

Still a problem on #1336

Does NOT appear to happen on #1315

I really want to say its the commit that did "Allow chunks to unload while world saving is disabled." or "Clean up ThreadedChunkProvider, don't return chunks before population"

Basically, i feel like the loading of chunks is being put into ram and never being "released" - The JVM Memory increases and never goes down when people load chunks. Maybe related to Chunk Caching? No idea.

Also, issuing "save-all" on the new builds makes memory SUPER increase.

**Comment by Puremin0rez** [comment]
@nallar

I appear to have fixed it!

I'm about an hour and a half into a fresh boot with #1336 and seeing very very low (normal) ram usages - the JVM heap is actually decreasing properly now too.

How did I fix it? Well, somewhere along the lines my config file must have reset and turned "loadChunkOnProvideRequest" back on - Guess what? This option appears to cause memory leaking!

As soon as I turned it off and rebooted the server, memory now appears to be looking very normal.

15 people online with 800MB in memory being used - before with that option on, we were already at like 5gb used with 13 people on. Made no sense at all, considering only 2000 chunks were loaded (or so)

Not sure if "save-all" is still messed up, really don't want to try right now since I have angry players from the LinkedQueue crash last night and the memory leaks today.

**Comment by Puremin0rez** [comment]
Just further confirming that turning "loadChunkOnProvideRequest" to false has fixed all memory issues.

No idea what's up there, but yeah.

**Comment by Nohau** [comment]
Hmm I really want to upgrade to the latest version but I do utilize this option for BukkitForge because every time I tried FTB Ultimate with MCPC+ our quarries don't work after server restart half the time.

**Comment by Nohau** [comment]
I am running 1343 now will watch memory usage.

**Comment by Puremin0rez** [comment]
Yeah, left that option off all night and the memory stayed below 2gb.

I turned it on for the hell of it on 1343 and once again memory ran out within an hours time.

**Comment by Puremin0rez** [comment]
@nallar has now defaulted the setting to off so if you have it on you might want to reconsider it.

Having it off has fixed all of my lag spikes and of course, running out of memory within an hours time. I've been able to run for almost 48 hours straight with zero issues whatsoever.

Scary option.

**Comment by Nohau** [comment]
Yea but it fix's https://github.com/nallar/TickThreading/issues/293 and Every Time I have tried MCPC+ with FTB Ultimate the quarries don't work after server restart.

**Comment by Puremin0rez** [comment]
@Nohau 

Yes your correct, having that option on is REQUIRED for quarries to work through server reboots. Maybe @nallar can change that?

**Comment by Puremin0rez** [comment]
Made both issues separate tickets and closing this one

https://github.com/nallar/TickThreading/issues/338
https://github.com/nallar/TickThreading/issues/339
