### ISSUE TITLE
Mobs instantly Despawn

### ISSUE THREAD

**Issue by NachtRaben** [MinimallyCorrect/TickThreading#322]
So mobs are instantly despawning on my server. i can't really figure out why. there are no errors or anything. Mobs worked for the first 24 hours i was running build #1315
Mcpc+ legacy 15
mods: Dynmap forge 1.5, barrels, bibliocraft, buildcraft, chickenchunks, coFH core, Computercraft 1.5, Damage Indicators, DivineRPG 1.3.0.4, extrabeez, forestry, logisticspipes, iron chest, miscperipherals 3.1c, obsidiplates, omnitools, soulshards 1.26, steves carts, thaumcraft, thermal expansion, tickthreading 1315, xreliquarry.

plugins: DynmapCBBridge, Dynmap essentials, Dynmap griefprevention, essentials, essentials spawn, grief prevention, herochat, permissions ex, remote bukkit, secretswitch, silkspawners, torch command, treeassist, vault, wireless redstone.

Link to my TT config: http://pastebin.com/GWASXQHr

any help would be greateful nallar, love this mod. 
if needed i can post the loggs too, but like i said there are no errors or exceptions at all in them.

Noted: at 100fps i can notice non passive mobs (Divinerpg crabs) spawning but instantly despawning in less than half a second

Noted: Some areas there is an overabundance of hostile vanilla mobs and there are some where here are literally none.

![Untitled](https://f.cloud.github.com/assets/4164436/389354/22bde2c2-a703-11e2-9da8-0e0bd244c9a1.png)
**running /profile r**
![Untitled2](https://f.cloud.github.com/assets/4164436/389459/16c9d91a-a70a-11e2-8101-17991ffd8b7d.png)
**area with no mobs and a 22 entity count (all passive)**
![Untitled3](https://f.cloud.github.com/assets/4164436/389460/16d716a2-a70a-11e2-8bd4-954b3bdf585d.png)
**area with 80 entity count and hostiles spawning**

**Comment by Puremin0rez** [comment]
Same issue and I know exactly why :P

See how your in creative mode? For some reason, mobs refuse to spawn when you are in creative mode. Strange issue? Yes it is.

Try it yourself - grab some spawn eggs and spawn some while in creative mode, they will despawn instantly. Switch to survival, try again - they shouldn't despawn now.

Literally do not know why it does it, but I don't find it a huge deal since its only in creative mode.

I am running MCPC+ and TT aswell, might be an issue with that.

**Comment by NachtRaben** [comment]
Sadly, Perfect answer. i went up later to build a quarry in that plains biome and got owned by several divinerpg king crabs xD i guess TT confuses bukkit into thinking a creative mode player isn't acctually a player and has the chunk stay in some sort of sleep mode? lol
