### ISSUE TITLE
Build 1336 RuntimeException: Already decorating

### ISSUE THREAD

**Issue by Kusinagie** [MinimallyCorrect/TickThreading#323]
Well there is a couple here. 
Note: allow world unload is false if that makes any difference to you.
(-The Inconsistent state i believe has to do with a chest i had picked up and moved with a portal gun
-The buildcraft error is the same as the one i posted about before (316)
-I believe i saw this Exception ticking world as an issue here somewhere but cant find it )

And then the error that kicked me from the server
(apparently i can't decorate if I'm already decorating,i know I'm bad at multitasking....bad joke i know its late for me here ha ha.)
Here's a TT log
https://gist.github.com/Kusinagie/5402360
And here is the server log...which is quite long unlike my attention span when I'm 
decorat okay i'll stop
server log
https://gist.github.com/Kusinagie/5402364
And i managed to log in long enough to grab a shot of this to before i was booted again:
![2013-04-17_02 47 14](https://f.cloud.github.com/assets/4134724/390063/27521ae6-a731-11e2-9b9c-607a130eee75.png)
And for future reference if i have a few different errors should i make separate issues for them or is it easier for you if i just report them with one log like this?

**Comment by LunNova** [comment]
Fixed via 9722f5c47f32a0ea. Make separate issues.
