### ISSUE TITLE
TT#1343 - Portal Gun Spam

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#330]
[SEVERE] The mod PortalGun attempted to force load a chunk with an invalid ticket. This is not permitted.
7:15:52 PM
 CONSOLE:
[SEVERE] The mod PortalGun attempted to force load a chunk with an invalid ticket. This is not permitted.

Nothing in TT Log

04-17 19:09:38 [INFO] [TickThreading] iq['Pillowghost47'/1947, l='world', x=6689.53, y=29.92, z=2265.08] changed dimension from Twilight Forest/7 to Overworld/0
04-17 19:18:19 [WARNING] [TickThreading] Admin notify: hayden88 moved wrongly!

Forge Log : 

https://gist.github.com/Nohau/5408867

**Comment by Puremin0rez** [comment]
I've been getting this issue too +1

**Comment by LunNova** [comment]
I think this just happens if the mod goes over its allowed chunk loading
limit. Can you try raising it?

**Comment by Puremin0rez** [comment]
I raised it and still seem to be getting it when people shoot portals >_>

I also notice they're not keeping chunks loaded

**Comment by LunNova** [comment]
Portal gun isn't releasing its tickets then :( I'll try to fix that when
back from school.

**Comment by LunNova** [comment]
The changes for quarries should also fix this.

**Comment by LunNova** [comment]
Is that fix confirmed working?

**Comment by cjm721** [comment]
Noticed this happens when I try to shoot the moon. Could it be trying to send a ticket to keep a chunk loaded that is not loaded?

**Comment by LunNova** [comment]
Anyone able to confirm that this doesn't happen in vanilla when shooting the moon?

**Comment by cjm721** [comment]
When I was still running one server with TT and one server without I never saw invalid ticket on the one without. Forge has updated quite a bit also have not seen this in a while so I will try and see if I can replicate it again and post how.

**Comment by LunNova** [comment]
Assuming this is fixed as had no confirmation in a month that it's still happening, after a related fix.
