### ISSUE TITLE
TT#1343 Server in constant restart

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#332]
Logs : https://gist.github.com/Nohau/5409054

Got the codechicekn chunk load errors then just started doing this.

Thanks

**Comment by Nohau** [comment]
More background user created a mystcraft age and Named it VOID ...

**Comment by Nohau** [comment]
Renamed users age then deleted the age and changed his dat file to come back to overworld ... server became stable.

User logged off in this age so every time he was getting on it was restarting shortly after.

**Comment by LunNova** [comment]
Is that the right log? It looks like BukkitForge stopped the server... https://gist.github.com/Nohau/5409054#file-forgemodloader-server-1-log-L5532

**Comment by Nohau** [comment]
Yep that is the right log so something might caught the keyword VOID and was just causing restarts Only other thing I can think of could be McMyAdmin thinking that was a severe error and it is set to restart on severe error..
