### ISSUE TITLE
Concurrent Network Ticks?

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#333]
Just how buggy is it now?

Last time I tried it was a good 3+ months ago and chunks failed to load.

Is it any better now? What kind of incompatibilities are there?

**Comment by LunNova** [comment]
Haven't done much work on this. Anyone else tested it recently and know how
badly it breaks?

**Comment by Puremin0rez** [comment]
https://github.com/nallar/TickThreading/issues/337
