### ISSUE TITLE
Build #1356 - "loadChunkOnProvideRequest" being set to true introduces a Memory Leak?

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#339]
You can view more information about this here:
https://github.com/nallar/TickThreading/issues/321

I can verify this multiple times over if more testing is needed.

It almost appears as if chunks do not unload for some reason. Ram just goes up and up and up and never goes down.

Yes, I am checking the actual JVM.

**Comment by Puremin0rez** [comment]
Also keep in mind it might be a mod in the FTB Ultimate pack introducing this issue or even MCPC+ itself.

I am not blaming TT but I will say it only happens with this option enabled :)

**Comment by LunNova** [comment]
I'll need a heap dump. Does the chunks count in `/tps` still seem okay?

**Comment by Puremin0rez** [comment]
@nallar 

Yes the chunk count appears to be perfectly normal, I was thinking maybe Cache or something was related.

I'll hopefully be able to do another test run soon, not going to upset my players for the moment. I can't reproduce locally so my server is the only thing I'm able to test on.

This particular issue does not bother me (as I've had it set to false since I found this out), but I know it is required for things like quarries to work between restarts so people having this option set to true might be suffering.

**Comment by Puremin0rez** [comment]
I'm thinking this option and the generateChunk one should possibly be removed from configuration once the issues are worked out with both being disabled. (see my other issue for the issue with generateChunk)

To be honest they're the most vague options in TT but appear to do a world of harm when configured incorrectly.

**Comment by Puremin0rez** [comment]
Well now that all of my issues with them being set to false are fixed, this issue no longer really bothers me :P
