### ISSUE TITLE
Deadlock problems again, ( 2 deadlocks under 30 minutes )

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#345]
https://gist.github.com/HaoSs07/5423070
https://gist.github.com/HaoSs07/5423062

**Comment by xfloh22** [comment]
can confirm errors

**Comment by LunNova** [comment]
First issue looks like an explosion took too long - see https://gist.github.com/HaoSs07/5423070#file-gistfile1-txt-L1463 . Try increasing the deadlock detector time.

Second issue looks like it's stuck processing ForgeEssentials `/top` command. Not sure why.

**Comment by HaoSs07** [comment]
deadlock is at 90 seconds, hopefully the first one will not repeat 

as for the /top, probably bug with FE, i used /top and i got teleported in a wall above 256 hight limit ( was in end )
