### ISSUE TITLE
GriefPrevention protections broken

### ISSUE THREAD

**Issue by LunNova** [MinimallyCorrect/TickThreading#348]

**Comment by KunJakob** [comment]
I had this issue last night the latest build. Not finding anything in the logs. Full TT log: http://pastebin.com/zs5GFCsM

**Comment by LunNova** [comment]
This might only happen if world unloading is enabled, griefprevention can't handle world unloading properly.

**Comment by KunJakob** [comment]
Cool! What am i gonna miss out on by disabling world unloading?

**Comment by LunNova** [comment]
It'll prevent the end/nether/forge mod worlds from unloading.

**Comment by joey19982** [comment]
Apparently this is fixed in the 1.5 version of GriefPrevention. I submitted a ticket a while ago when I first reported the issue here.

http://dev.bukkit.org/server-mods/grief-prevention/tickets/54-me-ryanhamshire-grief-prevention-block-event-handler/

**Comment by LunNova** [comment]
Closing this as invalid, as there is a workaround (now also in the wiki) and it's caused by a GriefPrevention bug.
