### ISSUE TITLE
TT #136 Console spam of "[WARNING] MultiBlock already removed: [Random # here] server

### ISSUE THREAD

**Issue by Cyteq** [MinimallyCorrect/TickThreading#356]
Example of what is going on http://i.imgur.com/lQbKJwv.png

Also there was this same issue back in #292 that said it had been fixed.

**Comment by LunNova** [comment]
Which build is this on?

**Comment by Cyteq** [comment]
Sorry messed up the title it is on TT 1361

**Comment by LunNova** [comment]
That was fixed in 1365.
