### ISSUE TITLE
Build 1368 - World Anchors not working in other dimensions properly?

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#359]
For some reason, World Anchors appear to not work in other dimensions (such as the Nether) properly when there is not a single player in the dimension.

The chunks are being loaded, but they are not "working" unless there is at least one person in the dimension of the chunk loader.

This hasn't always happened, so i'm not sure why it's started to act up.

**Comment by LunNova** [comment]
Does `/tps` show the expected tile entity count in that world?

**Comment by xfloh22** [comment]
your changes fixed it for me. closed?

**Comment by Puremin0rez** [comment]
Appears to be fixed, i'll leave this here for a few hours more since I just only switched to the new build.

**Comment by Puremin0rez** [comment]
@nallar 

Nope, not fixed.

Peoples World Anchors refuse to work unless there is at least one person in the world (Nether)

They can be anywhere in the world and it will make all of them work. Soon as the single person leaves, all of them stop working.

In particular, the situation I'm describing is using lava pumps next to a World Anchor.

**Comment by Puremin0rez** [comment]
https://github.com/nallar/TickThreading/issues/364

**Comment by Puremin0rez** [comment]
Definitely fixed now :)
