### ISSUE TITLE
Build 1393 "Moved too quickly!" cheat detection

### ISSUE THREAD

**Issue by G1itcher** [MinimallyCorrect/TickThreading#361]
After installing TickThreading, the "xxxx Moved too Quickly!" message pops up when using at least one legitimate means of moving quickly via a mod pack (portal mod faith plates). This did no happen before installing TickThreading. It also teleports the player back to where they were before the incident. Turning off antiCheatNotify stops the messages, but not the teleporting.

Server is set to allow flying.

**Comment by HaoSs07** [comment]
never had this problem and using TT for a long time, try a fresh install ?

**Comment by Puremin0rez** [comment]
I have the same issue, actually.

The portal gun faith plates throw the moved too quickly error so they're unusable.

**Comment by HaoSs07** [comment]
have you tested with TT off ? i had this problem on old bukkit server, and
it was a config related thing

**Comment by G1itcher** [comment]
As per the original post; does not happen on the server without TickThreading installed. Bukkit is not installed on this server, it is Forge only.

**Comment by LunNova** [comment]
I cleaned up the movement update handling code today, this might be fixed now.

**Comment by BHare1985** [comment]
I have this same problem using TickThreading-1.4.7-1.0.0.1715.jar using Feed the beast ultimate. It especially tells me it when I use a /home command. I get really strange behavior -- here is a video showcasing the weirdness: http://youtu.be/sMG1KX7FZTg  - I am using client and server FTB ultimate 1.0.1 with a linux server

**Comment by LunNova** [comment]
Having the world unload under you as well isn't quite the same problem! :P

Can you paste the patcher log? Also, if possible could you get a sampling snapshot of the server using jvisualvm?

See the instructions [in the comments of issue #515](https://github.com/nallar/TickThreading/issues/515]), and run the sampler while doing similar stuff to what you did in the video.

**Comment by BHare1985** [comment]
Here is the patcher log: http://pastebin.com/raw.php?i=UW9SrAB4 . I might be upgrading the server to the new ultimate 1.1.2 soon and suppose ill need to repatch.

As far as jvisualvm I download the java SDK for my system and I got it to run, on the server I am running the follow command from my sh file:

java -Dcom.sun.management.jmxremote.port=3333 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -XX:UseSSE=4 -XX:+UseCMSCompactAtFullCollection -XX:ParallelGCThreads=4 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+DisableExplicitGC -XX:+CMSIncrementalMode -XX:+CMSIncrementalPacing -XX:+UseCompressedOops -XX:+AggressiveOpts -Xms3G -Xmx4G -jar FTB-Beta-A.jar

but it failed to connect to my server with port 3333. The server address is kniloc.com which points to 193.183.98.29. I am trying to connect to 193.183.98.29:3333 on my local machine. Does the server need java SDK as well? The linux vps has no firewall that would prevent it.

**Comment by BHare1985** [comment]
Update: I got it going by installing the sun-sdk (since I installed sun-jre over the open jre). Jstatd wouldnt open for me but following http://www.codefactorycr.com/java-visualvm-to-profile-a-remote-server.html helped.

Will post in a few

**Comment by BHare1985** [comment]
Here are 2 snapshots, at first I was running the server right from the sh file without McMyAdmin and it was very snappy much more so than the previous video with no weird hangups but still with moving too quickly messages. So I decided to try again with McMyAdmin while keep everything the same and I guess last night was a fluke with the hangup and extreme lag. Nothing has been added or changed since then.

Here are the two snapshots: http://db.tt/pf4EGhYU

**Comment by BHare1985** [comment]
I also took video of each snapshot to get an idea of the weird things it was doing this time. It seems when I am far away from home, and then teleport back to home the chunks surrounding home have unloaded and need to reload, but they seem to load very slowly. Oddly though, all the chunks not close to home are still loaded (in all directions). I would chalk it up to slow server, which could be be part of the case but the server loads chunks way faster when going to new locations than what is shown in the video.

http://youtu.be/yprnqiK1O6I

http://youtu.be/VovOypP2FBs

**Comment by LunNova** [comment]
Sorry for the lack of response, been busy recently. Made more changes to movement updates in latest, can you check if it's still broken?

**Comment by darkdeath1332** [comment]
Still broken with latest version. When I do a teleportation over a long distance its bugging me trough both places for a while.

**Comment by LunNova** [comment]
Still broken, but can be worked around by disabling concurrentMovementUpdates in the config.
