### ISSUE TITLE
Build 1393 Multiple users based far away from each other causes mob spawning to not work correctly

### ISSUE THREAD

**Issue by G1itcher** [MinimallyCorrect/TickThreading#362]
In this example, if a user is at X: 25100, Z:241, users at X:227, Z:-2629 do not experience mob spawning correctly; the chunks in that area act as though the server is set to peaceful (hostile mobs despawn, friendly mobs do not)

If the person at X: 25100, Z:241 disconnects or teleports to the other users, mob spawning at X:227, Z:-2629 begins to function again.

This seems to occur whether or not the enableFastMobSpawning is enabled or not.

**Comment by Puremin0rez** [comment]
Are you sure the player in the area where mobs despawn is not in creative mode?

I have an issue where whenever I'm in creative mode, all mobs despawn around the region and do not spawn.

**Comment by G1itcher** [comment]
Aha, got it in one. Seems if we turn off creative things spawn again. Thanks for that.

**Comment by maezred** [comment]
We're having a similar issue, but my testing does not link it to players being very far away or to creative mode (which would be perfectly fine, as we are a survival only server). I can't get mobs to spawn beyond shortly after server start. I haven't been able to do much testing beyond by myself for now, but at the moment, mobs spawn when I connect for the first time after server start, but then as soon as they all die or despawn, no more spawn ever; this seems to include squids (as they do not persist). I should also note that fast mob spawning makes the issue slightly worse (mobs spawn much less on my first connection).

We're running build #1412 on MCPC+ L15, FTB Ultimate.

I can break this into a separate issue if needed.

**Comment by LunNova** [comment]
Are you using fast spawning, or default spawning? Try whichever one you're
not using.

**Comment by G1itcher** [comment]
For us it happens regardless of that setting.

**Comment by maezred** [comment]
I edited it in, but I don't know if you spotted it: yes, I've tried both settings. We spent all night trying to get mobs to spawn. The only thing that really band-aided it was setting the spawn-limits per player to a very high (10k+) value which would let people play with mobs for a few hours, but would ultimately lead to out of memory, if we let it run like that, of course.

**Comment by maezred** [comment]
After leaving the server up for about 24 hours now, mobs are spawning correctly for everyone but only when select players are online. We're still trying to determine if it has to do with being op, ever (not currently) being in creative mode while the server was running, a plugin, or a mod. But they are not spawning correctly even if everyone is in survival mode. A side note, creepers are not doing block damage when they do happen to spawn.

**Comment by maezred** [comment]
We restarted the server with no plugins, and I have a slight correction to my previous statement, mobs spawn in very sparse quantities for everyone else when a player that has mobs spawning correctly is online, but mobs do spawn correctly for that one player. We're still running build 1412, and we'll update TickThreading tonight when you're all done tweaking it for the day for more testing. As always, good work; our server would have never worked without your amazing plugin, nallar. :)

**Comment by maezred** [comment]
We decided to stick with 1412 for a while and just enjoy the peacefulness (sans the occasional player that signed on screaming, "I bring the death!"). We just bumped to TT 1516, and mob spawning appears to be working as intended again. Spent a few hours flying around (in survival) from -16,000x-16,000 to 8,000x8,000; and mobs continually spawn without issue.
