### ISSUE TITLE
#1404 internal server error

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#363]
Right clicking/placing block in world will disconnect players

https://gist.github.com/HaoSs07/5430358

**Comment by HaoSs07** [comment]
also there are allot of exception related to reappearing blocks, wrath lamp

**Comment by LunNova** [comment]
Revert to 1399 or earlier, will have a fix soon.

**Comment by HaoSs07** [comment]
reverted to 93, the one i had before, had to re-upload mods and re-patch but it works now
