### ISSUE TITLE
Build 1412- Chunk loaders not working

### ISSUE THREAD

**Issue by Kusinagie** [MinimallyCorrect/TickThreading#364]
This is possibly related to issue 359. 
On server start before anyone logs in tps reports dimensions loaded but no chunks loaded
(Allow world unload=false) 
After a player visits a dimension with a chunk loader in it, it then functions with or without a player logged in.
(This is with chickenchunks loaders.)

**Comment by LunNova** [comment]
Which chunk loaders?

**Comment by Kusinagie** [comment]
Still the same with build 1423, On server start the loaders are not functioning. once i log in and go to each dimension all is good even if i log out for a while. i will try with world anchors later to see if its the same right now this is with chickenchunks.
Any thing i can get info from for you that helps, I'm not seeing anything in any logs?

**Comment by Kusinagie** [comment]
Tried a restart with world anchors in place. loaded up fine and they were working so its just chickenchunks.
Also to my knowledge i read that portals from portal gun act as chunkloaders somehow, they seem to be acting up as well. If i have a portal far away when i log in that color portal isn't working till i travel there and load the chunk its in.

**Comment by LunNova** [comment]
Are the ChickenChunks loaders set to load only when the owning player is online?

**Comment by Kusinagie** [comment]
No its set to work without players. It was working fine with build 1393 then i updated to 1412 and it stopped working properly.

**Comment by Kusinagie** [comment]
Actually this may have started with build 1368 just from looking at the issue list though I'm pretty sure it was 1393-1412. I will try to narrow it down later by trying a few different ones. 

So to recap its chicken chunks and Portal gun portals not working till a player loads their chunks

**Comment by Kusinagie** [comment]
Well did some testing, ended up dropping all the way to 1315 (jumping a bunch of builds at a time) just to get the chunk loaders to load on a server start  (even noticed the chunk count wasn't quite what it should be but they were working.)

 There may or may not be something going on with this save because i dont remember having the issues back then. I will re-build the server and a new world with each chunkloader i have available to me in a different dimemsion each and pin this down to what build it goes wonky in when i have some more time

**Comment by LunNova** [comment]
It goes wonky when loadChunkOnProvideRequest was disabled, I'm just
confused as with the latest changes it should work. Can you empty the
patchedMods folder and repatch before trying again with latest?

**Comment by Kusinagie** [comment]
Okay either something between 1427 and 1429 or deleting everything in patched folder did the trick Thanks. Now its just the portal gun portals not loading on a server start :p

**Comment by Kusinagie** [comment]
Sorry Nallar portal gun portals still are not loading till a player loads them :p

**Comment by Kusinagie** [comment]
Sorry again, still not working.

**Comment by Kusinagie** [comment]
Updating to 1484 and i see this in the log on start up:
[SEVERE] [ForgeModLoader] The mod PortalGun attempted to force load a chunk with an invalid ticket. This is not permitted.
Never saw this before now but could this be the culprit or perhaps unrelated?

**Comment by LunNova** [comment]
Is chunkloading working correctly now? TT now includes MCPC+'s chunkloading changes, so as far as I know it should be working.

**Comment by LunNova** [comment]
Assuming this now works, as no-one has replied to say that it doesn't since I asked two weeks ago.

**Comment by ZigTheHedge** [comment]
Using 1.5.2.179 - chunkloaders dosn't work, when there's noone in the dimension.
