### ISSUE TITLE
[TT #1416, MCPC+ L15]TC3 aura node disappearing

### ISSUE THREAD

**Issue by wormzjl** [MinimallyCorrect/TickThreading#371]
I've left my server running with TT but when I woke up in the morning I've found that the 1300 size pure node in my base disappeared. Such things happened before build 1373 but it still persists in the latest version.

The only issue that I found is a deadlock when I'm asleep, Is there a problem with tc3 aura node saving upon server crash?
http://pastebin.com/DsQPcxcS

**Comment by LunNova** [comment]
I think the aura node issues are caused if you have multiverse worlds, see https://gist.github.com/nallar/5439817.

**Comment by wormzjl** [comment]
No I don't have multiverse installed on my server. It appears to be pretty strange to me since it's the only node that keeps disappearing every time I rolled it back, just for info I got a world anchor beside it.

**Comment by wormzjl** [comment]
Additional info: the whole aura system in that region got reset.

**Comment by Nohau** [comment]
I have had this happen with 3k node but found several post that this was a issue with TC3 when doing some google search's so didn't report it on TT.

**Comment by alicheek** [comment]
I have this issue too but ive never seen it before having TT I mean could be right might not be TT though :)

**Comment by LunNova** [comment]
I've definitely also had aura nodes vanish without using TT, but it was a rare occurrence, we reset aura every few days. @wormzjl How regularly does this happen, can you confirm that it definitely doesn't happen without TT?

**Comment by wormzjl** [comment]
My aura node was very stable before installing TT, but after then the aura system around my house just keeps changing everyday.

**Comment by LunNova** [comment]
Is this still a problem?

**Comment by wormzjl** [comment]
Sorry, I've just moved my server to 1.5 so I can no longer test TT on it.
Hope that TT would be on 1.5 soon :+1:
