### ISSUE TITLE
Build #1423 - Computercraft melee turtles

### ISSUE THREAD

**Issue by Hoiafar** [MinimallyCorrect/TickThreading#374]
We recently updated from 942 into 1423 and turtles now return false on turtle.attack() even though there are enemies infront of it.

**Comment by SuddenTurmoil** [comment]
My server is on build 1444 and the 6 melee turtles on the server all function as intended. Do you have a sleep cycle after that turtle.attack()? I found adding that in increased my turtle stability even when not running TT.

**Comment by Hoiafar** [comment]
No I do not, but I have tried going into lua and doing turtle.attack() and it still returns false.
However, half the time they do, half the time they don't. There's no discernible pattern to when they will work and when they will not.

**Comment by GUIpsp** [comment]
Do they still deal damage even when returning `false`?

**Comment by Hoiafar** [comment]
No they do not, they do nothing.

**Comment by SuddenTurmoil** [comment]
So, I do not mean to slander your intellect but are you sure that there is a mob directly in front of the melee turtle at the time of issuing the attack commend? Ticks are marvelously small periods of time so if there is any wiggle room the turtle might not see the mob. You can try saturating the area in front of the turtle with mobs or briefly throw in a attack script and see how frequently it is able to attack mobs in front of it. A good basic attack script is: 

```
function attack()
 turtle.attack()
 sleep(.1)
end

while true do 
 attack()
end
```

**Comment by Hoiafar** [comment]
Yes there are mobs infront of it. I've tried several different scenarios, I've tried spawning in new skeletons and turtles and just placing them at a random location in the world (obviously right next to eachother), I've tried putting 4 turtles pointing inwards into one block and drop skeletons in there.

**Comment by SuddenTurmoil** [comment]
You have certainly thoroughly tested it then. Still running the same build of TT?

**Comment by Hoiafar** [comment]
No, we updated to 1463 a few days ago, problem still persists.

**Comment by LunNova** [comment]
Not sure, but I think something's broken with `TileEntityTurtle.rayTraceEntities`.

**Comment by LunNova** [comment]
This may also be related to https://github.com/MinecraftPortCentral/MCPC-Plus/issues/837

**Comment by Hoiafar** [comment]
We are not using MCPC+. Only the standard Ultimate FTB pack.
