### ISSUE TITLE
Build #1423 - "Null Receiver"

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#379]
Probably a mod spitting useless debug spam. It FLOODS my console.

Could it possibly be removed? Might be related to Wireless Redstone or RP2 or something.

**Comment by LunNova** [comment]
Confirmed as wireless redstone. Did this just start happening recently as people began to use WR, or did it happen immediately after updating TT or MCPC?

**Comment by Puremin0rez** [comment]
Not sure actually, it's possible people just started getting into Wireless Redstone. All I know is, the past few days, it has absolutely FLOODED my console. Doesn't stop. Worst then the IC2 spam :P

**Comment by wormzjl** [comment]
It's caused by wrcbe, I've seen this since the 1.2.5 age.
IMO it's not TT related.
