### ISSUE TITLE
Sentry Turrets no longer play audio

### ISSUE THREAD

**Issue by LunNova** [MinimallyCorrect/TickThreading#383]

**Comment by Nohau** [comment]
NOOOOOOOOOo!!!!

**Comment by SuddenTurmoil** [comment]
The sentry turrets on my server do play audio, however, there is a bit of a delay from coming within range to the audio starting. I times about 15 seconds from getting in range of the turrets to them tempting me with certain doom.

**Comment by LunNova** [comment]
Caused by #562.
