### ISSUE TITLE
TT1423 / MCPC L15 ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#385]
Keep seeing this error in console :not sure if this is your error or not as i know you do the -1 for disableFastMobSpawningDimensions .

4:05:22 AM
 CONSOLE:
[SEVERE] java.lang.ArrayIndexOutOfBoundsException: -1
4:05:22 AM
 CONSOLE:
[SEVERE] at java.util.ArrayList.add(ArrayList.java:412)
4:05:22 AM
 CONSOLE:
[SEVERE] at thaumcraft.common.AuraCalculationThread.checkFlux(AuraCalculationThread.java:222)
4:05:22 AM
 CONSOLE:
[SEVERE] at thaumcraft.common.AuraCalculationThread.run(AuraCalculationThread.java:27)
4:05:22 AM
 CONSOLE:
[SEVERE] at java.lang.Thread.run(Thread.java:722)

**Comment by LunNova** [comment]
Fixed with world loading/unloading changes.
