### ISSUE TITLE
TT1423 / MCPC L15 New Player Join Stuck

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#387]
Not getting any error logs but have been fighting this since i moved to mcpc with TT1423 . 

When a new player joins they are stuck at spawn can't move they have to relogin then they can move. It may be a combination of with mcpc with TT as we did not have this prior to mcpc but it can also be a mcpc bug?

Thanks,
Nohau

**Comment by alicheek** [comment]
its a knowen issue I have it too but it doesn't happen with just MCPC I think nallar might of fixed it haven't tested the latest build out yet

**Comment by Nohau** [comment]
Ok as i spent hours redoing my spawn multiple times thinking it was something we where doing wrong lol finally at my wits end lol

**Comment by alicheek** [comment]
haha I was the same just to make sure it wasn't something I did but nallar found it quickly :)

**Comment by Nohau** [comment]
Running 1446 now will update if I see anymore stuck players
