### ISSUE TITLE
ComputerCraft deadlock - error found

### ISSUE THREAD

**Issue by gustav9797** [MinimallyCorrect/TickThreading#39]
http://pastebin.com/x4aas2LW
+
http://pastebin.com/jwD9zv3T

**Comment by LunNova** [comment]
Surprisingly, this isn't a TickThreading bug! That exact issue can happen with a Vanilla install.

As you can see, a computercraft thread is waiting on a tick thread, which is waiting on that CC thread. Without TT installed, the only difference is it'd be the main server thread and not a tick thread. Poke dan200 with the first log.
