### ISSUE TITLE
Enhancement tps command

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#396]
Can you add pagination to /tps as it become impossible to read once you have over a 100 mystcraft worlds

**Comment by LunNova** [comment]
Are you unable to turn on world unloading for some reason? I could maybe add patching to whatever plugin has the issue, having that many worlds loaded isn't good for performance. I'll also implement this, although my current design for making the tables may need quite a few changes.

**Comment by Nohau** [comment]
Yes stupid Towny and GriefPrevention

**Comment by alicheek** [comment]
as I said before townys new dev build should solve that issue

**Comment by Nohau** [comment]
ok but GriefPrevention is far better as you can configure the id's of the stuff which allows it to work with mods like FTB Ultimate i.e Big issue with Towny is it doesn't lock down user chest only vanillia items unless that was fixed?

**Comment by alicheek** [comment]
u could always list down the items in towny issue is it doesn't seem to pick up some of the handlers or something like mining lasers, but I think that's actually a mod issue

**Comment by Nohau** [comment]
I don't think it pickups up none of the 975:\* items i.e iron chest / obsidian / crystal etc. I will load the dev version of it though and give it a look as well people can steal from iron tanks etc last i checked with towny unless that was fixed .

**Comment by alicheek** [comment]
it does but you put them in  manually

**Comment by Nohau** [comment]
Yep your right i completely overlooked that for some reason this is what happends when i do stuff at 3am ..

**Comment by Nohau** [comment]
allcheck do you guys have a place where you hang out i.e irc or something always nice sharing experience or issues we find to double check with people or even create a TickThreading channel?

**Comment by joey19982** [comment]
I'm unable to turn it on because of GriefPrevention, yeah. I haven't really looked into Towny. According to the GriefPrevention Author it is fixed in the latest builds, but the latest builds are for 1.5.

**Comment by floh22** [comment]
guys, get rid of towny and grief prevention. both dont fully work. use mytown. its a forge mod and blocks everything. there is no possible way to bypass it. its like towny. it works with worldunloading as well :)

**Comment by LunNova** [comment]
Not implementing this, as having that many worlds loaded is bad for performance, and should be avoided.
