### ISSUE TITLE
TT1460 | MCPC L5  TPS Overall Calculated?

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#397]
Just curious how overall is calculated as all worlds show 20 but overall shows 15.4

Unfortunately I had to grab this info from console as to many worlds was loaded and couldn't get it all in a single screen shot.. System is not cpu starved hovering below are around 60%-70%  6 core server and ram usage is at roughly 80%

TickThreading v1.0.0.1460 for MC1.4.7 on 1.4.7 tickthreading,mcpc,spigot,craftbukkit,forge,fml
                   World |    TPS | Entities | Tiles | Chunks |     Load
             Age 381/381 | 20.000 |        0 |     0 |      0 |   3.716%
             Age 332/332 | 20.000 |        0 |     0 |      0 |   1.265%
             Age 368/368 | 20.000 |        0 |     0 |      0 |   1.930%
             Age 233/233 | 20.000 |        0 |     0 |      0 |   2.699%
          Mooshrooms/126 | 20.000 |        0 |     0 |      0 |   2.710%
             Age 138/138 | 20.000 |        0 |     0 |      0 |   2.541%
             Age 102/102 | 20.000 |        0 |     0 |      0 |   2.395%
Age 194(SmForestSky)/194 | 20.000 |        0 |     0 |      0 |   2.336%
       Age 200(Void)/200 | 20.000 |        0 |     0 |      0 |   2.533%
             Age 255/255 | 20.000 |        0 |     0 |      0 |   4.032%
       Age 195(void)/195 | 20.000 |        0 |     0 |      0 |   2.294%
             Age 357/357 | 20.000 |        0 |     0 |      0 |   2.049%
             Age 193/193 | 20.000 |        1 |     7 |     29 |   1.287%
             Age 304/304 | 20.000 |        0 |     0 |      0 |   2.411%
          Base Desert/85 | 20.000 |        0 |     0 |      0 |   1.310%
             Age 346/346 | 20.000 |        0 |     0 |      0 |   1.535%
             Age 183/183 | 20.000 |        0 |     0 |      0 |   2.426%
             Age 123/123 | 20.000 |        0 |     0 |      0 |   2.342%
             Age 377/377 | 20.000 |        0 |     0 |      0 |   2.490%
                Power/36 | 20.000 |        0 |     0 |      0 |   2.493%
             Age 120/120 | 20.000 |        0 |     0 |      0 |   2.201%
             Age 334/334 | 20.000 |        0 |     0 |      0 |   2.152%
             Age 308/308 | 20.000 |        0 |     0 |      0 |   2.515%
             Age 227/227 | 20.000 |        0 |     0 |      0 |   2.219%
             Age 263/263 | 20.000 |       12 |    94 |     49 |   4.091%
             Age 355/355 | 20.000 |        0 |     0 |      0 |   2.286%
             Age 298/298 | 20.000 |        0 |     0 |      0 |   2.384%
               Age 25/25 | 20.000 |        0 |     0 |      0 |   2.750%
             Age 260/260 | 20.000 |        0 |     0 |      0 |   4.188%
             Age 266/266 | 20.000 |        0 |     0 |      0 |   2.562%
             Age 229/229 | 20.000 |        0 |     0 |      0 |   2.315%
             Age 307/307 | 20.000 |        0 |     0 |      0 |   2.244%
             Age 264/264 | 20.000 |        0 |     0 |      0 |   2.061%
               Age 11/11 | 20.000 |        0 |     0 |      0 |   2.310%
             Age 175/175 | 20.000 |        0 |     0 |      0 |   2.243%
               Swamp/116 | 20.000 |        0 |     0 |      0 |   2.670%
             Age 115/115 | 20.000 |        0 |     0 |      0 |   2.428%
             Age 235/235 | 20.000 |        0 |     0 |      0 |   2.660%
             Age 306/306 | 20.000 |        0 |     0 |      0 |   2.273%
             Age 118/118 | 20.000 |        0 |     0 |      0 |   2.148%
               Nether/-1 | 20.000 |        6 |    49 |    180 |   4.744%
             Age 313/313 | 20.000 |        0 |     0 |      0 |   2.196%
             Age 319/319 | 20.000 |        0 |     0 |      0 |   1.266%
             Age 223/223 | 20.000 |        0 |     0 |      0 |   2.694%
               Age 65/65 | 20.000 |        0 |     0 |      0 |   2.407%
             Age 148/148 | 20.000 |        0 |     0 |      0 |   2.980%
               Age 56/56 | 20.000 |        0 |     0 |      0 |   2.696%
               Age 87/87 | 20.000 |        0 |     0 |      0 |   2.374%
               Age 75/75 | 20.000 |        0 |     0 |      0 |   2.428%
               Age 78/78 | 20.000 |        0 |     0 |      0 |   2.245%
             Night BJ/73 | 20.000 |        0 |     0 |      0 |   2.035%
             Age 305/305 | 20.000 |        0 |     0 |      0 |   2.280%
               Is Ok/130 | 20.000 |        0 |     0 |      0 |   2.660%
             Age 166/166 | 20.000 |        0 |     0 |      0 |   2.769%
             Age 182/182 | 20.000 |        0 |     0 |      0 |   2.672%
             Age 154/154 | 20.000 |        0 |     0 |      0 |   2.140%
               Age 54/54 | 20.000 |        0 |     0 |      0 |   2.541%
             Age 367/367 | 20.000 |        0 |     0 |      0 |   4.756%
           Need Sand?/72 | 20.000 |        0 |     0 |      0 |   2.109%
             Age 294/294 | 20.000 |        0 |     0 |      0 |   2.052%
             Age 311/311 | 20.000 |        0 |     0 |      0 |   2.440%
             Age 290/290 | 20.000 |        0 |     0 |      0 |   2.328%
               Age 48/48 | 20.000 |        0 |     0 |      0 |   2.598%
             Age 318/318 | 20.000 |        0 |     0 |      0 |   1.172%
             Age 310/310 | 20.000 |        0 |     0 |      0 |   2.278%
             Age 164/164 | 20.000 |        0 |     0 |      0 |   2.254%
             Age 203/203 | 20.000 |        0 |     0 |      0 |   2.726%
               Age 57/57 | 20.000 |        0 |     0 |      0 |   2.351%
             Age 224/224 | 20.000 |        0 |     0 |      0 |   2.680%
Age184(twi/swampMOB)/184 | 20.000 |        0 |     0 |      0 |   2.606%
             Age 226/226 | 20.000 |        0 |     0 |      0 |   2.348%
             Age 145/145 | 20.000 |        0 |     0 |      0 |   2.486%
             Age 211/211 | 20.000 |        0 |     0 |      0 |   2.247%
             Age 282/282 | 20.000 |        0 |     0 |      0 |   2.317%
               Chests/81 | 20.000 |        0 |     0 |      0 |   1.410%
               Age 42/42 | 20.000 |        0 |     0 |      0 |   2.451%
             Age 192/192 | 20.000 |        0 |     0 |      0 |   2.503%
             Overworld/0 | 20.000 |     2487 | 10416 |   2877 |  46.060%
             Age 312/312 | 20.000 |        0 |     0 |      0 |   2.222%
          Dark, Open/125 | 20.000 |        0 |     0 |      0 |   2.574%
                    1/70 | 20.000 |        0 |     0 |      0 |   1.309%
             Age 132/132 | 20.000 |        0 |     0 |      0 |   2.577%
             Age 231/231 | 20.000 |        0 |     0 |      0 |   2.446%
             Age 159/159 | 20.000 |        0 |     0 |      0 |   2.497%
   My Penis is Bigger/80 | 20.000 |        0 |     0 |      0 |   1.411%
             Age 296/296 | 20.000 |        0 |     0 |      0 |   0.981%
             Age 207/207 | 20.000 |        0 |     0 |      0 |   2.552%
             Age 209/209 | 20.000 |        0 |     0 |      0 |   2.874%
             Age 325/325 | 20.000 |        0 |     0 |      0 |   2.068%
             Age 309/309 | 20.000 |        0 |     0 |      0 |   2.408%
             Age 219/219 | 20.000 |        0 |     0 |      0 |   2.567%
                    5/86 | 20.000 |        0 |     0 |      0 |   2.206%
             Age 362/362 | 20.000 |        0 |     0 |      0 |   4.698%
             Age 352/352 | 20.000 |        0 |     0 |      0 |   1.442%
             Age 117/117 | 20.000 |        0 |     0 |      0 |   2.059%
             Age 221/221 | 20.000 |        0 |     0 |      0 |   2.395%
     Dense Ore Danger/66 | 20.000 |        0 |     0 |      0 |   2.386%
             Age 246/246 | 20.000 |        0 |     0 |      0 |   2.215%
                     /43 | 20.000 |        0 |     0 |      0 |   2.473%
             Age 168/168 | 20.000 |        0 |     0 |      0 |   2.180%
             Age 153/153 | 20.000 |        0 |     0 |      0 |   2.404%
    New mining world/167 | 20.000 |        0 |     0 |      0 |   1.182%
             Age 157/157 | 20.000 |        0 |     0 |      0 |   2.048%
               Age 60/60 | 20.000 |        0 |     0 |      0 |   2.547%
             Age 135/135 | 20.000 |        0 |     0 |      0 |   2.631%
             Age 366/366 | 20.000 |        0 |     0 |      0 |   4.551%
             Age 217/217 | 20.000 |        0 |     0 |      0 |   2.520%
             Age 119/119 | 20.000 |        0 |     0 |      0 |   2.207%
             Age 241/241 | 20.000 |        0 |     0 |      0 |   2.188%
       Age 197(Void)/197 | 20.000 |        0 |     0 |      0 |   2.369%
               mining/37 | 20.000 |        0 |     0 |      0 |   2.489%
             Age 369/369 | 20.000 |        0 |     0 |      0 |   2.378%
             Age 280/280 | 20.000 |        0 |     0 |      0 |   2.117%
             Age 178/178 | 20.000 |        0 |     0 |      0 |   2.460%
             Age 190/190 | 20.000 |        0 |     0 |      0 |   2.250%
                    3/83 | 20.000 |        0 |     0 |      0 |   1.673%
      Copper, Tin Age/61 | 20.000 |        0 |     0 |      0 |   2.320%
             Age 351/351 | 20.000 |        0 |     0 |      0 |   2.054%
                 Sand/88 | 20.000 |        0 |     0 |      0 |   1.096%
             Age 370/370 | 20.000 |        0 |     0 |      0 |   1.975%
      Page hunt world/51 | 20.000 |        0 |     0 |      0 |   1.188%
             Age 124/124 | 20.000 |        0 |     0 |      0 |   2.522%
             Age 353/353 | 20.000 |        0 |     0 |      0 |   2.283%
             Age 114/114 | 20.000 |        0 |     0 |      0 |   2.271%
             Age 147/147 | 20.000 |        0 |     0 |      0 |   2.565%
             Age 248/248 | 20.000 |        0 |     0 |      0 |   2.086%
             Age 146/146 | 20.000 |        0 |     0 |      0 |   2.426%
             Age 272/272 | 20.000 |        0 |     0 |      0 |   2.508%
             Age 137/137 | 20.000 |        0 |     0 |      0 |   2.463%
               Age 77/77 | 20.000 |        0 |     0 |      0 |   2.024%
             Age 316/316 | 20.000 |        0 |     0 |      0 |   1.218%
             Age 177/177 | 20.000 |        0 |     0 |      0 |   2.272%
             Age 250/250 | 20.000 |        0 |     0 |      0 |   2.314%
               Age 91/91 | 20.000 |        0 |     0 |      0 |   2.165%
               Age 98/98 | 20.000 |        0 |     0 |      0 |   2.680%
             Age 320/320 | 20.000 |        0 |     0 |      0 |   1.869%
       Twilight Forest/7 | 20.000 |      316 |   127 |    163 |   5.252%
          Suck Me Off/71 | 20.000 |        0 |     0 |      0 |   2.250%
             Age 121/121 | 20.000 |        0 |     0 |      0 |   0.906%
     Semi Flat, Dark/127 | 20.000 |        0 |     0 |      0 |   2.524%
     Twilight forest/288 | 20.000 |        0 |     0 |      0 |   2.810%
                    4/84 | 20.000 |        0 |     0 |      0 |   1.242%
             Age 174/174 | 20.000 |        0 |     0 |      0 |   1.059%
               The End/1 | 20.000 |        0 |     0 |      0 |   2.133%
             Age 359/359 | 20.000 |        0 |     0 |      0 |   3.524%
             Age 245/245 | 20.000 |        0 |     0 |      0 |   2.524%
             Age 143/143 | 20.000 |        0 |     0 |      0 |   2.471%
             Age 363/363 | 20.000 |        0 |     0 |      0 |   4.529%
             Age 133/133 | 20.000 |        0 |     0 |      0 |   2.459%
         Andrew's age/68 | 20.000 |        0 |     0 |      0 |   1.081%
               Age 94/94 | 20.000 |        0 |     0 |      0 |   2.260%
             Age 371/371 | 20.000 |        0 |     0 |      0 |   1.755%
               Age 23/23 | 20.000 |        0 |     0 |      0 |   1.253%
             Age 252/252 | 20.000 |        0 |     0 |      0 |   4.169%
             Age 179/179 | 20.000 |        0 |     0 |      0 |   2.333%
             Age 354/354 | 20.000 |        0 |     0 |      0 |   1.485%
             Age 213/213 | 20.000 |        0 |     0 |      0 |   2.314%
             Age 328/328 | 20.000 |        0 |     0 |      0 |   2.356%
             Age 162/162 | 20.000 |        0 |     0 |      0 |   2.222%
               Age 76/76 | 20.000 |        0 |     0 |      0 |   2.287%
             Age 267/267 | 20.000 |        0 |     0 |      0 |   2.161%
             Age 106/106 | 20.000 |        0 |     0 |      0 |   2.706%
                     /49 | 20.000 |        0 |     0 |      0 |   2.428%
               Age 92/92 | 20.000 |        0 |     0 |      0 |   2.400%
        Rainbow Trees/69 | 20.000 |        0 |     0 |      0 |   2.146%
             Age 270/270 | 20.000 |        0 |     0 |      0 |   4.246%
             Age 158/158 | 20.000 |        0 |     0 |      0 |   2.561%
             Age 108/108 | 20.000 |        0 |     0 |      0 |   2.317%
             Age 210/210 | 20.000 |        0 |     0 |      0 |   2.344%
            Water age/53 | 20.000 |        0 |     0 |      0 |   2.680%
             Age 360/360 | 20.000 |        0 |     0 |      0 |   4.348%
             Age 170/170 | 20.000 |        0 |     0 |      0 |   1.247%
         White Shite/161 | 20.000 |        0 |     0 |      0 |   2.270%
             Age 204/204 | 20.000 |        0 |     0 |      0 |   2.222%
             Age 144/144 | 20.000 |        0 |     0 |      0 |   2.420%
             Age 286/286 | 20.000 |        0 |     0 |      0 |   2.139%
             Age 330/330 | 20.000 |        0 |     0 |      0 |   2.006%
             Age 364/364 | 20.000 |        0 |     0 |      0 |   4.262%
             Age 373/373 | 20.000 |        0 |     0 |      0 |   1.753%
             Age 206/206 | 20.000 |        0 |     0 |      0 |   2.605%
             Age 215/215 | 20.000 |        0 |     0 |      0 |   2.213%
          Big Jungle/113 | 20.000 |        0 |     0 |      0 |   1.128%
             Age 259/259 | 20.000 |        0 |     0 |      0 |   4.360%
             Age 122/122 | 20.000 |        0 |     0 |      0 |   2.614%
             Age 100/100 | 20.000 |        0 |     0 |      0 |   2.324%
             Age 104/104 | 20.000 |        0 |     0 |      0 |   2.872%
             Age 326/326 | 20.000 |        0 |     0 |      0 |   2.357%
   Age 186(endstone)/186 | 20.000 |        0 |     0 |      0 |   2.642%
           Just Cool/129 | 20.000 |        0 |     0 |      0 |   2.526%
             Age 142/142 | 20.000 |        0 |     0 |      0 |   2.522%
             Age 156/156 | 20.000 |        0 |     0 |      0 |   2.149%
             Age 321/321 | 20.000 |        0 |     0 |      0 |   1.548%
             Age 201/201 | 20.000 |        0 |     0 |      0 |   2.765%
             Age 268/268 | 20.000 |        0 |     0 |      0 |   2.282%
             Age 342/342 | 20.000 |        0 |     0 |      0 |   2.431%
  Age 90 - Experiment/90 | 20.000 |        0 |     0 |      0 |   2.143%
             Age 253/253 | 20.000 |        0 |     0 |      0 |   4.504%
             Age 181/181 | 20.000 |        0 |     0 |      0 |   2.432%
             Age 140/140 | 20.000 |        0 |     0 |      0 |   2.283%
             Age 165/165 | 20.000 |        0 |     0 |      0 |   2.615%
      ALL THE SYMBOLS/62 | 20.000 |        0 |     0 |      0 |   2.126%
               Farms/134 | 20.000 |        4 |    56 |     49 |   3.109%
             Age 322/322 | 20.000 |        0 |     0 |      0 |   2.396%
             Age 151/151 | 20.000 |        0 |     0 |      0 |   2.343%
               Age 63/63 | 20.000 |        0 |     0 |      0 |   2.274%
           Glowstone/261 | 20.000 |        0 |     0 |      0 |   1.117%
             Age 160/160 | 20.000 |        0 |     0 |      0 |   1.107%
             Age 237/237 | 20.000 |        0 |     0 |      0 |   2.281%
             Age 180/180 | 20.000 |        0 |     0 |      0 |   2.384%
               Penis/171 | 20.000 |        0 |     0 |      0 |   1.314%
             Age 239/239 | 20.000 |        0 |     0 |      0 |   2.164%
               Age 44/44 | 20.000 |        0 |     0 |      0 |   2.409%
             Age 139/139 | 20.000 |        0 |     0 |      0 |   2.369%
                Main/131 | 20.000 |       10 |   169 |      9 |   3.272%
             Age 265/265 | 20.000 |        0 |     0 |      0 |   2.178%
             Age 302/302 | 20.000 |        0 |     0 |      0 |   2.372%
             Age 185/185 | 20.000 |        0 |     0 |      0 |   1.244%
             Age 375/375 | 20.000 |        0 |     0 |      0 |   4.477%
             Age 278/278 | 20.000 |        0 |     0 |      0 |   2.427%
             Age 173/173 | 20.000 |        0 |     0 |      0 |   2.074%
            Evans Mum/74 | 20.000 |        0 |     0 |      0 |   2.378%
             Age 243/243 | 20.000 |        0 |     0 |      0 |   2.238%
             Age 191/191 | 20.000 |        0 |     0 |      0 |   1.149%
               Age 58/58 | 20.000 |        0 |     0 |      0 |   2.639%
             Age 292/292 | 20.000 |        0 |     0 |      0 |   2.201%
             Age 361/361 | 20.000 |        0 |     0 |      0 |   4.235%
  Floating Structures/67 | 20.000 |        0 |     0 |      0 |   1.118%
               Age 89/89 | 20.000 |        0 |     0 |      0 |   0.945%
             Age 276/276 | 20.000 |        0 |     0 |      0 |   2.364%
               Age 59/59 | 20.000 |        0 |     0 |      0 |   2.818%
             Age 324/324 | 20.000 |        0 |     0 |      0 |   2.389%
             Age 208/208 | 20.000 |        0 |     0 |      0 |   2.375%
             Age 110/110 | 20.000 |        0 |     0 |      0 |   2.433%
             Age 112/112 | 20.000 |        0 |     0 |      0 |   2.657%
             Age 293/293 | 20.000 |        0 |     0 |      0 |   1.101%
             Age 323/323 | 20.000 |        0 |     0 |      0 |   2.323%
             Age 128/128 | 20.000 |        0 |     0 |      0 |   2.462%
             Age 172/172 | 20.000 |        0 |     0 |      0 |   2.288%
             Template/55 | 20.000 |        0 |     0 |      0 |   2.320%
             Age 176/176 | 20.000 |        0 |     0 |      0 |   2.406%
   Twillight age copy/52 | 20.000 |        0 |     0 |      0 |   2.682%
             Age 169/169 | 20.000 |        0 |     0 |      0 |   2.412%
             Age 150/150 | 20.000 |        0 |     0 |      0 |   2.263%
               Age 96/96 | 20.000 |        0 |     0 |      0 |   2.611%
             Age 141/141 | 20.000 |        0 |     0 |      0 |   2.346%
             Age 155/155 | 20.000 |        0 |     0 |      0 |   2.637%
               Age 45/45 | 20.000 |        0 |     0 |      0 |   2.564%
               Quarry/40 | 20.000 |        0 |     0 |      0 |   2.843%
Age 196(SkyIslandLG)/196 | 20.000 |        0 |     0 |      0 |   2.600%
             Age 257/257 | 20.000 |        0 |     0 |      0 |   4.172%
             My Baby/327 | 20.000 |        0 |     0 |      0 |   1.329%
             Age 300/300 | 20.000 |        0 |     0 |      0 |   2.213%
               Age 64/64 | 20.000 |        0 |     0 |      0 |   1.104%
             Age 314/314 | 20.000 |        0 |     0 |      0 |   2.199%
             Age 149/149 | 20.000 |        0 |     0 |      0 |   2.457%
                     /50 | 20.000 |      268 |    56 |    123 |   4.997%
                 Age 2/2 | 20.000 |       74 |    26 |     27 |   2.618%
             Age 136/136 | 20.000 |        0 |     0 |      0 |   2.395%
                    2/82 | 20.000 |        0 |     0 |      0 |   2.150%
             Age 187/187 | 20.000 |        0 |     0 |      0 |   2.763%
             Age 189/189 | 20.000 |        0 |     0 |      0 |   2.524%
             Age 284/284 | 20.000 |        0 |     0 |      0 |   2.520%
             Age 225/225 | 20.000 |        0 |     0 |      0 |   2.581%
                 Home/12 | 20.000 |        0 |     0 |      0 |   2.455%
             Age 152/152 | 20.000 |        0 |     0 |      0 |   0.960%
             Age 344/344 | 20.000 |        0 |     0 |      0 |   2.202%
             Age 188/188 | 20.000 |        0 |     0 |      0 |   1.151%
         mining world/79 | 20.000 |        0 |     0 |      0 |   1.260%
             Cave age/47 | 20.000 |        0 |     0 |      0 |   1.369%
             Age 163/163 | 20.000 |        0 |     0 |      0 |   2.372%
                 Overall | 14.807 |          |       |        | 135.070%

**Comment by Nohau** [comment]
What is weird is i went from 1446 to 1460 and went from 20 performance between 8-15 it says now and /ticks is not showing nothing major.

**Comment by LunNova** [comment]
Please get a profiling snapshot with jvisualvm.

Each world's TPS is the TPS it would have if it was running on its own, without any other worlds. In your case, while no world takes too long, together they do take too long.

**Comment by LunNova** [comment]
Also, only 60-70% load is lower than desired, due to lock contention. Still need to implement #81.

**Comment by LunNova** [comment]
Still waiting on a snapshot, it is important to see why performance is worse.

https://visualvm.java.net/jmx_connections.html

**Comment by Nohau** [comment]
Thanks for the info I will taking a snapshot as soon as I can . I am looking at example of on enabling jmx on the minecraft server which looks similar to tomcat setup but since it is on a dedicated server I want to ensure it is setup in a secure environment and not leave it open .

**Comment by Nohau** [comment]
Trying to figure out how you would like me to upload these snapshots going to try gist first.

**Comment by Nohau** [comment]
Sent to your email addy in your profile.with 1484

**Comment by LunNova** [comment]
Oh, I meant a sampling snapshot. Once connected, go to the sampler tab, run CPU sampling for ~10 to 20 minutes, click the snapshot button there, and save that. It should be a `.nps` file.

**Comment by Nohau** [comment]
Ok will just have to wait again till off hours btw those snapshots the tps was between 8 to 16 at times.

**Comment by LunNova** [comment]
iirc the slowest thing in the snapshot(s) you emailed me is now fixed. Are you still having this problem?

**Comment by Nohau** [comment]
I will bite the bullet and upgrade most like the MFFS that will break again and I might have to try to replicate my fix on https://github.com/nallar/TickThreading/issues/402
