### ISSUE TITLE
[TT 1464] [MCPC+ L20] [Servere] Spam for random things like /gc detailed debugging maybe?

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#399]
![dump](https://f.cloud.github.com/assets/3965516/436635/07569c5c-b060-11e2-8d45-f3f0db214b90.png)

**Comment by Nohau** [comment]
yours looks tons better then mine everything is throwing exceptions even golems!

**Comment by alicheek** [comment]
think it was that logger system nallar has got in now was just wishing there was a way to clear it from my console :P but still log it

**Comment by LunNova** [comment]
Should be fixed in MCPC+ L22 or later, which will exist soon(tm). I messed it up, sorry. Revert to L19 and TT 1463 until then.
