### ISSUE TITLE
Incorrect total load in /tps? (Build 377)

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#40]
I've been using the "newer" builds for most of the day today, with pretty good success.

I've noticed that /tps shows much much higher numbers then before, and they don't always make sense.

I've had an instance earlier where the world had a load of 57%, and the nether had a load of 7%, but the total load was shown as 37%.

Here's an image of slightly miscalculated stats, but there are not alot of players on my server this morning so I can't show you the crazily mathed stats I experienced with 10+ people online.

http://i.imgur.com/qRuTx.png
http://i.imgur.com/zm43T.png

**Comment by LunNova** [comment]
Total loads don't add up together now, as worlds tick concurrently. Probably shouldn't be way off though.
