### ISSUE TITLE
[TT1465 - MCPC L20] "joey19982 lost connection: Internal error: null" when sending a message in chat.

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#403]
This has been happening since somewhere around build #1440 now. I personally have not been on when it happens, but it has been happening very frequently apparently and I can see from the logs.

When sending a message in chat, the player is instantly kicked and given either "Internal error: null" or something along the lines of "software cause socket timeout"
This happens for about 5 minutes for every chat message sent (Commands are fine, people have been using /me to communicate) with seemingly no trace. The only thing I am told by the log is this:
2013-04-28 21:43:21 [INFO] joey19982 lost connection: Internal error: null
2013-04-28 21:43:21 [INFO] Unloading Player: joey19982

I'm not even sure if this is TickThreading, but I'm not sure what else it could be. I haven't changed anything on my server aside from upgrading TickThreading.

I'll try to get some more information next time it happens, hopefully I will be on.

**Comment by joey19982** [comment]
Just happened. Here is a screenshot of the client error:
http://puu.sh/2JbCn.png

Still can't find anything other than that.

This could be MCPC+ as well obviously. Tried downgrading to 15 and I'll see what happens.

**Comment by LunNova** [comment]
I'll need to change whatever's logging 
2013-04-28 21:43:21 [INFO] joey19982 lost connection: Internal error: null, it's not giving any useful information.

That may be related, your database server is possibly overloaded if you're using one. If it's just SQLite that's unlikely.

**Comment by LunNova** [comment]
Also, is it still happening after downgrading MCPC+?

**Comment by LunNova** [comment]
There should also be a `Failed to handle packet from name` followed by the stack trace in your FML log. Definitely not there? :s

**Comment by joey19982** [comment]
I just got home and haven't tried your newer builds yet. From what I understand, this is still happening after the downgrade. I use MySQL but really doubt that it is overloaded.

One of my staff members was watching the console closely today and found this error spit out. Should give you some useful information.

29.04 15:30:00 [Server] INFO at iv.a(NetServerHandler.java:1182)
29.04 15:30:00 [Server] INFO at iv.chat(NetServerHandler.java:1267)
29.04 15:30:00 [Server] INFO at net.minecraftforge.event.EventBus.post(EventBus.java:103)
29.04 15:30:00 [Server] INFO at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
29.04 15:30:00 [Server] INFO at net.minecraftforge.event.ASMEventHandler_191_ChatListener_onServerChat_ServerChatEvent.invoke(.dynamic)
29.04 15:30:00 [Server] INFO at miscperipherals.peripheral.PeripheralChatBox$ChatListener.onServerChat(PeripheralChatBox.java:152)
29.04 15:30:00 [Server] INFO at miscperipherals.peripheral.PeripheralChatBox.access$100(PeripheralChatBox.java:27)
29.04 15:30:00 [Server] INFO at miscperipherals.peripheral.PeripheralChatBox.onChat(PeripheralChatBox.java:117)
29.04 15:30:00 [Server] INFO at miscperipherals.peripheral.PeripheralChatBox.notInRange(PeripheralChatBox.java:139)
29.04 15:30:00 [Server] INFO java.lang.NullPointerException
29.04 15:30:00 [Server] SEVERE Failed to handle packet from kennthium
29.04 15:30:00 [Server] INFO Unloading Player: domovon
29.04 15:30:00 [Disconnect] User domovon has disconnected, reason: Internal error: null
29.04 15:30:00 [Server] INFO at ch.run(PatchTcpReaderThread.java:24)
29.04 15:30:00 [Server] INFO at cg.readNetworkPacket(TcpConnection.java:37)
29.04 15:30:00 [Server] INFO at cg.i(TcpConnection.java:348)
29.04 15:30:00 [Server] INFO at cu.a(Packet3Chat.java:59)
29.04 15:30:00 [Server] INFO at iv.a(NetServerHandler.java:1182)
29.04 15:30:00 [Server] INFO at iv.chat(NetServerHandler.java:1267)
29.04 15:30:00 [Server] INFO at net.minecraftforge.event.EventBus.post(EventBus.java:103)
29.04 15:30:00 [Server] INFO at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
29.04 15:30:00 [Server] INFO at net.minecraftforge.event.ASMEventHandler_191_ChatListener_onServerChat_ServerChatEvent.invoke(.dynamic)
29.04 15:30:00 [Server] INFO at miscperipherals.peripheral.PeripheralChatBox$ChatListener.onServerChat(PeripheralChatBox.java:152)
29.04 15:30:00 [Server] INFO at miscperipherals.peripheral.PeripheralChatBox.access$100(PeripheralChatBox.java:27)
29.04 15:30:00 [Server] INFO at miscperipherals.peripheral.PeripheralChatBox.onChat(PeripheralChatBox.java:117)
29.04 15:30:00 [Server] INFO at miscperipherals.peripheral.PeripheralChatBox.notInRange(PeripheralChatBox.java:139)
29.04 15:30:00 [Server] INFO java.lang.NullPointerException
29.04 15:30:00 [Server] SEVERE Failed to handle packet from domovon

Second time:

29.04 15:44:55 [Server] INFO Unloading Player: Drullkus
29.04 15:44:55 [Disconnect] User Drullkus has disconnected, reason: Internal error: null
29.04 15:44:55 [Server] INFO at ch.run(PatchTcpReaderThread.java:24)
29.04 15:44:55 [Server] INFO at cg.readNetworkPacket(TcpConnection.java:37)
29.04 15:44:55 [Server] INFO at cg.i(TcpConnection.java:348)
29.04 15:44:55 [Server] INFO at cu.a(Packet3Chat.java:59)
29.04 15:44:55 [Server] INFO at iv.a(NetServerHandler.java:1182)
29.04 15:44:55 [Server] INFO at iv.chat(NetServerHandler.java:1267)
29.04 15:44:55 [Server] INFO at net.minecraftforge.event.EventBus.post(EventBus.java:103)
29.04 15:44:55 [Server] INFO at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
29.04 15:44:55 [Server] INFO at net.minecraftforge.event.ASMEventHandler_191_ChatListener_onServerChat_ServerChatEvent.invoke(.dynamic)
29.04 15:44:55 [Server] INFO at miscperipherals.peripheral.PeripheralChatBox$ChatListener.onServerChat(PeripheralChatBox.java:152)
29.04 15:44:55 [Server] INFO at miscperipherals.peripheral.PeripheralChatBox.access$100(PeripheralChatBox.java:27)
29.04 15:44:55 [Server] INFO at miscperipherals.peripheral.PeripheralChatBox.onChat(PeripheralChatBox.java:117)
29.04 15:44:55 [Server] INFO at miscperipherals.peripheral.PeripheralChatBox.notInRange(PeripheralChatBox.java:139)
29.04 15:44:55 [Server] INFO java.lang.NullPointerException
29.04 15:44:55 [Server] SEVERE Failed to handle packet from Drullkus

**Comment by joey19982** [comment]
He also managed to track down when it starts happening:

[5:42:58 PM] Drullkussnʞןןnɹp: I read the error first
[5:43:18 PM] Drullkussnʞןןnɹp: And then I knew the common issue: When someone was at spawn, the chat bug appeared
[5:43:24 PM] Drullkussnʞןןnɹp: That meant, there were chat boxes at spawn
[5:43:35 PM] Drullkussnʞןןnɹp: ...on my Chat Turtles at the theater
[5:43:42 PM] Drullkussnʞןןnɹp: I removed the turtles
[5:43:50 PM] Drullkussnʞןןnɹp: Problem solved

**Comment by LunNova** [comment]
If the turtles are replaced, does it break again?

**Comment by joey19982** [comment]
So far, no. Not sure if it was a freak thing or something that happens after a while. When the other staff member gets on I'll have him set them up exactly how they were before.

**Comment by HaoSs07** [comment]
just side note, this fix failed in jenkins

**Comment by LunNova** [comment]
And I closed the wrong issue.

**Comment by LunNova** [comment]
@joey19982 Still not happened again?

**Comment by joey19982** [comment]
Sorry, forgot to check back here. I haven't had any issues with it since, so I think it's safe to close.
