### ISSUE TITLE
High CPU Usage? (Build 377)

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#41]
There is currently zero people on my server and it's taking anywhere from 10-25% CPU

When there is a single person on (being me) It'll jump anywhere from 25-70%, even if I'm just sitting absolutely still with no machines etc ticking.

All chunk loading features etc are disabled, so it can't be that...

I did not have this issue on Build 290

**Comment by LunNova** [comment]
Is it any better in 381?

**Comment by Puremin0rez** [comment]
@nallar 

I'll have to give it a shot in a few hours, I'm on my way out right now.

**Comment by Puremin0rez** [comment]
Managed to throw 381 really quick, I mean, I guess it's slightly better.... but I'm still seeing some odd behavior.

0 People on = 20% CPU with random spikes etc
4 People on = 20-40% CPU with random spike etc

It definitely didn't do this on 290, load is much higher and I'm not sure why.

**Comment by LunNova** [comment]
Can you a) try the latest build again, b) change cores in config file to the number of cores you have.
