### ISSUE TITLE
[TT 1471] MyTown: Crash on /t spawn from another dimension.

### ISSUE THREAD

**Issue by nylser** [MinimallyCorrect/TickThreading#412]
The server crashes everytime a player uses /t spawn to go his home town from another dimension. I need to SIGKILL the java process for it to stop. After restarting the server, and the player logs in again he is at a random place in the dimension he teleported to, right next to a portal. (Using the newest build 1471 )

Tickthreading-Log: http://pastebin.com/yJKfdSVr

**Comment by nylser** [comment]
Is this really fixed? I just tested with the newest build 1474 and it still seems to happen..

**Comment by HaoSs07** [comment]
also getting this on last build, is not fixed

**Comment by LunNova** [comment]
New log? If it's still broken it's broken in a different way.

**Comment by HaoSs07** [comment]
http://pastebin.com/Xg03zA5k here you go nallar

**Comment by LunNova** [comment]
I forgot to implement the fix for forge, only MCPC+. Are you both using only Forge? Should be fixed now.

**Comment by nylser** [comment]
Yeah, it's working for me. Doing an awesome job, nallar! Edit: Yes I'm using only Forge with MyTown
