### ISSUE TITLE
[MCPC+19, TT1471] Applied Energistics EU Feed back.

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#414]
The glass fiber cable leading to my ME system disappears as if it exploded.

Two servers I run:

Direwolf20 Pack: Been running solely with TT and been having reports of this issue.

Ultimate Pack: Installted Recently on ultimate server never had this issue before now have it happen several times.

As far as I can tell no errors or reports in any logs

**Comment by geoffcorey** [comment]
Experienced the same thing on Ulitmate v1.0.1.   I am suspecting that restarts may have something to do with it but still have not been able to reproduce repeatedly.

**Comment by cjm721** [comment]
It might happen on restarts, but had it happen when playing. I never had it happen while I was sitting at the ME though so no idea if it is then related to load/unload.

**Comment by cjm721** [comment]
Got this this to happen on demand now. Built a huge ME system to test #628 and noticed that the glass fiber cable I had coming from 8 ultimate hybrids and the glass fiber disappeared. Just sitting it uses 878 units / t and happens within a minute of placing the cable.

**Comment by LunNova** [comment]
Does AE try to return energy it's unable to use?

**Comment by cjm721** [comment]
No clue but I could see that causing an explosion since its using near 1500EU/t but in 512 packets.

**Comment by LunNova** [comment]
Can you still replicate this after the recent rework of how TT handles AE networks?

**Comment by aMUSiC** [comment]
This is happening on my server a lot (1.4.7). If this has been indeed reworked and fixed for a 1.5.2 release could you point me to the particular fix so I can fork the project and compile it with that fix? (assuming of course that you won't be adding fixes to the 1.4.7 branch any more).

**Comment by LunNova** [comment]
I closed all issues as support for 1.6 and earlier has been dropped, and
when/if I have time to update TT it will be a partial rewrite to reduce the
need to manually make patches for everything, invalidating almost all
issues.
