### ISSUE TITLE
[MCPC+ - 19/21] [TT 1484] Deadlock on (certain) player login / chunk load.

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#424]
MCPC 19 TT 1484 

FTB Ultimate Pack 1.01
Occurs also on Direwolf20 Pack (running MCPC 21)

From what I have been able to deduce from the occurrences on my server I have gotten this:

1) Due to chunks loading at location of player login, ie if I go there from another account that is already logged in and then player1 logs in no deadlock.

2) If I change where the player will login (using essentials / world player file) there is no crash when they come on.

Sub note about the deadlock I link is that player is logging in age 29 while TT logs say issue is in age 24 (player has not gotten back to me if he has a chunk-loader there of which I have them only on if the owning player is online)
3) All the lua stacktraces are from ComputerCraft, or at least only thing I know that uses lua API in ultimate pack and the huge amount of threads relating to them corresponds to the large use of turtles on my server.

http://pastebin.com/nrm8mqgt

Also Direwolf20 server crashed an 30 minutes ago:

http://pastebin.com/9yxgtNPt

**Comment by LunNova** [comment]
The issue on the DW20 server appears to be an MCPC+ bug, see https://github.com/MinecraftPortCentral/MCPC-Plus/issues/847
