### ISSUE TITLE
#1488 MFFS not raising shields

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#425]
Players on my server have reported MFFS projectors are not working. I hopped on ran a few tests, and this is quite true. The shields are not raised when they are turned on and Tickthreading is enabled.

I think https://github.com/nallar/TickThreading/issues/404 relates, and was closed prematurely, as another player reported this 3 days ago.

**Comment by Nohau** [comment]
See https://github.com/nallar/TickThreading/issues/402
