### ISSUE TITLE
Question not issue: Is there permission nodes for /ticks /tps

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#431]
hey there the heading basically is the question, was just wondering because it would be good if my admins could use them (they aren't op so don't automatically get the perm)

Thanks

**Comment by LunNova** [comment]
Disable the require ops setting, and use the permission node assigned by MCPC+.

**Comment by alicheek** [comment]
cant seem to find any references to permission nodes for it any chance u can give me the link to it?

**Comment by LunNova** [comment]
They're listed in console while the server is starting.

**Comment by Nohau** [comment]
Added it to https://github.com/nallar/TickThreading/wiki in case anyone is interested in the future.

**Comment by LunNova** [comment]
@Nohau 
Thanks :)
