### ISSUE TITLE
[TT 1488] [MCPC L21] Found Lag issue Twilight Forest animals/mobs

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#432]
Found an issue with twilight forest mobs/animals people are still finding them very laggy like one second u can hit them then the for about 1 min they are all frozen and don't move, don't take any hit damage in this time, also one of my admins and I noticed that some animals were stuck in blocks and they were originated in laggy areas  that is given by /ticks not sure why it would be intensive because of that

**Comment by alicheek** [comment]
also quick question what does the N stand for in the co ordinates in /ticks  ?

**Comment by LunNova** [comment]
Number of entities or tile entities in that region.
Try disabling variable tick rate in the config, it may be avoiding ticking the areas if they're very laggy. Of course, doing that will decrease performance.

**Comment by alicheek** [comment]
ah cheers , ill give it a try but I don't think its that I mean the server will be at 20 tps and the TF mobs will still do this

**Comment by LunNova** [comment]
Still a problem?

**Comment by alicheek** [comment]
Ope is fixed thanks :)
