### ISSUE TITLE
TT1500 / MCPC L22 - Player movement updates ignored in some cases

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#434]
not getting no errors or nothing just right where spawn is located there is like ghost blocks can't world edit and destroy them.

**Comment by Nohau** [comment]
Reverted back to TickThreading-1.4.7-1.0.0.1488.jar and the spawn glitch is gone you can now walk around where spawn is and you don't get stuck.

**Comment by LunNova** [comment]
Probably an issue in e371e31ee5fdbf7d607fef964c4f4c2fa5c3b70f or 6a6584dd79df63559e3929d27b5169fabf3c6f01.

**Comment by aquagene** [comment]
This issue does NOT occur in builds #1500 to #1503 for me.

**Comment by LunNova** [comment]
It's the same problem, I just made it worse instead of better. Oops?
