### ISSUE TITLE
[Enhancement] "Show known bugs" to config option.

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#436]
Add to config to make it something configurable like op only or enable /disabled . 

Rather not have people complain saying TT deleting items when it could be or not, but it gives them something to blame and try to hang it over me.

Original Commit:
85d74ecc0aec6a226d54acf87a3faf33556f740d

**Comment by LunNova** [comment]
Not going to add this, too many people were annoying @AlgorithmX2 about issues with TT and AE because they didn't realise that TT was on the server.

If you feel that the message is ambiguous and making users think that TT + AE could cause any items to be deleted, not just those in AE storage, suggest a new message. I'm bad at documentation.

**Comment by cjm721** [comment]
What I am saying is that there were / are a few people on my server (out of over 200 unique people that log in every day) that try and get items by saying "You caused it by adding ____" and what not.

Currently the version in the ultimate pack there are several mod relations that cause item deletion (improper use of Deep storage units) so TT is not to blame (have not had any NBT complete resets with AE in the first place), and for people reporting problems to @AlgorithmX2 without knowing what running on the server is more of an issue with the person reporting as @AlgorithmX2 is going to ask for logs to see if there was any errors and if the person can't access the logs then in all reality to @AlgorithmX2 that person is little use (And TT is pretty obvious in logs on startup) . Not to mention he has fixed many of those issues already but Ultimate/Direwolf both are running old versions which reduces the usefulness of their report even more because the problem could of already been fixed.

I understand not wanting @AlgorithmX2 to be getting false reports caused by TT but at the same time causing quite an annoyance to server admins/owners that have people that want to blame the loss of anything on something and the message via TT gives them something to attach onto. Also with that the players should be contacting and admin/owner first before going to the mod author to make sure there was not something else or an error in the logs and at that point the admin/owner can either explain to them or just take over the report as I do (double check if it is an issue and do some more testing before reporting). 

Now after typing all of that could make it a default true in the config or ability to customize the message.

As for changing the message it really depends on what your wanting to get across to the players, The fact that TT is installed or that there is issues with TT and AE 

Such as:
"This server is running TIckThreading Version ##, Please check active TickThreading issues before reporting to mod Authors."

Personally I have a message on login saying "Report any issues and bugs to cjm721." I also wrote/writing a plugin to prevent many issues and notify me of possible occurrences so that I don't have to ban items, and with that I do follow up if it is a real issue.

**Comment by LunNova** [comment]
I've got bad news for you, players don't do what you expect.

I will add a config option, but I really don't agree with changing it from the default. If other mod authors continue to have players annoy them about this I will be removing the option again.

**Comment by cjm721** [comment]
Correct players don't do what you expect so if they are going to complain to someone they are unlikely to read anything anyways and then either to anoy me about lost items or still keep going to AE and not pay attention to your message either.

In all reality if they are going to complain to AE before going to TT / don't know if they have TT they are going to go to @AlgorithmX2 anyways. I tried to get that across in my second post which I kinda failed at explaining that when I was saying they should be going to their server admin/owner first.
