### ISSUE TITLE
Build 396 - ComputerCraft - Turtles don't save inventory or programs if the server stops.

### ISSUE THREAD

**Issue by gustav9797** [MinimallyCorrect/TickThreading#44]
I've noticed this two times now, turtles don't save their data. A turtle had 4 stacks of wood in it and was running a program when I restarted the server, and when I came back the program and wood was missing.

**Comment by Puremin0rez** [comment]
I'm not quite able to reproduce this - are you setting a label on the turtle?

Turtles only save there data with a label set

label set yournamehere

I've tried to replicate your issue on Build 403 and couldn't - but 403 is pretty instable anyways, so.

**Comment by gustav9797** [comment]
I mean you place a turtle, place some stuff in its inventory and code a program, run the program, stop the server, start and the program and inventory are gone. This might only occour when the turtle is running a program and is moving, though.

**Comment by gustav9797** [comment]
I should also mention that turtles tend to loose their tools all the time(Server restart too I think)

**Comment by gustav9797** [comment]
Found this thread. Hope it helps..
http://www.computercraft.info/forums2/index.php?/topic/6831-142smpftbcc-v146turtle-looses-his-mining-pickaxe-after-server-crash/

**Comment by LunNova** [comment]
Closing this as it's a confirmed computercraft bug.

**Comment by Puremin0rez** [comment]
Are we sure this isn't a issue where TT is making a problem worse?

I've never gotten this issue ever on 209 but now on 400+ I'm getting this issue frequently without the server even restarting, the second the chunk unloads any moving turtles will revert to a normal, broken turtle.
