### ISSUE TITLE
[TT 1507] [MCPC+ L22] Big tps lag but was fine at TT 1500 weird over % of load in /tps

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#442]
Don't understand how the overall load is double the total load

![2013-05-03_21 52 51](https://f.cloud.github.com/assets/3965516/461219/d56ad8fc-b433-11e2-85ed-5baec338e0b6.png)

**Comment by HaoSs07** [comment]
also do a /profile e and post it

**Comment by alicheek** [comment]
`Profiling for 7 seconds in Overworld/0
2013-05-03 21:09:48 [INFO] [TickThreading] 
                                 Obj | Time/Tick |     %
          TileOutputCable 166,97,382 |     4.218 | 2.450
TileEntityFertilizer -2069,116,-2040 |     2.652 | 1.541
      tile.TileController 163,96,401 |     2.099 | 1.219
    player.EntityPlayerMP 777,67,440 |     2.000 | 1.162
          TileGenericPipe 103,36,898 |     1.892 | 1.099
                Class | Total Time/Tick |      %
      TileGenericPipe |          28.657 | 16.645
      TileOutputCable |           6.424 |  3.731
player.EntityPlayerMP |           6.326 |  3.675
  gadgets.TileMachine |           5.488 |  3.188
   BaseMetaTileEntity |           5.140 |  2.985
               Class | Time/tick | Calls
TileEntityFertilizer |     2.652 |    45
    EntityCaveSpider |     0.580 |    90
 tile.TileController |     0.517 |   225
 TileEntityCapacitor |     0.465 |    45
     TileEntityMiner |     0.355 |    45
`

**Comment by LunNova** [comment]
Please upload a jvisualvm cpu sampler snapshot.

**Comment by alicheek** [comment]
how do I do that ? sorry for the silly questions just not done it before

**Comment by HaoSs07** [comment]
http://docs.oracle.com/javase/6/docs/technotes/guides/visualvm/profiler.html see this

or this https://visualvm.java.net/jmx_connections.html ( provided by nallar)

**Comment by Nohau** [comment]
I just got the same just completely random running 1521 . Then it went right away ... but it was like a sudden hicup in the whole server just paused perhaps gc happening but that is a first we seen this and effected that bad.

![2013-05-05_16 57 11](https://f.cloud.github.com/assets/4019875/464240/b6fbb880-b5cf-11e2-9cdf-d1e7f0ccdbf6.png)

**Comment by LunNova** [comment]
There is nothing I can do without snapshots.

**Comment by Nohau** [comment]
Just got a 30-40 minute cpu sample . I stopped the sample then clicking snapshot (Take Snapshot of collected results).. I hope that is how you do it .. I still have it up just in case that was wrong. Question is did I catch it when it happened again or not.

**Comment by Nohau** [comment]
Email sent to your email addy posted on github profile.

**Comment by wormzjl** [comment]
Getting similar lag with AE in the latest build.

**Comment by Nohau** [comment]
Please get cpu sample snapshots of your minecraft server to help identify the issue.
