### ISSUE TITLE
Update to 1.5

### ISSUE THREAD

**Issue by nylser** [MinimallyCorrect/TickThreading#448]
Will TickThreading be updated to 1.5? Or maybe even wait for 1.6?

**Comment by Puremin0rez** [comment]
Please make it a separate branch or something =)

Feed the Beast is still on 1.4.7, sadly.

**Comment by joey19982** [comment]
As long as 1.4.7 is still regularly updated, I think it should be. Some people will be wanting 1.5 for the beta versions coming out this week, though

**Comment by LunNova** [comment]
I will be moving to 1.5 once full support for the 1.4.7 FTB ultimate pack is done.

As far as I know the only severe issue left with the ultimate pack is #246, which may now be fixed.

**Comment by Nohau** [comment]
Well if you run a pvp ultimate server MFFS Projectors being broken is pretty bad good thing is at lease defense system works https://github.com/nallar/TickThreading/issues/402

**Comment by joey19982** [comment]
Nallar, don't forget us Direwolf20 players. D:

**Comment by LunNova** [comment]
Postponing this until 1.4.7 is, for most servers, completely stable. Freeze on any new features, unless the new feature gives a very noticeable performance increase, so (hopefully) no new bugs will be introduced.

**Comment by nylser** [comment]
Awesome that this is taken on now was waiting for that for my private server ;).

**Comment by Puremin0rez** [comment]
Can't wait for 1.5 =) Got my server ready to go -> minus TT of course!

**Comment by Puremin0rez** [comment]
Oh god, running 1.5.2 without TT is very noticeable. I miss you TT!

**Comment by LunNova** [comment]
http://forum.feed-the-beast.com/threads/tickthreading-concurrent-entity-tile-entity-ticks-and-other-optimisations.6498/page-28#post-310029

**Comment by nylser** [comment]
Nallar, you are my hero!

**Comment by LunNova** [comment]
Build up on the buildservice under TickThreading-1.5.2. It compiles, but the patches are mostly broken and it will probably crash on startup if you try to use it.

**Comment by LunNova** [comment]
Need to modify patching to work with SRG obfuscated mods, may take some time.

**Comment by Puremin0rez** [comment]
@nallar 

Thanks for starting work on 1.5.2! I'll try it out in a few days =P
