### ISSUE TITLE
Leaf decay on modded trees? (Build 403)

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#46]
I went into a giant forest and all of the leaves are decaying, even though there is definitely log right next to them. I've sat here for 5~ minutes and the entire tree lost all of its leaves. It's doing this in all of the big tree biomes from what I can see.

This doesn't appear to be happening to smaller trees.

This might not be a TT Bug, but I've just noticed it.

**Comment by Puremin0rez** [comment]
I should note the trees this is happening too is from ExtraBiomesXL

**Comment by LunNova** [comment]
This doesn't seem to be happening to me, what's the biome name?

**Comment by Puremin0rez** [comment]
It appears to have just been a one time fluke, rebooting the server fixed it.
