### ISSUE TITLE
[TT1565] | [MCPC L22] [INFO] Failed to fetch resident: [[Forestry]]

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#468]
No idea why im getting this coming up a lot, yes its doesn't seem to be causing issues but it is getting a bit spammy, haven't changed anything to do with the Forestry's residents either

15:37:26  [INFO] Failed to fetch resident: [[Forestry]]
15:37:26  [INFO] Failed to fetch resident: [[Forestry]]
15:37:26  [INFO] Failed to fetch resident: [[Forestry]]
15:37:26  [INFO] Failed to fetch resident: [[Forestry]]

**Comment by alicheek** [comment]
ps sorry bout that realised I put it in all wrong so quickly closed it and re edited it :)

**Comment by LunNova** [comment]
I don't think this is a TT bug.

Try enabling fake player login for forestry in bukkit.yml.
