### ISSUE TITLE
TT patching itself?

### ISSUE THREAD

**Issue by wormzjl** [MinimallyCorrect/TickThreading#470]
Just found a file named TickThreading-1.4.7-1.0.0.1582.jar in the patched mod folder with the latest build.
Is that normal that TT patches itself?

**Comment by LunNova** [comment]
Yes, started doing this recently as java has a design issue - or at least I think it's a design issue - which makes certain code terribly verbose.

Java has the `synchronized` keyword which can be used for threadsafety. You use it like this:

`synchronized (something) {
   // Code in here will never be ran at the same time as code which is in another synchronized() using the same something.
}`

However, if you do not know whether you need to synchronize, this gets silly.

`if (something != null) {
    synchronized(something) {
        // Do action A
    }
} else {
    // Do action A
}`

While this is kinda' manageable, especially if "action A" is only one line of real code, it gets worse if there are multiple somethings, and "action A" is many lines.

One way of avoiding this mess is by using locks:

`if (something != null) {
    something.lock();
}
// Do action A
if (something != null) {
    something.unlock();
}`

However, this is slower than using synchronized(), and requires that something be a Lock. Synchronized can be used on any object.

To solve this problem, the patcher is used to transform code which uses locks into code which uses synchronized internally, making it easy to modify but still fast.
