### ISSUE TITLE
[TT 1582] [MCPC #23] Iron Tank Crash

### ISSUE THREAD

**Issue by floh22** [MinimallyCorrect/TickThreading#471]
i got kicked and all iron tanks i had got reset

console log:

http://pastebin.com/1w6iP4eK

**Comment by LunNova** [comment]
That's actually an IC2 issue, it's odd that it caused an iron tank to be reset...

**Comment by LunNova** [comment]
Can you try MCPC+ L15?

**Comment by floh22** [comment]
same issue

**Comment by floh22** [comment]
wierd thing is that it turns out it doesnt just happen with iron tanks. sometimes when people tp they get kicked and the exact same error shows. i did not have this without TT

and one quick question, is there any reason why a world would be jumping from 32k tile entities to 15k tile entities within minutes, and then jumping back again? it seems to be the main cause of lag

**Comment by LunNova** [comment]
@floh22 

Probably from an area with lots of tile entities being loaded and unloaded repeatedly.
