### ISSUE TITLE
[TT #1582 MCPC+ L23] Server freeze without crash report

### ISSUE THREAD

**Issue by wormzjl** [MinimallyCorrect/TickThreading#474]
After updating to this version of TT my server is experiencing a frequent server freeze. 
All players just timed out and there is no crash/error report and no console output.

This could be caused by players working in a region with intensive AE installations (~ 1k AE block), teleporting in/out of this region could also caue freeze.

For more information my server had this problem before installing TT:
https://github.com/MinecraftPortCentral/MCPC-Plus/issues/694
And TT saved my server from crashing with this every 5 min.

But the situation for this crash to happen is quiet similar with what we are having right now, except that there is no crash report.

**Comment by LunNova** [comment]
Decrease the deadlock detector time, leave the server running after it
freezes until it gives a deadlock detector report.

**Comment by wormzjl** [comment]
I was unable to get a deadlock report even I set the time to 10s.
The server was not responding to any commands.

**Comment by LunNova** [comment]
Thread dump with jvisualvm?

**Comment by wormzjl** [comment]
Moved my server to a VPS for this, it's no longer freezing now but crashing the OS instead...Will investigate further

**Comment by LunNova** [comment]
Ah, it's possible this was a slow full GC. What were your JVM parameters? Are you on latest java 7?

**Comment by wormzjl** [comment]
There could be a memory leak somewhere, if I left my server running for some time it will end up doing GC all the time and no longer playable.

I'm running it with:

java -server -XX:UseSSE=4 -XX:+UseCMSCompactAtFullCollection -XX:ParallelGCThreads=6 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+DisableExplicitGC -XX:+CMSIncrementalMode -XX:+CMSIncrementalPacing -XX:+UseCompressedOops -XX:+AggressiveOpts -Xmx2500M -Xms2500M -XX:MaxPermSize=128m -jar mcpc-plus-legacy-1.4.7-R1.1-SNAPSHOT-f534-L25.jar -nojline

With latest java7 yes.

**Comment by SNIPER722** [comment]
on our VPS  
java version "1.7.0_21"

SE Runtime Environment build 1.7.0_21-b11
Java Hotspot 64-bit Server CM build 23.21-b01,mixed mode 

i think this is the latest version of java7

**Comment by LunNova** [comment]
@wormzjl definitely seems to be a memory leak then.

Fixed a few since you made this issue, related to BC pumps and world unloading. Make sure cleanWorlds is enabled, if you have world unloading enabled.

If it's still a problem, you may also need to reduce TT's chunk cache's size.

**Comment by LunNova** [comment]
Assuming this is no longer a problem.
