### ISSUE TITLE
Cheat/Dupe Detection Question

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#478]
Do you plan on adding more Anti Dupe detection.. I was going to post a list of things that can be duped and how to do it but decided not as I don't want it to be easy reading grounds for people to see all known dupes in one spot.

If you are should i just post it in a issue or drop a email explaining how etc?

**Comment by cjm721** [comment]
If nallar does not decide to add it in Nohau would you mind trading lists? I wrote a plugin to stop and alert possible attempts for quite a few for ultimate/direwolf.

**Comment by Nohau** [comment]
Yea sure I haven't found any plugins or mods so far that do it I searched 2 days before asking this question .. I was even tempted to figure out how to write my own  as well. Is your plugin plublic?

**Comment by cjm721** [comment]
No, I keep adding and changing things, it does the basic job, but I know there are better ways I do some things and don't know how to implement it. Considering I just finished my finals so I will try and have a more finalized version ready and I'll push it to MCPC or bukkit's plugin page.

**Comment by cjm721** [comment]
I don't know if @nallar noticed but on the FTB forums I sent a message with all the dupes I know of. The way my plugin works causes extra work, but with how nallar patches stuff it would cause no additional load.

**Comment by LunNova** [comment]
Noticed, but busy, sorry. May get something done eventually.

**Comment by LunNova** [comment]
This kinda' goes outside of the scope of TT, so won't be doing this in most cases. In severe cases, such as with the NEI issue, I will patch it.

**Comment by cjm721** [comment]
I wish I understood how you did the class patching as I been having to deobfuscate > decompile > fix the decompiling issues > make sure it will recompile > fix the logic error > recompile > take out class file changed and add to old jar file.
