### ISSUE TITLE
TT 1592 / MCPC L24 Quarrys Reset after server restart

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#483]
This bug is back after server reset all quarries are reseting and have to put the markers back down and redo them again.

**Comment by LunNova** [comment]
Doesn't happen on L15, probably conflicting ForgeChunkManager changes.

**Comment by Maximuscr31** [comment]
It does not happen on L22 either. When I update past that they reset everytime.

**Comment by Nohau** [comment]
I wonder if has to do with L23 When they made changes to loadChunkOnProvide

**Comment by Maximuscr31** [comment]
They are actually compiling a fix for this issue I believe in L26 right now.

**Comment by Meatnog** [comment]
FYI, if I am one of the first people to log into the server after a restart, it does not crash.   But if I log in after it has been running for a while, that's when this crash takes place.   I hope that helps.

**Comment by Nohau** [comment]
Verified on MCPC L27 Resolves this problem.
