### ISSUE TITLE
TT 1592 / MCPC L24 TileCrystalCapictor causing abnormal load?

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#484]
So we have a user that has about 30 Crystal capacitors inside his age . I am always seen it's load worst then overworld or some times at part ...  

![2013-05-11_22 56 44](https://f.cloud.github.com/assets/4019875/492514/05d08ad2-baba-11e2-8d76-5851f4d211d1.png)

![2013-05-11_22 57 16](https://f.cloud.github.com/assets/4019875/492515/20c153bc-baba-11e2-9b72-352291466ea1.png)
![2013-05-11_22 57 49](https://f.cloud.github.com/assets/4019875/492516/26f29610-baba-11e2-8e36-3d3bb6b4f6a1.png)
![2013-05-11_22 58 07](https://f.cloud.github.com/assets/4019875/492517/2da1eede-baba-11e2-9b8e-9d6e7ff042f9.png)

Thanks

**Comment by LunNova** [comment]
https://gist.github.com/nallar/5563223

Not sure what's slow here, will need to do some profiling.

**Comment by LunNova** [comment]
Looks like thaumcraft's AuraManager has some design issues, would be better to just replace that class completely.

I'll try to do that later.

**Comment by LunNova** [comment]
Oh, and there's a bug making it worse, if there are no aura nodes within range it completely breaks.

**Comment by LunNova** [comment]
Now down to 90% load with 70,000 of them loaded.

![](http://i.imgur.com/KL3fAKW.jpg)

Client FPS however, is absolutely terrible. Not my problem! :P
