### ISSUE TITLE
[TT #1600, MCPC+ L25] TT + Multiverse = freeze on start?

### ISSUE THREAD

**Issue by wormzjl** [MinimallyCorrect/TickThreading#486]
After adding multiverse to my plugins folder, my server freezes on start and refuses to respond to any commands.
Here is a threaddump, did I derp up something?
http://pastebin.com/3PBHLXPP

**Comment by LunNova** [comment]
How long did you leave it running for? Looks like it's not frozen, just generating chunks in a world.

**Comment by wormzjl** [comment]
Using an existing world so there shouldn't be anything generating...
It's working now but still pretty strage though.

**Comment by LunNova** [comment]
The seed may not have been saved correctly after it was generated, so the spawn location was different, so more chunks were generated after restarting. iirc that can happen with MCPC+, although it might've been fixed.
