### ISSUE TITLE
WorldGen Buggyness

### ISSUE THREAD

**Issue by NachtRaben** [MinimallyCorrect/TickThreading#487]
So was gonna run a local server with vanilla/forge instead of mcpc+ i had preinstalled build 1597 of TT and this was my worldgen
![untitled4](https://f.cloud.github.com/assets/4164436/493364/f0a68176-bb3a-11e2-810e-ceafb97f4098.png)
![untitled3](https://f.cloud.github.com/assets/4164436/493363/f0a5d35c-bb3a-11e2-92a9-e387c857d07e.png)

after removing tt and restoring the backup server jar this is how the terrain was spose to look.

![untitled](https://f.cloud.github.com/assets/4164436/493366/0f6411d2-bb3b-11e2-922b-349cd4218b65.png)
![untitled2](https://f.cloud.github.com/assets/4164436/493367/0f675554-bb3b-11e2-8009-187718835e4c.png)

**Comment by NachtRaben** [comment]
10 minutes and i will get you results from the same seed.

**Comment by NachtRaben** [comment]
![untitled](https://f.cloud.github.com/assets/4164436/493561/54d02d0c-bb52-11e2-8be6-0ac1dd897b79.png)
Problem persists. Also note that every time i log into the server after a regen i slowly fall into the void and can literally watch the terrain generate over top of me.

**Comment by joey19982** [comment]
I had a similar issue on my server when generating a new map. It wasn't nearly as bad, but in some places trees and villages were cut in half. I figured it was just FTB being buggy.

**Comment by NachtRaben** [comment]
no, this is the same seed. i had noticed it on a previous map so i went to test on it alil. the seed is : StillerFTBCraft if you wish to go test it yourself. i am no using mcpc, but i can recreate it with mcpc also

**Comment by nylser** [comment]
Its funny but I'm getting this bug on a modded 1.5.1 server WITHOUT TT, so it may be another mods fault...

**Comment by NachtRaben** [comment]
when i get home from school i will run a test mod by mod, but the first 2 images were with TT installed, and the other was a regen without TT installed.

**Comment by NachtRaben** [comment]
just for reference, this is what im using.
Direwolf20 Modpack (latest dev from launcher)
    Added mods: FlatBedrock, PowerCrystalsCore, MFReloaded (all from the 1.1 Dev of Ultimate Pack) and DivineRPG 3.0.4
    Removed mods: ExtraBiomes (Interferes with spawning in DivineRPG 3.0.4)

**Comment by LunNova** [comment]
Yes, this is almost definitely a TT issue, I made some changes to population recently.

**Comment by NachtRaben** [comment]
Well if you need anything tested, i can use the same seed and give you the results. Just lemme know which build to test. i can also run tests with the vanillaforge server or mcpc+ also.

**Comment by Xanadu16** [comment]
I can sort of fix this temporarily by regenerating chunks (//chunk then //regen) with MCPC+ and WorldEdit.
