### ISSUE TITLE
TT 1600 / MCPC L27 Potential Memory Leak

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#494]
There may be a potential memory leak in this combination and I am not getting any erors to go off of . What would be the best route to get this info to someone after I let the server run for a bit should I get a HEAP DUMP ?

First time we have actually utilized all our memory that wasn't self inflicted ..  (700 ages loading all at once and going OOM is self inflicted!) 

Server is starting off at 1.7G memory used and we ended up at 8.2G before having to restart it because deadlock detector kept on popping up saying it was deadlocked but nothing inside the logs . 

I have moved to 1606 to see if anything is resolved on this side bu let me know just in case it isn't.

**Comment by cjm721** [comment]
On my server we have recently noticed that the java process is not ending and we have to manually kill it after we stop the server for it to release its resources (same if it crashes/deadlocks).

**Comment by Nohau** [comment]
Yea i noticed that as well but I just waited and it eventually did die off when I seen this memory leak it took roughly 10 minutes for the jvm to shutdown completely.  Just have to be patient when you hit this type of issue unfrotunately.. I am so used to Tomcat Webservers seeing this I guess though.

**Comment by Nohau** [comment]
So i have a heap dump but it is roughly 8G let me know if you would like a copy of it or not.

**Comment by Nohau** [comment]
I also managed to get a 5 minute profile of the memory via threw X11 forwarding but java didn't like that at all and caused the server to come to a halt ...using MCPC L26 which looks like it still has the bug server running only for a few hours and was taking up 5G of ram.

**Comment by LunNova** [comment]
Compress the dump then send it.

**Comment by Nohau** [comment]
Email sent with url to the heap dump.

**Comment by LunNova** [comment]
Going to be a while before I can analyse this, don't have enough RAM and using swap is going to take a long time.

**Comment by Nohau** [comment]
Yea I had to give visualvm 10G .. I have 22G in my desktop machine if you can point me about what i am looking for i can take pics i do know there is one specific class that is taking most of the ram (not at my home machine to see it) but I did have it open.

**Comment by LunNova** [comment]
Unfortunately visualvm is not of much use for debugging this, I use YourKit for memory leaks.

Will be leaving it running overnight, will hopefully find the problem tomorrow.

**Comment by LunNova** [comment]
Disregard that, I set `-Xmx` in the wrong place. Sorry for wasting your time :(

**Comment by Maximuscr31** [comment]
I am experiencing this problem this morning. We use Clearlag and it has an option to do /lagg unloadchunks. When I done this it unloaded 1741 chunks and _seems_ to be coming down in memory usage. I am not sure if that is helpful at all but it is the observation I noted this morning.

**Comment by LunNova** [comment]
It's likely that that either did nothing, or unloaded chunks which should
be loaded. Did the chunk count seem correct in /tps?

Still loading the heap dump, using 29GB of memory so far. 0.o

**Comment by Maximuscr31** [comment]
It looked normal before and the number didn't seem to change much before/after. I just pegged 6gb of ram. Clearlag didn't affect it at all this time. Turned the server off, raised the limit to 12gb, and am now using 6gb on startup and looks to be climbing.

**Comment by alicheek** [comment]
does this seem to be affecting tps also because over time my tps just goes down to 10 from it being strong at 20 even when there is more people on before, and its not like my server is underpowered :S

Server specs:
Dual Xeon L5520, 
64gb DDR3 ECC Fully Buffered, 
4x SSD's in Hardware RAID 0

**Comment by LunNova** [comment]
Okay, since this is apparently taking infinite time to load, can you get a
heap dump once it reaches 1.5 GB above normal?

**Comment by alicheek** [comment]
sure sorry for wasting your time but how do I do a heap dump? all ive done on this is just forward the errors I get atm :)

**Comment by LunNova** [comment]
If you've already got jvisualvm working, just connect and right click on
the server at the left and select heap dump.

Otherwise, Google it/use one of the guides linked in other issues. Would
explain properly, but using a phone so it's annoying to try.

**Comment by alicheek** [comment]
ive got it installed but I cant get it to use the right java jdk or what ever also got a profile e and the numbers are looking a bit crazy : 
![2013-05-15_21 35 44](https://f.cloud.github.com/assets/3965516/509246/46876856-bd9f-11e2-8275-3c732ea3e546.png)

**Comment by LunNova** [comment]
Okay, finally done, @Nohau's issue seems to be a broken BC pump.
