### ISSUE TITLE
Deadlock almost every 15 mins [TT1615, MCPC L28]

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#500]
Server has been having deadlock often, almost every 15 mins.. Sometimes it runs fine for hours, then freeze chains all of a sudden.

TickThreading log:
http://pastebin.com/KifrRt1s

Patcher log:
http://pastebin.com/6j2ssQPP

Any help in this matter is highly appreciated.

**Comment by alicheek** [comment]
does your server's tps start slowing down because I have have that issue to , starts off fine but over time it just grinds to a halt

**Comment by LunNova** [comment]
Not 100% sure that that'll work, if it doesn't I'll need to change a bunch of how ChickenChunks works, so it may be a while before I can fix it.

**Comment by mainsheep** [comment]
So far, it seems the problem is gone, but instead of deadlocking, the TPS drops to 2-3 for a min or two, then goes back up to normal.. This doesn't happen often though, so it might not be related at all..

**Comment by mainsheep** [comment]
A few mins after I typed that it seems ok, it deadlocked.. Latest patcher and logs in the links below.

Patcher:
http://pastebin.com/DumMEdUY

Logs:
http://pastebin.com/4zLv7pBs

Is it possible to go back to a previus MCPC and TT build for the moment, until this issue is resolved?

Edit: Forgot to mention that I updated to TT1619

**Comment by cjm721** [comment]
I am getting blocked Async Chunkloader also on TT 1620 MCPC 28

https://gist.github.com/cjm721/5596419
