### ISSUE TITLE
[TT 1620][MCPC+ 28] Xycraft tanks reset with chunkloaders

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#503]
In reference to #500 any xycraft tanks that are loaded at the time must be re-initiated once you come back in, and they lose all the fluids they had. Xycraft tanks which are not currently loaded seem to have no problem.

TT 1620
MCPC+ 28

Since the items are losing their NBT data (so it appears) might be related to #246 last fix as before that I never saw this happening.

**Comment by LunNova** [comment]
I believe this is an MCPC+ issue, can you try downgrading to L15?

**Comment by Maximuscr31** [comment]
Mine started doing this after one of the TT upgrades. L22 had been fine and then it started. I have up/downgraded above and below that but not l15. I will go back and try it.

**Comment by cjm721** [comment]
I will have to do that on test server as for both my main ones if I go back to 15 I am going to get Xycraft attempted to place tile enity spam.

**Comment by LunNova** [comment]
Can you try latest? Also L33 of MCPC+ if possible.

This should now be fixed.

**Comment by cjm721** [comment]
Have not had any reports of this happening again let, but still using MCPC 31 as I have not had time to change mystcraft folders.

**Comment by LunNova** [comment]
Updated TT also attempts to resolve this issue, so that would be normal. Closing this, as it appears to be fixed, and if  it's still happening requires an MCPC+ update.
