### ISSUE TITLE
Limiting Entities

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#508]
I'm sorry if this isn't the place to post this, but I was not sure where I could.

Is there any way with TT to limit the amount of entities in each chunk or in the worlds in general? If so, how do I change these settings?

I know aPerf got options for this, but I'm not using aPerf or MyTown as I am using MCPC+ for bukkit support. There are some plugins that help with spawners, but those I've tried only limit to a certain degree (vanilla spawners I think).

Thanks.

**Comment by Shybella** [comment]
Sorry to be off-topic, you got Mytown and MCPC+ to work correctly with permissions? If so, can you tell me how

But, I limit mobs with Clearlagg and mobcontrol

**Comment by LunNova** [comment]
Added in dbadd44022856eb2817831a6546c1d9e20212eda.
