### ISSUE TITLE
[TT 1620][MCPC+ 28] Implosion Compressor not responding to right click

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#509]
Also when it unloads when the chunk unloads and when you com back it stays as a machine block and doesn't change back to the implosion compressor.

**Comment by LunNova** [comment]
In a mystcraft age?

**Comment by LunNova** [comment]
I mean multiverse world.

**Comment by alicheek** [comment]
nope in the Overworld which is strange
