### ISSUE TITLE
Deadlocks and IndexOutOfBounds - Build 414

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#51]
Frequent Deadlock: (and i do mean frequent!!!)
http://pastebin.com/6N7Ge6Mv

IndexOutOfBounds:
http://pastebin.com/zWBiPnqf

**Comment by Puremin0rez** [comment]
Okay wow, this is happening like every second for me :(

**Comment by LunNova** [comment]
First issue should be fixed, if not comment on issue #49.

The second issue looks more like an EBXL issue - invalid biome ID... Just in case, made a possible fix in 6425d54dd.
