### ISSUE TITLE
Area 0 0 causing many ticks

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#514]
Lately /ticks have been showing coordinates 0 0 to generate many ticks. When investigating that area, there is nothing happening there.

---- Slowest tick regions ----
  |    X |     Z |   N |   Time
T | 1568 | -1328 | 669 | 14.100
T | 1568 | -1312 | 275 |  9.574
T |    0 |     0 |   4 |  9.113
E | 4592 |  5936 |   4 |  4.262
T | 1584 | -1312 | 206 |  3.242
T | 1584 | -1328 | 478 |  2.898
T | 3856 |   480 | 123 |  2.847

We have tried to delete that region (as its empty), but the problem is only fixed for a certain amount of time before the area is back and generating many ticks.

Anyone else have this problem? Running TT1620 and latest MCPC+ version.

**Comment by LunNova** [comment]
What does /profile c show if you stand in that chunk?

**Comment by mainsheep** [comment]
http://imgur.com/DPn3iK0

**Comment by mainsheep** [comment]
It seem "profile c" is calculating ticks outside the area we are standing on that screenshot.. However I can verify that we did do "profile c" while inside chunk 0 0..
