### ISSUE TITLE
[TT 1621][MCPC+ 28] From 20 tps with over 60 people on to 4 tps with 40 people on

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#515]
So my problem is over about 2 to 3 hours the server will work amazing with out any sign of strain what so ever this is with over 60 people on the server running at 20 tps, but almost like clock work if the server has been running over about 2 hours and 30 mins the servers tps dramatically drops to about 4 tps now befoe this happens  ive done /ticks and it shows all the most intensive regions which are at the most 6 and 5 ms but when this random lag occurs all the same areas increase up to 30 ms or around athat amount .

![2013-05-17_22 18 07](https://f.cloud.github.com/assets/3965516/520486/813c28f6-bf39-11e2-936b-d0f0247c7851.png)
![2013-05-17_22 19 07](https://f.cloud.github.com/assets/3965516/520487/84177fc6-bf39-11e2-80c9-8be2fcef5a2b.png)

**Comment by LunNova** [comment]
Need a jvisualvm CPU sampler snapshot to see what's happening here.

**Comment by alicheek** [comment]
dammit lol im terrible with this stuff ive got it to work just need to get it to connect to the server take it I need profiling set to true for it to work?

**Comment by LunNova** [comment]
Once connected, click ![this](http://i.imgur.com/WGdibfS.png).

Wait for 5-10 minutes, then click ![this](http://i.imgur.com/GQ5Hner.png).

Finally, save it by clicking ![this](http://i.imgur.com/er2w1ak.png), then give me the file you saved.

**Comment by alicheek** [comment]
when I try  to connect it just says it cant connect ive got the right ip ive got  the servers root logins im using the right port yet it just wont let me connect , don't know what im doing wrong

**Comment by LunNova** [comment]
You're adding the java parameters before the `-jar`? You could try setting it not to use a password and just make sure to disable it once you're done.

**Comment by alicheek** [comment]
im just havin trouble where it says add  JMX Connecion

it says to put your hostname in with the port so I put 109.169.93.205:25565
then it says security credentials now im guessing this is the login for ssh, if so I put that in and all I get out is error : cannoct connect to username@ftb.brierie.co:25565 using service:.....    (also tried  the raw ip which didn't work)

**Comment by LunNova** [comment]
You don't use the SSH credentials, or the normal port. https://visualvm.java.net/jmx_connections.html explains which java parameters you need to add to set it up.

**Comment by alicheek** [comment]
so put those parameters in my servers startup.sh basically then use the corresponding ports that I set ?

**Comment by LunNova** [comment]
Yes, and make sure to remove the parameters after if you haven't set up
password authentication.

**Comment by alicheek** [comment]
lol so wait before the -jar or after it ?

**Comment by LunNova** [comment]
Before -jar

**Comment by LunNova** [comment]
Oh, I meant "after" as in "after you're done, remove the parameters you
added."

**Comment by alicheek** [comment]
ok got it to work only thing is its not got any issues of course atm since its just started? so should I wait or just make one now?

**Comment by alicheek** [comment]
fs did it again

**Comment by alicheek** [comment]
ok sent it to ur email

**Comment by LunNova** [comment]
Yes, I'll need a snapshot from when it's lagging. Won't be able to check it
until tomorrow, going to sleep now.

**Comment by alicheek** [comment]
cool man thanks any way its really appreciated

**Comment by alicheek** [comment]
@nallar 
ok sent u the profiler with the low tps occurring only had 29 people on at that time the picture also shows the cpu never really being used over 20% which is weird apart from that spike of course

**Comment by LunNova** [comment]
Can you try latest, and when it lags do the same as before, but profile for a bit longer and set ![these options](http://i.imgur.com/p0dKeWY.png).

Also, possibly check if anyone's using a TF magic map when this happens?

Does memory usage steadily climb until it starts lagging?

**Comment by alicheek** [comment]
@nallar 

ill try and get it done, just so you know the server crashes over time if it doesn't get restarted, I may have leave the profiler on because im going to be out for a bit , but it will have the settings you asked for, oh and before it starts to get laggy yes the memory spikes up to crazy levels like 20 gbs but then eventually calms down but the allocated level still stays up around there don't know if that is any help towards a clue

**Comment by LunNova** [comment]
Then the issue is some sort of memory leak. Using jvisualvm, once it reaches ~2GB usage higher than it starts at make a heap dump ![make a heap dump](http://i.imgur.com/x2XvfeU.png).

Compress that file, then send me a link to it.

**Comment by alicheek** [comment]
can that still cause the server to crash because its never hitting any where near the 64Gb of ram so Im not really sure why it would crash then

**Comment by LunNova** [comment]
If Xmx isn't actually set to 64GB in your parameters, yes. Else, no idea why it's crashing then.

It's best to keep Xmx set something less than 32GB, you'll actually get better performance.

**Comment by alicheek** [comment]
its set to 60GB but its a custom set up done by my hoster, I still think its something to do with the processes so when it goes to the low tps ill do a profiler and a heap dump for you

**Comment by LunNova** [comment]
I need a heap dump when it's at about 6GB because the heap dump is just a copy of everything in memory of the java process. If you do it when it's about to crash it'll a) be a huge file. b) it'll take approximately forever for yourkit to analyze it.

**Comment by alicheek** [comment]
Cool will do that shouldn't really be going over 6 in the first place since my view distance is pretty low and the cache is only set at the default level so may bring something when analysing it

**Comment by alicheek** [comment]
unluckily it crashed when i was away here part most of the forge log has a hell a lot of errors coming out of it then stops with out any crashes . the server just becomes unresponsive, or the screen i set is and it keeps saying timed out:
http://pastebin.com/9WBUZni9

**Comment by alicheek** [comment]
@nallar 

getting another snapshot now , lol right now when I type /tps it says this:

![2013-05-18_23 07 38](https://f.cloud.github.com/assets/3965516/522206/8483e48a-c007-11e2-9c07-411b0a427cca.png)

**Comment by alicheek** [comment]
@nallar 
sent u an email with the snapshot

**Comment by LunNova** [comment]
What are your java parameters? It's quite odd, seems that everything is
getting really slow, not just certain things. :s

On my phone just now, but got a few fixed I'll push tomorrow which would
help a bit.

**Comment by alicheek** [comment]
@nallar 

Sent them to your email :)

**Comment by alicheek** [comment]
@nallar 

Any updates on what the issue could be? :)

**Comment by LunNova** [comment]
Did the new java parameters help?

**Comment by alicheek** [comment]
didn't get to try them, was given other parameters and some other modifications, as I thought it wasn't TT :)

**Comment by darkdeath1332** [comment]
So how did you fix it? I have the same issue.
