### ISSUE TITLE
[Request] IC2 Nuke item drop disable

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#516]
Well I was messing around on my test server and was noticing that if I disable drops (all) then when using nukes there would be no lag at all for the client or the server. With that I searched to see if there was a way to disable drops just for IC2 nukes and:

There was some talk of this on IC2's forums (http://forum.industrial-craft.net/index.php?page=Thread&threadID=8910&pageNo=1) and someone mentioned that the field was already there just no config or api way to change it.

**Comment by LunNova** [comment]
It shouldn't cause bad server lag either with drops on, have you tested?

**Comment by cjm721** [comment]
Yes I have. If you a shell denotation method I can destroy most of everything within 300+ blocks of the detention site. Have gotten upwards of near 100k items on the ground from doing that. Clients pretty much freeze if they are within viewing distance. Now for the server most of the lag is from the pure detonation and spawning in the items from the block breaks, with drops off the detonation did not cause any drop in tps, with drops on the server froze for about a minute then came back. 

Then about a minute latter water and lava started to get to the 50k+ items on the ground and that started to cause more issues until they stopped moving.

**Comment by LunNova** [comment]
When did you last test this? I recently changed items to attempt to merge
before spawning.

**Comment by cjm721** [comment]
Well I have MCPC also which has that built in from Spigot. Just a single nuke will not cause to many issues, but consistently we have people set off 40 plus (with a initial tnt cannon style spread) and that usually requires me to clear the drops once its over. I was not kidding about clearing a 300 radius area, that is 360000 stacks if its all cobble.

**Comment by LunNova** [comment]
Can you try latest again? I'd prefer to get a real fix working for this, instead of just disabling drops.

**Comment by cjm721** [comment]
Yes I will test it tonight.

**Comment by cjm721** [comment]
Do you just want the xml snapshot or what?
