### ISSUE TITLE
patcher doesn't work

### ISSUE THREAD

**Issue by pianocat9521** [MinimallyCorrect/TickThreading#518]
I'm Running Mac OS X Mountain Lion. When i try to run the patcher it gives me an error. Here is the log pastebin.com/kEwqdfK8

**Comment by LunNova** [comment]
What is in 'PATCHME.command'? Check that the path to the TT jar is correct in it.

Also, why did you rename it from PATCHME.sh? Also, make sure you're using the .sh one, if you renamed the .bat one that might not work.

**Comment by LunNova** [comment]
No response from @pianocat9521, I can't fix issues without details. Assuming they either gave up or found a fix themselves, and forgot to post it here.
