### ISSUE TITLE
Item merging issue with new TT stacking system

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#520]
OK so what happens is the player presses q to drop the item, if they do that once its fine, but if they try and press q multiple times to drop the item they just vanish ive been told by a lot of my players , I think its got something to do with  91fa91b

**Comment by joey19982** [comment]
Was just about to post this. Seems like build 1635 would introduce it, so going to try 1634 now.

**Comment by alicheek** [comment]
yea that version works
