### ISSUE TITLE
Implement integration with Alpha's Forge PEX

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#527]
with what mode are the perm for /ticks /profile. etc suppose to work ? i tried with forgeessentials and does not work

**Comment by LunNova** [comment]
They support permissions, but only using MCPC+. I haven't integrated them with FE.

**Comment by HaoSs07** [comment]
hm what about the ported pex for forge ? it runs so much smoother then fe one

**Comment by LunNova** [comment]
It doesn't actually integrate with anything for permissions, just MCPC+ automatically adds permissions for forge commands.

Do you mean Alpha's forge PEX? Might be able to integrate with that at some point.

**Comment by HaoSs07** [comment]
that one, those who don't use mcpc are for sure using mytown and pex, is the only protection that works right now and works good. FE one is not finished

**Comment by LunNova** [comment]
Relabeled/titled this will implement this at some point, possibly in the near future.

**Comment by HaoSs07** [comment]
that would be appreciated

**Comment by HaoSs07** [comment]
wow already ? that was fast :D
