### ISSUE TITLE
Cant run Tick Threading on FTB Ultimate

### ISSUE THREAD

**Issue by monkstick-git** [MinimallyCorrect/TickThreading#533]
Im not sure if its just incompatible or Im not doing something correctly, but heres my issue.
This is for a completly clean installed server, running in my M: drive
Downloaded latest (TickThreading-1.4.7-1.0.0.1658) .jar and dumped it into my mods folder (M:\mods).  Ran the server and it closed like it should.  I ran the newly created Patchme.cmd and it apparently patches everything fine. I look in the log and yes everything is patched.

I try and run the server and it closes.  I look in the logs and its telling me"
2013-05-21 13:41:25 [WARNING] [TickThreading] Patching required for M:\mods\railcraft.jar because it is out of date.
Expected -1305073034, got null
"
for all the mods.

Server Specs:

i7-2600k @4ghz
8gb ddr3 1600mhz ram
512mb RamDisk NTFS

if you need Any more information feel free to ask!  I will provide anything you need.

**Comment by monkstick-git** [comment]
Sorry, I completely forgot to add a log. 

http://pastebin.com/wfr2KtSB

**Comment by Nohau** [comment]
Is the ram disk your M drive as I can see running the patch then if your ram disk was flushed not keep the patchs?

**Comment by monkstick-git** [comment]
Yes the ram disk is my M drive.  For testing purposes I tried running tickthreadding on my C: instead which worked flawlessly.  My RamDisk works fine as I always run my servers from it.

Another thing I noticed when it was in M:, it never creates a config file in M:/config/tickthreadding.cfg

Maybe an oversight on your part and it automatically thinks to look in the C: drive?  I don't know, just throwing ideas out there.

**Comment by Nohau** [comment]
Just out of curiosity what does your PATCHME.cmd have inside it?

It should be a relative path which if it is you will need to ruch the PATCHME.cmd file via command promopt in windows such as the following in your command prompt make sure your in M:\ then type PATCHME.cmd

**Comment by monkstick-git** [comment]
"C:\Program Files\Java\jre7\bin\java" -cp "mods\TickThreading-1.4.7-1.0.0.1666.jar;lib\guava-12.0.1.jar" me.nallar.tickthreading.patcher.PatchMain patcher "ftbserver.jar,coremods,mods"

Running it inside my M: drive

**Comment by Nohau** [comment]
Can you please add the patch log located in TickThreadingLogs I am sure Nallar may need it when he gets around to this ticket. 

Only other thing I can think of is a permissions issue or not enough disk space (my windows foo is horrid but get me on a linux box is different )

**Comment by monkstick-git** [comment]
http://pastebin.com/g3S2q8Ab Here is your log.

There's 250mb free space in the ram drive so there's plenty (relative to a Minecraft server anyway) of space left.
I can read/write to the drive fine, as I previously said its my main way of hosting servers.

**Comment by monkstick-git** [comment]
http://www.youtube.com/watch?v=kv9b_6KVQRk

Heres a quick video showing exactly what I did from what drive

**Comment by LunNova** [comment]
It definitely seems to be saving the changes, are you sure the RAM drive isn't configured in a way which is ignoring changes made by TT's patcher?
