### ISSUE TITLE
Request for bugfix in ExtraBees

### ISSUE THREAD

**Issue by Torins** [MinimallyCorrect/TickThreading#54]
Right, the extrabees bug where ender bees don't mutate.
In binnie.extrabees.ExtraBeeMutation, all occurences of "EnumExtraBeeSpecies.getVanilla("End")" should be patched into "EnumExtraBeeSpecies.getVanilla("Ended")"

**Comment by LunNova** [comment]
Closing this as I didn't get around to it, and it's fixed in extrabees which will be updated in the FTB packs soon.
