### ISSUE TITLE
[MCPC+ 28] [TT 1663] [SEVERE] java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#544]
22:09:55 [SEVERE] java.util.ConcurrentModificationException

> 22:09:55 [SEVERE]       at java.util.ArrayList.writeObject(ArrayList.java:713)
> 
> 22:09:55 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 
> 22:09:55 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> 
> 22:09:55 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 
> 22:09:55 [SEVERE]       at java.lang.reflect.Method.invoke(Method.java:601)
> 
> 22:09:55 [SEVERE]       at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:975)
> 
> 22:09:55 [SEVERE]       at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1480)
> 
> 22:09:55 [SEVERE]       at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1416)
> 
> 22:09:55 [SEVERE]       at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
> 
> 22:09:55 [SEVERE]       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
> 
> 22:09:55 [SEVERE]       at twilightforest.TFFeatureCache.save(TFFeatureCache.java:120)
> 
> 22:09:55 [SEVERE]       at twilightforest.world.TFWorldChunkManager.saveFeatureCache(TFWorldChunkManager.java:415)
> 
> 22:09:55 [SEVERE]       at twilightforest.TFEventListener.worldSave(TFEventListener.java:429)
> 
> 22:09:55 [SEVERE]       at net.minecraftforge.event.ASMEventHandler_114_TFEventListener_worldSave_Save.invoke(.dynamic)
> 
> 22:09:55 [SEVERE]       at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
> 
> 22:09:55 [SEVERE]       at net.minecraftforge.event.EventBus.post(EventBus.java:103)
> 
> 22:09:55 [SEVERE]       at in.a(WorldServer.java:158)
> 
> 22:09:55 [SEVERE]       at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:517)
> 
> 22:09:55 [SEVERE]       at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:619)
> 
> 22:09:55 [SEVERE]       at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
> 
> 22:09:55 [SEVERE]       at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Fixed, forgot to close this.
