### ISSUE TITLE
[TT 1669] [MCPC L31] [SEVERE] [ForgeModLoader] Encountered an unexpected exceptionNoClassDefFoundError

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#552]
When trying to launch the server with the MCPC L31 and TT1669 I get the following error and the server goes into a boot loop:

2013-05-23 10:26:47 [SEVERE] [ForgeModLoader] Encountered an unexpected exceptionNoClassDefFoundError
java.lang.NoClassDefFoundError: net.minecraftforge.event.entity.EntityEvent

> ```
>   at java.lang.Class.getDeclaredConstructors0(Native Method)
>   at java.lang.Class.privateGetDeclaredConstructors(Class.java:2413)
>   at java.lang.Class.getConstructor0(Class.java:2723)
>   at java.lang.Class.getConstructor(Class.java:1676)
>   at net.minecraftforge.event.EventBus.register(EventBus.java:69)
>   at net.minecraftforge.event.EventBus.register(EventBus.java:53)
>   at factorization.common.Core.<init>(Core.java:53)
>   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
>   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>   at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
>   at java.lang.Class.newInstance0(Class.java:374)
>   at java.lang.Class.newInstance(Class.java:327)
>   at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:459)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:601)
>   at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
>   at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
>   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
>   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
>   at com.google.common.eventbus.EventBus.post(EventBus.java:268)
>   at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:153)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:601)
>   at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
>   at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
>   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
>   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
>   at com.google.common.eventbus.EventBus.post(EventBus.java:268)
>   at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:86)
>   at cpw.mods.fml.common.Loader.loadMods(Loader.java:494)
>   at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
>   at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:351)
>   at ho.c(DedicatedServer.java:86)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:159)
>   at fy.run(ThreadMinecraftServer.java:16)
> ```

**Comment by LunNova** [comment]
Duplicates #545.
