### ISSUE TITLE
[MCPC + 33] [TT 1680] Myst-craft worlds "regening"

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#556]
Server Starts fine, but any mystcraft world make a new folder inside of <server main folder>/world_myst, old/original ones are named age# while new ones are DIM_MYST#

So the world are not being deleted but it is creating a new world with the same name and world gen properties.

**Comment by LunNova** [comment]
MCPC+ is changing the way worlds are stored back to being similar to what forge does in new builds, not a TT issue.

**Comment by cjm721** [comment]
So before I just start rolling back untill I find a version that works do you know where this was changed? Considering I assume if I rename the files everything will work fine?

**Comment by cjm721** [comment]
MCPC 31 works with old files, Going to have to test a bit to see how i have to change the file structure for mystcraft worlds now.
