### ISSUE TITLE
steve's carts bug ?

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#570]
So i tested with tt of for a wile and the bug was not there, so i guess its TT related

When i restart the server, or chunk gets loaded / unloaded , SOMETIMES carts from steve's carts mod disappear, so every time 1 disappeared i builded another till 1 day when all the old carts reappeared on the tracks ( even 2 weeks old carts ), and i had a 7 steves carts train

**Comment by LunNova** [comment]
Is this chunk chunkloaded?

**Comment by HaoSs07** [comment]
from what i tested the one whit NO chunkloader did not lose carts, just the one with world anchor

**Comment by LunNova** [comment]
It's possible that the per-chunk entity lists were being corrupted, fix for that in e04606ee38b7cc7. Might not be related.

**Comment by HaoSs07** [comment]
will update today and test.

**Comment by HaoSs07** [comment]
happend again last night.

**Comment by LunNova** [comment]
If you run `/ticks e` when it happens does it show a warning that it fixed x discrepancies?

**Comment by HaoSs07** [comment]
well i have a small bug in gamecp with gamequery and the server reboots sometime ,a /ticks e right now shows no discrepancies, but this may not be accurate 

also i'm never there when it happens ...you just log in and its gone. or you log in and see a train of carts running.
The bug does not happen when you log in. All tree had time to fully grow when i logged in today.

**Comment by HaoSs07** [comment]
happend again . this time i was on,
ticks e fixed 5 discrepancies this time

**Comment by LunNova** [comment]
Fixed in latest.
