### ISSUE TITLE
[MCPC +31] [TT1715] Ultimate 1.1.0 ChickenChunks Missing Method

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#575]
Don't know if this is patcher related or just Chicken-bones missing something.

Causing server crash very often.

https://gist.github.com/cjm721/5659051

**Comment by vanZeben** [comment]
Also happening on the DireWolf20 v5.3.1 Pack

**Comment by LunNova** [comment]
Doesn't look like a TT issue, can you confirm that it doesn't happen without TT?

**Comment by vanZeben** [comment]
Our server was crashing nearly instantaneous when starting up with TickThreading v1715, MCPC v41 and been running it for about 15 minutes no crashes yet without TickThreading

**Comment by LunNova** [comment]
It looks like an issue caused while trying to place a ChickenChunks chunkloader, so if you can confirm that that works correctly that would be helpful.

**Comment by vanZeben** [comment]
Yeah alright, it seems it's still happening. Isn't a TickThreading issue then

**Comment by cjm721** [comment]
How did this not get caught in the testing. Anyone know of any fixes besides disabling placement.

**Comment by LunNova** [comment]
Try updating CodeChickenCore, looks like it's out of date for the version of ChickenChunks.

Not a TT issue, but leaving it open as I may still fix it, if it doesn't involve too much messing with Chickenchunks.

**Comment by vanZeben** [comment]
It's an issue with ChickenChunks v1.3.1.1 which was fixed in in v1.3.1.2, however the FTB team decided to include 1.3.1.1 as opposed to the fixed version in the new "Recommended" updates for whatever reason

You can update it manually to v.1.3.1.2, however it will also require your users to manually update themselves, which sucks for public servers...

**Comment by cjm721** [comment]
With the updates last night FTB fixed their screw up.
