### ISSUE TITLE
BukkitForge + TickThreading

### ISSUE THREAD

**Issue by Konman156** [MinimallyCorrect/TickThreading#576]
I can't seem to get bukkitforge and tickthreading to work together!
Okay so my server runs with bukkitforge and tickthreading but when anyone tries to place a block it kicks them. If i remove bukkitforge the problem goes away. ive tried everything ive found online to fix this. please help i really like tickthreading

**Comment by Konman156** [comment]
im using ftb ultimate with latest TT

**Comment by dariusc93** [comment]
You can try mcpc-plus. I never had that issue with BF and TT. What version are you on?

**Comment by LunNova** [comment]
http://jenkins.bukkitforge.com:8080/job/BukkitForge-1.4.7/4/

It's a BF bug, you need to use the latest jenkins BF.

Alternatively, chunkload the chunks surrounding the 0,0 chunk.
