### ISSUE TITLE
MV Core wont tp to worlds : [MCPC+ L44] [TT 1718] 

### ISSUE THREAD

**Issue by Bucky420** [MinimallyCorrect/TickThreading#581]
the error may be related to mcpc+ it self i reported it there too but i downgraded back to LL43 witch was working and now i cant tp to my spawn world.
this is the error i got with build LL44 
https://github.com/MinecraftPortCentral/MCPC-Plus/issues/1069
but like i said i don't think it is with TT

there is also an issue that i cant explaine and thats ic2 info panels are all facing up thats a paine :\ at first it was only in MV worlds but now it is in the maine world ill keep an eye out for updates and test them 

ill be downgrading to TT1716 or TT1715

EDIT: TT1716 seams to be the tp issue as i do relise that TT1716 was due to me reporting chunk issues 

ill be going back to TT1715 and keep an eye out for updates

**Comment by LunNova** [comment]
You probably need to update to the version of MV which supports world unloading, released recently. Not sure if that's the issue, so I'll leave this open.

**Comment by Bucky420** [comment]
oh ok :+1:  ill try that

**Comment by Bucky420** [comment]
got an opinion on the ic2 info panels?
