### ISSUE TITLE
FTB 1.1.2 TT loading a little slow ?

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#583]
2013-05-28 22:22:45 [INFO] [Minecraft] Done (81.902s)! For help, type "help" or "?"
2013-05-28 22:22:45 [INFO] [Minecraft] Starting GS4 status listener
2013-05-28 22:22:45 [INFO] [Minecraft] Query running on 94.60.40.38:25565
2013-05-28 22:22:50 [INFO] [Buildcraft] Version check failed
2013-05-28 22:26:05 [SEVERE] [TickThreading] TickThreading v1.0.0.1718 for MC1.4.7 on 1.4.7 forge,fml, ForgeEssentials is installed on this server!
If anything breaks, check if it is still broken without TickThreading
We don't want to annoy mod devs with issue reports caused by TickThreading.
Seriously, please don't.

**Comment by LunNova** [comment]
It'll probably load even slower without TT :P

Grab a snapshot while it's starting up, make sure to start sampling very quickly after starting the server.

**Comment by HaoSs07** [comment]
tomorrow you will have the sample. usualy it takes 50-60 sec for all mods to load and another 10 for mytown to enable. but now. is like 10 minutes for a load

**Comment by HaoSs07** [comment]
5th restart is a succes :) server laoded under 1 minute seams it got fixed by itself 

edit. ignore the error, i forget to turn something off in a config after the update :)

**Comment by LunNova** [comment]
Looks like one of the classes MyTown expects to exist just doesn't exist. You do actually have TrainCraft installed?

Possibly TrainCraft has been updated and MyTown no longer works correctly with it.

If you can get it to start slowly again it'd be nice to get a snapshot so I can try to fix whatever made it so slow.

edit: Okay, error ignored.

**Comment by HaoSs07** [comment]
i did not have traincraft, but fore some reason in mytown protection for traincraft was on, now its ok,

as for the lag, have no idea how to reproduce it, it just started to work. :|
