### ISSUE TITLE
200% load with only 40,000 TileEntiites

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#586]
2013-05-28 22:04:29 [INFO] [TickThreading] 
TickThreading v1.0.0.1718 for MC1.4.7
                  |    E |    TE |    C |  P |       L
Twilight Forest/7 |  540 |   392 |  475 |  5 |  13.85%
        Nether/-1 |   79 |   169 |  308 |  5 |   5.98%
      Overworld/0 | 2643 | 41011 | 3929 | 74 | 154.17%
     World_VIP/13 |   17 |    17 |   31 |  0 |   3.55%
          Overall | 3279 | 41589 | 4743 | 84 | 202.69%
 9.87 TPS [ ###################~~~~~~~~~~~~~~~~~~~~~ ] 

take it TE is tile entities, if so that's a lot of them I have lol :S

**Comment by LunNova** [comment]
Yep, TileEntities.

There are almost a million TileEntities loaded in total across all TickThreading instances which are currently running with metrics enabled, and on a new enough version to report loaded tile entities.

**Comment by LunNova** [comment]
Oh, also your server's running too slowly, can I have another snapshot? Need to fix that!

**Comment by alicheek** [comment]
sure ill get on it now

**Comment by alicheek** [comment]
ah dammit cant do a proper snapshot atm but I can do the profilers if that even helps at all? ill try and get snapshots done when we can

**Comment by floh22** [comment]
on a side note, version 1.1.2 seems to be a lot slower than 1.0.1. not sure why, but if you tell me how to do snapshots, i will try to get some :)

**Comment by LunNova** [comment]
Made some fixes recently, load any better on latest?

**Comment by LunNova** [comment]
Assumed fixed in latest.
