### ISSUE TITLE
Lag Spikes [TT #1723]

### ISSUE THREAD

**Issue by floh22** [MinimallyCorrect/TickThreading#590]
So after updating we have been having spike issues so i set the DeadLockDetector to 1

this is the error that came from it:

http://pastebin.com/FjNS4PhK

giant error i know but you might be able to find something....

**Comment by LunNova** [comment]
Can you try again with latest?

Got another change to make based on that report, but it's a tedious, annoying ThreadedChunkProvider locking related change and I'll do it tomorrow.

**Comment by floh22** [comment]
sorry :3

**Comment by LunNova** [comment]
Forgot to mention the issue number in the commit, e68eb5d5fa3b661d648dcc was for this issue and should make a reasonable difference.

**Comment by floh22** [comment]
getting different errors from the lagspikes now.

http://pastebin.com/QazAXNVC

**Comment by LunNova** [comment]
This was caused while saving chunks. What does `/ticks` show for PartialSave?

**Comment by floh22** [comment]
288

this is the complete result from /ticks:

2013-05-29 16:36:56 [INFO] [TickThreading] 
World: Overworld/0
---- Slowest tick regions ----
  |      X |     Z |    N |  Time
T | -12832 | 17936 |  147 | 9.143
T |    448 | -1088 |  461 | 7.975
T | -12832 | 17952 |  260 | 7.395
T |   2864 |  -736 |  525 | 7.297
T |   5344 | -3632 |  367 | 6.541
T |  -2400 |  2816 |  318 | 5.303
T |    912 |  3360 | 1173 | 5.145
---- World stats ----
Loaded 1836 Loading 0 Unload 0 UnloadSave 0 Locks 0 PartialSave 288 Forced 497 Cached 1331
Average tick time: 0.39851022ms
Max tick time: 9.247544ms
Effective tick time: 17.388012ms
Average effective tick time: 63.237103ms
Global TPS: 16.41ms

**Comment by LunNova** [comment]
What does `/profile e` show?

Also, could you update again? Made some more changes to chunk saving.

**Comment by floh22** [comment]
/profile e shows some odd numbers.

here it is anyway, i will update and try to do the same again.

http://pastebin.com/K3u6WPnX

**Comment by floh22** [comment]
just got another error with the new builds:

http://pastebin.com/yewdziZN

one thing to note, i only get this when the server starts and then like 20 minutes later

**Comment by LunNova** [comment]
Possibly your database server is overloaded? MyTown is spending a lot of time doing database stuff there.

**Comment by floh22** [comment]
it has about 6gb ram open and its own core dedicated to it. not sure why it would be overloaded

**Comment by LunNova** [comment]
It's not actually, poor collection choice in MyTown meaning that it's searching through every resident that has ever existed every time it gets the resident. Not exactly fast, will try to fix that.

**Comment by floh22** [comment]
ur amazing

**Comment by floh22** [comment]
it seems like your fixes have brought some troubles with them. people cannot build in their land. they are still in the towns, they just cant interact with them it seems

**Comment by LunNova** [comment]
Oh, that's not good :( I'll look into it.

**Comment by floh22** [comment]
quick edit. it looks like it usually affects mayors and is a database problem. even after going back to an old build of TT, mayors cant access their chunks. BUT if i add people to their towns again, its fixed. so strange. note that i am using mysql like before

**Comment by LunNova** [comment]
Reverted the changes in latest.

**Comment by floh22** [comment]
well it seems like the newest build doesnt really fix it. like i said its a database error. readding the people to their towns fixes the problem though

**Comment by LunNova** [comment]
Original thing from this issue fixed in latest, mytown problem already fixed (was discussed in another issue.)
