### ISSUE TITLE
Some server lag spikes, Snapshot inside

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#596]
https://dl.dropboxusercontent.com/u/76651664/snap1.nps
https://dl.dropboxusercontent.com/u/76651664/snap2.nps

I suspect its from AE autocraft, but it should not be there when crafting using disks.

**Comment by alicheek** [comment]
ive noticed this too auto crafting in them makes huge amounts of lag and really badly when it hits a loop where it cant craft the item.

**Comment by HaoSs07** [comment]
https://dl.dropboxusercontent.com/u/76651664/snap3.nps 

and snap 3 :)

**Comment by LunNova** [comment]
Yes, this does seem to be an AE issue. However I'm afraid to mess with AE now that it actually works! :(

**Comment by floh22** [comment]
ive found that if you make the crafting cubes smaller it seems to make it a bit better. also something i have noticed: indexers cause HUGE amounts of lag when there are about over 1k bees in them. people have gotten the ticktime up to 800ms with one that has about 500k bees

**Comment by Puremin0rez** [comment]
Applied Energetics is sadly one of the laggiest mods on my server, had to remove it.

Auto crafting will DESTROY you. Even moving around disks with like 700k items in them caused everything to lock up. It's too easy to make this mod cripple your server, sadly.

**Comment by LunNova** [comment]
The best method of finding what's causing lag spikes is to set the DeadlockDetector time to 1 in the config.

Snapshots are better when left running for a longer time, and used to find overall performance issues.

**Comment by HaoSs07** [comment]
yah, tried this 3 times but i had bad luck :)) the spike did not happen again after restart. also players did not login back, i was in lag spike mode with 4 players online and nothing to log .

its ok if i run the server in lag spike longer ? a full day or so ?

**Comment by LunNova** [comment]
You could just leave it permanently in lag spike mode, it'll still detect and restart after a deadlock if it's stopped for > 45 seconds.

**Comment by HaoSs07** [comment]
https://gist.github.com/HaoSs07/5677354

lagspike, it seems i always get this when i reboot with lagspike on. and only once

**Comment by LunNova** [comment]
That one's caused by FE being slow to check permissions.

**Comment by HaoSs07** [comment]
hmm. i'm getting some lag spikes with multiple deadlocks ,server recovers after 5-10 seconds, but the log remains clean :|
![2013-05-30_17 44 32](https://f.cloud.github.com/assets/3189195/585440/d90fae56-c937-11e2-8843-94a6e3c02205.png)

**Comment by LunNova** [comment]
There was a bug which was causing it only to report the first lag spike. It should now work correctly.

**Comment by HaoSs07** [comment]
are you sure you fixed it ? i have lag spikes but log clean...

**Comment by HaoSs07** [comment]
started to work after the second restart :)

https://gist.github.com/HaoSs07/5679086

but it seems to be the same one, fe related

**Comment by LunNova** [comment]
Yes. You may want to report that one to FE.

**Comment by HaoSs07** [comment]
I have bugs moths old reported there, and sill no fix, bugs are not even present in the next 1.3 milestone, that has no ETA, also they have moved on to 1.5, and only 1.5, 1.4.7 is somewhat dead :) I will see FTB launcher 2 and ultimate 1.6 before they fix this. I'm probably better of just dealing with it :)

LE. il upload another cpu sampler, see what you can detect there, if nothing new, just close this

**Comment by HaoSs07** [comment]
https://dl.dropboxusercontent.com/u/76651664/snapfinal.nps

40 minuts or so snap,there was some nasty 100% cpu spike in this one...

**Comment by LunNova** [comment]
And made another change which fixes a case where the report wouldn't've been made when it should have. I'll look at the snapshot soon.

**Comment by HaoSs07** [comment]
so ? anything from the snapshot ?

**Comment by LunNova** [comment]
Far too much time is being wasted in ForgeEssentials' permissions checking. If possible, swap to an alternative, maybe MyTown or MCPC+ + a bukkit protections plugin.

**Comment by LunNova** [comment]
If FE has any settings for database caching try increasing the memory it can use for that.

**Comment by HaoSs07** [comment]
mcpc/bukkit protections don't work good. for example they cant stop a quary from mining your house. 
ill try to remove protection module as i;m not using it anyway. they did something strange there. made protection for every item in game banned by default. and config containing huge amount of items set to true for them to work. Usually its the other way around. all true by default and only ban what you need.
