### ISSUE TITLE
MCPC L38 TT 1736 World Update Entities very high causing low TPS

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#598]
Hey there seems to be a problem with the amount of time being spend on updating entities now there is only about 2k entities on the world, this is with the tps down to 10 now its not even chunk related it seems its like the whole server lag spikes since the chunks all go up and down in the time it takes to tick them

![2013-05-29_19 37 19](https://f.cloud.github.com/assets/3965516/580776/f5916e38-c88e-11e2-8e36-655162ace602.png)

**Comment by LunNova** [comment]
updateEntities includes entities and tile entities, it normally is the highest. Still need a profiling snapshot to find what's causing your problem.
