### ISSUE TITLE
MCPC+ 1.5.2 B486 Exception ticking world

### ISSUE THREAD

**Issue by CircaShoes** [MinimallyCorrect/TickThreading#599]
Server Crash after 10 Minutes

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 5/29/13 10:26 PM
Description: Exception ticking world

java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
    at net.minecraft.entity.monster.EntitySkeleton.func_82164_bB(EntitySkeleton.java:343)
    at net.minecraft.entity.monster.EntitySkeleton.func_82163_bD(EntitySkeleton.java:420)
    at net.minecraft.world.SpawnerAnimals.func_77188_a(SpawnerAnimals.java:336)
    at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:262)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:358)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:821)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:728)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:612)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:174)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.entity.monster.EntitySkeleton.func_82164_bB(EntitySkeleton.java:343)
    at net.minecraft.entity.monster.EntitySkeleton.func_82163_bD(EntitySkeleton.java:420)
    at net.minecraft.world.SpawnerAnimals.func_77188_a(SpawnerAnimals.java:336)
    at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:262)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:358)

-- Affected level --
Details:
    Level name: DIM7
    All players: 2 total; [EntityPlayerMP['_truxx'/15, l='DIM7', x=221.82, y=72.16, z=514.18](_truxx at 221.82138653266446,72.15806667911451,514.1757245392977), EntityPlayerMP['Circa_Shoes'/394, l='DIM7', x=213.74, y=31.42, z=517.77](Circa_Shoes at 213.74288818232088,31.419999986886978,517.7745801190182)]
    Chunk stats: ServerChunkCache: 473 Drop: 0
    Level seed: -1875833685
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (0,33,0), Chunk: (at 0,2,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 5146 game time, 5146 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 87276 (now: false), thunder time: 121614 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:821)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:728)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:612)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

-- System Details --
Details:
    Minecraft Version: 1.5.2
    Operating System: Linux (amd64) version 3.8.13-c6_MC_c_300_a
    Java Version: 1.7.0_15, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 267191904 bytes (254 MB) / 830668800 bytes (792 MB) up to 2863333376 bytes (2730 MB)
    JVM Flags: 2 total; -Xmx3072M -Xms256M
    AABB Pool Size: 5865 (328440 bytes; 0 MB) allocated, 2 (112 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 32
    CraftBukkit Information: 
   Running: CraftBukkit version git-MCPC-Plus-jenkins-MCPC-Plus-486 (MC: 1.5.2) (Implementing API version 1.5.2-R0.2-SNAPSHOT) true
   Plugins: {}
   Warnings: DEFAULT
   Threads: { RUNNABLE DestroyJavaVM: [], RUNNABLE Listen thread: [java.net.PlainSocketImpl.socketAccept(Native Method), java.net.AbstractPlainSocketImpl.accept(Unknown Source), java.net.ServerSocket.implAccept(Unknown Source), java.net.ServerSocket.accept(Unknown Source), net.minecraft.server.ServerListenThread.run(ServerListenThread.java:82)], TIMED_WAITING Thread-5: [java.lang.Thread.sleep(Native Method), net.minecraft.server.dedicated.DedicatedServerSleepThread.run(SourceFile:60)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Unknown Source), org.bukkit.craftbukkit.v1_5_R3.CraftCrashReport.call(CraftCrashReport.java:27), net.minecraft.crash.CrashReportCategory.func_71500_a(CrashReportCategory.java:106), net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:59), net.minecraft.crash.CrashReport.<init>(CrashReport.java:41), net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:302), net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:825), net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320), net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:728), net.minecraft.server.MinecraftServer.run(MinecraftServer.java:612), net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)], RUNNABLE Signal Dispatcher: [], TIMED_WAITING process reaper: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Connection #5 read thread: [java.net.SocketInputStream.socketRead0(Native Method), java.net.SocketInputStream.read(Unknown Source), java.net.SocketInputStream.read(Unknown Source), java.io.FilterInputStream.read(Unknown Source), org.bouncycastle.crypto.io.CipherInputStream.nextChunk(Unknown Source), org.bouncycastle.crypto.io.CipherInputStream.read(Unknown Source), java.io.FilterInputStream.read(Unknown Source), net.minecraft.network.packet.Packet.func_73272_a(Packet.java:156), net.minecraft.network.TcpConnection.func_74447_i(TcpConnection.java:300), net.minecraft.network.TcpConnection.func_74450_c(TcpConnection.java:528), net.minecraft.network.TcpReaderThread.run(SourceFile:94)], RUNNABLE Connection #8 read thread: [java.net.SocketInputStream.socketRead0(Native Method), java.net.SocketInputStream.read(Unknown Source), java.net.SocketInputStream.read(Unknown Source), java.io.FilterInputStream.read(Unknown Source), org.bouncycastle.crypto.io.CipherInputStream.nextChunk(Unknown Source), org.bouncycastle.crypto.io.CipherInputStream.read(Unknown Source), java.io.FilterInputStream.read(Unknown Source), net.minecraft.network.packet.Packet.func_73272_a(Packet.java:156), net.minecraft.network.TcpConnection.func_74447_i(TcpConnection.java:300), net.minecraft.network.TcpConnection.func_74450_c(TcpConnection.java:528), net.minecraft.network.TcpReaderThread.run(SourceFile:94)], WAITING TC Aura Update Thread: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), thaumcraft.common.aura.AuraUpdateThread.run(AuraUpdateThread.java:21), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Spigot Metrics Thread: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)], TIMED_WAITING Thread-78: [java.lang.Thread.sleep(Native Method), net.minecraft.network.TcpMasterThread.run(SourceFile:298)], TIMED_WAITING Connection #8 write thread: [java.lang.Thread.sleep(Native Method), net.minecraft.network.TcpWriterThread.run(TcpWriterThread.java:49)], WAITING TC Aura Calculation Thread: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), thaumcraft.common.aura.AuraCalculationThread.run(AuraCalculationThread.java:23), java.lang.Thread.run(Unknown Source)], WAITING Chunk I/O Executor Thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], TIMED_WAITING File IO Thread: [java.lang.Thread.sleep(Native Method), net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:36), net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:22), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Thread-77: [java.lang.Thread.sleep(Native Method), net.minecraft.network.TcpMonitorThread.run(SourceFile:375)], WAITING TC Aura Deletion Thread: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), thaumcraft.common.aura.AuraDeleteThread.run(AuraDeleteThread.java:19), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Connection #5 write thread: [java.lang.Thread.sleep(Native Method), net.minecraft.network.TcpWriterThread.run(TcpWriterThread.java:49)], WAITING Thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), cpw.mods.fml.relauncher.FMLRelaunchLog$ConsoleLogThread.run(FMLRelaunchLog.java:79), java.lang.Thread.run(Unknown Source)], RUNNABLE Thread-6: [java.io.FileInputStream.readBytes(Native Method), java.io.FileInputStream.read(Unknown Source), java.io.BufferedInputStream.fill(Unknown Source), java.io.BufferedInputStream.read(Unknown Source), java.io.FilterInputStream.read(Unknown Source), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader$1.read(ConsoleReader.java:167), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:267), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:204), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:995), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1167), net.minecraft.server.dedicated.DedicatedServerCommandThread.run(DedicatedServerCommandThread.java:37)], TIMED_WAITING Spigot Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:87)],}
   Recent tasks from 15052-15082{}
    FML: MCP v7.51 FML v5.2.12.712 Minecraft Forge 7.8.0.712 58 mods loaded, 58 mods active
    mcp{7.44} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{5.2.12.712} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{7.8.0.712} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.5.2.2} [CoFH Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{0.8.6.9} [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowerCrystalsCore{1.1.6} [PowerCrystals Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_bspkrsCore{v2.06(1.5.2)} [bspkrsCore]([1.5.2]bspkrsCorev2.06.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    QuiverMod{1.3.1} [QuiverMod](craftbukkit.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHNetwork{1.5.2.2} [CoFHNetwork](CoFHCore-1.5.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHWorld{1.5.2.2} [CoFHWorld](CoFHCore-1.5.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TreeCapitator{Forge 1.5.2.r01} [TreeCapitator]([1.5.2]TreeCapitator.Forge.1.5.2.r01.Uni.CoreMod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DamageIndicatorsMod{2.7.0.1} [Damage Indicators](1.5.2 DamageIndicators v2.7.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    barrels{1.9} [The Barrels Mod](Barrels 1.5+.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.2.3} [BiblioCraft](BiblioCraft[v1.2.3].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CyanSwords{1.5.5} [Cyan Warrior Swords](Cyan_Swords_Mod_v.1.5.5_beta.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtrabiomesXL{3.13.1} [ExtrabiomesXL](ExtrabiomesXL-universal-1.5.2-3.13.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    minechem{@VERSION@} [MineChem](MineChem_v3.0.0.129.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{3.5.3} [BuildCraft](buildcraft-A-3.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{3.5.3} [BC Builders](buildcraft-A-3.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{3.5.3} [BC Energy](buildcraft-A-3.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{3.5.3} [BC Factory](buildcraft-A-3.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{3.5.3} [BC Transport](buildcraft-A-3.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{2.4.3.0} [Thermal Expansion](ThermalExpansion-2.4.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2{1.115.338-lf} [IndustrialCraft 2](industrialcraft-2_1.115.338-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded{1.5.1R2.6.0} [MineFactory Reloaded](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAppliedEnergistics{1.5.1R2.6.0} [MFR Compat: Applied Energistics](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAtum{1.5.1R2.6.0} [MFR Compat: Atum](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatBackTools{1.5.1R2.6.0} [MFR Compat: BackTools](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatBiomesOPlenty{1.5.1R2.6.0} [MFR Compat: Biomes O' Plenty](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatChococraft{1.5.1R2.6.0} [MFR Compat: Chococraft](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatExtraBiomes{1.5.1R2.6.0} [MFR Compat: ExtraBiomes](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForestryPre{1.5.1R2.6.0} [MFR Compat: Forestry (2)](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry{2.2.4.3} [Forestry for Minecraft](forestry-A-2.2.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForestry{1.5.1R2.6.0} [MFR Compat: Forestry](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatIC2{1.5.1R2.6.0} [MFR Compat: IC2](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatMagicalCrops{1.5.1R2.6.0} [MFR Compat: Magical Crops](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatMystcraft{1.5.1R2.6.0} [MFR Compat: Mystcraft](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatNatura{1.5.1R2.6.0B1} [MFR Compat: Natura](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatPams{1.5.1R2.6.0} [MFR Compat: Pam's Mods](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatRP2{1.5.1R2.6.0} [MFR Compat: RP2](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatSoulShards{1.5.1R2.6.0} [MFR Compat: SoulShards](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatSufficientBiomes{1.5.1R2.6.0} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{3.0.5e} [Thaumcraft](Thaumcraft3.0.5e.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MFReloaded|CompatThaumcraft{1.5.1R2.6.0} [MFR Compat: Thaumcraft](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatThermalExpansion{1.5.1R2.6.0} [MFR Compat: ThermalExpansion](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatTConstruct{1.5.1R2.6.0B1} [MFR Compat: TConstruct](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{1.18.1} [The Twilight Forest](twilightforest-1.18.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatTwilightForest{1.5.1R2.6.0} [MFR Compat: TwilightForest](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatVanilla{1.5.1R2.6.0} [MFR Compat: Vanilla](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatXyCraft{1.5.1R2.6.0} [MFR Compat: XyCraft](MineFactoryReloaded-2.6.0-862.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Railcraft{7.1.0.0} [Railcraft](Railcraft_1.5.1-7.1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowerConverters{1.5.1R2.3.0} [Power Converters](PowerConverters-2.3.0-54.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SGCraft{0.4.0} [SG Craft](SGCraft-0.4.0-mc1.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer{1.0.4} [Thaumic Tinkerer](Thaumic Tinkerer [1.0.4].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WirelessRedstoneCore{1.7} [Wireless Redstone](WirelessRedstone-Universal-v1.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{3.5.3} [BC Silicon](buildcraft-A-3.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{5.2.6.424} [Iron Chest](ironchest-universal-1.5.2-5.2.6.424.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AdvancedSolarPanel{3.3.7} [Advanced Solar Panels](mod_AdvancedSolarPanels_3_3_7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 102 (5712 bytes; 0 MB) allocated, 37 (2072 bytes; 0 MB) used
    Player Count: 2 / 4; [EntityPlayerMP['_truxx'/15, l='DIM7', x=221.82, y=72.16, z=514.18](_truxx at 221.82138653266446,72.15806667911451,514.1757245392977), EntityPlayerMP['Circa_Shoes'/394, l='DIM7', x=213.74, y=31.42, z=517.77](Circa_Shoes at 213.74288818232088,31.419999986886978,517.7745801190182)]
    Is Modded: Definitely; Server brand changed to 'mcpc,craftbukkit,fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by LunNova** [comment]
TickThreading isn't for 1.5.2, also did you post this issue to the wrong place?

**Comment by DarkenMoon** [comment]
Will it update to 1.5.2 anytime soon? Cause I am going to need this really soon.

**Comment by LunNova** [comment]
The plan is to begin working on updating it after my last exam on friday. Of course, it is likely to be VERY, VERY, VERY buggy initially, with so many mods updating and needing new patches.

**Comment by DarkenMoon** [comment]
Alright, thanks for the update/news.
