### ISSUE TITLE
[TT v1715] [MCPC++ 41] Exception in thread "Deadlock Detector"

### ISSUE THREAD

**Issue by vanZeben** [MinimallyCorrect/TickThreading#600]
After this exception is thrown the server half responds. Chunks will update and the server responds to pings, but blocks/chests/items/commands cannot be interacted with...

http://pastebin.com/Q2LpT274

**Comment by LunNova** [comment]
Already fixed in latest.

**Comment by vanZeben** [comment]
Oh sorry, must have overlooked it
