### ISSUE TITLE
[MCPC +31] [TT1748] Null point on dump

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#609]
Works fine if I put in the cordnates but not if I look at a block or just in the air and type /dump

12:10:32 [INFO] cjm721 issued server command: /dump
12:10:32 [SEVERE] java.lang.NullPointerException
12:10:32 [SEVERE]   at me.nallar.tickthreading.minecraft.commands.DumpCommand.dump(DumpCommand.java:58)
12:10:32 [SEVERE]   at me.nallar.tickthreading.minecraft.commands.DumpCommand.processCommand(DumpCommand.java:52)
12:10:32 [SEVERE]   at me.nallar.tickthreading.minecraft.commands.Command.b(Command.java:63)
12:10:32 [SEVERE]   at x.a(CommandHandler.java:91)
12:10:32 [SEVERE]   at org.bukkit.craftbukkit.v1_4_R1.command.CraftSimpleCommandMap.dispatch(CraftSimpleCommandMap.java:53)
12:10:32 [SEVERE]   at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchVanillaCommand(CraftServer.java:553)
12:10:32 [SEVERE]   at iv.d(NetServerHandler.java:1395)
12:10:32 [SEVERE]   at iv.chat(NetServerHandler.java:1258)
12:10:32 [SEVERE]   at iv.a(NetServerHandler.java:1182)
12:10:32 [SEVERE]   at cu.a(Packet3Chat.java:59)
12:10:32 [SEVERE]   at cg.b(TcpConnection.java:467)
12:10:32 [SEVERE]   at iv.d(NetServerHandler.java:220)
12:10:32 [SEVERE]   at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
12:10:32 [SEVERE]   at iw.b(NetworkListenThread.java)
12:10:32 [SEVERE]   at ht.b(DedicatedServerListenThread.java:34)
12:10:32 [SEVERE]   at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:414)
12:10:32 [SEVERE]   at ho.r(DedicatedServer.java:309)
12:10:32 [SEVERE]   at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:292)
12:10:32 [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:194)
12:10:32 [SEVERE]   at fy.run(ThreadMinecraftServer.java:16)

**Comment by LunNova** [comment]
`/dump` is supposed to require coordinates. Right click with a clock while opped and it will run /dump for you.

edit: Do you still want it to /dump the block in front of you if you use it without giving coordinates? The clock should make that unnecessary.

**Comment by cjm721** [comment]
Ok. use to things just saying proper user /yada kind of thing

**Comment by LunNova** [comment]
It was supposed to, should be fixed now.
