### ISSUE TITLE
[TT 1758, MCPC L28] [ForgeModLoader] Exception loading chunk asynchronously. java.lang.OutOfMemoryError: PermGen space

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#612]
Server runs fine for 1-2 hours, then suddenly crashes and restarts.

[ForgeModLoader] Exception loading chunk asynchronously.
java.lang.OutOfMemoryError: PermGen space

> at java.lang.Class.getDeclaredConstructors0(Native Method)
> at java.lang.Class.privateGetDeclaredConstructors(Class.java:2413)
> at java.lang.Class.getConstructor0(Class.java:2723)
> at java.lang.Class.newInstance0(Class.java:345)
> at java.lang.Class.newInstance(Class.java:327)
> at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:399)
> at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:396)
> at java.security.AccessController.doPrivileged(Native Method)
> at sun.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:395)
> at sun.reflect.MethodAccessorGenerator.generateConstructor(MethodAccessorGenerator.java:94)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:48)
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
> at lv.a(EntityList.java:139)
> at aam.a(ThreadedChunkLoader.java:440)
> at aam.a(ThreadedChunkLoader.java:185)
> at aam.a(ThreadedChunkLoader.java:159)
> at im.f(ThreadedChunkProvider.java:708)
> at im.getChunkAtInternal(ThreadedChunkProvider.java:528)
> at im.getChunkAt(ThreadedChunkProvider.java:502)
> at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:882)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Set the `-XX:MaxPermSize=176m` java parameter. If you have already done so, try 256m. If this still occurs, but just takes longer, you have a permgen leak.

**Comment by mainsheep** [comment]
I didn't see that statement in your link on https://github.com/nallar/TickThreading/blob/master/INSTALL.md ..

Added that JVM option now (176M) :) Fingers crossed.

**Comment by LunNova** [comment]
It's not necessary for most people, the permgen space is where classes(and some other things such as interned strings) are stored. As you add more mods and plugins, with more code and more classes, you may need to increase its size.

**Comment by mainsheep** [comment]
Ok I understand.. Thank you for your fantastic support :) Keep up the good work.

**Comment by mainsheep** [comment]
Does it matter if it's a small m or a large M in this option?

Sorry for n00bish questions :/

**Comment by mainsheep** [comment]
At 1h40m mark, the server started lagging.

A /lag showed the following:
2013-05-31 12:35:38 [INFO] Current TPS = 15.3
2013-05-31 12:35:38 [INFO] Maximum memory: 29,306 MB.
2013-05-31 12:35:38 [INFO] Allocated memory: 29,306 MB.
2013-05-31 12:35:38 [INFO] Free memory: 29,306 MB.

The server seem to crash very close to 1h40m every time.

I now put the 256m in the MaxPerm statement, so fingers crossed.

**Comment by LunNova** [comment]
If MaxPermGen size is the issue it should just crash, probably won't make it laggy. If you can get a snapshot while it's being laggy that would be helpful.

**Comment by mainsheep** [comment]
Issue was caused by Prism it seems.. Closing thread.
