### ISSUE TITLE
[TT # 1784] More Lag Spike Issues

### ISSUE THREAD

**Issue by floh22** [MinimallyCorrect/TickThreading#623]
Its spamming in the console:

http://pastebin.com/Dmqycq5k

seems to be the reason the server is lagging, cause when the error is gone the server runs fine

**Comment by LunNova** [comment]
This is during chunk saving. I'll make chunk saving more configurable, currently TT aims to regularly save not very many chunks, unlike vanilla which less regularly saves many chunks.

Obviously, this isn't working. What does `/ticks` show for `PartialSave`?

**Comment by LunNova** [comment]
The latest commit should also reduce the time it takes to perform a partial save.

**Comment by floh22** [comment]
one sec, ima install the newest version of TT

**Comment by floh22** [comment]
partialsave is at 347

**Comment by LunNova** [comment]
Try latest, PartialSave should be lower.

**Comment by LunNova** [comment]
Actually latest would just crash, sorry. Working now.

**Comment by floh22** [comment]
this caused the server to crash with the newest build:

http://pastebin.com/4jLNicCB

**Comment by LunNova** [comment]
github didn't auto-close this due to odd commit message wording, should've been closed via 74de696.
