### ISSUE TITLE
[Question] TickProfiler

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#626]
Noticed https://github.com/nallar/TickProfiler on your build sever and was wondering what it was compared to TickThreading, IE is it just the profiling stuff from tickthreading or is it more.

**Comment by LunNova** [comment]
It's just TT's `/profile [e/c]` commands as a separate, more stable mod. It also currently has one extra feature, JSON output for periodic profiling, but I'll be merging that back into TT soon.
