### ISSUE TITLE
[DUPE] [MCPC +31] [TT1781] AE item duplicated when pulled out.

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#628]
Had a member on my server just duplicate a  canvas bag by trying to spam pull it out of a ME Chest. Been trying to replicate it but have not been able to. Also about to update the server anyways if this has been fixed.

Member that did it is trustworthy so  he is not messing with me and I saw all the duplicated bags when I pulled them out of his inventory.

**Comment by LunNova** [comment]
Can you try, on the same server without TT, to get this to happen?

This is handled in the network tick, and that is not made concurrent by TT, so I expect this could also occur without TT.

Unless you turned on concurrent network ticks in TT's config, then that would probably be the cause.

**Comment by CappyT** [comment]
Be aware that: Canvas Bag has a duplication glitch, quite easy to do... I don't know if you patched it or fixed it... but here's a youtube video explaining how to do this.
http://www.youtube.com/watch?v=QT9jhMHJ5tI

Hope it helps keep your server safe.

**Comment by LunNova** [comment]
Previously TT patched that out, but that broke RP tweaks. Since RP tweaks fixes that, and some other issues, it's best just to install RP tweaks.

**Comment by LunNova** [comment]
Also, don't tell the user you disabled TT. I half suspect they found a different dupe bug and are trying to invent a fake issue with AE to blame it on. Maybe a bit cynical of me, but I've seen it happen before.

**Comment by cjm721** [comment]
@CappyT I use rptweaks to fix that. Have another 4 Dupes blocked with my plugin and like I said the player that did it is trustworthy and came to me right after it happened.

I been trying to get this to happen at all, I'll keep trying and I do keep and eye on quite a few forums and blogs that post about glitches/dupes/etc before they usually hit youtube and such.

Also I know AE been having some issues with itself so TT or not @nallar done a pretty awesome job of fixing other peoples mistakes and improving upon ideas.

And to make more clear it was not just a client side visual bug of duplicated items as I used a plugin to look inside his inventory and took them right after he told me.

**Comment by HaoSs07** [comment]
@nallar any chance you can fix forestry backpacks dupe like you did with canvas ? can't manage to ban them. tried like 3 different ways(including FE banlist), best thing i managed to make is to remove custom id's from the config and only let normal ores enter backpacks , and get duplicated...

**Comment by alicheek** [comment]
oh god yea that would be a great one if u could fix it maybe just make it you can do shortcuts or something have to manually place the items in the bag and all that

**Comment by cjm721** [comment]
Ok I was finally able to recreate it. I used my Logitech G13 to click extremely fast (80+ clicks per second) and was able to duplicate items. Not 100% about 1/10 attempts worked. Have to be careful at least with using my method as the java buffer gets filled extremely fast.

From testing in single player have not been able to recreate it. Also from talking again to that player he was stating it seemed to happen when his connection lagged for a second (which i assumed placed his buffered actions very close to each-other time wise)

**Comment by LunNova** [comment]
Confirmed not to be a TT bug then, in single player? Report it to algo, although it might already be fixed as you're stuck on an old AE version.

**Comment by cjm721** [comment]
@nallar I was not able to do the dupe in singleplayer. It is hard to get it to work even in multiplayer with TT so it is by no means 100%, but I was able to replicate it twice in 10 minutes. As for multiplayer server without TT I have not been able to do it, my game just crashes from overload.

**Comment by LunNova** [comment]
Intentionally kill the TPS on a normal server and try to get it to happen, this will make it easier to get the removals processed on the same network tick.

**Comment by LunNova** [comment]
Still unable to reproduce this issue. @cjm721 can you still get it to happen? Has anyone else been able to get it to happen?

**Comment by cjm721** [comment]
I can test again since you made the other changes to Applied Energetics. Just now to think how to cause lag as I use to use ME crafting to cause it but you fixed that now.

**Comment by cjm721** [comment]
I have been noticing that my System that controls my fussion reactor is having a net increase of cells even though I have no input into it. Part is I do not know if that has something to do with all the GT machines or with ME.  Considering would setting the ticks to run at to 1 be the same effect for network ticks as causing mass lag or not since its not really having to calculate very much?

**Comment by HaoSs07** [comment]
+1 for cell dupe. also have a report of this. used with fusion reactor. from 5k cells it went up to 22k. 
his build is a mix of ae and routers

**Comment by cjm721** [comment]
Same here using Routers AE and GregTech buffers.

**Comment by HaoSs07** [comment]
i suspect to be the routers but i will test it first to be sure
