### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by BitVector** [MinimallyCorrect/TickThreading#63]
It would be nice to have colors in the /tps and /ticks commands to help distinguish information in them.

**Comment by Puremin0rez** [comment]
I agree :+1:

**Comment by keplersj** [comment]
+1

**Comment by LunNova** [comment]
Technically implemented in latest - although just for table cell dividers.

**Comment by LunNova** [comment]
![](http://i.imgur.com/UGzoOLb.png)
