### ISSUE TITLE
TT1786 / MCPC L5[0,5,7] Routers High Tick time - Load

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#637]
Been seeing this a lot lately.

![2013-06-02_06 12 19](https://f.cloud.github.com/assets/4019875/596235/c4afcf96-cb75-11e2-9bfd-56eb1191741e.png)
![2013-06-02_06 12 22](https://f.cloud.github.com/assets/4019875/596236/c6b14504-cb75-11e2-963e-64bd9ff6a616.png)
![2013-06-02_06 12 35](https://f.cloud.github.com/assets/4019875/596237/c964e24c-cb75-11e2-80fa-da66fff13243.png)
![2013-06-02_06 12 54](https://f.cloud.github.com/assets/4019875/596238/cb8ef2d8-cb75-11e2-814e-664b8e6c9a07.png)
![2013-06-02_06 12 56](https://f.cloud.github.com/assets/4019875/596239/ce0c537a-cb75-11e2-8e5a-6f8e4f603a2d.png)

**Comment by HaoSs07** [comment]
can confirm this. but not sure its TT related.
Routers are in top of my lag list also when used with allot of machines. like 1 router for 30-40 machines. make huge lag

**Comment by Nohau** [comment]
yea seeing the same thing a single router can create huge load but can be just a single machine as well and causes this unfortunately.

**Comment by HaoSs07** [comment]
would probably help if you made screen also with the router setup

**Comment by cjm721** [comment]
I notice high load from a few routers when I use with my 256 apiary field. Happens most often when there is no available slot (assume a shortcircuit for loop ie when it finds something it stops looking). just for how the router works does several checks per block per tick it might just be doing to much more then a leak.
