### ISSUE TITLE
MFFS begging down the server (Performance Idea)

### ISSUE THREAD

**Issue by CappyT** [MinimallyCorrect/TickThreading#639]
Hello everyone,
My server use the MFFS mod to provide protections to players... The problem is when someone turns on a big shield... the server freezes for some moments, and kicks a lot of people.
Can this action be less laggy? Cause i faced some problems also with some forcefields with insufficient energy, "blinking" and begging down the server...

Thank you again nallar for the hard work =)

**Comment by HaoSs07** [comment]
at the start i also used MFFS for protection, even if i reported a memory leak and performance got improved by allot, something like 80 %. MFFS still lags the server :)

try mytown and pex. ( ported one ) in you want a clean with good protection server

**Comment by cjm721** [comment]
In the MFFS config:

```
# How many field blocks can be generated per tick? (Default = 5000)
I:forcefieldmaxblockpeerTick=5000
```

lower number means its going to place less blocks per tick ie less cpu requirement for it.

**Comment by CappyT** [comment]
@cjm721 reduce that number is a bad idea, cause the server freezes for more long time, since it must do more tick to generate a big shield. Tested. 5000 is a right number, but still freeze the server.

@HaoSs07 The problem is that my server is a free-pvp raiding, so my players MUST craft shields to protect their stuff. I don't want a faction-town based server...

**Comment by LunNova** [comment]
Decreasing that number is definitely supposed to improve performance, might want to report that as an MFFS bug.

**Comment by CappyT** [comment]
@nallar well, from my tests, the lower the number, the bigger the time the server is freezed.
Try to set 500. After turning on a sphere shield, you must wait 10-15 minutes. Of course, server freezed.

**Comment by alicheek** [comment]
What you are saying is wrong 500 blocks will be generated per tick 500 blocks for the CPU to generate that is 4500 less per tick for the original settings. So think about it 5000 blocks to generate in one tick is much more intensive than 500

**Comment by HaoSs07** [comment]
if there is a bug in the time itself and not the number of blocks generated, having a lower number may make more lag then having a highter one. this needs some testing

**Comment by CappyT** [comment]
@alicheek read what @HaoSs07  said, is what I mean. The problem is not the CPU load, but the time the server it gets freezed.

**Comment by alicheek** [comment]
@CappyT  did the test with 500 ur right the server gets bogged down people get disconnected as well , big lag spikes occur

**Comment by HaoSs07** [comment]
can u also test using . lets say 10.000 blocks /t ?

**Comment by alicheek** [comment]
cant do it atm, would have to restart the server and 80 people would be raging at me! maybe some one else can have a go?

**Comment by HaoSs07** [comment]
to bad he did not put any config for max FF dimension, fixed shape. and thinks like that . i had to ban MFFS when 1 player made max size FF and killed the server :)
