### ISSUE TITLE
Server lagging, tickthreading solution?

### ISSUE THREAD

**Issue by hipy** [MinimallyCorrect/TickThreading#643]
Hi,

My server has a lot of mods, the cpu is constantly spiking 100%+

A list of mods that I have installed:
Baconmod 
Buildcraft 
CompactSolars 
ComputerCraft 
Ender Storage Mod 
Equivalent Exchange 3 
ExtrabiomesXL 
Factorization 
IC2 
IC2 Nuclear Control 
Iron chests mod 
Power Converters 
NEI 
Rei's minimap 
Basic Components(UE) 
Galacticraft 
Easycrafting

I found out that galacticraft was the origin of the lag. After contacting them I was send here.. recommending tickthreading. Will this solve the problem of lag? My server runs 1.5.1 so I don't think it will be a quick solution :s

screenshot: http://s.hipy.nl/XaJ2FL.png

**Comment by LunNova** [comment]
See #448. 1.5 support will come once 1.4.7 is stable.

I too am unsure of why they sent you here when there is no version of TT for 1.5 yet.

**Comment by LunNova** [comment]
Oh, also, you may want to swap to the default texture pack while using TickProfiler, or use the default font. The tables won't line up with different fonts. Doesn't matter if it doesn't bother you.
