### ISSUE TITLE
TT1818 /profile c - Still NPE's

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#644]
9:57:59 PM
 CONSOLE:
[INFO] LadyDivine issued server command: /profile c 7 0
9:58:01 PM
 Prism]::
&9Bigdaddy11d7 found 3 lapis ore 26% light
9:58:05 PM
 CONSOLE:
[SEVERE] Exception in thread "TickProfiler"
9:58:05 PM
 CONSOLE:
[SEVERE] java.lang.NullPointerException
9:58:05 PM
 CONSOLE:
[SEVERE] at me.nallar.tickthreading.minecraft.commands.ProfileCommand$1.run(ProfileCommand.java:93)
9:58:05 PM
 CONSOLE:
[SEVERE] at me.nallar.tickthreading.minecraft.profiling.EntityTickProfiler$1.run(EntityTickProfiler.java:70)
9:58:05 PM
 CONSOLE:
[SEVERE] at java.lang.Thread.run(Thread.java:722)

**Comment by LunNova** [comment]
That's because it's using 7, 0 as the chunk coords, not the time and dimension.
