### ISSUE TITLE
Strange overcrowding of mobs in specific chunks

### ISSUE THREAD

**Issue by BitVector** [MinimallyCorrect/TickThreading#65]
Our aPerf mod showed an unusual amount of monsters spawning in chunks that are within the -8 x-coordinate as shown here:
![2013-01-17_17 59 53](https://f.cloud.github.com/assets/744690/76919/75466a8a-610a-11e2-8fed-f6e638fae43a.png)

We cleared out a few of the chunks that had hundreds of mobs in them:

![2013-01-17_17 48 06](https://f.cloud.github.com/assets/744690/76923/9ba576ee-610a-11e2-9eb0-5dc1ca75282f.png)

![2013-01-17_17 54 18](https://f.cloud.github.com/assets/744690/76924/a8ffea54-610a-11e2-8c04-452809298917.png)

Our aPerf SpawnLimiter is currently off, and TickThreading fast mobs is on.

**Comment by Puremin0rez** [comment]
Hehehe, I noticed this last night with Fast mobs on - I see why it's defaulted off :)

**Comment by LunNova** [comment]
Fixed in build 472 - I can't do bitwise math :(
