### ISSUE TITLE
TT1826 profile c still no worky

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#653]
Also to note no matter what you type in as for cordinates it always says the wrong cordinates  below screenshot : 

![2013-06-03_17 16 46](https://f.cloud.github.com/assets/4019875/602439/59f1264c-cc9b-11e2-9e4b-b5c0935da38b.png)

The error without cords : 

5:14:41 PM
 CONSOLE:
[INFO] Nohau issued server command: /profile c
5:14:47 PM
 CONSOLE:
[SEVERE] Exception in thread "TickProfiler"
5:14:47 PM
 CONSOLE:
[SEVERE] java.lang.NullPointerException
5:14:47 PM
 CONSOLE:
[SEVERE] at me.nallar.tickthreading.minecraft.commands.ProfileCommand$1.run(ProfileCommand.java:99)
5:14:47 PM
 CONSOLE:
[SEVERE] at me.nallar.tickthreading.minecraft.profiling.EntityTickProfiler$1.run(EntityTickProfiler.java:70)
5:14:47 PM
 CONSOLE:
[SEVERE] at java.lang.Thread.run(Thread.java:722)
5:14:51 PM
 CONSOLE:
[SEVERE] Not in range.
5:14:51 PM
 CONSOLE:
[INFO] AdeClark issued s

The error with cords : 

5:15:59 PM
 CONSOLE:
[INFO] Nohau issued server command: /profile c 207 161
5:16:07 PM
 CONSOLE:
[SEVERE] Exception in thread "TickProfiler"
5:16:07 PM
 CONSOLE:
[SEVERE] java.lang.NullPointerException
5:16:07 PM
 CONSOLE:
[SEVERE] at me.nallar.tickthreading.minecraft.commands.ProfileCommand$1.run(ProfileCommand.java:99)
5:16:07 PM
 CONSOLE:
[SEVERE] at me.nallar.tickthreading.minecraft.profiling.EntityTickProfiler$1.run(EntityTickProfiler.java:70)
5:16:07 PM
 CONSOLE:
[SEVERE] at java.lang.Thread.run(Thread.java:722)
5:16:13 PM
 CONSOLE:
[SEVERE] Could not pass event EntityExplodeEvent to Prism v1.6.2-MC1.4-Compat
5:17:27 PM
 CONSOLE:
[INFO] Nohau issued server command: /profile c 207 161
5:17:35 PM
 CONSOLE:
[SEVERE] Exception in thread "TickProfiler"
5:17:35 PM
 CONSOLE:
[SEVERE] java.lang.NullPointerException
5:17:35 PM
 CONSOLE:
[SEVERE] at me.nallar.tickthreading.minecraft.commands.ProfileCommand$1.run(ProfileCommand.java:99)
5:17:35 PM
 CONSOLE:
[SEVERE] at me.nallar.tickthreading.minecraft.profiling.EntityTickProfiler$1.run(EntityTickProfiler.java:70)
5:17:35 PM
 CONSOLE:
[SEVERE] at java.lang.Thread.run(Thread.java:722)

**Comment by Nohau** [comment]
Yes @Nallar you can blow me up on a test server if you want to after i keep reporting issues on profile c :P MIght stand up a server just so you can place a nuke near me lol!

**Comment by LunNova** [comment]
It uses chunk coordinates, not block coordinates. NPE is still an issue,
