### ISSUE TITLE
Jenkins Problems?

### ISSUE THREAD

**Issue by floh22** [MinimallyCorrect/TickThreading#655]
recently i have been having trouble downloading Tickthreading. a single download takes about 20 minutes. anyone else having this problem? everything else on the internet is fine.

edit: now its not downloading all...

**Comment by LunNova** [comment]
Fixed now?

**Comment by floh22** [comment]
still slow but its downloading at a decent speed. the dl takes one minute.. a week ago it took 5 seconds :p dont worry though, its fine

**Comment by HaoSs07** [comment]
it think is from you. works good for me. download in under 1 sec.

**Comment by floh22** [comment]
odd. everything else works just fine
