### ISSUE TITLE
[TT # 1830] Server Deadlock

### ISSUE THREAD

**Issue by floh22** [MinimallyCorrect/TickThreading#656]
the server almost starts up normally, then just doesnt respond:

http://pastebin.com/nsF7rSDW

**Comment by floh22** [comment]
confirmed to not happen without tick threading

**Comment by LunNova** [comment]
This is actually a BC bug (now fixed), not sure why TT is making it more likely to happen. I'll try to include the fix as a patch.

**Comment by floh22** [comment]
you are amazing. i had to reset the map now though since i was trying to fix it and then corrupted the world with chicken chunks. amazing....

**Comment by LunNova** [comment]
You don't keep backups? :(
