### ISSUE TITLE
Redwood trees decaying for no reason

### ISSUE THREAD

**Issue by BitVector** [MinimallyCorrect/TickThreading#66]
Extrabiomes XL Redwood trees are dropping their saplings like crazy, and there seems to be no apparent reason for the decay. No players have chopped any logs or broke any leaf blocks, however, all redwood leaf blocks are decaying and will probably eventually leave the redwoods bare naked.

![2013-01-17_19 55 28](https://f.cloud.github.com/assets/744690/77153/068994da-611b-11e2-8edd-90d31cb85a95.png)

This might not be TT-related, however, we haven't ever had this issue before, so I'm just making sure Nallar knows about it.

Also, another thing that might be related is that I have been receiving CMEs occasionally when I try to remove those Redwood saplings with aPerf (they are, at the moment, dropping hundreds every few seconds).

**Comment by Puremin0rez** [comment]
I've had this issue a few times too, but it seems to happen randomly on my server.

https://github.com/nallar/TickThreading/issues/46
