### ISSUE TITLE
[TT 1826, MCPC L60] High ticks from area 0 0 again

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#661]
> 2013-06-05 09:22:38 [INFO] [TickThreading]
> World: Overworld/0
> ---- Slowest tick regions ----
>   |    X |     Z |   N |   Time
> T |    0 |     0 |  10 | 16.084
> T | 1568 | -1328 | 670 | 10.046
> T | 1568 | -1312 | 277 |  4.695
> E | 2944 |  1296 |   1 |  1.866
> T | 1584 | -1328 | 478 |  1.511
> T | 1296 | -1424 | 878 |  1.482
> E | 1824 | -2208 |   2 |  1.171
> ---- World stats ----

Restart of the server removes the problem temporary. After a couple of hours, the problem is back.

**Comment by LunNova** [comment]
When this happens, what does `/profile c 0 0` show?

**Comment by mainsheep** [comment]
TPS: 18.703598
                Single Entity | Time/Tick |      %
    EntityPassengerSeat 0,0,0 |     0.001 | 49.306
projectile.EntityArrow 0,35,0 |     0.001 | 28.472
projectile.EntityArrow 0,74,0 |     0.000 | 22.222
Chunk | Time/Tick |       %
 0, 0 |     0.002 | 100.000
  All Entities of Type | Time/Tick |      %
projectile.EntityArrow |     0.001 | 50.694
   EntityPassengerSeat |     0.001 | 49.306
Average Entity of Type | Time/tick | Calls
   EntityPassengerSeat |     0.001 |   130
projectile.EntityArrow |     0.001 |   260
