### ISSUE TITLE
Crash on First Install

### ISSUE THREAD

**Issue by Charredspear** [MinimallyCorrect/TickThreading#663]
**Background:** First time user; was hoping to get this installed client side- then upload the data to my hosted server (and potentially use it client side- way too many mods / entities in my base as it stands, and would love a some more tps localization).

**Modpack:** FTB Direwolf20 1.4.7+ BetterDungeons, ArsMagica, DynamicElavators, EnchantingPlus, gregtech(290h)

**Outside Influences:** Was using Optifine (however tried it without aswell), using **ID resolver**

 **Getting the out of date errors:** 2013-06-05 18:14:53 [INFO] [TickThreading] Started TT metrics reporting. This can be disabled in PluginMetrics.cfg
2013-06-05 18:14:54 [WARNING] [TickThreading] Patching required for D:\Feed the Beast\Direwolf20\minecraft\mods\thermalexpansion.zip because it is out of date.
Expected 1196531359, got null

  **The error log includes numerous mods including, but not limited to:** MinecraftForge,  Twilight forest, Railcraft, Redpower, Xycraft, etc... and for **TickThreading 1.4.7-1.0.0.1834.jar.**

-Ran the patcher (instantly disappears- used CMD (-k) function to keep it on screen), listed the following error:
  *\* Could not find or load main class me.nallar.tickthreading.patcher.patchmain**

-Not to be dissuaded I began some extensive google-fu; however, here I am six hours later and no progress has been made.
  I did see that you instructed someone (back in January) to use a custom "patchme.cmd" which would not require a fresh install; which would be lovely. However, this did not fix the issue.

-All the best to you, if I can get this thing working and it is sexy... man hugs for all!

Didn't post the client-side logs as they all say the same thing- out of date. Here's the pastebin if you wanted a little light reading while you soak in your bath tub, with lit candles, soft jazz and a glass of chardonnay wine

[Pastebin: Awe, it's broke](http://pastebin.com/tjxcfsqB)

**Comment by cjm721** [comment]
As far as I know it Tickthreading is not made to be ran in single player yet and is just for servers (said someone on the forums). If you want to just test it out I would suggest getting MCPC+ then installing Ticktreading and copying over your world file to it and then connect to it as a local server.

**Comment by LunNova** [comment]
As @cjm721 points out, TT is not currently for clients. I may be releasing another coremod which should help with FPS, even if TT did work on clients the benefit would be small as tile/entity ticks are not normally too slow on clients.
