### ISSUE TITLE
[MCPC 66] [TT 1834] IC2 issues and Quantum generator issue

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#664]
Ok don't seem to have any error logs for this but for the IC2 issue whats wrong is that if one of my players try to remove a IC2 machine with a wrench nothing will happen, now if I do it though it works fine with no hassle what so ever, there is also issues where the info boards are not in the right direction an the text wont show of course, this has happened before when we had the early concurrent network thing on but ive not turned it back on.

The quantum generator issue is a bit different, now ive only seen it for this gregtech machine but might be with other machines also, what the issue is that if you try and change the outputs value of the generator it wont respond and will just stay at 512

**Comment by alicheek** [comment]
back on 1822 and every thing is working fine again

**Comment by cjm721** [comment]
I am running MCPC 31 and TT 1834 also, but I am not having these issues. Both info panels work fine and quantum generator also works fine.

**Comment by alicheek** [comment]
may be something to do with L66 then but weird thing is its working fine now since I went back to TT 1822

**Comment by alicheek** [comment]
ok same thing is happening with TT 1822 now seems to be a MCPC issue

**Comment by LunNova** [comment]
Can you check if it happens with MCPC+ L66 without TT?

**Comment by alicheek** [comment]
its now doing it on version of TT 1839 and MCPC L61

**Comment by alicheek** [comment]
ill try to see if its fine with out TT , does seem to be that this occurs over time and not straight away its strange, it just reminds me when ever I tried turning on concurrent network ticks , most IC2 items like solar panels would no longer be facing up to the sun and the info panels wouldn't be connecting together or be in the right direction and the foam blocks would become invisible when a wire is In the middle of them

**Comment by cjm721** [comment]
And I have started to notice some strange things also. Randomly players could not use a minion stone to craft. Restart fixed the issue but it was not happening when the server started.

**Comment by alicheek** [comment]
ah yea we have that issue also

**Comment by cjm721** [comment]
I forgot to mention Running MCPC 31 TT 1834/1837

**Comment by alicheek** [comment]
just a little update im on  MCPC L67 TT 1852 , this issue is still occurring, it doesn't happen straight away though; it seems to be over a period of time the server is on then some blocks will not be facing the right way.

Here are some pics:

As you can see here the solars to my right are fine (they are ones ive just placed then) the ones to my left were like this but when you go to another place that involves unloading this chunk and then come back they go like that.
![2013-06-10_15 44 59](https://f.cloud.github.com/assets/3965516/632172/3cdc20b0-d1dd-11e2-98c9-fc61cf671033.png)

Its the same with these info panels; however this does not occur to advanced solar panels or ultimate or hybrid since its another mod
![2013-06-10_15 30 57](https://f.cloud.github.com/assets/3965516/632179/69063c02-d1dd-11e2-8495-b5138d1c8084.png)

**Comment by Slind14** [comment]
are u using multiverse ? or any other mutliworld bukkit plugin ?

**Comment by alicheek** [comment]
yes im using multiverse  but this world is the over world so it shouldn't have an issue I would of thought

**Comment by alicheek** [comment]
Sorry wrong button yet again lol

**Comment by Slind14** [comment]
try it without multiverse. i had the same issue without TT after i switched from multiverse to mystcraft it was gone

**Comment by alicheek** [comment]
ok tested as soon as you use a multiworld plugin this breaks, IC2 blocks used to never be affected in the overworld, only on the other multiworld plugin worlds. But ever since going to the new versions of TT even the overworld is affected by this, not sure if there is something you can do just to make it work again for the overworld or not, not too bothered if it doesn't work for the other worlds.

**Comment by Slind14** [comment]
its a mcpc+ with multiworld plguins issue not tt

**Comment by alicheek** [comment]
ah lol dam kinda wishing it was a TT issue now :P MCPC no longer do any more fixes for our version :(

**Comment by Slind14** [comment]
yeah, but they wouldnt if it would be still supported, too

**Comment by alicheek** [comment]
why would that be? :/

**Comment by Slind14** [comment]
i asked them before, they said it is to much work and they will focus on more important stuff

**Comment by alicheek** [comment]
lol I would of said it was important , oh well :P
