### ISSUE TITLE
[TT] Crash at Startup

### ISSUE THREAD

**Issue by RandyF** [MinimallyCorrect/TickThreading#666]
Possibly related to mod headers?  Null pointer?

Pasted: http://pastebin.com/AMrL67Qs

**Comment by RandyF** [comment]
Hmm... Issue #666.  Sorry about that!

**Comment by LunNova** [comment]
Are you using an old version of http://www.minecraftforge.net/forum/index.php/topic,1102.0.html ?

Update it, the mod dev made a mistake which I pointed out on the first page of that thread, so it should be fixed now.
