### ISSUE TITLE
TT stopping mining turtles

### ISSUE THREAD

**Issue by doctruscott** [MinimallyCorrect/TickThreading#667]
I have noticed a issue where i have a mining turtle set up and its working fine untill i leave for a extended time, the area is chunk loaded ( chicken chunkloaders ) but the turtle will stop and go from a mining turtle to a normal turtle. i have disabled world unloading via 
 # Whether worlds should be allowed to unload.
    B:allowWorldUnloading=false
and 

   # Whether to clean worlds on unload - this should fix some memory leaks due to mods holding on to world objects
    B:cleanWorlds=false

pastebin of the entire config file : http://pastebin.com/8zJNLp43

any idea on how to fix this?

**Comment by LunNova** [comment]
Fixed, see #678.
