### ISSUE TITLE
[MCPC 61] [TT 1839] Jason profiler :profiler.txt doesnt seem to be structured properly? 

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#675]
If you open up the .txt file with notepad ++ its just all in one line it seems so is a bit hard to read.

[[{"%":"3.606","Time/Tick":"4.092","Single Entity":"gadgets.TileGearbox 2024,60,1995"},{"%":"1.820","Time/Tick":"2.066","Single Entity":"TileLogicPointer 679,81,-1270"},{"%":"1.620","Time/Tick":"1.838","Single Entity":"gadgets.TileGearbox -2575,73,-2846"},{"%":"0.545","Time/Tick":"0.619","Single Entity":"Carts.entMCBase 2022,136,1959"},{"%":"0.481","Time/Tick":"0.546","Single Entity":"EntityGolemWood 6204,58,2322"},{"%":"0.413","Time/Tick":"0.468","Single Entity":"tile.TileChest -3302,59,-3023"},{"%":"0.222","Time/Tick":"0.306","Single Entity":"Carts.entMCBase -623,64,2615"},{"%":"0.213","Time/Tick":"0.241","Single Entity":"TileEntityConverter 4037,58,140"},{"%":"0.174","Time/Tick":"0.197","Single Entity":"gadgets.TileMachine -2585,72,-2823"},{"%":"0.158","Time/Tick":"0.180","Single Entity":"TileConduitEnergy -2588,65,-2805"},{"%":"0.158","Time/Tick":"0.179","Single Entity":"EntityTFSkeletonDruid 4233,40,4924"},{"%":"0.156","Time/Tick":"0.177","Single Entity":"TileEntityAreaDefenseStation 59,43,833"},{"%":"0.155","Time/Tick":"0.176","Single Entity":"TileEntityCapacitor 165,95,396"},{"%":"0.148","Time/Tick":"0.168","Single Entity":"Carts.entMCBase -355,64,2144"},{"%":"0.144","Time/Tick":"0.163","Single Entity":"player.EntityPlayerMP -2557,72,-2821"},{"%":"0.144","Time/Tick":"0.163","Single Entity":"TileEntityAreaDefenseStation 4671,60,4630"},{"%":"0.141","Time/Tick":"0.160","Single Entity":"TileEntityAreaDefenseStation 169,91,396"},{"%":"0.134","Time/Tick":"0.152","Single Entity":"TileEntityAreaDefenseStation -2526,63,512"},{"%":"0.132","Time/Tick":"0.150","Single Entity":"TileOutputCable -2541,59,508"},{"%":"0.129","Time/Tick":"0.146","Single Entity":"EntityGolemStraw -2551,85,-2819"}],[{"%":"4.273","Time/Tick":"4.962","Chunk":"-158, 32"},{"%":"4.070","Time/Tick":"4.726","Chunk":"126, 124"},{"%":"3.548","Time/Tick":"4.119","Chunk":"-207, -189"},{"%":"2.447","Time/Tick":"2.841","Chunk":"-161, -176"},{"%":"2.377","Time/Tick":"2.760","Chunk":"126, 123"},{"%":"2.105","Time/Tick":"2.444","Chunk":"-160, -176"},{"%":"1.991","Time/Tick":"2.312","Chunk":"-162, -176"},{"%":"1.982","Time/Tick":"2.302","Chunk":"-161, -178"},{"%":"1.962","Time/Tick":"2.279","Chunk":"388, 145"},{"%":"1.927","Time/Tick":"2.238","Chunk":"-162, -177"},{"%":"1.893","Time/Tick":"2.198","Chunk":"10, 24"},{"%":"1.841","Time/Tick":"2.138","Chunk":"42, -80"},{"%":"1.835","Time/Tick":"2.130","Chunk":"241, -208"},{"%":"1.832","Time/Tick":"2.127","Chunk":"-1, -62"},{"%":"1.802","Time/Tick":"2.092","Chunk":"-161, -177"},{"%":"1.759","Time/Tick":"2.043","Chunk":"-206, -189"},{"%":"1.746","Time/Tick":"2.027","Chunk":"173, -91"},{"%":"1.633","Time/Tick":"1.896","Chunk":"126, 122"},{"%":"1.581","Time/Tick":"1.836","Chunk":"199, -57"},{"%":"1.525","Time/Tick":"1.770","Chunk":"-96, 20"}],[{"%":"10.638","All Entities of Type":"TileGenericPipe","Time/Tick":"12.352"},{"%":"6.609","All Entities of Type":"gadgets.TileMachine","Time/Tick":"7.673"},{"%":"5.229","All Entities of Type":"gadgets.TileGearbox","Time/Tick":"6.071"},{"%":"4.377","All Entities of Type":"TileTankIronWall","Time/Tick":"5.082"},{"%":"3.612","All Entities of Type":"TileConduitEnergy","Time/Tick":"4.193"},{"%":"3.433","All Entities of Type":"TileConduitLiquid","Time/Tick":"3.986"},{"%":"3.038","All Entities of Type":"TileEntityTransformerLV","Time/Tick":"3.528"},{"%":"2.905","All Entities of Type":"core.EntityBlock","Time/Tick":"3.373"},{"%":"2.894","All Entities of Type":"BaseMetaTileEntityMJ","Time/Tick":"3.360"},{"%":"2.810","All Entities of Type":"silicon.TileLaser","Time/Tick":"3.262"},{"%":"2.797","All Entities of Type":"TileEntityBarrel","Time/Tick":"3.248"},{"%":"2.131","All Entities of Type":"TileEntityChest","Time/Tick":"2.474"},{"%":"2.097","All Entities of Type":"TileLogicPointer","Time/Tick":"2.435"},{"%":"1.944","All Entities of Type":"TileTankIronGauge","Time/Tick":"2.257"},{"%":"1.851","All Entities of Type":"machine.TileTube","Time/Tick":"2.150"},{"%":"1.742","All Entities of Type":"TileEntityTransformerMV","Time/Tick":"2.023"},{"%":"1.725","All Entities of Type":"gadgets.TileEngine","Time/Tick":"2.003"},{"%":"1.623","All Entities of Type":"TileEntitySolarGenerator","Time/Tick":"1.885"},{"%":"1.408","All Entities of Type":"TileEntityCapacitor","Time/Tick":"1.635"},{"%":"1.359","All Entities of Type":"alpha.TileCokeOven","Time/Tick":"1.578"}],[{"Time/tick":"1.967","Average Entity of Type":"gadgets.TileGearbox","Calls":"531"},{"Time/tick":"0.475","Average Entity of Type":"tile.TileChest","Calls":"177"},{"Time/tick":"0.377","Average Entity of Type":"EntityTFNatureBolt","Calls":"5"},{"Time/tick":"0.178","Average Entity of Type":"EntityTFSkeletonDruid","Calls":"180"},{"Time/tick":"0.173","Average Entity of Type":"Carts.entMCBase","Calls":"1207"},{"Time/tick":"0.149","Average Entity of Type":"EntityGolemWood","Calls":"885"},{"Time/tick":"0.088","Average Entity of Type":"TileLogicPointer","Calls":"4782"},{"Time/tick":"0.082","Average Entity of Type":"TileEntityConverter","Calls":"708"},{"Time/tick":"0.073","Average Entity of Type":"TileEntityAreaDefenseStation","Calls":"2655"},{"Time/tick":"0.072","Average Entity of Type":"TileEntityCapacitor","Calls":"4071"},{"Time/tick":"0.057","Average Entity of Type":"EntityGolemStone","Calls":"354"},{"Time/tick":"0.054","Average Entity of Type":"EntityGolemStraw","Calls":"708"},{"Time/tick":"0.050","Average Entity of Type":"TileEntitySequencer","Calls":"177"},{"Time/tick":"0.049","Average Entity of Type":"player.EntityPlayerMP","Calls":"3732"},{"Time/tick":"0.046","Average Entity of Type":"EntityGolemStoneAdvanced","Calls":"177"},{"Time/tick":"0.040","Average Entity of Type":"TileEntityNuclearReactorElectric","Calls":"1124"},{"Time/tick":"0.038","Average Entity of Type":"core.EntityRobot","Calls":"177"},{"Time/tick":"0.037","Average Entity of Type":"silicon.TileLaser","Calls":"15983"},{"Time/tick":"0.033","Average Entity of Type":"TileEntityProjector","Calls":"1239"},{"Time/tick":"0.032","Average Entity of Type":"TileBlueAlloyFurnace","Calls":"177"}]]

**Comment by alicheek** [comment]
{Time/tick":"0.037","Average Entity of Type":"silicon.TileLaser","Calls":"15983"} 

Also does that look right seems quite a lot of calls (don't know much about these things though)?

**Comment by Nohau** [comment]
That is valid JSON  if that is what you mean you can check by doing a google search for json validators and formators which make it easier to read.

I just checked it  in : http://jsonlint.com/

**Comment by LunNova** [comment]
It's not supposed to be human readable, this is for if you want another program to be able to read the profiling data from TT.

**Comment by alicheek** [comment]
What program what I use to read the profiling data? :)

**Comment by LunNova** [comment]
If you want human readable data, just don't set that to true.

**Comment by alicheek** [comment]
ah ok
