### ISSUE TITLE
Random shutdown.

### ISSUE THREAD

**Issue by ThuGie** [MinimallyCorrect/TickThreading#679]
Hey guys,

I keep getting random shutdowns in my server.
Error is different each time.

In my eyes you guys are the fix it all guys with this plugin :$
As i aint sure what the problem is i hope you guys dont mind me posting this here in the hope you guys can solve it.

its to big so here :) http://pastebin.com/MJy0436e
updated TickThreading and MCPC-Plus(L66) to latest version both.
Using extra bukkit plugins
ChatManager,Modifyworld with PermissingEx < the 2 before it belong with permissionEx
ColorMe
CoreProtect
GriefPrevention
SimpleSpawn

Hope this helps.

**Comment by LunNova** [comment]
Update your JRE. Looks like java is crashing hard when trying to start computercraft threads, and an outdated java is a likely cause. Few things can cause hard crashes.

**Comment by ThuGie** [comment]
I did as you said and within a half hour or so it happened again
http://pastebin.com/jcjA7uki

Really not sure what the problem is as you can see it should be latest java now.
Any help is good :p.

I would even give you root access if you think you can fix it.
Currently the players are leaving cause of the often crashing.
