### ISSUE TITLE
TickThreading exception java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by geoffcorey** [MinimallyCorrect/TickThreading#68]
Jar - TickThreading-1.4.6-1.0.0.466.jar

This error was repeated about every few minutes when I was the only one on the server.

Gist - https://gist.github.com/4565750

Symptoms:

High CPU when nobody was on, however there were likely a couple of chunk loaders present.  migration process was very high.   Changed kernel.sched_nr_migrate=32 to kernel.sched_nr_migrate=2 to see if that helps.

Let me know if I can provide anymore information.

**Comment by geoffcorey** [comment]
Updated Gist with kernel.sched_nr_migrate=2    Made things worse.   Backed out the change and set it back to 32

**Comment by LunNova** [comment]
Do you have the full log for that deadlock? It seems to be cut off, as it's only showing computercraft threads.

The concurrent modification exception can probably be worked around by turning off concurrent world ticking, I've still not figured out what's causing it - see issue #58.

**Comment by geoffcorey** [comment]
Unfortunately the logs have been rotated off.   Running it today with your recommended JVM settings and no issues.  

java -server -Xms512M -Xmx7G -XX:UseSSE=4 -XX:+UseCMSCompactAtFullCollection -XX:ParallelGCThreads=6 -XX:+UseConcMarkSweepGC -XX:+DisableExplicitGC -XX:+CMSIncrementalMode -XX:+CMSIncrementalPacing -XX:+UseCompressedOops -XX:+AggressiveOpts -Xmx8192M -jar mindcrack.jar nogui

Let's call this issue closed for now.   I will dump the world if it occurs again on pastebin.
