### ISSUE TITLE
Entities not ticked in worlds with no players

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#685]
As title says

**Comment by LunNova** [comment]
Worlds with chunk loaders should not be unloaded, I'll add a check for that.

**Comment by HaoSs07** [comment]
it does not actualy unload the world.made a mistake there. but when i had worldunload on false. all things in nether worked . but now when its back on,if the player leaves nether, they do not. but the world remains listed under /tps

**Comment by HaoSs07** [comment]
hmm seems nether with no players still wont work. sory cant give you more info.dont have time to make more tests. i have exams. only report what players tell me...

**Comment by HaoSs07** [comment]
an update on this. only happens when things are loaded with world anchor. if using chicken chunk loaders. they work after leaving the nether.

**Comment by ZigTheHedge** [comment]
Nope. Even with CC spotloaders nether stops working when last player leaves it.
