### ISSUE TITLE
Teleportation Bugs

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#687]
Im using MCPC with TickThreading, both latest versions. 

When I dont turn B:antiCheatNotify=false Then it will spam me with eveyone speedhacking or movement hacks.

Now I have it false so it wont spam me, but when I tp over a lond distance like /tpa or /spawn it will move me quickly trough the old and the new posistion. It stopts after an couple seconds.

It still does the same but only doesnt send an message. This drops my ticks quite bad. 
It runs 20 constant but when some poeple teleport it goes to 17 and then later back to 20.
(Around 80/90 people online)

**Comment by alicheek** [comment]
yea this is something that has been around in TT for quite a while now when u tp to a position u spaz from the new pos to the old one never really thought anything about it but I suppose its not something that really should not occur

**Comment by darkdeath1332** [comment]
Its really annoying my players, and when it really drops my TPS

**Comment by darkdeath1332** [comment]
Oops wrong button...

**Comment by cjm721** [comment]
From a previous report @nallar mentioned all that is doing is taking the vanilla notify and tells ops.

**Comment by Slind14** [comment]
who needs this. let ur user use fly/speed hack but do something against xray

**Comment by darkdeath1332** [comment]
no, that against xray is in mcpc. I want to kill that fly cheat function !

**Comment by Slind14** [comment]
than install a plugin, and the mcpc+ anti xray isnt working
i told them this, but they just closed the ticket

**Comment by cjm721** [comment]
@slind14 @agaricusb told you why it was closed and linked you to other issues to explain what all is still broken (no support currently over id 255). 

As for the teleportation issue only time I ever spas is when both locations are in client side view distance, but as for it dropping your TPS it should no unless the chunks are not loaded, but that is a harddrive access problem more then CPU (could put a chunkloader at spawn if that is the case)

**Comment by LunNova** [comment]
Any better now? Tweaked the teleportation timings in latest.
