### ISSUE TITLE
TPS command 

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#688]
I have worldedit, worldguard for /lag but it shows 2 diffrent things.

First one is from /lag
Second is the command /tps

Screenshot:
![image](https://f.cloud.github.com/assets/3824354/629363/fc5eadac-d144-11e2-9de6-c6dd02664799.png)

**Comment by cjm721** [comment]
As a side note that is not the tps command from tickthreading. Its from a plugin. I had to go into the tickthreading config and change the command to ttps so I could use it.

**Comment by LunNova** [comment]
I have no idea which one is correct, I made neither of those commands. Use TT's TPS command, it should be correct.

**Comment by Nohau** [comment]
That right there is the /gc command and most versions like mcpc+ it has it's own ttps command whic TT doesn't override the way you get it working is change TT's config file  for tps command to something else.
