### ISSUE TITLE
Dynmap+Tickthreading

### ISSUE THREAD

**Issue by Konman156** [MinimallyCorrect/TickThreading#689]
My Map keeps going black when rendering. Any fix for this? im using 1.7

**Comment by Konman156** [comment]
Any ideas?

**Comment by nicecube** [comment]
I have the same bug but i find a solution ... i use the old version of dynmap plugins for tekkit and everything work perfect now. I tried the last version of dynmap mod + dynmap bridge but dynmap stay black

**Comment by Konman156** [comment]
Which version do u use

**Comment by Konman156** [comment]
I tried 1.6 that didn't work.I guess there is no fix

**Comment by LunNova** [comment]
Try latest.

**Comment by Konman156** [comment]
latest dynmap also?

**Comment by Konman156** [comment]
Just updating tt didn't work.  I'm using dynmap 1.6

**Comment by LunNova** [comment]
Patch was against 1.7, can you try that?

**Comment by Konman156** [comment]
After work I will.  Then I'll let you know 
.thx man

**Comment by Konman156** [comment]
i dont think its working . i replaced 1.6 jar with 1.7

**Comment by Konman156** [comment]
okay trying 1.7.1

**Comment by LunNova** [comment]
There were two issues, both broke it. Try latest again.
