### ISSUE TITLE
Chunkloading still not working #1843

### ISSUE THREAD

**Issue by krim404** [MinimallyCorrect/TickThreading#691]
All chunkloaders are not working on the latest version. No errors - just not working.
Tested with: ChickenChunks, Railcraft WorldAnchors

**Comment by alicheek** [comment]
I haven't got this issue and I'm on the latest TT

**Comment by LunNova** [comment]
Also unable to get this to happen.

**Comment by krim404** [comment]
Fixed after uninstall of LogisticPipes. Dunno why

**Comment by LunNova** [comment]
Asked in #RS485, and they also have no idea why. Closing this as invalid/wontfix, as I can't get it to happen, and many other TT users are successfully using LP.
