### ISSUE TITLE
Severe Exceptions

### ISSUE THREAD

**Issue by Apallo** [MinimallyCorrect/TickThreading#693]
These seem to happen randomly.

13:03:55 >2013-06-10 14:04:26 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.transport.tileentity.TileTeleportEnergy @1045210022 in Overworld/0 at x, y, z: 5130, 23, 720
13:03:55 java.util.ConcurrentModificationException
13:03:55 at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
13:03:55 at java.util.HashMap$KeyIterator.next(HashMap.java:874)
13:03:55 at buildcraft.factory.TilePump.getNextIndexToPump(TilePump.java:172)
13:03:55 at buildcraft.factory.TilePump.isActive(TilePump.java:303)
13:03:55 at buildcraft.factory.TileMachine.powerRequest(TileMachine.java:20)
13:03:55 at thermalexpansion.core.Utils.addToAdjPowerProvider(Utils.java:131)
13:03:55 at thermalexpansion.transport.tileentity.TileTeleportEnergy.addToAdjPowerProvider(TileTeleportEnergy.java:172)
13:03:55 at thermalexpansion.transport.tileentity.TileTeleportEnergy.receiveEnergy(TileTeleportEnergy.java:137)
13:03:55 at thermalexpansion.transport.tileentity.TileTeleportEnergy.sendEnergy(TileTeleportEnergy.java:115)
13:03:55 at thermalexpansion.transport.tileentity.TileTeleportEnergy.g(TileTeleportEnergy.java:160)
13:03:55 at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
13:03:55 at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
13:03:55 at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
13:03:55 at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
13:03:55 at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

[SEVERE] [TickThreading] Exception ticking entity iq['OxNil'/13225, l='world', x=6463.88, y=59.00, z=3768.05](OxNil at 6463.877517641478,59.0,3768.050000011921) in rX: 403, rZ: 235, hashCode: 15401363/Overworld/0:
13:04:46 java.util.ConcurrentModificationException
13:04:46 at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
13:04:46 at java.util.HashMap$EntryIterator.next(HashMap.java:880)
13:04:46 at java.util.HashMap$EntryIterator.next(HashMap.java:878)
13:04:46 at java.util.AbstractCollection.containsAll(AbstractCollection.java:307)
13:04:46 at java.util.AbstractSet.equals(AbstractSet.java:95)
13:04:46 at bq.equals(NBTTagCompound.java:428)
13:04:46 at ur.d(ItemStack.java:407)
13:04:46 at ur.b(ItemStack.java:399)
13:04:46 at rq.b(Container.java:108)
13:04:46 at iq.j_(EntityPlayerMP.java:22)
13:04:46 at yc.a(World.java:391)
13:04:46 at in.a(WorldServer.java:844)
13:04:46 at yc.g(World.java:2717)
13:04:46 at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:54)
13:04:46 at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
13:04:46 at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
13:04:46 at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
13:04:46 at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
13:14:02  [SEVERE] [TickThreading] Exception ticking entity iq['OxNil'/13225, l='world', x=6463.88, y=59.00, z=3768.05](OxNil at 6463.877517641478,59.0,3768.050000011921) in rX: 403, rZ: 235, hashCode: 15401363/Overworld/0:
13:14:02 java.util.ConcurrentModificationException
13:14:02 at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
13:14:02 at java.util.HashMap$EntryIterator.next(HashMap.java:880)
13:14:02 at java.util.HashMap$EntryIterator.next(HashMap.java:878)
13:14:02 at java.util.AbstractMap.hashCode(AbstractMap.java:494)
13:14:02 at bq.equals(NBTTagCompound.java:426)
13:14:02 at ur.d(ItemStack.java:407)
13:14:02 at ur.b(ItemStack.java:399)
13:14:02 at rq.b(Container.java:108)
13:14:02 at iq.j_(EntityPlayerMP.java:22)
13:14:02 at yc.a(World.java:391)
13:14:02 at in.a(WorldServer.java:844)
13:14:02 at yc.g(World.java:2717)
13:14:02 at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:54)
13:14:02 at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
13:14:02 at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
13:14:02 at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
13:14:02 at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
13:14:06  [SEVERE] [TickThreading] Exception ticking entity iq['OxNil'/13225, l='world', x=6463.88, y=59.00, z=3768.05](OxNil at 6463.877517641478,59.0,3768.050000011921) in rX: 403, rZ: 235, hashCode: 15401363/Overworld/0:
13:14:06 java.util.ConcurrentModificationException
13:14:06 at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
13:14:06 at java.util.HashMap$EntryIterator.next(HashMap.java:880)
13:14:06 at java.util.HashMap$EntryIterator.next(HashMap.java:878)
13:14:06 at java.util.AbstractMap.hashCode(AbstractMap.java:494)
13:14:06 at bq.equals(NBTTagCompound.java:426)
13:14:06 at ur.d(ItemStack.java:407)
13:14:06 at ur.b(ItemStack.java:399)
13:14:06 at rq.b(Container.java:108)
13:14:06 at iq.j_(EntityPlayerMP.java:22)
13:14:06 at yc.a(World.java:391)
13:14:06 at in.a(WorldServer.java:844)
13:14:06 at yc.g(World.java:2717)
13:14:06 at me.nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:54)
13:14:06 at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
13:14:06 at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
13:14:06 at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
13:14:06 at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
What build is this on?

**Comment by Apallo** [comment]
TickThreading-1.4.7-1.0.0.1845
