### ISSUE TITLE
[MCPC +31] [TT 1852]  NPE On world save.

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#694]
In my personal plugin I made a auto save every 10 minutes (probably now redundent with TT's) during some of the saves I get this message. All my plugin does is run the save-all command in console.

> 2013-06-10 12:19:52 [SEVERE] [ForgeModLoader] Exception posting event: net.minecraftforge.event.world.WorldEvent$Save@377f3ea0
> 12:19:52 [SEVERE] java.lang.NullPointerException
> 12:19:52 [SEVERE]   at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionEventHandler.onWorldSave(WorldExtensionManager.java:79)
> 12:19:52 [SEVERE]   at net.minecraftforge.event.ASMEventHandler_193_WorldExtensionEventHandler_onWorldSave_Save.invoke(.dynamic)
> 12:19:52 [SEVERE]   at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
> 12:19:52 [SEVERE]   at net.minecraftforge.event.EventBus.post(EventBus.java:104)
> 12:19:52 [SEVERE]   at in.a(WorldServer.java:162)
> 12:19:52 [SEVERE]   at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.save(CraftWorld.java:733)
> 12:19:52 [SEVERE]   at org.bukkit.command.defaults.SaveCommand.execute(SaveCommand.java:30)
> 12:19:52 [SEVERE]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
> 12:19:52 [SEVERE]   at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCommand(CraftServer.java:537)
> 12:19:52 [SEVERE]   at com.gmail.cjmiller721.AdminHelp.AutoSave.run(AutoSave.java:22)
> 12:19:52 [SEVERE]   at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
> 12:19:52 [SEVERE]   at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
> 12:19:52 [SEVERE]   at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
> 12:19:52 [SEVERE]   at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:357)
> 12:19:52 [SEVERE]   at ho.r(DedicatedServer.java:309)
> 12:19:52 [SEVERE]   at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:292)
> 12:19:52 [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:194)
> 12:19:52 [SEVERE]   at fy.run(ThreadMinecraftServer.java:16)

**Comment by LunNova** [comment]
Just xycraft being bad, it has issues :P

There should be no need for running /save-all, TT ensures that changed chunks are saved within a few minutes.

**Comment by cjm721** [comment]
I had the auto save before I installed TT, I should probably just remove it now anyways. Thanks for the info.
