### ISSUE TITLE
[MCPC +31] [TT 1852] Chance to get kicked on opening arcane worktable.

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#697]
> 17:27:58 [INFO] [AdminHelp] §6MikeWalsh313 interacted with Arcane Worktable: world: [COORDS HIDDEN]
> say 2013-06-10 17:28:00 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 9824084
> java.lang.NullPointerException
>     at ur.a(ItemStack.java:454)
>     at sq.b(SlotCrafting.java:71)
>     at thaumcraft.common.container.SlotCraftingArcaneWorkbench.a(SlotCraftingArcaneWorkbench.java:41)
>     at rq.a(Container.java:274)
>     at thaumcraft.common.container.ContainerArcaneWorkbench.a(ContainerArcaneWorkbench.java:174)
>     at iv.a(NetServerHandler.java:1760)
>     at dc.a(Packet102WindowClick.java:46)
>     at cg.b(TcpConnection.java:467)
>     at iv.d(NetServerHandler.java:220)
>     at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
>     at iw.b(NetworkListenThread.java)
>     at ht.b(DedicatedServerListenThread.java:34)
>     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:417)
>     at ho.r(DedicatedServer.java:309)
>     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:292)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:194)
>     at fy.run(ThreadMinecraftServer.java:16)
> 17:28:00 [WARNING] Failed to handle packet for MikeWalsh313/98.113.221.223: java.lang.NullPointerException
> java.lang.NullPointerException
>     at ur.a(ItemStack.java:454)
>     at sq.b(SlotCrafting.java:71)
>     at thaumcraft.common.container.SlotCraftingArcaneWorkbench.a(SlotCraftingArcaneWorkbench.java:41)
>     at rq.a(Container.java:274)
>     at thaumcraft.common.container.ContainerArcaneWorkbench.a(ContainerArcaneWorkbench.java:174)
>     at iv.a(NetServerHandler.java:1760)
>     at dc.a(Packet102WindowClick.java:46)
>     at cg.b(TcpConnection.java:467)
>     at iv.d(NetServerHandler.java:220)
>     at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
>     at iw.b(NetworkListenThread.java)
>     at ht.b(DedicatedServerListenThread.java:34)
>     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:417)
>     at ho.r(DedicatedServer.java:309)
>     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:292)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:194)
>     at fy.run(ThreadMinecraftServer.java:16)
> 17:28:00 [INFO] Unloading Player: MikeWalsh313

**Comment by LunNova** [comment]
This happens with all arcane worktables?

Can you find the exact build this started on? It's an odd issue. :(

**Comment by cjm721** [comment]
Ya I am kinda confused what caused this, but had three players all getting kicked by it. This is the first time I seen it happen as my plugin has notify for arcane work tables and never seen any issues with people opening them before.

**Comment by cjm721** [comment]
Ok I think I narrowed it down. Crafting Tinker Table using gregtech recipies (I had to manually add the recipies https://github.com/cjm721/GregRecipies) so the client can't see the crafting. Tried the other recipies and they work fine. I will look at my code and see if I can figure out why also now that it seems to be in part due to my plugin.

Here I tried with default crafting bench:

> 17:40:42 [WARNING] Failed to handle packet for cjm721/50.122.43.81: java.lang.NullPointerException
> java.lang.NullPointerException
>     at ur.a(ItemStack.java:454)
>     at sq.b(SlotCrafting.java:71)
>     at sq.a(SlotCrafting.java:119)
>     at rq.a(Container.java:274)
>     at iv.a(NetServerHandler.java:1717)
>     at dc.a(Packet102WindowClick.java:46)
>     at cg.b(TcpConnection.java:467)
>     at iv.d(NetServerHandler.java:220)
>     at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
>     at iw.b(NetworkListenThread.java)
>     at ht.b(DedicatedServerListenThread.java:34)
>     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:417)
>     at ho.r(DedicatedServer.java:309)
>     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:292)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:194)
>     at fy.run(ThreadMinecraftServer.java:16)
> 2013-06-10 17:40:42 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 10132187
> java.lang.NullPointerException
>     at ur.a(ItemStack.java:454)
>     at sq.b(SlotCrafting.java:71)
>     at sq.a(SlotCrafting.java:119)
>     at rq.a(Container.java:274)
>     at iv.a(NetServerHandler.java:1717)
>     at dc.a(Packet102WindowClick.java:46)
>     at cg.b(TcpConnection.java:467)
>     at iv.d(NetServerHandler.java:220)
>     at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
>     at iw.b(NetworkListenThread.java)
>     at ht.b(DedicatedServerListenThread.java:34)
>     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:417)
>     at ho.r(DedicatedServer.java:309)
>     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:292)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:194)
>     at fy.run(ThreadMinecraftServer.java:16)

**Comment by cjm721** [comment]
Tracked it down I miss typed an item id in my config 727 != 725.
