### ISSUE TITLE
Build-1859 Tools not working

### ISSUE THREAD

**Issue by Kusinagie** [MinimallyCorrect/TickThreading#699]
Certain tools like the diamond drill(ic2),chainsaw,at least two of the pickaxes from twilightforest( i think the steeleaf and fiery)

Best i can describe it would be the picks gets one hit on a block then the hit count gets reset, so every hit is the first hit it never progresses.

I know the ic2 chainsaw didn't work either (same description) i have yet to test any other tools like shovels or axes.

**Comment by alicheek** [comment]
Yea we have this issue on TT 1859 vanilla items work fine but things like the ic2 drills dont

**Comment by alicheek** [comment]
still the same on TT 1857 think works fine on TT1852 though

**Comment by LunNova** [comment]
Fixed via 1164141c534066a812bc9d931542454e9568f89d.
