### ISSUE TITLE
Divide by Zero error in /tps (Build #234)

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#7]
Every other time the command is used, a divide by zero error is thrown.

You can replicate it pretty easily by spamming /tps over and over again

/ticks also appears to not work at all.

The following commit did not solve the issue:
https://github.com/nallar/TickThreading/commit/15dc70b2d47203cffa30664fd8a6bf0c97bc816d

**Comment by LunNova** [comment]
Should be fixed in de7bc713

**Comment by Puremin0rez** [comment]
@nallar 

Hmm well I'm using Build 234 which is a few commits after that one and it's still causing the issues

**Comment by LunNova** [comment]
Ah, looks like you ran into a different divide by zero error. Should be fixed in build 237.

**Comment by Puremin0rez** [comment]
Fixed :+1:
