### ISSUE TITLE
[TT 1851 and 1859] [MCPC L67] [SEVERE] [TickThreading] Exception while updating block neighbours in Overworld/0 at 2259, 76, 2010

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#702]
When launching my server, the server immediately throw this error. I'm unsure if this is a serious bug or not, but I'm hoping this is something that can be fixed :)

> 2013-06-11 04:34:42 [SEVERE] [TickThreading] Exception while updating block neighbours in Overworld/0 at 2259, 76, 2010
> java.lang.NoClassDefFoundError: Could not initialize class miscperipherals.util.Util
>         at miscperipherals.asm.ASMHelper.getTurtleTanks(ASMHelper.java:68)
>         at dan200.turtle.shared.TileEntityTurtle.getTanks(TileEntityTurtle.java)
>         at thermalexpansion.transport.tileentity.TileConduitLiquid.getAdjacentTankContainers(TileConduitLiquid.java:500)
>         at thermalexpansion.transport.tileentity.TileConduitLiquid.checkIfNode(TileConduitLiquid.java:531)
>         at thermalexpansion.transport.tileentity.TileConduitLiquid.onNeighborBlockChange(TileConduitLiquid.java:334)
>         at thermalexpansion.transport.block.BlockConduit.a(BlockConduit.java:141)
>         at yc.m(World.java:306)
>         at yc.h(World.java:1071)
>         at yc.f(World.java:1015)
>         at dan200.computer.shared.NetworkedComputerHelper.update(NetworkedComputerHelper.java:117)
>         at dan200.turtle.shared.TileEntityTurtle.g(TileEntityTurtle.java:2350)
>         at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
>         at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
>         at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
>         at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
>         at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Still broken? Not sure why TT would break loading that class, and it works for me.

**Comment by mainsheep** [comment]
Nope problem seems to be fixed.
