### ISSUE TITLE
Leaves falling off fir and redwood trees - extremebiomes Ultimate

### ISSUE THREAD

**Issue by donkeypanic** [MinimallyCorrect/TickThreading#703]
Hai Nallar!
Big fan of all your hard work! I've just implemented tickthreading on an FTB Ultimate using mcpc+ build # L67.  When a player enters an extremebiome with redwood and fir trees the leaves begin to instantly decay.  because these trees are so darn big, this is leading to entity issues on the ground with hundreds of saplings falling in the player-loaded area.  I have another server running same pack same mcpc+ build without tickthreading and i can confirm this phenomenon to be unique to TT.  thanks so much for everything nallar.  Have a great day!

**Comment by alicheek** [comment]
which TT version is this?

**Comment by donkeypanic** [comment]
sorry, # 1858 from yesterday

**Comment by alicheek** [comment]
use TT 1852 that should work

**Comment by donkeypanic** [comment]
roger that.  ty ali :)

**Comment by donkeypanic** [comment]
put in 1852.  restarted server, flew to new chunks, loaded and waited.  same effect.  if it helps to test, i could generate a new map and try same.  i have no attachment to the map, and no one is on this server yet.

**Comment by alicheek** [comment]
hmm strange so ur using FTB Ultimate 1.1.2 MCPC+ L67 and TT 1852 but still getting that issue? maybe just try out a new map and see how that goes

**Comment by donkeypanic** [comment]
im genning the map now.  ill find the biome and report back.  meanwhile i tried 1859 and re patched with same effect.  i will wipe it all now and report back.  im also going to launch with no plugin jars installed to further isolate.  may take up to 30m.  thanks again for assistance ali.  any yes ulti 1.1.2 L67 TT1852, 1858, 1859

**Comment by alicheek** [comment]
Yea seems it might be a plugin issue then or something because I'm
On on all of the exact same builds as you , just not sure what plugin could cause that

**Comment by donkeypanic** [comment]
ok well its not the plugins.  running new genned map re-patched 1852 with no plugins.  same same.  im now going to create an entirely separate server with a newly downloaded modpack and see if i can reproduce the effect or if one of my mod files is bugged.  While we wait...i understand there is a patch class file for arcane dupe but i cant find any info.  this is just a side question, but do you know anything about that, per chance :3

**Comment by alicheek** [comment]
ive just made it that its not possible to destroy it tbh didnt even know there was a patch for it lol

**Comment by donkeypanic** [comment]
there is, but the ones who have it seem to be guarding it tightly (or bluffing)  i have a different solution atm: admin alerts with worldguard when its broken. One time you are moving it, 10 times in the same exact spot... well :/ 
im almost done loading in the files on the new server.

**Comment by alicheek** [comment]
tbh ive thought about hiring a coder to fix the issues like the dupes but tbh ive just found loopholes to basically prevent most of them

**Comment by donkeypanic** [comment]
ok i have installed a fresh pack on a new server with only L67.  i have located the biome and am now making sure the leaves do not decay preTT.  I will wait 5 mins and then load and patch in TT and try same test with only L67 and TT on new world new server. and yes.  loopholes ftw XD.

**Comment by donkeypanic** [comment]
Reproduced:
Error: Leaves decay rapidly on their own in lush redwoods biome.
Steps to Reproduce this error:
Install fresh modpack Ultimate1.1.2
Run MCPC+ L67 as a .jar file
Run to generate world
Add any TT 1852-1859
Run Server to generate PATCHME.sh file
Stop server
Run sh PATCHME.sh from SSH
Restart server with patches in place
Navigate to any biome with Redwoods/Fir Trees
Leaves fall off causing loads of saplings on the ground and ugly trees.

Note: this does not appear to effect worlds genned Before the current update, per comments by alicheek.

![2013-06-11_10 53 36](https://f.cloud.github.com/assets/3970126/638021/10e2cd58-d2b2-11e2-800d-8901ffff6310.png)

**Comment by donkeypanic** [comment]
btw, lol dont assume it to do with the nukes in my inv. -.- i blew a big hole AFTER the leaves fell of to test a ticking entity error from another server. i noticed after posting it looks bad.

**Comment by cjm721** [comment]
I can confirm this happening. Was sitting afk on top of a redwood forest come back and there was 500 entities bellow me. Cleared them and then more came back.

**Comment by donkeypanic** [comment]
not sure if its to do with it, but found this anomalous from startup log: (server loaded normally otherwise)
12.06 00:42:44 [Server] WARNING Sufficient Biomes missing - MFR Sufficient Biomes Compat not loading

definitely never saw that before TT.  hope its useful.

**Comment by LunNova** [comment]
This bug is very persistent - it had previously been caused by ticking chunks before population, although that should no longer be happening. Will need to recheck that code.

@donkeypanic, also, thanks for the very generous donation :D

**Comment by donkeypanic** [comment]
lol np nallar you absolutely deserve it man! work on more important stuff than this.  id rather have 20tps and no leaves at all!  also i have put tt on two additional servers (one dw and one ulti) where the worlds had genned before the most recent pack updates, and the bug isnt there.  keep on keepin the pack together buddy! i hope more ppl find a few dollars to shove at you soon!
