### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#704]
This is what gets into my console, I dont know what it is.

2013-06-11 17:04:19 [INFO] [ChestShop] ilan21344 bought 1 X13658 for 500,00 from adminshop at [world] 924, 70, -236
2013-06-11 17:04:19 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.transport.tileentity.TileConduitEnergy @2033072373 in Nether/-1 at x, y, z: 54999, 49, -28336
java.util.ConcurrentModificationException

> ```
>   at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
>   at java.util.HashMap$KeyIterator.next(HashMap.java:874)
>   at buildcraft.factory.TilePump.getNextIndexToPump(TilePump.java:172)
>   at buildcraft.factory.TilePump.isActive(TilePump.java:303)
>   at buildcraft.factory.TileMachine.powerRequest(TileMachine.java:20)
>   at thermalexpansion.transport.tileentity.TileConduitEnergy.transferEnergy(TileConduitEnergy.java:501)
>   at thermalexpansion.transport.GridEnergy.transferEnergy(GridEnergy.java:111)
>   at thermalexpansion.transport.tileentity.TileConduitEnergy.g(TileConduitEnergy.java:337)
>   at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
>   at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
>   at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
>   at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
>   at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
> ```

**Comment by darkdeath1332** [comment]
2013-06-11 18:12:01 [INFO] bruttern123 issued server command: /m darkdeath1332 why go away my things?
2013-06-11 18:12:02 [INFO] cptnnick issued server command: /back
2013-06-11 18:12:03 [INFO] [P] iCraft_: me 2 !
2013-06-11 18:12:13 [INFO] [P] iCraft_: i lost my canvas bag too at this nabby !
2013-06-11 18:12:13 [SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.transport.tileentity.TileConduitEnergy @501671478 in Nether/-1 at x, y, z: 54999, 49, -28336
java.util.ConcurrentModificationException

> ```
>   at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
>   at java.util.HashMap$KeyIterator.next(HashMap.java:874)
>   at buildcraft.factory.TilePump.getNextIndexToPump(TilePump.java:172)
>   at buildcraft.factory.TilePump.isActive(TilePump.java:303)
>   at buildcraft.factory.TileMachine.powerRequest(TileMachine.java:20)
>   at thermalexpansion.transport.tileentity.TileConduitEnergy.transferEnergy(TileConduitEnergy.java:501)
>   at thermalexpansion.transport.GridEnergy.transferEnergy(GridEnergy.java:111)
>   at thermalexpansion.transport.tileentity.TileConduitEnergy.g(TileConduitEnergy.java:337)
>   at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
>   at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
>   at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
>   at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
>   at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
> ```
> 
> 2013-06-11 18:12:13 [INFO] voldean issued server command: /money

**Comment by LunNova** [comment]
Fixed in latest.
