### ISSUE TITLE
Error in console Spam

### ISSUE THREAD

**Issue by nicecube** [MinimallyCorrect/TickThreading#705]
HI nallar first ty vm for TickThreading its awsome
Im using mcpc+ L15
TickThreading-1.4.7-1.0.0.1678.jar

I tried mcpc+ L67 
TickThreading-1.4.7-1.0.0.1840.jar
But not working machine face down ans lost machine in overworld

I have an error on my console spaming every time.
13:02:10 CONSOLE: [SEVERE] Exception while fetching chunks:
13:02:12 CONSOLE: [SEVERE] Exception while fetching chunks:
13:02:12 CONSOLE: [SEVERE] Exception while fetching chunks:
13:02:14 CONSOLE: [SEVERE] Exception while fetching chunks:
13:02:14 CONSOLE: [SEVERE] Exception while fetching chunks:
13:02:16 CONSOLE: [SEVERE] Exception while fetching chunks:
13:02:16 CONSOLE: [SEVERE] Exception while fetching chunks:
13:02:22 CONSOLE: [SEVERE] Exception while fetching chunks:
13:02:52 CONSOLE: [SEVERE] Exception while fetching chunks:

Sometime i have this error i dont know if its linked
13:07:48 CONSOLE: [SEVERE] Exception ticking TileEntity c buildcraft.transport.TileGenericPipe @22084193 in Overworld/0 at x, y, z: -631, 65, -564

I dont know how to fix this 

Ty very much sry for my poor english 

Mods:
AdditionalPipes.jar
AdvancedMachines.zip
AdvancedPowerManagement.jar
AdvancedSolarPanels.zip
buildcraft.jar
compactsolars.zip
ExtrabiomesXL.jar
IC2NuclearControl.zip
industrialcraft.jar
ironchest.zip
Jammy_Furniture.zip
PetroGen.zip
Railcraft.jar
RedPowerCompat.zip
RedPowerCore.zip
RedPowerDigital.zip
RedPowerMechanical.zip
TickThreading-1.4.7-1.0.0.1678.jar
Transformers.zip

Plugins:
Autorank
Buycraft
Citizens2
Disguiscraft
Dynmap
Essentials
FoundDiamonds
HawkEye
iConomie
ItemFrameShop
LWC
Multiverse-core 2.4
Multiverse portal 2.4
Payday
Ported_SimpleBackup.jar
PtFix
Vault
Worldborder
Worldedit
Worldguard

**Comment by LunNova** [comment]
Fixed via e9947ab916f17dfa768b4a49e076625581573ebf.
