### ISSUE TITLE
Urgent! [TickThreading] The server appears to have deadlocked.

### ISSUE THREAD

**Issue by ThuGie** [MinimallyCorrect/TickThreading#706]
Hey,

I got this after upgrading to latest version.
I tried to downgrade but it just kept and kept crashing.
Please help, players aren't quite to happy haha.

http://pastebin.com/b7bQQaZ3

**Comment by LunNova** [comment]
You have a broken xycraft fabricator somewhere.

**Comment by LunNova** [comment]
Try latest.

**Comment by ThuGie** [comment]
Thank you! i will
Btw no error yet!
