### ISSUE TITLE
[MCPC +31] [TT 1852] Y axis swiching on player save/login.

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#708]
Had this happen to two players now. Log out and then log back in and they log in at the negative Y of their position. No clue as to exactly what caused it yet though.

> 14:44:35 [INFO] NicholasLawrence[/90.203.37.135:49467] logged in with entity id 16431335 at ([world_myst/age29] 308.8581949797313, -40.658174329584035, -349.9728523009561)

**Comment by LunNova** [comment]
Does it manage to prevent them dying by moving them to +ve y?

**Comment by cjm721** [comment]
No they fall out of the world. Overworld the moving them back + works.

**Comment by LunNova** [comment]
That should be fixed in latest, although the issue will still happen.

Do players occasionally take fall damage for no apparent reason?

**Comment by cjm721** [comment]
Have not had any reports of taking random fall damage anymore, and even before I only had two people fall out of the world on login out of the 100s that go threw each day.

I'll start running around without my shock absorbers to see if I am taking fall damage or not.
