### ISSUE TITLE
Cant leave server on longer than 2 hours

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#709]
My server runs mostly 20 ticks and without any lag, after some time my server ping starts to drop badly and my tps just start drowning. 

When I type /ticks the slowest chunk is around 1.9 MS. My server haves around 60 players online at that moment and runs really slow. It cant be my CPU or my network, if I check them there both barely loaded.

**Comment by LunNova** [comment]
Please get a profiling snapshot.

**Comment by darkdeath1332** [comment]
Using the /profile command?

**Comment by LunNova** [comment]
Jvisualvm.

**Comment by LunNova** [comment]
But first, check with /tps that the issue isn't in another world than the one you're running /ticks in.

**Comment by darkdeath1332** [comment]
Im running /tps /lag /gc, when the server is up less than an hour its always 20 and when its around 2 hours uptime then the ticks go to 8 or 10. 

Running /ticks in all worlds and they arent higher than 2 ms. The chat is also extremely slow at those moments asking all of my players for a restart.

**Comment by darkdeath1332** [comment]
Same amount of players online and none who really create lag, when I leave the server on at those moments it only get even more worse. the ticks keep dropping and the chat gets slower. My highest uptime without lag was 3 hours.

**Comment by LunNova** [comment]
Use jvisualvm to get a sampling snapshot, see https://github.com/nallar/TickThreading/issues/442#issuecomment-17419675

**Comment by LunNova** [comment]
Also, more instructions here https://github.com/nallar/TickThreading/issues/515#issuecomment-18088117

**Comment by darkdeath1332** [comment]
So its monitoring my connection?
If its server side, I run linux on it.

**Comment by darkdeath1332** [comment]
Ok got it, can I do that over putty? And what profiling you need, CPU RAM?

**Comment by cjm721** [comment]
Something I have noticed that is effecting this is chunkloaders are not turning off for me when the player logs off (option in chickenchunks config) or when the chunkloader is broken the ticket says there until server restart.  

Which also reminds me that when I do /chunkloaders I crash now with an EOFException (https://gist.github.com/cjm721/5760931)

**Comment by darkdeath1332** [comment]
Im going to find awnsers on using it over SSH on google, I come with a screenshot tommo.

**Comment by darkdeath1332** [comment]
Server had around 70 players on constantly and running 20 ticks, after 20 hours uptime ticks when 10 and after 30 minutes the server gave up and crashed.

I can really find out how to install Java VisualVM

**Comment by LunNova** [comment]
It's installed as part of the JDK, you run it on your home computer, not the server. The links I gave you earlier both have instructions on how to use it.

edit: You gave the right profile in the screenshot, only read the text. Doesn't seem to be anything odd there, so definitely need a jvisualvm snapshot (while the issue is happening) to fix this.

That `/profile a` was from while the issue was happening? If not, please get it again once it starts being slow.

**Comment by darkdeath1332** [comment]
That profile was when the uptime was 2 hours, Im expecting the issue to come in some minutes. (Not with the issue)

Going to use it now, Also when the issue comes up the ping will start to get over 1500 MS while its normally around 40.

**Comment by darkdeath1332** [comment]
PS, I think some ticks drop come from the TP bug. Player movement is really high. (profile)

**Comment by alicheek** [comment]
its the entities in my opinion

**Comment by darkdeath1332** [comment]
They get cleared when they hit to much.

**Comment by alicheek** [comment]
then again that's a  lot of calls for playermovement

**Comment by darkdeath1332** [comment]
Server should be able to handle alot? I have a 12 core processor on 3.8 GHZ.

The Player movements come from the TP bug.

**Comment by darkdeath1332** [comment]
alicheek, you should be the owner of brierie. How did you fix it for the tick drops?

**Comment by alicheek** [comment]
I sent a message to you on the website, but in all honesty it wasn't me that sorted the issue it was my hosters they never told me what they did though.

**Comment by darkdeath1332** [comment]
Ive sent you a new PM, nallar im making a profile when the lag comes.

**Comment by darkdeath1332** [comment]
Do I have to make multiple screenshots for the profiler? Its one big list off stuff when I make a snapshot.

This is what happends before the server crashes when the lag and connection problems start to act.

http://pastebin.com/eK7EAGW3

**Comment by darkdeath1332** [comment]
New error when I updated to the latest build:

http://pastebin.com/4LquMfu1

**Comment by LunNova** [comment]
You need to save the snapshot after sampling, and give me the .nps file.

**Comment by darkdeath1332** [comment]
Ok did it,

http://www.mediafire.com/?tbx0l47sxtqm9x4

**Comment by darkdeath1332** [comment]
Tell me when you got the snap so I can delete the download.

**Comment by LunNova** [comment]
Got it.

On 12 June 2013 19:30, darkdeath1332 notifications@github.com wrote:

> Ok did it,
> 
> http://www.mediafire.com/?tbx0l47sxtqm9x4
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nallar/TickThreading/issues/709#issuecomment-19345344
> .

## 

Ross Allan

**Comment by darkdeath1332** [comment]
I think it are powersuits, when the server starts to lag the connection of powersuits are really high, and server crashes with an network error.

Cant you like block those packets?

**Comment by cjm721** [comment]
mmmPowerSuits is taking up a ton for me also (not effecting tps though)

Tops the cart on count and size.

> 2013-06-12 18:34:20 [INFO] [TickThreading] 
>                                      Packet | Count |    Size
>                               mmmPowerSuits | 13237 | 1139359
>                        35EntityHeadRotation |  2885 |   14425
>                            28EntityVelocity |  1710 |   17100
>                             31RelEntityMove |  1585 |   11095
>                         33RelEntityMoveLook |  1405 |   12645
>                                         FOR |   779 |   45553
> com.eloraam.redpower.core.Packet211TileDesc |   688 |       0
>                                32EntityLook |   520 |    3120
>               Packet | Count |    Size
>        mmmPowerSuits | 13237 | 1139359
>                  FOR |   779 |   45553
>     28EntityVelocity |  1710 |   17100
>                   TE |   392 |   16803
>        AX2AppEng.net |   193 |   15596
> 35EntityHeadRotation |  2885 |   14425
>  33RelEntityMoveLook |  1405 |   12645
>                  ic2 |   274 |   11422

**Comment by darkdeath1332** [comment]
I removed powersuits, fixed alot of lag. 

Server has been up for 5 hours now with night players on it, now just 21 online and ticks are changing all the time between 20 to 1.

Failed again in keeping it up longer with no extreme lag, the spikes are really annoying.

**Comment by darkdeath1332** [comment]
So what was cousing it?,,,,

It keeps happening and its getting worser and worser.

**Comment by darkdeath1332** [comment]
This is my crash error, not really and crash but it shut down after this:

2013-06-13 14:37:21 [SEVERE] Exception in thread "Connection #627 read thread" 
2013-06-13 14:37:21 [SEVERE] java.lang.OutOfMemoryError: PermGen space           (I run 64 gb ram so why?)
2013-06-13 14:37:21 [SEVERE]    at iv.a(NetServerHandler.java:1211)
2013-06-13 14:37:21 [SEVERE]    at cu.a(Packet3Chat.java:59)
2013-06-13 14:37:21 [SEVERE]    at cg.i(TcpConnection.java:348)
2013-06-13 14:37:21 [SEVERE]    at cg.readNetworkPacket(TcpConnection.java:71)
2013-06-13 14:37:21 [SEVERE]    at ch.run(ReplaceTcpReaderThread.java:22)

Before server restart:

2013-06-13 14:38:27 [INFO] Read timed out

**Comment by darkdeath1332** [comment]
Made new post with better title.
