### ISSUE TITLE
Misc Errors

### ISSUE THREAD

**Issue by xiph3r** [MinimallyCorrect/TickThreading#713]
I still have this issue with TT-1863

server log is dropped here  http://198.27.83.35/server/

Tickthreading logs are empty and the forgemodloader log doesnt have any error..
![screenshot from 2013-06-12 15 43 58](https://f.cloud.github.com/assets/4541235/644954/0cc2baba-d39a-11e2-8b3b-6cb93b441e79.png)

![screenshot from 2013-06-12 16 00 09](https://f.cloud.github.com/assets/4541235/644982/ba5a6272-d39a-11e2-9452-fec3414795d5.png)

**Comment by LunNova** [comment]
AuraManager NPEs fixed in latest.
