### ISSUE TITLE
[MCPC 67] [TT 1867] Deadlock (unknown cause)

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#715]
Deadlocked a few times today without any clue whats causing it.

https://gist.github.com/cjm721/5770747

**Comment by OriginalMadman** [comment]
I deadlock several times daily now, and do not recover. I get some of the same errors as you but mostly this:
https://github.com/nallar/TickThreading/issues/649

Using MCPC67 and TT1870 - had it for a weeks worth of versions (at least since TT1840 I think).

**Comment by LunNova** [comment]
Forgot to close this, was fixed with that commit.
