### ISSUE TITLE
[MCPC+ L67] [TT 1867] Server gets huge TPS drop and Network lag when the uptime is around 2 hours

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#716]
I have a FTB ultimate server with just 20 plugins and around 50 - 100 people on it. I cant really leave my server online for longer than about 2 hours.

When the server is just started up the ticks are 20 all the time till my uptime gets longer than about 2 hours. I have this every time and dont know whats cousing it, the players when the server starts lagging is around 50 and when its just up it handles 100 easely. 

When the server is lagging the ticks will float around 15 to 1. Its really annoying and alot of people are leaving the server. 

I recorded a CPU sampler on visualVM its from when the server starts with no lag untill it hits lag. 

1 (from start till self crash, no error in console) http://www.mediafire.com/?i668kfd9uh2tf42

2 (from start till lag started, server stopped when lag came)  http://www.mediafire.com/?cmmi7g6m3pr7yok

**Comment by LunNova** [comment]
Ah, the snapshot should be from after it starts lagging, preferably also for more than 10 minutes.

Also, set these options: http://i.imgur.com/vNBAf2X.png

**Comment by LunNova** [comment]
Connect before it starts lagging, only sample after it starts lagging.

**Comment by LunNova** [comment]
Ah, it's probably a memory leak? Have you set -Xmx higher, or very close to, the memory you actually have? That could cause a crash.

What java parameters are you using? Also, pastebin the TT config.

**Comment by darkdeath1332** [comment]
I run RemoteToolkit and it starts my server with; java -Xms512M -Xmx60G -jar ftbserver.jar-Dcom.sun.management.jmxremote.port\=3333, -Dcom.sun.management.jmxremote.ssl\=false, -Dcom.sun.management.jmxremote.authenticate\=false, -Djline.terminal\=jline.UnsupportedTerminal,-XX:UseSSE\=4, -XX:+UseCMSCompactAtFullCollection, -XX:ParallelGCThreads\=12, -XX:+UseConcMarkSweepGC, -XX:+UseParNewGC, -XX:+DisableExplicitGC, -XX:+CMSIncrementalMode, -XX:+CMSIncrementalPacing, -XX:+UseCompressedOops, -XX:+AggressiveOpts, -XX:-OmitStackTraceInFastThrow

(How its setup in the config, thats why the kommas)

I have 65 GB ram in total, I made the server uses max 60 GB and runs normally 18, here is my config. 

CONSOLE before the crash,
http://pastebin.com/DiebLbYL

TT config,
http://pastebin.com/q9KW6iqp

sorry for my english.

**Comment by darkdeath1332** [comment]
I also have issues with the Anti Cheat bug, when someone teleports my CPU turns 100% for a sec becouse they get bugged trough both posistions.

**Comment by darkdeath1332** [comment]
What amount of RAM should I set my server?

**Comment by darkdeath1332** [comment]
Awesome its fixed, made my XMX 24g and all good now.
