### ISSUE TITLE
[MCPC+ L67] [TT 1867] Big errors

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#717]
Server has been up 1 hour and 45 minutes and now I get these errors:
Doesnt come up one time, but spamming all the time rapidly;

"pool-2-thread-81", "pool-2-thread-84" TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@59d26762

> ```
>   at sun.misc.Unsafe.park(Native Method)
>   -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@59d26762
>   at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
>   at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
>   at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
>   at java.util.concurrent.SynchronousQueue.poll(Unknown Source)
>   at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>   at java.lang.Thread.run(Unknown Source)
> ```
> 
> "pool-3-thread-1" TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@2ea3a148
>       at sun.misc.Unsafe.park(Native Method)
>       -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@2ea3a148
>       at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
>       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
>       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
>       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
>       at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
>       at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>       at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>       at java.lang.Thread.run(Unknown Source)

**Comment by LunNova** [comment]
Full log please.

**Comment by darkdeath1332** [comment]
Its not being logged to the server.log somehow.

**Comment by LunNova** [comment]
From the TickThreadingLogs folder.

**Comment by alicheek** [comment]
if its not there, there is a chance it will be in the screen logs if you keep them

**Comment by darkdeath1332** [comment]
Full log, not of this error but something else today,

http://www.mediafire.com/?zor0rvm2u1x6r56

**Comment by darkdeath1332** [comment]
Server is unreachable on startup,

2013-06-13 22:06:22 [SEVERE] java.lang.ArrayIndexOutOfBoundsException: -1
2013-06-13 22:06:22 [SEVERE]    at java.util.ArrayList.add(Unknown Source)
2013-06-13 22:06:22 [SEVERE]    at thaumcraft.common.AuraCalculationThread.checkFlux(AuraCalculationThread.java:222)
2013-06-13 22:06:22 [SEVERE]    at thaumcraft.common.AuraCalculationThread.run(AuraCalculationThread.java:27)
2013-06-13 22:06:22 [SEVERE]    at java.lang.Thread.run(Unknown Source)

**Comment by LunNova** [comment]
The newest log is tickthreading.1.log, so that's why that's an older log. Try to find the log file with that error and upload it, if you still have it.

**Comment by LunNova** [comment]
Assumed fixed as this was a deadlock, and the most common deadlocks on older build were with AE. Those have now been fixed.
