### ISSUE TITLE
[MCPC+ L67] [TT 1870] Server unreachable

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#718]
When I boot my server the server cant be reached, its up with 8 ticks and 900 chunks loaded.

No error on startup.

**Comment by darkdeath1332** [comment]
I cant get my server up...

**Comment by darkdeath1332** [comment]
![image](https://f.cloud.github.com/assets/3824354/650933/400d17da-d467-11e2-9632-e867d7e10f9a.png)

**Comment by LunNova** [comment]
Console is responding to commands then?

I don't see how TT could cause this, check that there aren't multiple java processes running - an old crashed server could be holding on to the port.

**Comment by darkdeath1332** [comment]
There is no other server running, console does respond to commands.

**Comment by darkdeath1332** [comment]
I got the block pos, how do I fix a corrupted chunk...

**Comment by LunNova** [comment]
Try http://www.minecraftforum.net/topic/302380-minecraft-region-fixer/

**Comment by LunNova** [comment]
Also, are you sure that's the problem? If the server appears to be running, but is unreachable, that probably isn't the problem.

Absolutely sure nothing else is using the minecraft server port? Didn't accidentally revert to an old config file with a different port, or wrong listening address?

**Comment by darkdeath1332** [comment]
Well a full server reboot seem to have worked, im sorry for my amount of posts.
