### ISSUE TITLE
Build 528 - Patcher corrupting MCPC+ jar

### ISSUE THREAD

**Issue by gustav9797** [MinimallyCorrect/TickThreading#72]
"Invalid or corrupt jar file"
After running the patcher and trying to start it.

**Comment by gustav9797** [comment]
Any update?
Actually TT removes the META-INF folder from the MCPC+ jar, moving it from original to the new patched jar works.
But then, exception at getting block type in world..

**Comment by LunNova** [comment]
Sorry, been a bit busy recently due to exams and not had time to look at everything.

The latest build may correct the patching issue, but probably not the issue getting block type in world. I'll do some testing myself with MCPC+ soon.

**Comment by LunNova** [comment]
I've made some progress, although chunks still don't seem to be loading.

**Comment by gustav9797** [comment]
Latest build of MCPC+(16) is working with TT, just some minor errors. Chunks do load.http://build.technicpack.net/job/MCPC-Plus/changes
