### ISSUE TITLE
[MCPC 67] [TT 1875] Batty Bee Index out of bounds spam

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#721]
Spams it once a second over and over. 

> 2013-06-13 22:39:03 [SEVERE] [TickThreading] Exception ticking TileEntity c forestry.apiculture.gadgets.TileAlvearyPlain @83414745 in DIM_MYST2/2 at x, y, z: 415, 65, 368
> java.lang.ArrayIndexOutOfBoundsException: 0
>     at forestry.core.genetics.EffectData.getBoolean(EffectData.java:34)
>     at thaumicbees.bees.AlleleEffectSpawnMob.doEffect(AlleleEffectSpawnMob.java:61)
>     at forestry.apiculture.genetics.Bee.doEffect(Bee.java:238)
>     at forestry.apiculture.genetics.Bee.doEffect(Bee.java:221)
>     at forestry.apiculture.BeekeepingLogic.update(BeekeepingLogic.java:178)
>     at forestry.apiculture.gadgets.TileAlvearyPlain.updateServerSide(TileAlvearyPlain.java:127)
>     at forestry.apiculture.gadgets.TileAlveary.g(TileAlveary.java:62)
>     at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
>     at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
>     at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
>     at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
>     at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment]
Can you confirm that this doesn't occur without TT? Looks like a bug which would occur without.

**Comment by LunNova** [comment]
Or possibly that alveary's corrupt, try breaking and replacing?

**Comment by cjm721** [comment]
I took out of his and put it in mine. Still working on getting a copy of what it had as extra bees I can get the straight bee but not with how he specialized it. From what we can tell it had something to do with two effects on it. (wishes there was a way to /give items with nbt data...)

**Comment by cjm721** [comment]
Tested in single player and got no warning, but no idea if its just not forge posting it either (with fine mode on).
