### ISSUE TITLE
[MCPC+ L67] [TT 1870] Client crash for any one that used /chunkloaders

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#723]
For some reason now when ever any one uses that command our client will crash, never used to do this, only things that have been changing on the server is really the TT builds

**Comment by cjm721** [comment]
Increasing Perm Gen space on my client seemed to fix it for my direwolf20 server, but on ultimate I been having this issue. I allocated -XX:PermSize=128M -XX:MaxPermSize=512M for it. Both are running same TT builds.

**Comment by LunNova** [comment]
What is the client crash?

**Comment by alicheek** [comment]
http://pastebin.com/ETfCPMq2

**Comment by LunNova** [comment]
Can you try with latest?

**Comment by cjm721** [comment]
Still crash. endofstream server side and (TT1883):

https://gist.github.com/cjm721/5789429

**Comment by alicheek** [comment]
Working in latest :)

**Comment by alicheek** [comment]
Seems to be broken again for some reason : 

http://pastebin.com/5GEKT3qw

**Comment by cjm721** [comment]
wonder if it has anything to do with #760 as when I could place chunkloaders fine the command worked fine.
