### ISSUE TITLE
[Question] Entity limiting

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#725]
Saw https://github.com/nallar/TickThreading/commit/7e1bd03e0e8d1546bc12dfa1eb01a847bd1c0ff9 as I was going threw the build server changes and was wonder if this was just for living entities or all entities, and if all entities does it remove them or just pause their spawning (as in for items if something like 30 diamond chests broke in a chunk and its over the  limit)?

**Comment by LunNova** [comment]
There are two options for limiting, one disables mob spawning if entities per player is above the count specified.

The other, `maxItemsPerChunk`, will do two things if the number of entities in a chunk exceeds the limit.

First, it will aggressively try to combine entity items within that chunk with others in that chunk. Then, if the limit is still reached the new item will be removed, and lost forever.
