### ISSUE TITLE
[MCPC+ L67] [TT 1907] Some Players lagging hard an cant move after TT update

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#728]
No logs to help us to see what the issue is but some players that weren't lagging before the TT update are now saying they cant even move its that laggy, no idea whats up since im fine and servers tps is at a solid 20

**Comment by LunNova** [comment]
What does `/profile p` show?

Can you try to find the exact build which caused this? Going to sleep now, if you can that'd be very helpful for fixing it quickly when I get up.

**Comment by alicheek** [comment]
ok this is what profile p shows:

![2013-06-16_04 27 25](https://f.cloud.github.com/assets/3965516/658945/742937a4-d635-11e2-9bed-62e4b319303c.png)
![2013-06-16_04 27 37](https://f.cloud.github.com/assets/3965516/658946/7700346e-d635-11e2-8d97-e8f8496b40f4.png)

**Comment by LunNova** [comment]
What does `/profile p` show with latest?

**Comment by alicheek** [comment]
@nallar 

ok just applied it there will tell  u how it goes, also my admins cant use ur TT commands is it because I need to remove the me. at the start of the permission node?

**Comment by alicheek** [comment]
Here are the results with /profile p now with 50 people on :)

![2013-06-16_17 43 38](https://f.cloud.github.com/assets/3965516/659555/fe824a3a-d6a3-11e2-9eaf-01883923ca7e.png)
![2013-06-16_17 43 46](https://f.cloud.github.com/assets/3965516/659556/ff23b262-d6a3-11e2-91e2-fad2d1f563af.png)

**Comment by LunNova** [comment]
Yes, that's correct. Permission nodes dropped the "me." with the package change.

Looks like the MPS fix works :)

**Comment by alicheek** [comment]
Great ill quickly edit that then in the perms, so glad that issue has been sorted was the main eater in our bandwidth haha made it bad for me also since ive got terrible internet :P

**Comment by LunNova** [comment]
Are players still having the lag problem?

**Comment by alicheek** [comment]
Sorry seems to be fixed :)
