### ISSUE TITLE
[MCPC+ L67] [TT 1907] App E Controller  lag

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#739]
IS there any way that the Applied Energetics  Controller can be slowed down a bit or something because they are the biggest cpu killer id say:

![2013-06-16_17 47 02](https://f.cloud.github.com/assets/3965516/659562/a30bba3c-d6a4-11e2-91dc-1dc7c1c07f91.png)
![2013-06-16_17 47 05](https://f.cloud.github.com/assets/3965516/659563/a3fb8364-d6a4-11e2-9538-fef6b108bdcb.png)

**Comment by LunNova** [comment]
What does just `/profile e` show?

**Comment by alicheek** [comment]
/profile e shows this : 

![2013-06-16_18 04 53](https://f.cloud.github.com/assets/3965516/659585/f23bf976-d6a6-11e2-95df-fe630d7f22ca.png)
![2013-06-16_18 04 59](https://f.cloud.github.com/assets/3965516/659586/f36c6de4-d6a6-11e2-8ab9-f323db2ac694.png)

**Comment by LunNova** [comment]
BC pipes are worse, as they're not that fast and there are far too many of them. Can you get another snapshot?

**Comment by alicheek** [comment]
A visualvm snapshot? issue with them is I need to get my hoster to edit the java parameters since they are set up very differently now so will take longer propably till Monday.

**Comment by cjm721** [comment]
Defraging my ME system and went a bit to fast...

> Definitely deadlocked: 
> "Entities in DIM_MYST35/35 - 5" Id=68498 BLOCKED on appeng.me.tile.TileDrive@4ba49d70 owned by "Server thread" Id=17
>     at appeng.me.tile.TileDrive.getCellArray(TileDrive.java:340)
>     -  blocked on appeng.me.tile.TileDrive@4ba49d70
>     at appeng.me.tile.TileController.getCellArray(TileController.java:825)
>     -  locked appeng.me.tile.TileController@52f17aaa
>     at appeng.me.tile.TileController.g(TileController.java:1024)
>     -  locked appeng.me.tile.TileController@52f17aaa
>     at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
>     at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
>     -  locked nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion@25f30285
>     at nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
>     at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
>     at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
> 
> "Server thread" Id=17 BLOCKED on appeng.me.tile.TileController@52f17aaa owned by "Entities in DIM_MYST35/35 - 5" Id=68498
>     at appeng.me.tile.TileController.resetWaitingQueue(TileController.java:226)
>     -  blocked on appeng.me.tile.TileController@52f17aaa
>     at appeng.me.GridInterface.resetWaitingQueue(GridInterface.java:62)
>     at appeng.me.tile.TileDrive.resetCache(TileDrive.java:510)
>     -  locked appeng.me.tile.TileDrive@4ba49d70
>     at appeng.me.tile.TileDrive.a(TileDrive.java:380)
>     at sr.c(Slot.java:103)
>     at appeng.gui.AppEngContainer.b(AppEngContainer.java:678)
>     at rq.a(Container.java:203)
>     at appeng.gui.AppEngContainer.a(AppEngContainer.java:487)
>     at iv.a(NetServerHandler.java:1766)
>     at dc.a(Packet102WindowClick.java:46)
>     at cg.b(TcpConnection.java:467)
>     at iv.d(NetServerHandler.java:220)
>     at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
>     -  locked ht@484ef743
>     at iw.b(NetworkListenThread.java)
>     -  locked ht@484ef743
>     at ht.b(DedicatedServerListenThread.java:34)
>     at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:417)
>     at ho.r(DedicatedServer.java:309)
>     at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:292)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:194)
>     at fy.run(ThreadMinecraftServer.java:16)

**Comment by LunNova** [comment]
I lied, did it anyway. Fixed in latest.
