### ISSUE TITLE
List of known working / not working mods

### ISSUE THREAD

**Issue by nvx** [MinimallyCorrect/TickThreading#74]
A published list of mods that do and don't work (including why for the latter) would be quite useful for server admins wanting to test this out!

**Comment by LunNova** [comment]
I've started [a wiki page](https://github.com/nallar/TickThreading/wiki/Mod-Compatibility) but it's incomplete as I don't have time. If anyone has time to make it nicer that'd be really helpful :)

**Comment by Puremin0rez** [comment]
Added the only two (besides Mystcraft since that's already listed) I use outside of the norm :)

**Comment by darkinnit** [comment]
Ah woops, only just seen this, ignore my crash report then. :)

Edit: It's late, I should take more time to read. It says Mystcraft is supported, so I guess my issue is relevant then.

**Comment by samlich** [comment]
Optifine doesn't seem to work for me. Please also ignore the issue I posted.

**Comment by keplersj** [comment]
I've done a lot of work on the wiki page. I think it's safe to close this issue.

**Comment by nvx** [comment]
I agree, closing now. :)

**Comment by LunNova** [comment]
Thanks :)

**Comment by keplersj** [comment]
Your welcome! I'll come back and put up more posting after I test more.
