### ISSUE TITLE
Frames broken when moving across chunk boundary

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#743]
Trying to not use to word so google finds this, but basically using my inch worm drive with a tesseract/pump system on it caused a frame block to encase a tesseract block. When I try and break the tesseract with an omniwrench I get the tesseract (breaking with pickaxe does samething), but it also says there. Logged out and back in and got another admin to come over and check so its not a visual glitch.

Seen no reports of this from the internet, but this being the touchy topic it is rather heisent on posting it as no clue if its related to TT or not working on seeing if I can make a system to recreate it.

![2013-06-16_14 24 15](https://f.cloud.github.com/assets/2738614/659746/c796d91a-d6bb-11e2-9c78-fb7b26841c52.png)

**Comment by LunNova** [comment]
TT can cause problems with frames when they are crossing chunk boundaries.

**Comment by cjm721** [comment]
I have the chunk lines up its all inside of one chunk, the last blocks where crossing the line when this happened. The computer in the top is touching the line.

**Comment by Slind14** [comment]
iron tanks loose their filling, i think its the same with the loaded and not loaded chunks
