### ISSUE TITLE
[Question] How is overall load calculated?

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#744]
Sorry if this has been answered somewhere before, but I noticed lately that the overall load is sometimes double of what the world load is. Shouldn't it just be all of the world load combined to get overall load? If not, what other factors contribute to the overall load?

Here is a screenshot of what I mean.
![1](http://puu.sh/3hdvE.jpg)

I don't see how it is getting the extra 30%. I'm probably just confused and missing something, though.

**Comment by LunNova** [comment]
Some load is not associated with any worlds, for example load from handling server tick events and from handling packets from players.

See `/profile a`.

**Comment by joey19982** [comment]
Ooh, thanks for that.

**Comment by joey19982** [comment]
This is what it outputs. Anything I can do about it, or is it just one of those things where you've gotta up hardware for it? 

![1](http://puu.sh/3hfDU.png)

At times the TPS will drop to 10ish for a few minutes, and not due to world load. It usually fixes itself, but it'd be nice to know if there is anything to do to prevent it. I know you can't do much without a screenshot of what is going on when that happens, though. The screenshot above is 20TPS with about the same load as before.

**Comment by LunNova** [comment]
You have a misbehaving mod/plugin taking far too long to process player
movement updates. Can you get a .NPS snapshot with jvisualvm?

**Comment by joey19982** [comment]
Sent you an email with it.

**Comment by joey19982** [comment]
Oh, duh. The issue was an AFK plugin tracking movement to see if a player was AFK.

**Comment by LunNova** [comment]
Sorry for not investigating quickly, been busy with 1.5 update + school.

**Comment by joey19982** [comment]
No problem, I know you've got enough on your plate.
