### ISSUE TITLE
TickThreading Crash on travelling to Mystcraft Dimension and back

### ISSUE THREAD

**Issue by darkinnit** [MinimallyCorrect/TickThreading#75]
This TickThreading (v552) crash occured after heading to a Mystcraft dimension ("Mining World") and back. Initial loading of the Mystcraft dimension was much slower than normal, but it came up after about 15 seconds. On returning to the overworld, was able to move around for about another 15 seconds, then this crash occurred. This is a test server, so I'm happy to mess about and try anything out.

java version "1.7.0_11"
Java(TM) SE Runtime Environment (build 1.7.0_11-b21)
Java HotSpot(TM) 64-Bit Server VM (build 23.6-b04, mixed mode)

TickThreading.log and Server.log:
https://gist.github.com/4590515

**Comment by darkinnit** [comment]
Just updating to say I've just seen Mystcraft is not supported, so sorry for filing this without reading the other issues first!
Edit: It's late, I should take more time to read. It says Mystcraft is supported, so I guess my issue is relevant then.

**Comment by LunNova** [comment]
Any mod is supported, that's just a list of what's known to work - must
craft normally does, anyway. I'll look into this tomorrow.

**Comment by Puremin0rez** [comment]
Getting the same thing with Mystcraft, TT has always worked fine with it before - just a minor incompatibility I suppose.

**Comment by LunNova** [comment]
Also, I meant "mystcraft", not "must craft", but autocorrect disagreed.

**Comment by LunNova** [comment]
This is fixed in bab0aece94273f57.
