### ISSUE TITLE
[TT1927, MCPCL 67]  [SEVERE] [TickThreading] The server appears to have deadlocked.

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#751]
http://pastebin.com/Jb2hfGwf

**Comment by alicheek** [comment]
second part http://pastebin.com/5sUDAypy

**Comment by alicheek** [comment]
Don't know if me using the chunk entity limiter has anything to do with it , got it set to 70 per chunk and 300 per char

**Comment by LunNova** [comment]
The per chunk limit is for items, not entities, although entities are items.

Also, it should probably be higher than 70, it's intended to be used to prevent overflowing machines causing performance problems, but even breaking a large chest could drop 70 items.

The deadlock isn't related to that, testing a fix just now.
