### ISSUE TITLE
cant find the error in the logs

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickThreading#757]
Hey,

i´m getting some errors in the console but if check the server.log, forgemodloader-server.log and tickthreading.log i cant find it. Is there any other error log ?

Because the screen dont show me everything, its still too long for a 24zoll monitor.

**Comment by LunNova** [comment]
The FML server log should show everything, other than some bukkit errors which might only be in server.log/console.

tickthreading.1.log should have the newest TT error log.

**Comment by Slind14** [comment]
nope they dont show the error.

**Comment by Slind14** [comment]
here is a screen of it, i cant find this in any of the logs:

http://minus.com/l63BF00S2vBKo

**Comment by LunNova** [comment]
Doesn't look like a TT issue, a forestry fake player is breaking the limitedcreative plugin when trying to place a block in a farm.

Try enabling fake player login in MCPC+'s config? Also, if that's not being logged to a file anywhere (are you sure it's not at the bottom of server.log?), then it's an issue with MCPC+ not logging it, not a TT bug.

**Comment by Slind14** [comment]
yeah thanks
