### ISSUE TITLE
cant update to the newer builds

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickThreading#758]
Hey,

if i try to launch my server with a 19+ build i get this:

http://minus.com/lbyMN0C7QPdnti

**Comment by LunNova** [comment]
Get a clean server jar.

**Comment by Slind14** [comment]
maybe u should write this into the wiki

**Comment by LunNova** [comment]
Don't have an FAQ page, you could add one if you want.

**Comment by Slind14** [comment]
maybe to the README.md
