### ISSUE TITLE
me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:33)

### ISSUE THREAD

**Issue by geoffcorey** [MinimallyCorrect/TickThreading#76]
Server crashed.  Quick scan of logs yields this as a suspicion.   

Current Thread: World Tick - 3
    PID: 88 | Alive: true | State: WAITING | Daemon: true | Priority:5    Stack:
        sun.misc.Unsafe.park(Native Method)
        java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
        java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
        java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:33)
        me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:150)

Full logs https://dl.dropbox.com/u/52804523/log-20130122.tgz

java -server -Xms512M -Xmx7G -XX:UseSSE=4 -XX:+UseCMSCompactAtFullCollection -XX:ParallelGCThreads=6 -XX:+UseConcMarkSweepGC -XX:+DisableExplicitGC -XX:+CMSIncrementalMode -XX:+CMSIncrementalPacing -XX:+UseCompressedOops -XX:+AggressiveOpts -Xmx8192M -jar mindcrack.jar nogui

Running FTB Minecrack v6 + Logistics Pipes on Ubuntu 12.10

[1.4.6]PetroGen-1.1.zip                           ForgeEssentials-worldborder-1.4.6-0.1.1.227.zip   RedPowerCore-2.0pr6.zip
AdvancedMachines_4.7a.zip                         ForgeEssentials-WorldControl-1.4.6-0.1.1.227.zip  RedPowerDigital-2.0pr6.zip
buildcraft-A-3.3.0.jar                            GregTechMod_2.73c.zip                             RedPowerMechanical-2.0pr6.zip
ChickenChunks 1.2.1.1.jar                         IC2NuclearControl-1.4.5.zip                       SoulShards-v1.21-universal.zip
ComputerCraft1.481.zip                            industrialcraft-2_1.112.170-lf.jar                StevesCarts2.0.0.a41.zip
EnderStorage 1.3.1.1.jar                          ironchest-universal-1.4.6-4.5.1.203.zip           Thaumcraft3.0.1c.zip
extrabees-1.4.9.6-prerelease.zip                  LogisticsPipes-MC1.4.6-0.6.9.74.jar               ThermalExpansion-2.1.6.zip
ExtrabiomesXL-universal-1.4.6-3.7.0.jar           miscperipherals-2.3.zip                           TickThreading-1.4.6-1.0.0.466.jar
Factorization-0.7.10.jar                          mod_AdvancedSolarPanels_3_3_2.zip                 Traincraft-3.1.13_010.jar
forestry-A-1.6.4.1.jar                            ModularForceFieldSystemV2.2.8.2.14.zip            twilightforest-1.14.0.zip
ForgeEssentials-chat-1.4.6-0.1.1.227.zip          mod_zGraviSuite_1_6.zip                           WR-CBE Addons 1.3.2.4.jar
ForgeEssentials-commands-1.4.6-0.1.1.227.zip      obsidiplates-universal-1.2.0.3.zip                WR-CBE Core 1.3.2.4.jar
ForgeEssentials-economy-1.4.6-0.1.1.227.zip       OmniTools-2.2.5.zip                               WR-CBE RedPower 1.3.2.4.jar
ForgeEssentials-playerlogger-1.4.6-0.1.1.227.zip  portalgun1.4.6v2.zip                              xycraft-universal-1.4.6-0.9.44.zip
ForgeEssentials-protection-1.4.6-0.1.1.227.zip    Railcraft_1.4.6-6.12.2.0.zip
ForgeEssentials-snooper-1.4.6-0.1.1.227.zip       RedPowerCompat-2.0pr6.zip

/usr/bin/java -version
java version "1.7.0_09"
OpenJDK Runtime Environment (IcedTea7 2.3.4) (7u9-2.3.4-0ubuntu1.12.10.1)
OpenJDK 64-Bit Server VM (build 23.2-b09, mixed mode)

Dedicated Server running Ubuntu 12.10
root@AD27:/proc# cat meminfo 
MemTotal:        8177388 kB
MemFree:         1473744 kB
Buffers:           14224 kB
Cached:           148652 kB
SwapCached:        17632 kB
Active:          6110824 kB
Inactive:         155304 kB
Active(anon):    6057696 kB
Inactive(anon):    45572 kB
Active(file):      53128 kB
Inactive(file):   109732 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       4190204 kB
SwapFree:        4123600 kB
Dirty:                24 kB
Writeback:             0 kB
AnonPages:       6090908 kB
Mapped:            24060 kB
Shmem:                16 kB
Slab:             179336 kB
SReclaimable:      33012 kB
SUnreclaim:       146324 kB
KernelStack:      135528 kB
PageTables:        49772 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     8278896 kB
Committed_AS:   25439016 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      290836 kB
VmallocChunk:   34359444284 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       48768 kB
DirectMap2M:     8339456 kB

**Comment by LunNova** [comment]
You ran out of native memory for threads, because computercraft started about, as far as I can see, 5000 lua interpreter threads.

**Comment by geoffcorey** [comment]
Yep!  Found a member on the server did some new coding and did something naughty.  Thank you for your help!

Issue Closed

Side note: Updating to TickThreading-1.4.6-1.0.0.475.jar and turning off WorldTickThreading since we using ChickenChunks.
