### ISSUE TITLE
[MCPC+ 67] [TT 1927] Crash on placing chunkloader

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#760]
Chunkloader gets place and is usable, but it is never taken out of inventory.

https://gist.github.com/cjm721/5798943

*added forge/server log error also.

**Comment by cjm721** [comment]
Ok update on this as I have no clue what caused this. Server froze a few minutes ago (deadlock detector did not kick in) and I ctrl-c and closed the terminal. Then patched to 1929 and also opened up system monitor and noticed I had two extra java processes running both taking up 3GB of ram. I killed those processes and when I started back up the server and tried to place a chunkloader where I had crashed the three times before I restarted the server everything was fine. No crash or errors. So I don't know if this has more to do with old hooks from that old java processes or what.

**Comment by LunNova** [comment]
Multiple server instances on the same world can cause all sorts of horrible problems. If you want to ensure the server always shuts down properly after a deadlock, set exitOnDeadlock to true. It's guaranteed to stop within 6 minutes, in most cases immedately.

**Comment by cjm721** [comment]
I do have that on. Thing is from looking in system monitor I can tell which server it was as my command to start them is different and for my direwolf20 server the last time I restarted it was yesterday and it had a clone. No idea how long the one from my ultimate had been there.

**Comment by cjm721** [comment]
Ok happened again and this time no extra java processes running... So I am at a lost.

**Comment by cjm721** [comment]
Tried deleteing all my forcedchunks.dat files which resets loaded chunks. Was able to place the first chunkloader fine then I logged off to see if the world would deload correctly. Come back on and get error then I try to place a chunkloader and get the same error as before.

https://gist.github.com/cjm721/5816299
(has all the errors and what they correspond to)

**Comment by LunNova** [comment]
If you disable world unloading, does it start working? Looks like CC may be trying to use unloaded worlds.

**Comment by cjm721** [comment]
@nallar turned unloading off and everything works fine again, including /chunkloaders.
