### ISSUE TITLE
High CPU useage

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#761]
Dont know why its eating so much, no laggy chunks. /stoplag enabled at this moment.
(no mobs, no drops)

![image](https://f.cloud.github.com/assets/3824354/664936/972dfe5e-d790-11e2-93f5-53a6a43c9535.png)

**Comment by LunNova** [comment]
How many cores do you have? Also, /stoplag should not be necessary, and depending on how it works may make things worse with TT.

**Comment by LunNova** [comment]
What does `/profile a` show?

**Comment by darkdeath1332** [comment]
I have 12 threads with 6 cores. 3.8 GHZ each.

Also, ur network fix really works for MPS, thank you.

![image](https://f.cloud.github.com/assets/3824354/664959/014e4e92-d791-11e2-84c6-930a6d5ed761.png)

**Comment by darkdeath1332** [comment]
Htop on puttye, with only 69 players online ;

![image](https://f.cloud.github.com/assets/3824354/664973/4bc9044e-d791-11e2-9e0c-90477fe8ae11.png)

**Comment by LunNova** [comment]
Basically, what this means is that TT is working, but you've just got a lot of stuff. I've seen > 40k TileEntities before on a worse server with the same load though, so this can definitely be improved.

**Comment by darkdeath1332** [comment]
How could this been improved? there are now 59 people online with a load of 80 - 97%

**Comment by LunNova** [comment]
Can you get a .nps snapshot using jvisualvm, while at high load? Leave it running for ~20 minutes.

**Comment by darkdeath1332** [comment]
Making one

**Comment by Slind14** [comment]
where can i find this networkfix for mps ?

**Comment by LunNova** [comment]
It's just another TT patch, as long as you use up to date TT it's included.

**Comment by Slind14** [comment]
ohh nice, thx
and darkdeath1332 are u using the original essentials or a modiefied version ?

**Comment by darkdeath1332** [comment]
I got my snapshot while high cpu useage, recorded 30 mins.

http://www.mediafire.com/?810zno0ow8hyi3z

**Comment by Slind14** [comment]
is it possible to run jvisualvm without an gui ?

**Comment by darkdeath1332** [comment]
@nallar will you be able to like find out whats cousing it with a snap?

**Comment by darkdeath1332** [comment]
I hate my phone.

**Comment by darkdeath1332** [comment]
Still have that issue, What up with the snap?

**Comment by Slind14** [comment]
dark, if i do the Test i get the same with 50 players online. 4/8 x 3.9ghz
![ftb_ultimate_de_2013-06-18_20-39-02](https://f.cloud.github.com/assets/3914677/670630/db8ec392-d846-11e2-9283-90e963193d00.jpg)

**Comment by alicheek** [comment]
yea I get lag also when at about 80 people : 

![2013-06-18_19 16 53](https://f.cloud.github.com/assets/3965516/670644/2e4e003e-d847-11e2-92c0-e626b762e940.png)

**Comment by Slind14** [comment]
@alicheek how much tps do u have with 80 players and how much cpu (threads/ghz) ?

**Comment by alicheek** [comment]
its a dual Xeon L5520 : 8 cores 16 threads at 2.5 GHz

**Comment by Slind14** [comment]
is this own hardware ? if not maybe u should think about upgrading to an 22nm (Haswell) for example as desktop cpu  i7-4770K or as server  E3-1270V3. there are no 22nm for dp or mp at the moment. or one of the six core E5 but they are all still 32nm

**Comment by alicheek** [comment]
its what my hosters have provided me with its this: http://ark.intel.com/products/40201/Intel-Xeon-Processor-L5520-8M-Cache-2_26-GHz-5_86-GTs-Intel-QPI

TBH im not very techy so I don't know everything about it that's what my hoster is good at :)

**Comment by Slind14** [comment]
yeah i cant say anything against these cpus. but they are old (mid 2009). Maybe u should talk to your hoster and ask which setup he could give u for the same price. with at least sandy/ivy bridge (32nm) cpu/cpu´s

@darkdeath1332 sry that we missused your issue report.

> I got my snapshot while high cpu useage, recorded 30 mins.
> http://www.mediafire.com/?810zno0ow8hyi3z

**Comment by darkdeath1332** [comment]
Slind14 I have 6/12  3,8 GHZ  and hit even more useage,

**Comment by Slind14** [comment]
you cant compare GHz to GHz. Take a 32nm (Sandybridge) 4x4HTx3,5(3,9Boost)GHz CPU and the same with 22nm (Haswell) and u have a benchmark increase from about 8-12%. And then u still have differences between the models. Its no rarity that u see a CPU with less GHz beating one with more. Same with your world, loaded chunks and loaded worlds.

**Comment by alicheek** [comment]
just another profile e with /tps at 200%   

![laggissuee](https://f.cloud.github.com/assets/3965516/671125/a8a7421c-d853-11e2-8913-7f0ac7654b45.jpg)

**Comment by darkdeath1332** [comment]
What about this one? Intel® Xeon® Processor E5-1650 

http://ark.intel.com/products/64601

**Comment by darkdeath1332** [comment]
@alicheek I have the same, 107% and it only came after updating from a lower build (around 1800)

I just fixed all quarry griefing and wands and stuff, now I have this ;S

**Comment by LunNova** [comment]
@alicheek 
Did you change JVM settings again? Because it looks like the "absolutely everything is slow" issue has happened again.

@darkdeath1332 
Will get back to you about the snapshot once I have the time to check it.

**Comment by Slind14** [comment]
ohh ok, i upgraded tickthreading and my root system at the same time. 

@darkdeath1332  MyTown ?
well, 32nm (Sandybridge) up to date in the 6 core section at the moment. if you think about upgrading you should that it is worth only if u double your budget. 
the next step would be something like alicheek has, but with up to date cpus.

but i dont know if TT is working better on more threads or more GHz per core/thread

**Comment by Slind14** [comment]
is there no private message feature in github ?
i was about asking you how much you are paying for your server

**Comment by alicheek** [comment]
@darkdeath1332  Oh nice still haven't jumped that hurdle yet for the wand griefing, towny doesn't seem to pick up the break events so it just lets it happen

**Comment by darkdeath1332** [comment]
Easy fix, in the config add the ID, same for that bypassing wrench. And yeah MyTown is a solution for us, I got it done with coded plugins check a towny protection of the owner, but mytown seems better.

**Comment by alicheek** [comment]
I did but they still bypass towny protection for some reason , haven tried in a while so maybe its sorted now

**Comment by darkdeath1332** [comment]
Use MyTown, Almost the same as towny.

http://www.minecraftforum.net/topic/1650110-146-151mytown-aperf-server-protection-and-performance-mods/
- What we need:
  Tight protection
  Protects against most mod world changing items like IC mininglaser, BC quarrys, TC excavationwand etc. Tailored for FTB MindCrack modpack.

**Comment by LunNova** [comment]
Towny can prevent them being used in a town, but it can not prevent using them outside a town and firing into a town.

**Comment by darkdeath1332** [comment]
I coded a plugin to block air clicking event, you can only click it on a block and as soon you move into an town it gets turned off.

**Comment by alicheek** [comment]
yea was moving to it when 1.6 version was released bit of a hassle to do it now with all the towns already in place :P 

@nallar  weird it doesn't for me they just bypass it all together even in the town

**Comment by alicheek** [comment]
@darkdeath1332  that's a very smart idea never would of thought of that :P

**Comment by darkdeath1332** [comment]
Bypassing with an wrench, I use lockette so I can just use a check for signs.

```
@EventHandler
public void onInteractWrench(PlayerInteractEvent event)
{
    Player player = event.getPlayer();
    int id = event.getClickedBlock().getTypeId();
    int sub = event.getClickedBlock().getData();
    int item = player.getItemInHand().getTypeId();
    Location face = event.getClickedBlock().getLocation();

    if(item == 6257) {

        if (event.getAction() == Action.RIGHT_CLICK_BLOCK) {
         player.
            if (id ==  617 && sub == 3) {

                if (face.add(0, 0, -1).getBlock().getType() == Material.WALL_SIGN || face.add(1, 0, 0).getBlock().getType() == Material.WALL_SIGN || face.add(0, 0, 1).getBlock().getType() == Material.WALL_SIGN || face.add(-1, 0, 0).getBlock().getType() == Material.WALL_SIGN ) {
                event.setCancelled(true);
                player.sendMessage("[BC] Remove the lockette protection before you wrench the machine, this is to stop griefing with this tool.");
```

**Comment by darkdeath1332** [comment]
Same for arcane table dupe, Just made it clear the drops when you break it.

**Comment by darkdeath1332** [comment]
@Slind14  Ive 'upgraded' a couple weeks ago. I thought It was GhZ and cores XD. 

Whats better? I still got them all online and not sure wich one to keep for my server.

Intel Xeon E5-1650
http://ark.intel.com/products/64601

Intel Xeon E3-1245 V2
http://ark.intel.com/products/65729

Intel Xeon E5-1620
http://ark.intel.com/products/64621

(Got skype? So I can tell the price there.)

**Comment by Slind14** [comment]
@darkdeath1332 well they all dont have QPI Link, so they work only as single cpus. In this case the six-core should be the best. but as I said, I dont know and dont find Benchmarks for TT between a quad and six-core. 

If you have the money, you could check out these as dual cpus, but dont forget the expensive mainboard and doubl energy consume:
DP E5645
DP X5660
DP E5606
DP E5620
DP X5647
DP X5670

But i think is would cost more than double.

Add me at Skype: Slind14

**Comment by darkdeath1332** [comment]
@Slind14 what about an dual xeon e5-2420?

6 cores 12 threads x 2, quite damn power

**Comment by Slind14** [comment]
@darkdeath1332 would work as dual and the mainboard wouldnt be so expensive for the 1356 socket, please add me at skype: slind14

**Comment by Slind14** [comment]
at this point i have to admit, something between TT1917 and TT36+ changed. The utilization raised.

**Comment by LunNova** [comment]
Still not a single snapshot? ...

**Comment by LunNova** [comment]
https://github.com/nallar/TickThreading/wiki#visualvm-snapshot-remote-connection

**Comment by Slind14** [comment]
thanks gonna do this today

**Comment by LunNova** [comment]
Can anyone confirm whether 35fd8d576d132c4b3 fixed this?

**Comment by floh22** [comment]
just one question, how are you guys running that many people on for example, a dual Xeon L5520? im running a Intel Xeon E3 1245 @ 3.4GHz and i start to drop at about 35 players... though most of them extremely advanced with AE systems with over 1 million items, turtles and everything. but i think it shouldnt start lagging at 35 people..

**Comment by darkdeath1332** [comment]
@floh22 I ran 118 people today on 69% cpu useage.

Idk all ive got is a hexa core CPU and I made 60% of my plugins myself. 

I fixed most of my lag with deleting tekkitcustomizer and making my own version wich is lightweight. I run 19 plugins and its going perfect on the latest version.

@nallar ITS FIXED YAY :D

**Comment by LunNova** [comment]
@floh22 

"though most of them extremely advanced with AE systems with over 1 million items, turtles and everything"

"but i think it shouldnt start lagging at 35 people"

Players being online causes very little lag, chunks with lots of stuff in them cause lag. Giant AE networks on 1.4.7? Not good for performance at all. AE is far better now, but 1.4.7 versions have performance problems.

Probably a good idea to ban AE networks with huge numbers of items - there shouldn't be any need.

**Comment by floh22** [comment]
well there is my problem then, all the lag is probably coming from those. i dont really want to ban them, at the moment its fine since the player limit is at 40 players. i guess i have to wait for a ftb 1.6 version...
