### ISSUE TITLE
Incorrect patching for server. Server crash on boot.

### ISSUE THREAD

**Issue by adamjones353** [MinimallyCorrect/TickThreading#764]
Ok so i am trying to install tick threading for a server but i cant run the patch on the server as it is in a data center. I am sorry if what i am about to ask it a stupid question but i am stuck. 

I have tried to install it by downloading the server on to my computer then patch it there then load it up on to the main server but this makes it crash everytime (log below), is there some thing i am doing wrong. The log is saying outdated mods but they are the same as on the main server so i cant work out what is wrong. 

thanks in advance. 

Log - http://pastebin.com/heX5Fvpz

Thaumcraft is a custom version.

**Comment by LunNova** [comment]
You should still be able to patch it on the server - just run the "./PATCHME.sh" command in the same directory as you would normally run "./start.sh", or whatever else you would normally run to start it.

**Comment by adamjones353** [comment]
I will have to talk to the server owner about this as i have no idea how to do this on mcmyadmin and my putty is broke. thank you for your help.
