### ISSUE TITLE
mobs not responding after leaving chunks

### ISSUE THREAD

**Issue by seriousvern** [MinimallyCorrect/TickThreading#767]
I have an issue that makes mob not respond to a player after he leaves the current chunk.
i am using the ultimate mod pack version 1.1.2 recommended. Also mobs seem to be pushed away from the player when they come in contact with them. I removed all plugins to try to rectify the issue with no success.
using 1929 tt and 67 mcpc

**Comment by cjm721** [comment]
Running save versions as you and not having any problems here. Try re patching?

**Comment by seriousvern** [comment]
i have tried removing and starting from scratch still same result

**Comment by seriousvern** [comment]
this is closed running flawlessly on my ultimate server now Thanks nallar great job

**Comment by LunNova** [comment]
You asked something on freenode at about 4AM this morning, wasn't here to reply. Still need help, or was it related to this issue?

**Comment by seriousvern** [comment]
yeah this was related to that but is no longer an issue thanks for the mod it is awesome
