### ISSUE TITLE
tickthreading wihtout ssh 

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickThreading#768]
hey,

TT is running so fine on my Root Server with the FTB Ultimate pack, Thank you for this.

But i have one more Server, a Mindcrack Server without Root and SHH.

When i patch the mods and the ftbserver.jar on my local win7 computer or on the root with debian and move it to the right location where i dont have ssh access and run the server, I get a message that thaumicbees and thaumcraft isnt working or are not well patched. 
Is there any workaround. ?

**Comment by dariusc93** [comment]
If you have FTP access just upload everything (dont forget the patchmods directory) and then give it a start.

**Comment by Slind14** [comment]
I did, i uploaded everything, the complete Server folder...

**Comment by Slind14** [comment]
1959 is working again
