### ISSUE TITLE
[MCPC 67] [TT1929] Profile C Not turning up any data for some Chunks

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#770]
Here is the screen shot:

![2013-06-18_19 34 11](https://f.cloud.github.com/assets/3965516/670605/482af3d2-d846-11e2-9d80-2bf7cac2ee94.png)

not really got any errors for it thought it seems

**Comment by LunNova** [comment]
Caused by #712. TickRegion management is broken.
