### ISSUE TITLE
[TT 1929] [SEVERE] [TickThreading] Exception in main tick loop java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#775]
This message appears from time to time.

> 2013-06-19 03:17:43 [SEVERE] [TickThreading] Exception in main tick loop
> java.lang.NegativeArraySizeException
>         at java.util.AbstractCollection.toArray(AbstractCollection.java:136)
>         at com.google.common.collect.ImmutableSet.copyFromCollection(ImmutableSet.java:350)
>         at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:345)
>         at net.minecraftforge.common.ForgeChunkManager$Ticket.getChunkList(ForgeChunkManager.java:340)
>         at codechicken.chunkloader.ChunkLoaderManager$TicketManager.remChunk(ChunkLoaderManager.java:130)
>         at codechicken.chunkloader.ChunkLoaderManager$ChunkLoaderOrganiser.tickDownUnloads(ChunkLoaderManager.java)
>         at codechicken.chunkloader.ChunkLoaderManager.tickDownUnloads(ChunkLoaderManager.java:892)
>         at codechicken.chunkloader.ChunkLoaderManager.serverTick(ChunkLoaderManager.java)
>         at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd(ChunkLoaderEventHandler.java)
>         at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
>         at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:28)
>         at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:82)
>         at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick_cpw_mods_fml_common_FMLCommonHandler_onPostServerTick_p0(FMLCommonHandler.java:275)
>         at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java)
>         at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:328)
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:194)
>         at fy.run(ThreadMinecraftServer.java:16)

**Comment by darkdeath1332** [comment]
Turn off chunk unloader
