### ISSUE TITLE
What CPU?

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#778]
What does tickthreading wants? Ghz? Cores? Threads?

**Comment by alicheek** [comment]
threads are TTs main way of getting performance, but it is variable to the Processor speed and amount of cores also

**Comment by darkdeath1332** [comment]
12 // 24 @ 1.9 GHZ

8 // 16 @ 2.26 GHZ

6 // 12 @ 3.2 GHZ

**Comment by darkdeath1332** [comment]
What cpu useage do you normally have with 8 // 16 @ 2.25 GHZ on ur server

**Comment by Slind14** [comment]
ok, after we discoverd that still with TT most of the stuff is single threaded everyone should still look at single thread power.

in this case:
http://www.cpubenchmark.net/singleThread.html
and oc the new haswells with 22nm are on top ;)

can be closed
