### ISSUE TITLE
v562 Crash on travelling to Nether

### ISSUE THREAD

**Issue by darkinnit** [MinimallyCorrect/TickThreading#78]
So v562 fixed my crash on returning from a Mystcraft age. So I tested going to the nether, going to Mystcraft age and all seemed well. Played the game for about an hour and then went to the nether a second time, but this time no chunks loaded. :(
TickThreading.log: https://gist.github.com/4598768

I'm using FTB Direwolf20 v4 modpack. As it includes ChickenChunks and I have a chunkloader in the overworld, I have World ticks disabled in the config as instructed in the wiki.
java version "1.7.0_11"
Java(TM) SE Runtime Environment (build 1.7.0_11-b21)
Java HotSpot(TM) 64-Bit Server VM (build 23.6-b04, mixed mode)

Let me know if you need any more info. I will try to see if I can reproduce the error again with a fresh start. The ForgeModLoader-server-0.log seems to contain 2MB worth of the exact same error from the TickThreading.log file.

**Comment by LunNova** [comment]
Do you have bukkitforge installed? If so, this should be fixed in 1bd9b8e6a585a

**Comment by darkinnit** [comment]
No, I don't have Bukkitforge, just the Direwolf20 v4 pack as it comes with your TickThreading applied (I wanted to test it on its own with as little conflicts as possible for now).

**Comment by LunNova** [comment]
Can you paste the patcher log?

**Comment by LunNova** [comment]
Oh, I see what's wrong. Can't fix it today, sorry.

**Comment by darkinnit** [comment]
Ah ok. I can't reproduce it with a rollback and fresh patch and more dimension hopping (still v562), so not sure if I was just unlucky or if it's because I played for longer earlier.

I can still get you the patcher log if necessary?

**Comment by Puremin0rez** [comment]
I can't seem to reproduce this, but apparently nallar found something that COULD cause that - so that's good.

**Comment by LunNova** [comment]
Fixed via 073a1f078071cf8.
