### ISSUE TITLE
Iron Tank

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickThreading#780]
Hey,

more and more player loose the content of their iron tanks. Since update to 1929 from a 1800+ build.

**Comment by LunNova** [comment]
Are you using MCPC+?

**Comment by Slind14** [comment]
yeah latest, but this wasnt happening before i updated TT

**Comment by LunNova** [comment]
Are the broken tanks only tanks which cross chunk borders? Are you seeing any warnings about loading chunks before world load event fired?

**Comment by Slind14** [comment]
yes they are build into two or three chunks

in which log would i find this information ?
