### ISSUE TITLE
Server running extreme low tps

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#781]
Just randomly came up, from 20 to 3

![image](https://f.cloud.github.com/assets/3824354/676017/e7128430-d8fd-11e2-919c-298e0b06f42b.png)

**Comment by LunNova** [comment]
`/profile a`, `/profile e`, and `/profile p` please?

**Comment by darkdeath1332** [comment]
Screens when 4 - 20 ticks Rapidly switching all the time.

![image](https://f.cloud.github.com/assets/3824354/676035/513f30b0-d8fe-11e2-99c8-52e18b8dd58e.png)
![image](https://f.cloud.github.com/assets/3824354/676037/5e8e799c-d8fe-11e2-97d9-a940a35bc290.png)
![image](https://f.cloud.github.com/assets/3824354/676056/9cc1e118-d8fe-11e2-819a-05e31a2a839e.png)
![image](https://f.cloud.github.com/assets/3824354/676058/aa97c320-d8fe-11e2-8ff8-087068a58992.png)

**Comment by LunNova** [comment]
Don't see anything obviously wrong there, can you get a snapshot? Only issue is very bad CC packet spam, but that shouldn't cause TPS to drop.

**Comment by darkdeath1332** [comment]
Whats the process ci.run ()?

**Comment by darkdeath1332** [comment]
Can It be someone speed hacking?....
![image](https://f.cloud.github.com/assets/3824354/676151/fde8a764-d8ff-11e2-8cf7-3a39c77ea651.png)

**Comment by LunNova** [comment]
Need the .nps. That would cause high playerMovement time, probably shouldn't make it this bad.

**Comment by darkdeath1332** [comment]
It was a CC program, deleted all and ticks are just fine. Packet spa
 Is also gone.
