### ISSUE TITLE
TT1933

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#782]
Getting this error : 

02:21:36 PM
 CONSOLE:
looking for config at ./config/rptweaks.conf
02:21:38 PM
 CONSOLE:
java.lang.NoClassDefFoundError: me/nallar/collections/ListSet
02:21:38 PM
 CONSOLE:
java.lang.ClassNotFoundException: me.nallar.collections.ListSet

**Comment by Nohau** [comment]
Got this error for not using MCPC L67 final build not sure if this is your bug though..

**Comment by LunNova** [comment]
Empty patchedMods folder, get a clean server jar. Recent TT update broke normal updating from before the package rename to after.

**Comment by Nohau** [comment]
Fixed doing the above
