### ISSUE TITLE
AE causing abnormal amounts of lag.

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#786]
For quite a while now, ME systems on my server have been causing much more lag then previously. AE has been part of the pack for a while now, and it wasn't until about two weeks ago when AE systems, mainly chests and controllers, have been appearing on the list. I don't know if it's a TickThreading issue or whether or not it's just a laggy mod.

I'm running TT1929 and MCPC+ L77, but as I said this has been happening for a while.

Here is a /profile e output, although this is at one of the calmer times. Sometimes the time gets in the 20's for them.
![1](http://puu.sh/3jCxz.jpg)

**Comment by LunNova** [comment]
It is just a very laggy mod, with older versions. It is apparently better in 1.5.2. I can't really do anything without replacing big chunks of AE, so this won't be fixed.

**Comment by Puremin0rez** [comment]
Just further confirming AE really got it's shit together in 1.5 - The latest update (v11) is phenomenal compared to previous versions.
