### ISSUE TITLE
Alternate Buildcraft by Sirse.

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#787]
http://www.mcportcentral.co.za/wiki/index.php?title=Mods_and_Plugins_for_1.4.7#Mods

Have not tried it, but saw that the patcher does not patch it and have not had time to really test it.

**Comment by Slind14** [comment]
should i rename it to buildcraft.jar that TT is patching it ?

**Comment by LunNova** [comment]
Definitely not being patched? Patcher shouldn't see a difference between this and normal BC.

**Comment by cjm721** [comment]
https://gist.github.com/cjm721/5827428

> 2013-06-19 18:48:06 [INFO] [TickThreading] Not patching com.mumfrey.liteloader.core.HookProfiler, not found.
> 2013-06-19 18:48:06 [INFO] [TickThreading] Not patching buildcraft.core.EntityRobot, not found.
> 2013-06-19 18:48:06 [INFO] [TickThreading] Not patching buildcraft.core.inventory.TransactorSimple, not found.
> 2013-06-19 18:48:06 [INFO] [TickThreading] Not patching buildcraft.energy.TileEngine, not found.
> 2013-06-19 18:48:06 [INFO] [TickThreading] Not patching buildcraft.BuildCraftFactory$QuarryChunkloadCallback, not found.
> 2013-06-19 18:48:06 [INFO] [TickThreading] Not patching buildcraft.factory.TilePump, not found.
> 2013-06-19 18:48:06 [INFO] [TickThreading] Not patching buildcraft.transport.TileGenericPipe, not found.
> 2013-06-19 18:48:06 [INFO] [TickThreading] Not patching buildcraft.transport.PipeTransportItems, not found.
> 2013-06-19 18:48:06 [INFO] [TickThreading] Not patching buildcraft.transport.PipeTransportPower, not found.
> 
> 2013-06-19 18:48:07 [INFO] [TickThreading] Not patching buildcraft.additionalpipes.pipes.PipePowerTeleport, not found.
> 2013-06-19 18:48:07 [INFO] [TickThreading] Not patching buildcraft.additionalpipes.pipes.TeleportManager, not found.

**Comment by cjm721** [comment]
I fell like an idiot... Inside of Sirse's buildcraft 3.4.3 zip are two folders one for mcpc and one for vanilla. Pulled the mcpc one out and it patched correctly.
