### ISSUE TITLE
steam boiler

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickThreading#788]
hey, 

is it normal that the big steam boiler require so much server ressources `?

**Comment by LunNova** [comment]
There is a bug with boilers next to chests. Use a small chest with always
one stack of fuel next to the boiler, instead of a big chest full of fuel.

**Comment by Slind14** [comment]
mhh, they just connected with liquiducts no chests

**Comment by LunNova** [comment]
Is this still happening? Can you get a .nps snapshot with jvisualvm if it is?

**Comment by Slind14** [comment]
dont know how to do a .nps snapshot via shell without surface

**Comment by LunNova** [comment]
https://github.com/nallar/TickThreading/wiki#visualvm-snapshot-remote-connection

**Comment by Slind14** [comment]
Cannot conenct to ip:3333 using service:jmx:rmi:.....

**Comment by Slind14** [comment]
got it, had to restart whole wrapper, sry

**Comment by Slind14** [comment]
http://www.mediafire.com/download/c269wob94ub44j7/mid_snapshot.nps

**Comment by LunNova** [comment]
Is this issue fixed then? Steam boilers don't seem to be being slow in that snapshot.

**Comment by Slind14** [comment]
mhh, the top 5 chunks still contain the most steamboilers

**Comment by LunNova** [comment]
Probably caused by whatever's in those chunks other than the steam boilers, lots of pipes/whatever?

**Comment by Slind14** [comment]
k, is there a ingame command to check just one chunk ? to see what needs most of the power in the current chunk ?

**Comment by LunNova** [comment]
Yes, stand in the chunk and run `/profile c`.

**Comment by Slind14** [comment]
mhh, with profile c i get the same like with profile e. all the chunks are listed....
![2013-07-11 02_37_50-ftb ultimate v1 1 2](https://f.cloud.github.com/assets/3914677/779009/2cee267e-e9c2-11e2-84d2-ded043528208.png)

**Comment by LunNova** [comment]
Probably because you're on an old build. Try after the AE fixes.
