### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by geoffcorey** [MinimallyCorrect/TickThreading#79]
1) Started with unpatched jars
2) Started server
3) Everything works
4) Shutdown server
5) Patch in Tick Threading
6) Turned off world tick threading
7) Started server
8) Server fails

All the logs are list in this gist https://gist.github.com/4602617 including the patch.log

This is with TickThreading-1.4.6-1.0.0.466.jar.  Also tried 475 build as well with similar results with v6 Mindcrack + Logistics Pipes

**Comment by Puremin0rez** [comment]
Geez, ChickenChunks REALLY hates TickThreading...

**Comment by LunNova** [comment]
This should finally be fixed in 3fd3ffdd48388e2. If it continues to happen, report in issue #58.

**Comment by geoffcorey** [comment]
Excellent!  Will patch it with the latest tonight and provide feedback if any issues arise!

**Comment by geoffcorey** [comment]
Running build 585 and everything has been nothing short then amazing!  Thanks!
