### ISSUE TITLE
[TT 1932] CC Turtles (Wireless Disabled) Deadlocks

### ISSUE THREAD

**Issue by Drehmini** [MinimallyCorrect/TickThreading#790]
I've disabled the crafting of wireless modems for turtles and set all wireless ranges to 0 and I'm still having issues with turtle deadlocks in the latest version.

I was able to copy over the region files and load up a test server with the exact same setup (except hardware differences) and have the same deadlock issues.

https://gist.github.com/Drehmini/5822629

I didn't have deadlocks until I upgrade to the 1929 build of TT

**Comment by Drehmini** [comment]
Also, sorry for being such a pain in the ass Nallar!

**Comment by LunNova** [comment]
That's a crash, not a deadlock.

Looks like something broke a chunk - set the chunkTileEntityMap field to null for some reason? :s

**Comment by Drehmini** [comment]
> set the chunkTileEntityMap field to null for some reason? 

I'm sorry I don't understand what this means, do you want me to set a setting or is it set already?

**Comment by LunNova** [comment]
It was a note for myself if I look at this issue again later, not something you can fix. A mod is doing something silly.

**Comment by Drehmini** [comment]
Gotcha, thanks again nallar.

Also how would I tell if it's a crash vs a deadlock? I've read through the log and it really didn't say.

**Comment by LunNova** [comment]
I was checking the 1.5 line numbers, this is actually caused by a block somewhere which has an invalid ID.
