### ISSUE TITLE
[MCPC+ 67] [TT1935] JRE Crash. Twilight forest related?

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#794]
JRE crashed. Nothing in any of the normal logs.

https://gist.github.com/cjm721/5826292

**Comment by LunNova** [comment]
Update your JRE, I can not fix this.

**Comment by cjm721** [comment]
Did not notice it started up in JRE 6 till you said that... Now why in the world did it start with JRE 6...
