### ISSUE TITLE
TT 1933 / MCPC L67 - Constant Lag Spikes

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#795]
GIST : https://gist.github.com/Nohau/5827510

Thanks I know some of it is from AE Controllers but also getting other things.

Thanks

**Comment by LunNova** [comment]
Only seeing AE reports there, looks like the file is truncated after line 18592.

Also, make sure you don't have any computercraft programs which are constantly running without sleeps/pullEvent/etc., they'll make everything else a bit slower.

**Comment by LunNova** [comment]
Closing this, as AE for 1.4.7 has serious lag problems, it's fixed in 1.5 AE versions, and I can't fix it without replacing much of AE.
