### ISSUE TITLE
[MCPC+ 67] [TT 1941] MFFS mass packets

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#798]
Noticed a large number of people on my server getting overflowed so I did profile p and noticed that MFFS was at 35MB while everything else was bellow 500KB. Anyone who was in the world (overworld) was having issues and seemed to be anyone with a slower internet was getting overflow. 

Used profile e to track it back and turn the mffs off and it disappeared on packets also.

**Comment by LunNova** [comment]
It's likely you have a forcefield somewhere which is turning on and off repeatedly, try to find and fix that.

**Comment by cjm721** [comment]
I found the forcefield and it had a solid system keeping it up. Only thing I can think of is that it was underground and did not have block breaker so it could be checking if space opened?
