### ISSUE TITLE
Server Deadlock Detector doesn't save to a log file

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#8]
Since the Deadlock Detector is designed to shut the server down when a deadlock occurs, there is no way to obtain the deadlock information as it does not get dumped to the server.log file.

A workaround for this issue is to pause whatever script you use to start the server, so it doesn't close the console.

**Comment by Puremin0rez** [comment]
This might be more of a feature then a bug, but it's much more annoying to grab a deadlock report when it doesn't dump to file.

**Comment by LunNova** [comment]
For now, I've made shutting it down optional. Will implement a proper log soon.

It should end up in FML's log file, but doesn't for some reason :s.

**Comment by Puremin0rez** [comment]
@nallar 

Cool beans. You work fast man!

**Comment by LunNova** [comment]
It now saves a log to `tickthreading.log`. The patcher saves to `patcher.log`.
