### ISSUE TITLE
[TT 1942] Factorization Router and Autocrafting Table MKII deadlocks

### ISSUE THREAD

**Issue by Drehmini** [MinimallyCorrect/TickThreading#806]
Here is the TT log : https://gist.github.com/Drehmini/5845743

Here is the error that causes the server to deadlock : http://i.imgur.com/CCDEHGC.jpg

I've tried removing TT and the server works just fine.

EDIT : Also I'm getting a Xycraft MutliBlock Validation failed.

**Comment by Drehmini** [comment]
This was actually caused by a Xycraft tank and secret rooms mod.

**Comment by LunNova** [comment]
In case you missed my reply on reddit, please stop using TT until I can fix
the issues, on holiday until Saturday.
