### ISSUE TITLE
High tick rate from area 0 0

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#807]
There is a returning problem with the area 0 0. This problem has been through most of the TT versions. Server uptime is now 1 day 2hours, so the stability is as good as it never has been! :) I just need this area 0 0 problem solved, and TT is as stable as never before.

Thanks for the continued excellet work nallar!

> ticks
> 2013-06-23 13:37:29 [INFO] [TickThreading]
> World: Overworld/0
> ---- Slowest tick regions ----
>   |     X |     Z |   N |   Time
> T |     0 |     0 |  66 | 85.859
> T |  3792 | -2064 | 684 |  3.289
> E | -6096 |  8720 |  53 |  3.200
> T | -2800 |   224 | 139 |  3.155
> T |   -96 |   368 | 185 |  2.790
> E | -3312 |  -288 |  13 |  2.626
> T | -1408 |   400 |  27 |  2.598
> ---- World stats ----

profile c 0 0

> 2013-06-23 13:38:35 [INFO] [TickThreading]
> TPS: 11.138083
>                 Single Entity | Time/Tick |      %
> projectile.EntityArrow 0,64,0 |     0.001 | 36.948
> projectile.EntityArrow 0,64,0 |     0.000 | 25.495
> projectile.EntityArrow 0,64,0 |     0.000 | 19.567
> projectile.EntityArrow 0,64,0 |     0.000 | 17.991
> Chunk | Time/Tick |       %
>  0, 0 |     0.002 | 100.000
>   All Entities of Type | Time/Tick |       %
> projectile.EntityArrow |     0.002 | 100.000
> Average Entity of Type | Time/tick | Calls
> projectile.EntityArrow |     0.000 |   308

**Comment by mainsheep** [comment]
Running TT 1941 now, by the way

**Comment by darkdeath1332** [comment]
What does /ticks say below the slowest chunk?

under World Stats, global TPS and the time

**Comment by mainsheep** [comment]
I restarted the server, so the problem is temporarly fixed. I'll post the full stats once the problem reappear, which it will in 12hours or so :)

Thanks.

**Comment by Nohau** [comment]
+1 see this every 6+ hrs as well

**Comment by mainsheep** [comment]
darkdeath1332, here are the info you requested:

> ticks
> 01:15:58 [INFO] HevyD_Frize issued server command: /tpa trap
> 2013-06-24 01:15:58 [INFO] [TickThreading]
> World: Overworld/0
> ---- Slowest tick regions ----
>   |     X |     Z |   N |  Time
> T |     0 |     0 |  14 | 7.240
> E |  5184 |   784 |   1 | 2.782
> T | -4288 |  -128 | 675 | 1.987
> T |   -96 |   368 | 185 | 1.851
> T | -6096 |  8704 | 360 | 1.606
> T | -6096 |  8720 | 546 | 1.593
> T |  4448 | -4720 | 567 | 1.527
> ---- World stats ----
> Loaded 4071 Loading 0 Unload 0 UnloadSave 0 Locks 0 PartialSave 32 Forced 477 Cached 1998
> Average tick time: 0.041116085ms
> Max tick time: 7.240062ms
> Effective tick time: 16.277828ms
> Average effective tick time: 16.957226ms
> Global TPS: 20.00
> 
> profile c 0 0
> 2013-06-24 01:16:48 [INFO] [TickThreading]
> Profiling for 7 seconds in Overworld/0 at chunk coords 0,0
> 2013-06-24 01:16:55 [INFO] [TickThreading]
> TPS: 20.0
>                 Single Entity | Time/Tick |      %
> projectile.EntityArrow 0,64,0 |     0.001 | 59.217
> projectile.EntityArrow 0,64,0 |     0.000 | 16.833
> projectile.EntityArrow 0,64,0 |     0.000 | 12.423
> projectile.EntityArrow 0,64,0 |     0.000 | 11.527
> Chunk | Time/Tick |       %
>  0, 0 |     0.002 | 100.000
>   All Entities of Type | Time/Tick |       %
> projectile.EntityArrow |     0.002 | 100.000
> Average Entity of Type | Time/tick | Calls
> projectile.EntityArrow |     0.001 |   556

**Comment by LunNova** [comment]
Can you get latest, run the server until the issue occurs, and then run `/ticks d` in console and paste the result here?

**Comment by LunNova** [comment]
Should be fixed in latest. If it's still broken, give the output from `/ticks d`.

**Comment by mainsheep** [comment]
This is indeed fixed :) Thank you nallar!
