### ISSUE TITLE
Quarrys need to much ressources with 1943

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickThreading#817]
![ftb ultimate v1 1 2_2013-06-26_22-04-37](https://f.cloud.github.com/assets/3914677/711862/bce1e298-de9b-11e2-8e56-4b6559c0a3d7.jpg)

**Comment by ghost** [comment]
Could we get the full screen? Also, keep in mind quarries are doing complicated logic to quickly mine out an area and they are also chunk loading themselves.

**Comment by Slind14** [comment]
mhh 11% from one quarry at 50 players online

**Comment by LunNova** [comment]
Sometimes, a quarry can break and recheck the area to be mined every tick.
It should not happen regularly, if it does, break and replace the quarry.
People should also not be using quarries as chunkloaders for their bases.

This is fixed in newer BC versions, but not any 1.4.7 versions.

**Comment by Slind14** [comment]
k thanks
