### ISSUE TITLE
Preformance leak

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#820]
The command /tps of tickthreading says that the server runs almost 100% CPU while my htop says 60.....

This should be an preformance issue.

![image](https://f.cloud.github.com/assets/3824354/726324/c70c47cc-e0e9-11e2-8d32-9d2068470d0e.png)

**Comment by darkdeath1332** [comment]
why is tickthreading not saying the same cpu useage as my machine says?

**Comment by LunNova** [comment]
TT doesn't make everything threaded, so some things can only run on one CPU at a time, making the load higher.

There are experimental options to improve this - concurrentNetworkTicks and waitForTileEntityTickCompletion can be changed, which should fix this. However, they are quite buggy. Isn't much else I can do, sorry. :(
