### ISSUE TITLE
[TT 1962] Deadlock Issues

### ISSUE THREAD

**Issue by Drehmini** [MinimallyCorrect/TickThreading#823]
https://gist.github.com/Drehmini/5895891/raw/1e390e22d32f826b246dcbc0f5b9141b2d04e792/gistfile1.txt

Not sure exactly what is going on, but it recovers and then deadlocks again.

**Comment by Drehmini** [comment]
Also I've added -XX:-OmitStackTraceInFastThrow to the launch parameters and it stills tells me to add that.

**Comment by LunNova** [comment]
Latest should log more info, hopefully showing why the exception has no stack trace.

Deadlock still not fixed.

**Comment by Drehmini** [comment]
This may be interesting :

2013-06-30 13:57:50 [WARNING] [MiscPeripherals] Turtle c dan200.turtle.shared.Re
dPowerTileEntityTurtleExpanded @1939206914 in Overworld/0 at x, y, z: 750, 63, 1
3 requested a fakeplayer but the world mismatches, unexpected things may happen!
 (t=null p=in@6612ec8b)
2013-06-30 13:57:50 [WARNING] [MiscPeripherals] Turtle c dan200.turtle.shared.Re
dPowerTileEntityTurtleExpanded @1939206914 in Overworld/0 at x, y, z: 750, 63, 1
3 requested a fakeplayer but its position is null!

This Warning did not appear until the last update [TT 1963]

**Comment by Drehmini** [comment]
Also,

2013-06-30 14:24:12 [SEVERE] [TickThreading] Removed c jds.bibliocraft.tileenti
ies.TileEntityArmorStand @1214879 in Overworld/0 at x, y, z: 780, 70, 1258 a
it should have been unloaded.
Removed c jds.bibliocraft.tileentities.TileEntityArmorStand @5727619 in Overw
rld/0 at x, y, z: 771, 70, 1258 as it should have been unloaded.
Removed c jds.bibliocraft.tileentities.TileEntityArmorStand @1989851 in Over
orld/0 at x, y, z: 772, 70, 1258 as it should have been unloaded.
Removed c jds.bibliocraft.tileentities.TileEntityArmorStand @1870941 in Over
orld/0 at x, y, z: 773, 70, 1258 as it should have been unloaded.
Removed c jds.bibliocraft.tileentities.TileEntityArmorStand @1272271 in Over
orld/0 at x, y, z: 775, 70, 1258 as it should have been unloaded.
Found and fixed 5 discrepancies in tile/entity lists in Overworld/0
tiles - invalid: 0, missing: 0, duplicate: 0, unloaded: 5
entities - missing: 0, duplicate: 0, unloaded: 0

**Comment by LunNova** [comment]
Is the Armor Stand at `772, 70, 1258` broken?

**Comment by Drehmini** [comment]
It wasn't broken, was just graphically overlapping. There were 2 beside it.
