### ISSUE TITLE
TT 1959 - More than annoyng - Quarrys

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickThreading#825]
We replaced ever single Quarry:
DIM29 is a farming world, there is nothing than quarrys. 
There was/is no problem with TT1917
![ftb ultimate v1 1 2_2013-06-30_19-55-17](https://f.cloud.github.com/assets/3914677/727638/8f7d976e-e1ae-11e2-8ad3-1431b32854cb.jpg)

**Comment by LunNova** [comment]
Are the quarries still functioning correctly, or stuck?

**Comment by Slind14** [comment]
working perferct.
the first one for example

quarry on normal size (without landmarks)
quarry, energy tesseract, enderchest
the enderchest gets emptied by a me system

**Comment by LunNova** [comment]
Try not connecting the quarry directly to the enderchest, they are slow to access and it may be being slow when adding items to the chest. Item tesseract, or quarry -> pipe -> enderchest.

**Comment by Slind14** [comment]
and the tesseract is ok? diretly connected ?

**Comment by Slind14** [comment]
i added pipes between the quarry and enderchest, no change

**Comment by LunNova** [comment]
https://github.com/nallar/TickThreading/wiki#visualvm-snapshot-remote-connection

**Comment by Slind14** [comment]
http://www.mediafire.com/download/c269wob94ub44j7/mid_snapshot.nps

**Comment by LunNova** [comment]
Assuming this is fixed now, as you commented that the TPS issues were fixed in your other issue.

**Comment by Slind14** [comment]
after AE fix Quarrys are back on top...

**Comment by Slind14** [comment]
do u see any way to improve the performance of them ?

**Comment by Slind14** [comment]
still the same, but ok

**Comment by LunNova** [comment]
Don't support 1.4.7 any more.
