### ISSUE TITLE
auto update/request

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#828]
Is there anyway to make tt auto update and run patch using ssh ?

host is on centos

**Comment by LunNova** [comment]
Use the script here http://forum.feed-the-beast.com/threads/tickthreading-concurrent-entity-tile-entity-ticks-and-other-optimisations.6498/page-27#post-304294

**Comment by HaoSs07** [comment]
[root@s1 service192]# sh update.sh
Usage: ./UPDATETT.sh <build number>
[root@s1 service192]#

there is no UPDATETT.sh

if run manually 

[root@s1 service192]# wget http://nallar.me/buildservice/job/TickThreading/$1/artifact/target/TickThreading.jar -O mods/TickThreading-$1.jar
--2013-07-01 02:39:22--  http://nallar.me/buildservice/job/TickThreading//artifact/target/TickThreading.jar
Resolving nallar.me... 173.236.6.240
Connecting to nallar.me|173.236.6.240|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2013-07-01 02:39:22 ERROR 404: Not Found.

[root@s1 service192]#

**Comment by LunNova** [comment]
"UPDATETT.sh" is just what I call it. Note that it tells you to use a build number, you'll want to run `./update.sh <build number here>`

**Comment by LunNova** [comment]
If you want to grab the latest build, instead of giving a build number give "lastSuccessfulBuild".

**Comment by HaoSs07** [comment]
youp. i'm blind as fu*k :)) working
