### ISSUE TITLE
[MCPC+ 67] [TT1966] CC computers Number format Exeption

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#829]
Any computer made is usable as if it is shutdown, error on console is bellow. Older computers/turtles work fine.

> 00:36:25 [INFO] ComputerCraft: Error running task.
> 00:36:25 [SEVERE] java.lang.NumberFormatException: null
> 00:36:25 [SEVERE]   at java.lang.Integer.parseInt(Integer.java:454)
> 00:36:25 [SEVERE]   at java.lang.Integer.parseInt(Integer.java:527)
> 00:36:25 [SEVERE]   at dan200.computer.core.Computer.getUserDir(Computer.java:644)
> 00:36:25 [SEVERE]   at dan200.computer.core.Computer.initFileSystem(Computer.java:670)
> 00:36:25 [SEVERE]   at dan200.computer.core.Computer.access$1100(Computer.java:31)
> 00:36:25 [SEVERE]   at dan200.computer.core.Computer$1.execute(Computer.java:911)
> 00:36:25 [SEVERE]   at dan200.computer.core.ComputerThread$1$1.run(ComputerThread.java:72)
> 00:36:25 [SEVERE]   at java.lang.Thread.run(Thread.java:722)

**Comment by LunNova** [comment]
Maybe the lastid.txt file in world/computers has been corrupted, make sure it's set to something sensible.

**Comment by LunNova** [comment]
Confirmed that that would cause this.
