### ISSUE TITLE
ComputerCraft doesn't like TT - Build 591

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#83]
Issue 1:
Mining Turtles, when in movement, will revert to a normal turtle as soon as the chunk is unloaded. I know there is an issue in vanilla CC similar to this where if the server crashes when turtles are moving, this will happen - but the problem is, the server isn't crashing in this scenario. I tried to repeat this without TT and the issue never happened.

Issue 2:
CC isn't loading startup programs correctly - CC should load this program upon server boot (or, first initial chunk load) but TT for some reason stops this from happening - instead, the person must first "right click" the turtle/computer for it to start the program - this is not the correct behavior

**Comment by LunNova** [comment]
Trying just now, and I can't get the second issue to happen. A turtle with "turtle.forward();" in its startup moves on chunk load without any need to right click.

**Comment by Puremin0rez** [comment]
I just tried 606 and I can't repeat the second issue anymore...

I can still repeat the 1st issue every single time though.

**Comment by LunNova** [comment]
1st issue seems not to be a TT issue - can you confirm that it's definitely TT? Seen reports on CC forums, and in #FTB.

**Comment by Puremin0rez** [comment]
@nallar 

I tried 30 minutes without TT trying to get it to happen and it simply never happened, It's possible it does happen without it, but I think TT is making it happen even more often

**Comment by Puremin0rez** [comment]
Just reconfirming that without TT, this reverting turtle issue simply never happens. Ran without TT for almost 2 days now (because of v8 MindCrack) and it never happened - had TT on my server again and less then 10 minutes later peoples turtles were reverting to the dataless counterpart.

Is there possibly something "threaded" I can disable that would resolve this?

**Comment by Puremin0rez** [comment]
Going to see if any of your recent entity changes possibly fixed this today.

**Comment by LunNova** [comment]
Still happening then? :(

**Comment by Puremin0rez** [comment]
Sorry, was busy and didn't get to test. Lots of people on my server today - so we'll see :)

**Comment by Puremin0rez** [comment]
Nobody has reported loosing turtles and i haven't either. I'll close this..... for now...
