### ISSUE TITLE
Not up to date, when it is?

### ISSUE THREAD

**Issue by Jonathan1999** [MinimallyCorrect/TickThreading#830]
I just installed tickthreading 1967 on my server, patched it and whenever I start up my server it crashes, I checked the log and it says its not up to date, when I'm using the latest version, here's the log: 

http://pastebin.com/yU7XyD3Y

**Comment by cjm721** [comment]
run the generated patchme.bat or patchme.sh

**Comment by LunNova** [comment]
It seems that it is patched, `2013-07-01 22:01:46 [INFO] [ForgeModLoader] Loaded 8 patched classes for AppliedEnergistics.zip.`.

@Jonathan1999 Can you get latest and try again? It will still be broken, but the log will now show which files it checked, which may explain why it doesn't work.

Post the full log here.

It's possibly related to the minecraft install being in the root of `R`, not in a folder.

**Comment by Jonathan1999** [comment]
At the time I was using the latest version, now I'm using 1970. It was because it's at the root of my RAMDisk, it's fine now, thanks for your help.
