### ISSUE TITLE
Crash on start 1.5.2 build 67-69

### ISSUE THREAD

**Issue by justin0a0** [MinimallyCorrect/TickThreading#834]
On start of the server I get a crash saying that the server is not patched.
Running Java 1.7.0_15 CentOS 6.2
Patcher log - http://pastebin.com/KYE64Zb2
Tickthreading log - http://pastebin.com/4hA9S887
ForgeModloader log - http://pastebin.com/egcYp0wY
Server log - http://pastebin.com/S0t1uvfn

Previously used build 32 and it loaded just fine updated to 67 had the following issue so tried 68 and 69 also same error not patched after patching it.

**Comment by Nohau** [comment]
Did you run the Patchme.sh file in the root minecraft folder that was created?

**Comment by justin0a0** [comment]
If you check the Patcher log you will see yes I did. even reset and did it twice same error on both setups.

**Comment by justin0a0** [comment]
This was all due to the out of date patches for MineFactory Reloaded.
I have gone back to the official releases and all is well again.
Just a heads up.
