### ISSUE TITLE
Can't place GT plates

### ISSUE THREAD

**Issue by Tencao** [MinimallyCorrect/TickThreading#836]
After patching the mods with tickthreading, you can no longer place plates on machines, it just does the interact right click instead.

Sadly, there is no error log to go with this issue

**Comment by Nohau** [comment]
TT Version and are you using MCPC or FTB server?

**Comment by Tencao** [comment]
MCPC version 592, and TT version 74 was the last one I tried this on

**Comment by demon959** [comment]
Still having the same issue using 143 build, on FTB server
