### ISSUE TITLE
1.5.2 IC2 Issue

### ISSUE THREAD

**Issue by Tencao** [MinimallyCorrect/TickThreading#842]
There seems to be an issue with IC2 power storage blocks (For example, batbox) That will only accept power from the output face, and output power from the output face. This bug is only present with tickthreading installed

TickThreading Version - #74
IC2 Version - 2_1.117.385-lf

**Comment by LunNova** [comment]
Why did you close this? Did you find what was causing it?

**Comment by Tencao** [comment]
The issue ended up been IC2 Dev version, after looking into it further, it happened even without tickthreading, and would only work correctly if the wires was setup and then the server was restarted

IC2 version 376 seems stable and working without issues
