### ISSUE TITLE
1.5.2 Block Lag issue

### ISSUE THREAD

**Issue by Tencao** [MinimallyCorrect/TickThreading#843]
There seems to be some weird blocklag going on with the 1.5.2 build. It appears to mainly be the packets been sent to the clients, as it's most apparent with falling blocks, and blocks destroyed by other players.

The lag can sometimes be as big as 3-5 second wait time before the blocks disappear

Tickthreading Version - 74

**Comment by LunNova** [comment]
Disable `rateLimitChunkUpdates` in the config.
