### ISSUE TITLE
TT1980 - Deadlocks

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#845]
The server has been continually deadlocking then recovering every few minutes. Here is the log:
http://pastebin.com/MpCP9c0B

I only included the first few as the whole thing exceeds Pastebin's limit. Hopefully that gives you enough information.

**Comment by LunNova** [comment]
I need the full log, use https://gist.github.com/ for pastes.

**Comment by LunNova** [comment]
That latest fix is based on me guessing at what the problem is, might be completely irrelevant :P

**Comment by darkdeath1332** [comment]
I have the same error.

**Comment by LunNova** [comment]
Paste the full error. @joey19982 still hasn't so I'm left to guess as to what is actually broken.

**Comment by darkdeath1332** [comment]
Here is my log....

http://www.mediafire.com/?54s451rp637l71l

**Comment by darkdeath1332** [comment]
Full log, please fix it nallar :(

http://pastebin.com/2ecrm5VE

**Comment by darkdeath1332** [comment]
I keep losing players, its crashing and spiking alot of times.

And why is nobody donateing? @nallar if you wish I could donate.

**Comment by LunNova** [comment]
Make a backup, remove Twilight Forest from the real copy. Seems to be related to it, froze up saving twilight forest.

**Comment by darkdeath1332** [comment]
@nallar Will deleting the world help?

**Comment by LunNova** [comment]
No, renaming the "twilight.fc" file might. Also another issue there, will fix it soon.

**Comment by darkdeath1332** [comment]
Ok ive got the file, backed up. In what do I have to rename it?...

**Comment by LunNova** [comment]
Oh, to anything. Just said rename instead of delete in case you needed to use it. You can delete it if you made a backup.

**Comment by darkdeath1332** [comment]
Restart required?

**Comment by LunNova** [comment]
May need to delete it while the server is stopped, TF will probably recreate it when you stop the server.

**Comment by darkdeath1332** [comment]
thanks, I hope its fixed.

**Comment by LunNova** [comment]
The other crash you had will be fixed in that build. It should now recreate the file, but much smaller.

**Comment by joey19982** [comment]
Sorry I didn't get back to you @nallar.
I'll check out the latest build next time my server restarts and report back with the log. Also, I didn't even know that you had donations. I sent a bit of money your way as a thanks for everything you do here.

**Comment by LunNova** [comment]
Thanks :D

**Comment by joey19982** [comment]
Getting some deadlocks here on #1988, however I don't think they are relating to this. You may have already fixed it since I see you've made a few more builds since I added this.

https://gist.github.com/joey19982/5937703

**Comment by LunNova** [comment]
Log still seems to be cut off. Logs should be much smaller on latest, if it does still happen.

**Comment by joey19982** [comment]
Strange, I know I pasted the full thing. I'll try the latest though.

**Comment by joey19982** [comment]
So far so good, so I'll close this.
