### ISSUE TITLE
Latest version eats CPU

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#847]
Ive been testing multiple versions on the same load quarrys and chunk loaders. This are our CPU results.

Latest version eats cpu, ive been testing with slind. 

Our results;
57 - 83%  Build [1970
29 - 87% Build [1917
28 - 35% Build [1947
26 - 36% Build [1863
30 - 36% Build [1964

**Comment by LunNova** [comment]
Nothing I can do without a .nps snapshot from jvisualvm. See earlier issues marked as "performance" for instructions on using it remotely. Will make a wiki page on using it soon.

**Comment by HaoSs07** [comment]
https://github.com/nallar/TickThreading/wiki

had some free time. already done

**Comment by LunNova** [comment]
Thanks :D

@darkdeath1332 follow the instructions that @HaoSs07 has posted and I will be able to fix this.

**Comment by LunNova** [comment]
Closing as duplicate of #825, presumably caused by that issue. Please give me the snapshot, I still can't fix this :(

**Comment by Slind14** [comment]
wow from 60% cpu usage to 200% something after 1947 changed,

**Comment by darkdeath1332** [comment]
Same, I dont want to snapshot becouse I lose quite alot of players due it.

**Comment by HaoSs07** [comment]
lose players because of a snapshot ?:)) ok... walking away. awkward

**Comment by darkdeath1332** [comment]
@HaoSs07 No from the build, I used the latest builld and when my server was about to reach 80 it lagged as fuck. I use 1947 again and my CPU is just 60% with 125 on.
