### ISSUE TITLE
MC1.4.7 TTbuild 1970 - Endermen extremely slow to spawn

### ISSUE THREAD

**Issue by elanini** [MinimallyCorrect/TickThreading#853]
They are usually quite quick to spawn everywhere in the end, often covering the asteroids off of the main island. However this is not the case with TickThreading - they are extremely slow to spawn. After installing TT I see maybe 1 or 2 in the middle of nowhere after waiting for quite a while. 

I had made an enderman xp/pearl farm, which this completely breaks. Really hoping for a fix. 

FastMobSpawning is enabled.

**Comment by LunNova** [comment]
Try disabling fast spawning in the end, add dimension 1 to the list of dimensions it is disabled in.

**Comment by elanini** [comment]
Disabling fast spawning in the End does solve the problem. Is this effect of fast spawning intended?

**Comment by LunNova** [comment]
It's not intended, but the algorithm for fast mob spawning just isn't very efficient in the end. Will disable it in the end by default.
