### ISSUE TITLE
Disabling ChickenChunks offline players chunkloading breaks online player chunkloading in other dimensions

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#857]
When enabled the option to disable chunkloading for offline players, the chunkloading for ONLINE players in for example nether is disabled. Thus making lava collection impossible.

This has been a problem on all the TT releases.

**Comment by joey19982** [comment]
I've also had reports of Personal Anchors randomly unloading, even in the same dimension. I haven't looked too much into it yet.
