### ISSUE TITLE
Long start thaumcraft/tf related ?

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#858]
Done (307.918s)! For help, type "help" or "?" 
usually is 20s . but now 5 minute to load cache ?
also before server restart i put thaumcraft in aura regeneration but the regeneration i know is done after world loads.

2013-07-07 22:01:21 [INFO] [TickThreading] Threading initialised for world Twilight Forest/7
2013-07-07 22:06:27 [INFO] [ForgeModLoader] [TwilightForest] Loaded feature cache with 4591 chunks present.

snapshot with server starting :
https://dl.dropboxusercontent.com/u/76651664/start.nps

**Comment by LunNova** [comment]
According to the snapshot, FE took a very, very long time trying to interact with the DB server. Looks like your DB server's being slow, not a TT issue.
