### ISSUE TITLE
Mystcraft packet failures upon teleport - Build #631

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#86]
http://pastebin.com/3yc5jHBc

Edit: Here's another paste link incase pastebin is loading SUPER slow for you (it is for me)
http://pastie.org/5865632

This is definitely a new issue and has never happened before.

**Comment by LunNova** [comment]
What was the last build you were on where it worked?

Is it still broken in latest?

**Comment by Puremin0rez** [comment]
I cannot for life of me remember what build I was on before, I think it might have been 623 - but I didn't do any testing at all on that build so I have zero idea when this issue started occurring.

It seems as if the first time every Mystcraft world is loaded (after a server reboot), the player will get kicked with the error I put above.

User A went to Book A and went to teleport to it - he got kicked, logged back in, was able to use the book fine.
User B went to Book A and went to teleport to it - he got kicked, logged back in, was able to use the book fine.
They are now able to use the book over and over again until the server gets rebooted.

For each new age, the same problem occurs.

**Comment by Puremin0rez** [comment]
I'll test the latest in 5+ Hours, can't until then...

**Comment by Puremin0rez** [comment]
Still happening, its an on / off issue - Can't reproduce everytime. Might be Mystcraft bug? Although it's never happened until recently, that i'm positive of.
