### ISSUE TITLE
Gates/BuildCraft pipes - Causing high tick rates

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#865]
I'm not sure where to put this, but maybe a suggestion to improve performance would be ok?

At the moment, the nr 1 reason for tps loss on my server, is buildcraft pipes and/or autarchic gates. Is there any way for TT to implement some sort of tweak to these systems so that it can cause less lag?

One way to improve this, would be to disable the autarchic gate "always on"-mode.

Below is a "profile e" output from my server:

> 2013-07-09 13:44:59 [INFO] [TickThreading]
> TPS: 18.42594
>                     Single Entity | Time/Tick |     %
> player.EntityPlayerMP -939,44,828 |     0.942 | 0.598
>  gadgets.TileGearbox -2834,60,232 |     0.905 | 0.579
>  tile.TileController -2811,63,224 |     0.899 | 0.576
> tile.TileController 1014,64,19065 |     0.755 | 0.484
>   tile.TileController 7391,61,244 |     0.677 | 0.434
>      Chunk | Time/Tick |     %
>   324, 798 |     8.269 | 5.136
>    90, -62 |     3.721 | 2.311
> -133, -341 |     2.699 | 1.676
>    -59, 51 |     2.425 | 1.506
>  -46, -286 |     2.080 | 1.292
> All Entities of Type | Time/Tick |      %
>      TileGenericPipe |    26.381 | 16.386
>     TileTankIronWall |    11.693 |  7.263
>    TileConduitLiquid |     8.408 |  5.222
>    TileConduitEnergy |     6.745 |  4.189
>  tile.TileController |     6.583 |  4.089
> Average Entity of Type | Time/tick | Calls
>       EntityGolemStraw |     0.242 |   665
>    tile.TileController |     0.180 |  4742
>    gadgets.TileGearbox |     0.148 |   931
>     EntitySpawnedBlaze |     0.092 |    17
>        EntityCartChest |     0.085 |   133

I think that GenericPipe is actually the gates, but i'm not 100% sure. TPing to the coords where ticks show the most ticks, useually there are tonns of autarchic gates on buildcraft pipes.

**Comment by LunNova** [comment]
Snapshot please?

**Comment by seriousvern** [comment]
i increased the network update factor and that solved alot of problems also made the item merging size larger so as to have less visible objects in the pipes. All of these tweaks can be found in the bc config folder

**Comment by mainsheep** [comment]
snapshot? You mean the version of TT I'm running? v2008. This has been for a couple of releases though. Probably since launch, but as more and more people start using these damn pipes and autarchic gates, the server gets less and less tps.

**Comment by mainsheep** [comment]
thank you seriousvern.. I'm thinking network update factor only saves bandwitdh, or I might be wrong. Bandwidth is not a problem for my server.. I've implemented the item merging size though, thanks.. This will probably not solve the autarchic gate problem, I'm guessing..

**Comment by LunNova** [comment]
No, this: https://github.com/nallar/TickThreading/wiki#visualvm-snapshot-remote-connection

**Comment by Slind14** [comment]
its similar to me, u can look into this snapshot.
http://www.mediafire.com/download/76ouoo6k688w56a/computercraft.nps

**Comment by Slind14** [comment]
why do u close everything ?

**Comment by LunNova** [comment]
Don't support 1.4.7 any more.

**Comment by Slind14** [comment]
ok
