### ISSUE TITLE
xReliquary debug spam

### ISSUE THREAD

**Issue by seriousvern** [MinimallyCorrect/TickThreading#866]
i get this in my console alot and have googled it and cannot find what it is from

08:42:09 [INFO] Slot 6 contains an item worth 1
08:42:09 [INFO] At the time of execution, total value sits at 64
08:42:09 [INFO] Slot 4 contains an item worth 0
08:42:09 [INFO] Slot 6 contains an item worth 1
08:42:09 [INFO] At the time of execution, total value sits at 64
08:42:09 [INFO] Slot 4 contains an item worth 0
08:42:09 [INFO] Slot 6 contains an item worth 1
08:42:09 [INFO] At the time of execution, total value sits at 64
08:42:09 [INFO] Slot 4 contains an item worth 0
08:42:09 [INFO] Slot 6 contains an item worth 1
08:42:09 [INFO] At the time of execution, total value sits at 64
08:42:09 [INFO] Slot 4 contains an item worth 0
08:42:09 [INFO] Slot 6 contains an item worth 1
08:42:09 [INFO] At the time of execution, total value sits at 64
08:42:09 [INFO] Slot 4 contains an item worth 0
08:42:09 [INFO] Slot 6 contains an item worth 1
08:42:09 [INFO] At the time of execution, total value sits at 64

does this look familiar or do you need more info
this is ftb ultimate 1.1.2
please help

**Comment by LunNova** [comment]
Xeno's reliquary alkahest handler.

**Comment by seriousvern** [comment]
dude you are the best of the best

**Comment by Drehmini** [comment]
I'm still receiving these messages: 2013-07-09 20:48:08 [INFO] [STDOUT] At the time of execution, total value sits a
t 64

**Comment by seriousvern** [comment]
i am also getting this alot in my console it is filling up my logs

**Comment by LunNova** [comment]
Accidentally only removed one of the debug lines, so it only half fixed the problem.
