### ISSUE TITLE
IC2 blocks not updating client-side

### ISSUE THREAD

**Issue by Khitara** [MinimallyCorrect/TickThreading#867]
Hi,
I've just installed TickThreading on my 1.4.7 custom server, home-run, to try and solve some TPS issues. 

The good news: It seems to make my server run at 20 TPS rather than the 7-16 I was getting.

The bad news: Any IC2 block I place is invisible, even though the entity is selectable, and if I break a block, it's still visible client-side, even though the item has been dropped on the floor. Reconnecting to the server fixes this, but only for those blocks affected. Any new block you'd have to reconnect for.

Couldn't quite find anything similar, any ideas? Any logs I need to post?

**Comment by LunNova** [comment]
Are you using multiverse + MCPC+? Other than that, never heard of this issue before, no idea what's causing it.

**Comment by Khitara** [comment]
I don't use either of those, just regular Forge

**Comment by LunNova** [comment]
Can you get latest, and add `-Dtickthreading.ic2remap=false` before the `-jar` in your start.sh? Might fix it.
