### ISSUE TITLE
Patcher no longer working on Windows

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#87]
http://pastebin.com/sZTm26yR

**Comment by Puremin0rez** [comment]
This was the commit that broke my ability to patch FYI
https://github.com/nallar/TickThreading/commit/e1a8fea1a16f6a42f3872c66df92d2584a6f8eee

**Comment by LunNova** [comment]
d957cd677cefc26187c43f588 should fix it - looks like it went over the file name length limit?

**Comment by Puremin0rez** [comment]
Yep it's fixed :)
