### ISSUE TITLE
502 Bad Gateway on Build Server

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#875]

**Comment by GUIpsp** [comment]
Ok, now tell me how this is a TickThreading issue.

**Comment by cjm721** [comment]
Can't download the new versions so can't test them. This is also a simple and effective way to get ahold of naller and shows other people that it has already been reported so he does not get his email spammed.

**Comment by LunNova** [comment]
And it's also why I have a "site" label. This is related enough, don't really have anywhere better to put issues with the site.

Fixed.
