### ISSUE TITLE
[MCPC+ 67] [TT 2012] Applied Energistics Cpu usage

### ISSUE THREAD

**Issue by cjm721** [MinimallyCorrect/TickThreading#876]
I do not know if this is from making my system import/export a bit more now then it was yesterday or from upgrading from 2008 to 2012 but on 2008 I could craft very large and complex recipes (such as an entire fusion reactor and several quantum tanks) at once and not go above 15% cpu usage. Now just telling it to craft a single quantum tank makes the CPU usage of every ME system spike. 

IE I start mine and every other ME system on the server seems to be effected and cause server load to skyrocket.

From looking at the commits I do not see anything that would of effected AE from 2008 > 2012 so kinda at a loss for it.

**Comment by LunNova** [comment]
See #877. You posted this first, but I noticed the other first and now it has my posts in it. Sorry!

Closed as duplicate.
