### ISSUE TITLE
Performance regression - better TPS with build 1947

### ISSUE THREAD

**Issue by Slind14** [MinimallyCorrect/TickThreading#877]
Check out these two pictures, one very small ME System with this CPU usage ???
![2013-07-11_01 18 19](https://f.cloud.github.com/assets/3914677/778700/6bbb34dc-e9b8-11e2-8dc4-16c5efc9f3c1.png)
![2013-07-11_01 18 45](https://f.cloud.github.com/assets/3914677/778701/6eb6194a-e9b8-11e2-800f-3b113c5d5942.png)
At all....
![2013-07-11_01 25 56](https://f.cloud.github.com/assets/3914677/778703/85c3f1de-e9b8-11e2-9a68-609f804499eb.png)

Server is running on higher TPS without TT

**Comment by LunNova** [comment]
Completely redoing AE patching just now, should be fixed soon.

**Comment by Slind14** [comment]
thanks a lot

**Comment by LunNova** [comment]
If you have a test server, now would be a good time to try latest. Should make AE stuff much faster, but may be buggy.

**Comment by Slind14** [comment]
i have a testserver but i cant load chunks for 50 people...

**Comment by Slind14** [comment]
jenkins down ?

**Comment by LunNova** [comment]
Should be up now, but my host might be having network issues. Fixed another big performance issue with forestry, so if you just updated you may want to update again.

**Comment by Slind14** [comment]
thanks, but i think wait until the new deadlock is fixed

**Comment by andremiller** [comment]
I don't know if is related to the latest changes, but since applying the latest build (going from 2005 to 2034) my ME network has been running very slowly. Import busses especially. Crafted items just sit in my furnaces for a long time without getting extracted with the import bus. It seems to help if I open up the machine's interface, then it seems to extract the item.

**Comment by LunNova** [comment]
@andremiller had a few requests to skip ticking AE devices sometimes as they cause performance issues in 1.4.7, so it sometimes skips them.

Can you not just set the import bus to transfer in stacks of items at a time, or is that still too slow?

**Comment by andremiller** [comment]
@nallar They're already set to import stacks at a time, but it's still too slow :(. Unless there's also another bug, it sometimes sits there for 4 or 5 seconds doing nothing. I've reverted to an older version of TickThreading for now.

Where the speed is really critical is in my setup to create Tritium and Deuterium fuel for my fusion reactor. I'm using AE to import/export cells into lots of electrolyzers, then into centrifuges and then into liquid transposers.

Is it possible to make the skipping of AE ticking a configurable option?

BTW Thanks for all the work you're putting into TickThreading. Without it I wouldn't be able to run my server on the hardware it's on!

**Comment by vsilvar** [comment]
@nallar It would be great if there as a config option to not skip ticking AE devices. On a side question, do factorization routers also suffer from this? They appear to be slower than normal.

**Comment by LunNova** [comment]
Should be fixed now, don't skip ticks for import/export buses.

**Comment by Slind14** [comment]
i updated to the latest version and there is no change:
![putty_2013-07-13_02-03-58](https://f.cloud.github.com/assets/3914677/791744/e3b3e964-eb4f-11e2-92e3-adb5692c6705.jpg)

**Comment by Slind14** [comment]
the server is still running on more tps without tickthreading. what changed since 1947 ?

**Comment by LunNova** [comment]
What are you using to measure TPS without TT? Bechill TPS? It actually measures incorrectly, doesn't measure time spent outside of world ticks.

Other than that, no idea why it's still slower for you on newer builds.

Although looking at that profile, it has definitely changed since the screenshot you gave earlier - there, AE took > 50ms per controller, here the worst controller only takes 14ms.

Are you using up to date java? I made some changes which assume you're using up to date java 7, and on old versions will make performance worse.

Other than that, I'll have some more changes related to AE controllers soon, which should improve performance a lot when auto crafting.

If you could get a .nps snapshot on latest that would be useful. Make sure to set the sampling frequency to 20ms.

**Comment by LunNova** [comment]
@Slind14 

Just noticed TileEntityChest is showing up as being slow in profiling. That definitely shouldn't happen, somethings does seem very broken :s

What does `/profile a` show? Can you run `/profile e 300` to get a long profile, in case it was just an odd result by chance as it only profiled for 7 seconds?

What are your java parameters?

**Comment by LunNova** [comment]
Had an idea of what the problem might be, made a change in build 2045 which might fix this. If it doesn't, still want the stuff I asked for in the previous post.

Also, the output of `/ticks l` could help too.

**Comment by Slind14** [comment]
./gc of essentials.

i will get u the result when there are some more people back on the server

java build 1.7.0 17-b02 -> should i update ?

**Comment by Slind14** [comment]
/profile a
![putty_2013-07-13_11-00-29](https://f.cloud.github.com/assets/3914677/792445/c8444412-eb9a-11e2-8fc1-79ecc6fdfa64.jpg)

/profile l
![putty_2013-07-13_11-01-52](https://f.cloud.github.com/assets/3914677/792449/ec9ba4c2-eb9a-11e2-8fdc-ce10e5f21479.jpg)

/profile e 300
![putty_2013-07-13_11-05-54](https://f.cloud.github.com/assets/3914677/792454/d49558d6-eb9b-11e2-823b-e19ce043425d.jpg)

**Comment by Slind14** [comment]
looks a way better now, but at this time there was nobody online with a huge me system with autocrafting, fusionreactor...

snapshot:
http://www.mediafire.com/download/ptkz7mom2s13mbc/mym_snapshot_2051.nps

**Comment by andremiller** [comment]
@nallar Thanks, it looks like my AE network is behaving again, exporting and importing items when it should :)

I did pick up an issue with my Fabricator, not sure if it is releated, issue #895

**Comment by Slind14** [comment]
1951 is working perfect with AE, thank u so much .D
![putty_2013-07-14_19-56-08](https://f.cloud.github.com/assets/3914677/794629/d2a804d8-ecae-11e2-92a1-71e66f9b63e2.jpg)
![putty_2013-07-14_19-59-26](https://f.cloud.github.com/assets/3914677/794632/2b20d5cc-ecaf-11e2-8f81-86b46b950523.jpg)
