### ISSUE TITLE
IC2 Energy Net broken with b661

### ISSUE THREAD

**Issue by bogie** [MinimallyCorrect/TickThreading#88]
Logs: http://bawki.de/minecraft/tickthreading/

Error is 2013-01-27 23:17:42 [WARNING] [IC2] EnergyNet.emitEnergyFrom: ic2.core.block.wiring.TileEntityElectricMFE@18acef70

for more see IC2warning.txt linked above.

Used build 661 on a clean version of ftb(mindcrack) with bukkitforge 139, last known working version was b587(testing 592 now)

**Comment by LunNova** [comment]
Are the machines at the listed coords working? If so, that's an IC2 bug with it being spammy when everything's fine.

If they're broken, I'll need to mess about with enet. Again.

**Comment by bogie** [comment]
Machines are working, but power does not flow via cables, you can charge your stuff in any energy storage/generation device though.

**Comment by LunNova** [comment]
Are you using a modified IC2 jar with the newer energynet? If so, can you try reverting it? That should no longer be necessary and might actually break stuff.

I've seen a problem like this before, but it goes away after a restart and doesn't return, making debugging difficult. Those logs don't actually show why, nor does IC2's design make it easy to find out.

**Comment by LunNova** [comment]
Still not sure what's causing it, but it goes away after a couple of restarts. I'll fix it as soon as I find exactly what's causing it.

**Comment by LunNova** [comment]
Javassist was producing incorrect bytecode for the enet patch. I've changed the way that's patched, and this issue should now be fixed in the latest build.

**Comment by LunNova** [comment]
Fix confirmed via forums.
