### ISSUE TITLE
Mass is not conserved through portals.

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#881]
Just got around to reporting this, I'm surprised it hasn't been reported all ready. For a while now Mass isn't conserved when traveling through portals. If you put two portals on the ground, rather than flying up a bit before going back down it will instantly teleport you between each one. Doing that with a bunch of items I'm sure could cause a denial of service attack of sorts.

Disabling Concurrent Movement Updates allows mass to be conserved again.

**Comment by LunNova** [comment]
This only applies to players, not items.

**Comment by joey19982** [comment]
Ah, okay. Didn't test items. That makes me feel better about it.
