### ISSUE TITLE
Personal Anchors rarely keep chunks loaded.

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#882]
On my server, the only chunk loaders allowed are Personal Anchors because they are a lot less "OP" then ChickenChunks, and they don't keep chunks loaded forever like World Anchors. Though since I made that change, I've been getting some reports about Anchors being very unreliable. They are supposed to keep chunks loaded until you log off, but they appear to do so only half of the time.

I set up a 2 turtles about 1000 blocks away on my local server and put a world anchor next to one and a Personal Anchor next to another. I left the area for about 30 minutes, then came back. The World Anchor was still going as normal, but the Personal Anchor had stopped.

I'm not sure if this has any relation to #857, but I figured I would report it just in case. I also hear that Quarries are being unloaded as well, but haven't tested that yet.

**Comment by LunNova** [comment]
Can you right click the stopped anchor with a clock and post the output? (Or run `/dump x y z` in console and copy/paste)

Are you sure the chunkloading limit isn't set too low? What does `/ticks` say for the world the anchor is in?

**Comment by joey19982** [comment]
Sorry, just saw your reply. I'm very forgetful when it comes to these tickets.

I'm running the test again now on both my local and main server. It shouldn't be the chunkloading limit, as it was on my freshly-generated local server with only me on.

**Comment by joey19982** [comment]
When I did my test it worked, and I haven't gotten any reports in a bit. Maybe you unintentionally fixed it? Or maybe it never happened in the first place and I'm just paranoid. I'll update this if I see it happen again, for now closing.
