### ISSUE TITLE
Railcraft not patching

### ISSUE THREAD

**Issue by VMBindraban** [MinimallyCorrect/TickThreading#883]
[code]C:\Users\Gebruiker\Desktop\Nieuwe map>"C:\Program Files\Java\jre7\bin\java" -cp
"mods\TickThreading.jar;lib\guava-12.0.1.jar" nallar.tickthreading.patcher.Patch
Main patcher "ftbserver.jar,coremods,mods"
2013-07-11 20:32:06 [INFO] [TickThreading] Running TickThreading v1.0.0.2034 for
 MC1.4.7 - 1.7.0_25-b17
2013-07-11 20:32:06 [SEVERE] [TickThreading] Can't patch - no backup for railcra
ft.jar exists, and a patched copy is already in the mods directory.
You will need to replace this file with a new unpatched copy.
2013-07-11 20:32:06 [SEVERE] [TickThreading] An error occurred while patching, c
an't continue
java.lang.Error: Missing backup for patched file
        at nallar.tickthreading.patcher.ClassRegistry.restoreBackups(ClassRegist
ry.java:257)
        at nallar.tickthreading.patcher.PatchManager.loadBackups(PatchManager.ja
va:71)
        at nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:97)
        at nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:31)
2013-07-11 20:32:06 [INFO] [TickThreading] Done. Press enter to exit.[/code]

Server keeps telling me:

[code]11.07 12:33:15 [Server] INFO Also, make a full backup of your server if you haven't already!
11.07 12:33:15 [Server] INFO To patch your server, simply run the PATCHME.bat/sh file in your server directory
11.07 12:33:15 [Server] SEVERE TickThreading is disabled, because your server has not been patched or the patches are out of date
11.07 12:33:15 [Server] INFO Expected 1350372139, got 2118572607
11.07 12:33:15 [Server] WARNING Patching required for /mods/railcraft.jar because it is out of date.
11.07 12:33:15 [Server] INFO Expected 71055302, got -214388034
11.07 12:33:15 [Server] WARNING Patching required for /mods/MineFactoryReloaded.jar because it is out of date.[/code]

**Comment by VMBindraban** [comment]
FTB Ultimate btw.

**Comment by LunNova** [comment]
`2013-07-11 20:32:06 [SEVERE] [TickThreading] An error occurred while patching, c
an't continue
java.lang.Error: Missing backup for patched file`

Did you delete the TTBackups folder?

You'll need to delete coremods and server jar, get them fresh from FTB ultimate and then patch again.

**Comment by LunNova** [comment]
Actually, railcraft.jar itself should never be patched. Also get a fresh mods folder.

**Comment by VMBindraban** [comment]
The oddest thing is, on my local machine is works just fine. If i copy it to a live server it gives a error.
They were fresh mods. I am running it on multicraft so i can't run the patch file from the server.

Can it have something to do with the fact that multicraft requires that the server.jar needs to be in the jar folder?
I patched the server file and placed it in the jar folder.

**Comment by donkeypanic** [comment]
@nallar heya nallar, might be worth mentioning that i just encountered a nearly identical error when changing from build 1875 to 2098 on DW20 1.4.7.  i had NOT deleted my TTBackups folder.  I followed your instructions here and then was it was fine.  And OMG buddy this freaking build is Rocket Fuel! You continue to impress and amaze. On another note, Is tt 1.5.2 safe for New World Pack at this time in your opinion? Im running pretty well without, no major crises anyway.  Best regards and keep up the good work!
