### ISSUE TITLE
Patcher requires user input to exit

### ISSUE THREAD

**Issue by vsilvar** [MinimallyCorrect/TickThreading#885]
I'm using your script to automatically update TickThreading but when java finishes patching the files, it waits for user input to exit.
Is it possible to remove this?

**Comment by LunNova** [comment]
Grab latest, add `-Dunattend=true` before the `-jar` to disable this.

**Comment by vsilvar** [comment]
It works great, thank you for taking the time to improve this project even with things as minor as this.
Keep up the great work.
