### ISSUE TITLE
Crash during launch

### ISSUE THREAD

**Issue by samlich** [MinimallyCorrect/TickThreading#89]
See edit below

I used multimc to launch an instance with only optifine, forge 6.6.0.516 and fml 4.7.22.537.
Lwjgl is updated to v2.8.5 due to an issue with the version mojang includes and the version of java I'm using.

Heres the crashlog http://pastebin.com/fHD6k3Fr

and the patch log http://pastebin.com/Bz3QFbUn

all the other logfiles in the tickthreading log directory were empty.

EDIT: I was dumb and didn't try not using optifine until after I posted this. I removed optifine and it worked. It's still an issue though that it doesn't work with optifine.

**Comment by Pyker** [comment]
I confirm this issue. Using DW20 modpack v5.0.1, Forge 6.6.1.523, FML 4.7.31.552, LWJGL v2.8.4, OptiFine D3.

Crash log: http://paste.ubuntu.com/1670791/
Patch log: http://pastebin.com/Lngs7YS0

Like @TheSandwichMakr, if I remove OptiFine it works.

**Comment by LunNova** [comment]
Closing, no longer any plans to have client support. Not much benefit for a client, as most time is spent rendering.
