### ISSUE TITLE
[Thaumcraft] Wand of Equal Trade doesn't work

### ISSUE THREAD

**Issue by joaopms** [MinimallyCorrect/TickThreading#901]
I'm using the latest version of TickThreading (v1.5.2.139) and I'm trying to use the Wand of Equal Trade. I'm trying to convert dirt to stone and it doesn't work. Yes, I'm using it right. I've tried it on single player and on a local server without TT and it works. No errors are given and I don't know what it can be

**Comment by Rumpelstiltskinny** [comment]
I also attempted to use my wand of Equal Trade recently. Visually speaking, it appeared to respond normally, but no blocks were replaced. I have used it successfully many times prior to installing TT180. No errors were given and no mention of it in the logs. Thaumcraft 3.0.5e
