### ISSUE TITLE
permgen error

### ISSUE THREAD

**Issue by Machiavellus** [MinimallyCorrect/TickThreading#902]
http://pastebin.com/RJgT7wqf

it spits that out about every 20 minutes on FTB ultimate server with about 8 people on max, regardless of people number. And starting with a random different entity every time. Not sure what we're doing wrong. We have the server allocated to use 12gigs ram and the machine itself as 16gigs. Suggestions? Do I need to give you more input? If so what info?

**Comment by theunicellular** [comment]
This is the most recent crash report from the same server Machiavellus is talking about. Thanks for any help or insight you may have in to our issue. We are completely out of ideas at this point. 

http://pastebin.com/0vehscA0

edit: Here is another one. http://pastebin.com/4zSqKcSw

**Comment by Slind14** [comment]
google: minecraft maxpermsize (java)

**Comment by theunicellular** [comment]
We have been googling things trying to find a solution for the last 3 days and only posted this because we are out of ideas. Changing heap/perm size hasn't fixed anything. We tried a number of different values to no avail. 

Our current startup is this: 

java -server -XmxG -XX:UseSSE=4 -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -XX:+UseConcMarkSweepGC -XX:+UseCMSCompactAtFullCollection -XX:+UseParNewGC -XX:+DisableExplicitGC -XX:+AggressiveOpts -XX:-OmitStackTraceInFastThrow -Xmx12000M -XX:PermSize=1024m -XX:MaxPermSize=2048m -jar mcpc-plus-legacy-1.4.7-R1.1-SNAPSHOT-f534-L67.jar -o true

**Comment by Slind14** [comment]
too mutch.

delete  -XX:PermSize=1024m
set  -XX:MaxPermSize=128m

**Comment by theunicellular** [comment]
I'll try that right now, thanks

**Comment by theunicellular** [comment]
Just crashed again a couple minutes ago but the errors looked different this time and there wasn't a TT log created. 
http://pastebin.com/ShveVQCN

It looked different in console, however, but I only caught this. 
INFO Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Connection #30 read thread"

Thanks for your input.

**Comment by LunNova** [comment]
Try

`java -server -XX:MaxPermSize=256m -Xmx4G -XX:UseSSE=4 -XX:+UseConcMarkSweepGC -XX:+UseCMSCompactAtFullCollection -XX:+UseParNewGC -XX:+DisableExplicitGC -XX:+AggressiveOpts -XX:-OmitStackTraceInFastThrow -jar mcpc-plus-legacy-1.4.7-R1.1-SNAPSHOT-f534-L67.jar`

**Comment by theunicellular** [comment]
I put the changes you suggested in but its crashed twice since I did. Thanks again for your help and let me know if you have any ideas or need any more info. 

http://pastebin.com/Yz8LtKs9
http://pastebin.com/tMmDJQdr

**Comment by LunNova** [comment]
Sorry, I have no idea then. Try removing all plugins, maybe one is constantly defining classes for some reason?

**Comment by LunNova** [comment]
Closing this as I have no idea why the JVM parameters aren't working, other than possibly some plugin creating millions of classes for no good reason, and it's not a TT issue.

**Comment by theunicellular** [comment]
Thanks for your help nallar and responding to my questions. I was actually not running the startup script properly through multicraft... so that was my bad. Love your mod, keep up the good work!
