### ISSUE TITLE
Applied energistics

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#903]
player reported problems:
Storage export bus freezes from time to time. and need to be replaced to work ( may be chunk load related),happens often if its on move/craft mode.
Ae autocraft system made on multiple chunks sometime does not craft components , and stops the autocraft

**Comment by LunNova** [comment]
Which build is this on? Some builds were known to have autocrafting issues but they should be fixed now, same with the buses.

**Comment by HaoSs07** [comment]
did not see anything related to AE to update and retest. is there any update after 2057 ? ae related

**Comment by LunNova** [comment]
No, looks like this is a new issue then.

**Comment by HaoSs07** [comment]
il ask players to retest. to make sure is not a older problem reported late

**Comment by HaoSs07** [comment]
no response from player
