### ISSUE TITLE
Alternative patch process start?

### ISSUE THREAD

**Issue by IonCannon218** [MinimallyCorrect/TickThreading#906]
Is it possible to have TT to have an alternative method to start the patch process instead of using a .sh/.bat script? Or an automatic patch when starting up and detecting unpatched files?

We have a server without SSH access and we cannot get it to run properly with TT installed. We even patched locally on 2 different machines and uploaded everything. Still errors on 4 mods. We verified that the patching was successful by starting the server with all files on the local machine.

I do see the reasoning of having a sh/bat script to patch but it is not a fit all solution.

**Comment by LunNova** [comment]
Main problem with this is that patching the server jar from a JVM which is using the server jar can cause problems. Will look into a workaround.

**Comment by Silverhustle** [comment]
I have same problem as well. I downloaded everything from the server, patched it and uploaded it but the console on the host website showed that it has a few errors related with a couple of mods. I tried to remove those mods that wasn't patched properly and then started it up without those mods and it worked.

I was using FTP application with that but why did some of mods works while some of mods didn't? Perhaps I did something wrong like uploading corrupted config folders or patchedmod folders or something? I would really like to have full mods of FTB Ultimate to be uploaded or patched successfully via FTP.

**Comment by IonCannon218** [comment]
What about a standalone jar that just does the patching? That jar could be called or process forked from the main server jar/process. It can be also called by a sh/bat script like you have now.

**Comment by LunNova** [comment]
That's the workaround I'm mplementing, except no need for a separate jar -
just another main class in the TT jar.

**Comment by Slind14** [comment]
i had this issue, too. but its working with the latest version, just be sure to copy mods coremods and the patched mcpc+. best would be to copy the whole server (instead of the map)

**Comment by Silverhustle** [comment]
Interesting, I may have done something wrong. Is it possible to download everything but world and dynmap folders? Currently my world is about 1.2GB on my server and it would be a bit of pain to download the entire server and then patch everything. You said we just need to patch mods and coremods right? (With patchedmods folder). 

Would it be okay if I download everything but worlds and dynmap folders? We're not using MCPC+ because there's some known issues for MCPC+ on FTB Ultimate 1.4.7 and it would fuck up dynmap with duplicate worlds on the list. I read some forums and some of them said it may be better not to use MCPC+ Legacy for FTB 1.4.7.

**Comment by LunNova** [comment]
You need to copy the coremods folder, server jar, and patchedmods folder to the server. Do not copy the mods folder, TT doesn't actually modify those.

**Comment by LunNova** [comment]
Not sure if this actually works, you'll need to test it. Should patch when you start the server.

**Comment by Silverhustle** [comment]
Ok, I'm testing it right now.

The console on the host website show that it's loading but it's seems it has stopped and not showing any errors. I'm using FTB Ultimate 1.4.7. Do I need to copy coremods, server jar and patchemods folders from the local machine in the server folder first before I put the modified tickthreading jar #906? in the mod folder?

EDIT: The error finally showed up but it's seems not related with tickthreading jar? I could be wrong. 

17.07 08:20:02 [Server] INFO at fy.run(SourceFile:849)
17.07 08:20:02 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:540)
17.07 08:20:02 [Server] INFO at ho.a(DedicatedServer.java:235)
17.07 08:20:02 [Server] INFO at ho.al(DedicatedServer.java:308)
17.07 08:20:02 [Server] INFO at x.a(CommandHandler.java:82)
17.07 08:20:02 [Server] INFO at hh.b(SourceFile:21)
17.07 08:20:02 [Server] INFO java.lang.NullPointerException
17.07 08:20:02 [Server] INFO An unknown error occurred while attempting to perform this command

The server log also say that:

Description: Exception in server tick loop

cpw.mods.fml.common.WrongMinecraftVersionException
    at cpw.mods.fml.common.Loader.sortModList(Loader.java:205)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:476)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:86)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:351)
    at ho.c(DedicatedServer.java:64)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
    at fy.run(SourceFile:849)

**Comment by HaoSs07** [comment]
ok. i'm thinking something like this, not sure how much is posible:
edit config and set patch to true,TT enters in PATCHING mode. ( turns off after patch and enter in normal server start mode):
in patching mode:
TT copies the server.jar to a separate folder and runs the patch,so it does not patch a running minecraft.jar + normal mod patch. Now we have a ( lets call it )minecraftpatched.jar in other folder.

from here one depends on what TT can do and how early.
1) auto force reboot the server after copying minecraftpatched.jar and overwrite the original minecraft.jar ( tt now enters in normal start mode )
2) ask for manual reboot/+autostop after copying minecraftpatched.jar and overwire the original minecraft.jar ( tt now enters in normal start mode ) 

3)experimenta: overwrite server start command. and start server with a minecraftpatched.jar if one is detected 
 probably possible only if:
- TT enters patch mode and runs the patch
- TT starts in normal mode after one of the above situation runs
- TT makes the check then autoreboot/manual reboot to overwrite start and force it to run on minecraftpatched.jar)
  ( i like to call this TT pached mode, enters normal mode if you delete miencraftpatched.jar, or enter patch mode if set patch on true in the config )

Lots of edit :)) read again

**Comment by Silverhustle** [comment]
> TT copies the server.jar to a separate folder and runs the patch,so it does not patch a running minecraft.jar + normal mod patch. Now we have a ( lets call it )minecraftpatched.jar in other folder.

Problem is that some of host companies with FTP prefer server.jar in a different folder called "jar". You would need to change the path for it if it'll search the jar in another folder and then copy it in there. Not to mention that some of hosts require exact jar name in order for it to execute the jar in the host's data center server.

**Comment by HaoSs07** [comment]
if they use gamecp they have only 2 standard option. bukkit.jar or minecraft.jar . I'm sure nallar can make a option in config to set custom name for "minecraftpatched.jar", was just an ideea not a fix name

**Comment by LunNova** [comment]
Can you get a clean copy of the server - no patched mods or anything, no TT folders - and drop the latest TT jar in mods, then start the server? Give full logs of what happens when you do that.

**Comment by IonCannon218** [comment]
Ran on my local linux desktop. FTB Ultimate 1.4.7 with TT build #2073.

Console output: http://pastebin.com/9Q8yC59D
ForgeModLoader-server-0.log: http://pastebin.com/B1JD1Tmt
patcher.1.log: http://pastebin.com/3RN5E3R4
tickthreading.1.log: http://pastebin.com/0GxzdSkm

While it seems to have failed on the first run. It starts up fine on second launch with working patches.

**Comment by LunNova** [comment]
It should require a restart after first run, but there should be no need to actually run the PATCHME.sh. Is that what happened for you?

**Comment by IonCannon218** [comment]
No, I didn't run the PATCHME.sh.

**Comment by LunNova** [comment]
That means it's working as intended.
