### ISSUE TITLE
Bukkitforge 1.4.7-4

### ISSUE THREAD

**Issue by tacharion** [MinimallyCorrect/TickThreading#908]
Had anyone a bukkitforge 1.4.7 url ? 

ich can´t download it

on the mainpage v.v

**Comment by LunNova** [comment]
Yes, their jenkins seems to be down. Not a TT issue, ask @alexbegt for a copy of the 1.4.7 bukkitforge with fixed PlayerInteractEvent.

**Comment by alexbegt** [comment]
nallar, http://build.technicpack.net/job/BukkitForge/

**Comment by LunNova** [comment]
That jenkins only has older builds - none with the changes in the 1.4.7 branch made 2 months ago.

For example, no build with https://github.com/keepcalm/BukkitForge/commit/09a5ef25471c17333e4d4b20c45050a279aba618

**Comment by alexbegt** [comment]
oh. ill get it built then

**Comment by tacharion** [comment]
this will be nice =D

**Comment by LunNova** [comment]
Or just use MCPC+.
