### ISSUE TITLE
1.4.7 RedPower Timer issue

### ISSUE THREAD

**Issue by jznomoney** [MinimallyCorrect/TickThreading#912]
I am having issues with the RedPower 2 timers stopping.  I place the timer and it starts working but eventually it just stops constantly on.  It happens when I am near it or when I place an anchor to keep it loaded when away.  I am using build     TickThreading-1.4.7-1.0.0.2072.jar.  I am new to using tickthreading so I am unsure if the issue is apparent in previous versions.

**Comment by mainsheep** [comment]
I'm also having these issues. They have been present in all of the TT versions afaik.

**Comment by jznomoney** [comment]
Also somehow deployers wind up getting lava buckets in them when they aren't even supposed to be in them.  I do have lava buckets going into certain deployers on my map but others that aren't even being fed anything wind up with lava bucks and then the area around gets filled with lava.

**Comment by jznomoney** [comment]
I  think it maybe redpower itself.   My deployers keep changing what items are in them randomly.   Sometimes the applied energistics network itself messes up and items passing threw a export cable don't work properly.   They just keep going when set with a level cable or ignore the item I tell to export.   I  am running tekkit lite the latest version.

**Comment by jznomoney** [comment]
here is there tickthreading error log file https://dl.dropboxusercontent.com/u/10166016/tickthreading.1.log
