### ISSUE TITLE
1.4.7 TT 2074 Server Deadlock, impossible to log in

### ISSUE THREAD

**Issue by gorea01** [MinimallyCorrect/TickThreading#915]
I lost the ThickThreading log in the process of removing this mod fast and putting server back up asp,  but i have the forgemodloader log with the error, maybe this will help.

http://pastebin.com/bv0J9cHQ

the item id 122 is End Stone and 119 is End Portal

server is FTB Ultimate mod Pack 1.4.7 with mcpc-plus-legacy-1.4.7-R1.1-SNAPSHOT-f534-L67

I really like your work and want to have this mod badly

**Comment by gorea01** [comment]
the 2076 will fix this too?

**Comment by LunNova** [comment]
No.

**Comment by seriousvern** [comment]
i took tickthreading out when i was getting a similar error then put it back and it has been smooth ever since
make sure you remove the old patch me file and patched mods

**Comment by LunNova** [comment]
@seriousvern that was just luck.

This issue still exists and can still happen until I fix it.

**Comment by seriousvern** [comment]
i can deal with luck for now better than going with out this mod :)

**Comment by gorea01** [comment]
i will wait until you have a fix for it and gonna try again, i tested this thickthreading on a test server but i guess it is not easy on a big one (20gb map) with allot of players 
I will try to have the correct logs in future, i just paniked and reinstall the modpack in my rush to make server up :D,
thank you

**Comment by gorea01** [comment]
Hell, 

I seen you fixed allot since then , does any of them fixes this too?

**Comment by LunNova** [comment]
This looks like the issue in #919, it should be fixed now.
