### ISSUE TITLE
TickThreading 1.4.7 Latest version - AC fix not 100% working

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#917]
Hey,

Some staff of my server reported this, the fix works fine but this is still bypassing. Some players managed it to be done alone but we did it together.

Till itsx fixed in TickThreading use this;
http://forum.feed-the-beast.com/threads/arcane-table-dupe-fix.26467/

Here is a video;
http://youtu.be/0jQKOmHZUPI

**Comment by LunNova** [comment]
Can you test that new fix to make sure it works? Previous fix removed all drops, this one should still drop but disallow  removing the item to be crafted.

**Comment by darkdeath1332** [comment]
works, but CPU went nuts.

I cant pick out the item anymore.

**Comment by darkdeath1332** [comment]
![image](https://f.cloud.github.com/assets/3824354/829970/a37a0a54-f11c-11e2-863b-a369155f29ec.png)

With an older version it was running 40% with this amount of players

Average tick time is 15 ms

**Comment by darkdeath1332** [comment]
How can I remove that 64K Tile Entitys?
