### ISSUE TITLE
[Crash] [MCPC+ 67] [TT 2091] Crash with ME Controllers

### ISSUE THREAD

**Issue by CoryManson** [MinimallyCorrect/TickThreading#919]
Hi Nallar,

Can't pinpoint whats causing the crash. But here's the log:

https://gist.github.com/Cozza38/0b1fd3eb947547125c20

**Comment by darkdeath1332** [comment]
Please fix this...

**Comment by LunNova** [comment]
Can't I at least have breakfast first? :P

No idea if this fix works, haven't had time to test it.

**Comment by darkdeath1332** [comment]
I paid ur breakfast XD, donated just a moment ago. 

Ill test it in a moment.

**Comment by darkdeath1332** [comment]
How you call this crash?

**Comment by LunNova** [comment]
Thanks for the donation :D

Tested that the patch doesn't crash or break anything horribly, but don't know if it actually fixes the problem. Hard to test as it's not possible to make the crash happen on demand - it's a timing issue.

**Comment by darkdeath1332** [comment]
Seems to work
