### ISSUE TITLE
World wont load after a deadlock

### ISSUE THREAD

**Issue by droosk** [MinimallyCorrect/TickThreading#924]
Changed over to MCPC+, 1.4.7, TT 2090, FTB Ultimate, no extra mods or plugins.

Server Deadlocked on a bad world tick. Attempted to bring it back up, everything seems to load fine, but when we get to where it loads the dimensions 0 and 7, it just stops. Commands don't work, and server does not appear in server list, and only way to do anything is to Ctrl C to stop the server.

If nothing else, instructions on recovering the world to be played on w/o TT would be amazing. Backups are several days old :(

**Comment by HaoSs07** [comment]
i have same problem on 2095. usually is form mysql. u run mysql for any mod??

**Comment by LunNova** [comment]
Give the full deadlock log. Wait until it makes one after starting the server.

To remove TT just remove it from mods folder and replace server jar/coremods with those in TTBackups folder, TT does nothing special to the world.
