### ISSUE TITLE
[MCPC+ L67] [TT 2093] Server Crash 'IC2'

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#926]
I had to reset my map due this;

(not full log becouse after that is only spam of ic2.core.block.machine.tileentity.TileEntityMiner.canReachTarget(TileEntityMiner.java:416)

http://pastebin.com/jbBUcsxm

**Comment by LunNova** [comment]
The paste is gone, accidentally close this issue.

**Comment by LunNova** [comment]
Looks like the IC2 miner infinite recursion bug. You could download the .mcr region file for that area and delete the miner using MCedit

**Comment by darkdeath1332** [comment]
Ive done a map reset, couldnt get the right mcr and my map was almost filling all my disc space.

288 GB :/

**Comment by LunNova** [comment]
Oh, that's unfortunate :( Can't help then. If you still had the .mcr could test locally and fix it.

**Comment by darkdeath1332** [comment]
Its not fixed, Just had it again.

All I know is the location of the miner... how do I fix this?

**Comment by darkdeath1332** [comment]
I broke the miner, it seems to happend with any miner.
