### ISSUE TITLE
sockets vs cores

### ISSUE THREAD

**Issue by seriousvern** [MinimallyCorrect/TickThreading#927]
I know in default minecraft single core speed is top for performance and i was wondering if with tickthreading would i be better to go with more sockets or cores
like is 4 sockets with 2 cores better or 1 socket 8 cores or 2 sockets 4 cores something along that line. i can change this all at will so i was wonderinf what you thought would be best for this specific type setup.
also what about hyperthreding how does that effect with this mod

**Comment by LunNova** [comment]
In general, performance is better with 1 socket 8 cores than 4 sockets 2 cores.
