### ISSUE TITLE
[SUGGESTION] To much tile enitites, command to clear

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#929]
Hey Nallar,

I think I would be awesome if we could clear the Tile Entities. This is becouse my old map; 60K TE @ 40% 0 players should be nice to get cleared a bit

Since I have a new map, its on 1k with @ 3% o players CPU

**Comment by LunNova** [comment]
A tile entity is associated with each machine/pipe/etc. Clearing them doesn't really make sense.
