### ISSUE TITLE
[1.5.2 TT173] Abnormal world usage and onPostWorldTick time?

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#931]
So my server just upgraded to the new 1.5 version of the Direwolf pack. Had to do a complete map reset and everything. However, there seems to be some sort of issue with something somewhere. I have no idea if it's TickThreading, a mod, or if it's even fixable. It does seem very odd though. 

/tps output
![1](http://puu.sh/3J66K.jpg)

/ticks
![2](http://puu.sh/3J6gY.jpg)

/profile a
![3](http://puu.sh/3J5OI.jpg)

The world usage is very high, yet no one even has any machines yet since the world was just reset a few hours ago. I don't want to imagine what it will be like when it gets cluttered with that. However, previously, even with those machines we were able to keep a steady 20TPS with 90+ people on.

I've thought that it may be from people generating chunks, however I've never seen it that bad at previous resets, though we never had that many people then either. Plus, 1.5 uses Biomes'O'Plenty rather than XLBiomes.

I'll generate an NPS snapshot for you next time the server restarts. Hopefully something can be done.

**Comment by LunNova** [comment]
Yes, need an nps snapshot. Looks like you've got a derpy mod taking forever to handle post-world tick.

**Comment by joey19982** [comment]
Here you go. It ran for about an hour before the high world usage came up again, then I let it run for another hour with the high usage.
https://dl.dropboxusercontent.com/u/37515491/snapshot-1374541470329-cpu-calltree.nps

**Comment by alexbegt** [comment]
Please fix :100:

**Comment by LunNova** [comment]
Hats mod is being stupid, taking 80% of your tick time for some reason.

**Comment by joey19982** [comment]
ಠ_ಠ
Hats.

Any specifics on which part of it? I'll go ahead and report it to the bug thread so they can hopefully fix/remove it before the official launch next week.

**Comment by joey19982** [comment]
So far with the new build it seems to be fixed, however it's a slower time of night and the server hasn't been up long. I'll report back tomorrow with how it's going.

**Comment by joey19982** [comment]
Post-World Tick is still pretty high up there, but not nearly as high as before. The usage seems to be at a pretty safe spot. 
![1](http://puu.sh/3JQ4p.jpg)

![2](http://puu.sh/3JQ3n)

I'm sure that's about as good as it gets. You're a lifesaver, nallar.
