### ISSUE TITLE
[1.5.2][TT-173]Dimensional Doors Crash

### ISSUE THREAD

**Issue by Teteros** [MinimallyCorrect/TickThreading#934]
TickThreading-1.5.2.173
DimensionalDoors-1.5.2R1.4.1RC1-194
https://gist.github.com/Teteros/6057674

**Comment by ruifung** [comment]
Using TT 152 b177. Still occurs.

**Comment by Tencao** [comment]
Same issue here, except I cant even boot up my server due to this error
