### ISSUE TITLE
High load from chunk generation due to speed hackers

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#936]
Hi Nallar,

Since TickThreading is to increase preformance I would suggest for a limit on chunk loading. People with speed hacks are continusly speed hacking and chunking. They chunk so much that the server goes shit.

I would suggest a function on how fast a chunk gets loaded, more when alot get loaded that it wont keep loading till the server cant handle it anymore.

Or anything to prevent the lag coused by speed hackers loading chunks.

**Comment by darkdeath1332** [comment]
Massive amount of lag due this.
![image](https://f.cloud.github.com/assets/3824354/842748/6a796a06-f3b0-11e2-8d9d-865f1e0b26a6.png)

**Comment by LunNova** [comment]
Unless you have 80 cores something broke with `/profile u` there.

**Comment by darkdeath1332** [comment]
Dont have 80 cores XD

Idk, but this is been going on alot. I know its speed hacking becouse I teleported to someone while the lag and he was flying very fast and generating new chunks. Banned him and it went normal.

That screen was to show that its coused by speed hack. I really would like a way to limit the speed of new chunk creating. :D

**Comment by darkdeath1332** [comment]
server loop is just 6ms and I have a tps of 10 :(
dang speed hackers.

![image](https://f.cloud.github.com/assets/3824354/843940/5844c2c2-f3c9-11e2-8e94-825055710237.png)

**Comment by LunNova** [comment]
`/tps` and `/profile a` and `/profile e`?

**Comment by darkdeath1332** [comment]
![image](https://f.cloud.github.com/assets/3824354/844775/80997ce4-f3d9-11e2-9d45-daf0d8699a3f.png)
![image](https://f.cloud.github.com/assets/3824354/844779/9213daf0-f3d9-11e2-80ac-82a997a7acd5.png)
![image](https://f.cloud.github.com/assets/3824354/844784/c48caec6-f3d9-11e2-947b-2f8f48a45b68.png)
![image](https://f.cloud.github.com/assets/3824354/844790/d0d10f92-f3d9-11e2-98fd-78cee3f08b8e.png)

**Comment by darkdeath1332** [comment]
Just banned someone for speed hacking....
![image](https://f.cloud.github.com/assets/3824354/844880/7baa5652-f3db-11e2-8d80-bf0397016ae9.png)

**Comment by ghost** [comment]
What modpack are you playing? You know on 1.4.7 you can make your Modular Power Suits armor invisible for very cheap right? If someone had invisible MPS armor with full power flight modules they could move incredibly fast, even faster that a Gravichest with boost turned on.

You may have just banned players that had just reached mid game and were exploring in their high tier armor. I am sure Nallar can find a way to help, but the best solution is getting better disk IO.

**Comment by LunNova** [comment]
WorldServer/tick being so slow is odd, can you get a .nps?

**Comment by darkdeath1332** [comment]
@DZCreeper I currently have 2x 300 GB SSD, the fastest I could get.

**Comment by darkdeath1332** [comment]
@nallar I added the lines to my boot script, waiting for the next restart.

**Comment by darkdeath1332** [comment]
@nallar new version seems to be broken, thats what slind told me. Ill wait for a new version so I can profile.
