### ISSUE TITLE
1.5.2 - TT179 - MCPC B608 - Unable to place barrel

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#938]
When placing a barrel, you get kicked with the following error in console:

> 2013-07-24 10:46:08 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 11
> java.lang.ClassCastException: factorization.common.TileEntityBarrel cannot be cast to factorization.common.TileEntityCommon
>         at factorization.common.FactoryType.makeTileEntity(FactoryType.java:116)
>         at factorization.common.ItemFactorization.placeBlockAt(ItemFactorization.java:33)
>         at net.minecraft.world.World.func_72931_a(World.java:4052)
>         at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:90)
>         at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:127)
>         at net.minecraft.item.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:582)
>         at net.minecraft.network.NetServerHandler.func_72472_a(NetServerHandler.java:874)
>         at net.minecraft.network.packet.Packet15Place.func_73279_a(SourceFile:58)
>         at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:442)
>         at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:222)
>         at net.minecraft.network.NetworkListenThread.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:53)
>         at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java)
>         at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:431)
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:307)
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:199)
>         at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
> 10:46:08 [WARNING] Failed to handle packet for Gravenlord/192.168.133.126: java.lang.ClassCastException: factorization.common.TileEntityBarrel cannot be cast to factorization.common.TileEntityCommon
> java.lang.ClassCastException: factorization.common.TileEntityBarrel cannot be cast to factorization.common.TileEntityCommon
>         at factorization.common.FactoryType.makeTileEntity(FactoryType.java:116)
>         at factorization.common.ItemFactorization.placeBlockAt(ItemFactorization.java:33)
>         at net.minecraft.world.World.func_72931_a(World.java:4052)
>         at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:90)
>         at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:127)
>         at net.minecraft.item.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:582)
>         at net.minecraft.network.NetServerHandler.func_72472_a(NetServerHandler.java:874)
>         at net.minecraft.network.packet.Packet15Place.func_73279_a(SourceFile:58)
>         at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:442)
>         at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:222)
>         at net.minecraft.network.NetworkListenThread.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:53)
>         at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java)
>         at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:431)
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:307)
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:199)
>         at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

**Comment by mainsheep** [comment]
I'm not sure if this is a TT issue or not, if not, please delete this post :)

**Comment by seriousvern** [comment]
same issue here and all previous barrels no longer exist

**Comment by droosk** [comment]
Just FYI, I am running 1.1.2 of the modpack, updated to the latest mcpc (Not brand new, but new enough), and running TT 1.5.2 #185 and barrels are working again.

**Comment by mainsheep** [comment]
Barrels still doesn't work here. Using MCPC B623 and TT185.

**Comment by LunNova** [comment]
Full patcher log please? This seems impossible so I guess something broke when patching.

**Comment by mainsheep** [comment]
Welcome back Nallar.

Patcher1 log:
http://pastebin.com/rBNQQnvP
