### ISSUE TITLE
[MCPC+ 612 1.5.2] [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 64

### ISSUE THREAD

**Issue by Lanuk1** [MinimallyCorrect/TickThreading#939]
Hello, to be quite honest with you I don't know what TickThreading or anything is, I just saw similar errors to mine posted here. If I got the completely wrong place or forgot some information, I apologize! Help would be appreciated!

So when I try to log on to my server, I get an "Internal Server Error" which looks like so in the log:

14:25:40 [INFO] Lanuk[/192.168.2.4:64695] logged in with entity id 64 at ([world] 976.3563146482702, 111.5, -1159.3009106414115)
14:25:40 [INFO] Loading Player: Lanuk
14:25:40 [INFO] Sending serverside check to: Lanuk

> 2013-07-24 14:25:41 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 64
> net.minecraft.util.ReportedException: Ticking player
>     at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:457)
>     at net.minecraft.network.NetServerHandler.func_72498_a(NetServerHandler.java:501)
>     at net.minecraft.network.packet.Packet10Flying.func_73279_a(SourceFile:136)
>     at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:442)
>     at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:222)
>     at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:53)
>     at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
>     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847)
>     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
>     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:716)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:600)
>     at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
> Caused by: java.lang.NullPointerException
>     at net.minecraft.entity.DataWatcher.func_75681_e(DataWatcher.java:101)
>     at net.minecraft.entity.EntityLiving.func_94056_bM(EntityLiving.java:3166)
>     at net.minecraft.entity.EntityLiving.func_70023_ak(EntityLiving.java:3151)
>     at chocolate.mods.BD.items.ItemArmorHelmetScouter.onUpdateEquiped(ItemArmorHelmetScouter.java:42)
>     at chocolate.mods.BD.items.ItemArmorBase.onArmorTickUpdate(ItemArmorBase.java:18)
>     at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:314)
>     at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:599)
>     at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:871)
>     at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:333)
>     at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:406)
>     ... 11 more
> 14:25:41 [WARNING] Failed to handle packet for Lanuk/192.168.2.4: net.minecraft.util.ReportedException: Ticking player
> net.minecraft.util.ReportedException: Ticking player
>     at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:457)
>     at net.minecraft.network.NetServerHandler.func_72498_a(NetServerHandler.java:501)
>     at net.minecraft.network.packet.Packet10Flying.func_73279_a(SourceFile:136)
>     at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:442)
>     at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:222)
>     at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:53)
>     at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
>     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847)
>     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
>     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:716)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:600)
>     at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
> Caused by: java.lang.NullPointerException
>     at net.minecraft.entity.DataWatcher.func_75681_e(DataWatcher.java:101)
>     at net.minecraft.entity.EntityLiving.func_94056_bM(EntityLiving.java:3166)
>     at net.minecraft.entity.EntityLiving.func_70023_ak(EntityLiving.java:3151)
>     at chocolate.mods.BD.items.ItemArmorHelmetScouter.onUpdateEquiped(ItemArmorHelmetScouter.java:42)
>     at chocolate.mods.BD.items.ItemArmorBase.onArmorTickUpdate(ItemArmorBase.java:18)
>     at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:314)
>     at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:599)
>     at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:871)
>     at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:333)
>     at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:406)
>     ... 11 more
> 14:25:41 [INFO] Unloading Player: Lanuk

I am using Hexxit 1.0.4 if it matters!

**Comment by LunNova** [comment]
> I am using Hexxit 1.0.4 if it matters!

Unless Hexxit have included TickThreading (I doubt it), this isn't related to me. Best to submit this on the hexxit forums (or issue tracker if they have one).
