### ISSUE TITLE
[TT  2099] Packet spam is back, mmmPowerSuits

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#947]
I just found out that the old packet spam fix isnt working anymore...

![image](https://f.cloud.github.com/assets/3824354/865936/25ba642c-f64b-11e2-8682-889a00532c30.png)

**Comment by darkdeath1332** [comment]
it ruined my player movement in the sever D:

All players move in stop motion.

**Comment by LunNova** [comment]
Uninstall power suits, must be a different packet spam bug and I don't have
time to fix it just now.

**Comment by darkdeath1332** [comment]
Will you be able to fix it soon? I cant really remove it, alot of people have powerarmor.

**Comment by LunNova** [comment]
Can you get another profile with latest? Should make it easier to find what's causing it.

**Comment by Slind14** [comment]
2096 is fine for me: 160kKB

ok, not anymore. deadlock ever 20 min.

**Comment by darkdeath1332** [comment]
Latest profile

![image](https://f.cloud.github.com/assets/3824354/931030/4273a9e6-0020-11e3-9524-d928199ce195.png)
