### ISSUE TITLE
TT incompatible with MindCrack v8

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#95]
Here is the logs from TTlogs folder
http://pastebin.com/3UVZh1dE

Here are some other ones that forge / mods gave
http://pastebin.com/X8xnsBur
http://pastebin.com/Hw42rYFq

**Comment by Puremin0rez** [comment]
Here's one I forgot to post:
http://pastebin.com/Hw42rYFq

**Comment by LunNova** [comment]
Log-spam related to classloading is fixed in latest, entity issue appears to involve entities being saved in the wrong chunk.

**Comment by LunNova** [comment]
I've added more debugging for entity loading in 67a505c8b78d798f.
