### ISSUE TITLE
[TT 1.5.2 #184] [MCPC+ B617 ][Hexxit Mod pack] [Mobs not ticking properly ]

### ISSUE THREAD

**Issue by Bucky420** [MinimallyCorrect/TickThreading#951]
Mobs will sometimes seem to not move or appear to get stuck and rubber band back. Also the issue is showing with Chocobos. (Mod in Hexxit ModPack)

EDIT: Though hours of testing, I found out that if the View Distance in the Server.Properties file is below 4, we had at 3. It will cause this issue above. 
So we changed it and it has been working fine since then. (Testing on a 150 Player Server)

**Comment by thejbone** [comment]
This is fixed, I am the other person that worked on it, but this needs to be read and as a reference for other people.
