### ISSUE TITLE
[1.5.2 TT184] Exception ticking TileEntity c appeng.me.tile.TileStorageBus

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#955]
A player has a line of Storage Buses lined up under their chests, about 10 of them. It seems that all are throwing errors to the log along with the controller.

http://pastebin.com/1CjHsntc

**Comment by Rumpelstiltskinny** [comment]
I have also seen numerous server messages stating "[SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.*" Many of the AppEng entities are "TileOutputCable" Relevant versions are 'TickThreading-1.5.2.180.jar' & 'appeng-rv11-e-mc15x.zip' Logs posted here: https://gist.github.com/Rumpelstiltskinny/6104815
