### ISSUE TITLE
Build Fails forge-exists

### ISSUE THREAD

**Issue by hansod1** [MinimallyCorrect/TickThreading#959]
This'll be a quick one.

I get the following error when I'm building:

/home/<user>/TickThreading/build.xml:83: The specified destination is a directory

To me, it looks like this line in build.xml:

 src="http://files.minecraftforge.net/${forge.name}" dest="${download.dir}" usetimestamp="True"

Should be: 

 src="http://files.minecraftforge.net/${forge.name}" dest="${download.dir}/${forge.name}" usetimestamp="True"

Am I correct, wrong, or is my environment not configured correctly?

I'm using Linux, Centos 6.4 with Java 7

**Comment by LunNova** [comment]
Are you using an old version of ant? For me, with a destination as a directory it downloads inside the directory.

**Comment by hansod1** [comment]
Looks like the Centos 6.4 standard repositories are way out of date on Ant! Looks like I need to upgrade myself.
