### ISSUE TITLE
any news about nallar ?

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#991]
it seems his mia for 2 weeks now. anyone has any news about him ?

**Comment by joey19982** [comment]
In the IRC he is online but has been away for these two weeks. Admittedly I'm a bit worried. Normally he'll post on the FTB forums when going on vacation.

**Comment by LunNova** [comment]
Still alive, just got burned out + slightly addicted to super hexagon and
then planetside 2.

Dropping 1.4.7 support now, will be working again soon-ish.

**Comment by alicheek** [comment]
Great to hear ! Yea gotta love planet side 2 well hope you are having a good summer man!

**Comment by HaoSs07** [comment]
any plans for 1.5.2 ? my players are asking for TT. server is not the same now.:D we miss you!

**Comment by alicheek** [comment]
The 185 build is pretty stable of you ask me and it helps with the performance by a lot so should give it a go !

**Comment by joey19982** [comment]
Great to hear Nallar. You definitely deserve a break after all you've done here.

**Comment by seriousvern** [comment]
cant wait to have you back
