### ISSUE TITLE
Idea: Don't allow simultanious updates on adjacent chunks

### ISSUE THREAD

**Issue by Xfel** [MinimallyCorrect/TickThreading#992]
Most deadlocks come from tile entities on each side of a chunk border, where the adjacent chunks are updated simultaniously by different threads.

An alternative solution would be disallowing such updates. If one thread updates one chunk, any other threads should not be allowed to update an adjacent chunk.

I don't know how much work this would be, it's just an idea for an improvement.

**Comment by Xfel** [comment]
Well thank you for not even commenting and goodbye

**Comment by LunNova** [comment]
Closed all issues as I'm not currently working on the project, no way of
bulk commenting as far as I can see.

On 27 October 2013 19:21, Xfel notifications@github.com wrote:

> Well thank you for not even commenting and goodbye
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nallar/TickThreading/issues/992#issuecomment-27176838
> .

## 

Ross Allan

**Comment by LunNova** [comment]
Also forgot to mention, when I start working again. Redoing the threading
model which makes almost all of these issues irrelevant. Will check for any
still relevant when I have time.
